Repository duckdb/duckdb, pull requests merged in 2021-11, with the labels that each got.

#2604 Fix #2599: maintain correct dependencies between UNION ALL nodes so that output is deterministic/in-line with what a sequential execution would produce
  src/include/duckdb/execution/executor.hpp
  src/parallel/executor.cpp
  test/sql/setops/union_limit.test
Labels: bug-fix

#2623 Fix #2612: Correctly check that default is set on copy of SetDefaultInfo
  src/parser/parsed_data/alter_table_info.cpp
  test/sql/alter/default/drop_default.test
  test/sql/alter/default/test_set_default.test
Labels: bug-fix

#2644 Fix #2641: correctly handle tab delimiters in COPY TO/FROM
  src/execution/operator/persistent/buffered_csv_reader.cpp
  src/function/table/copy_csv.cpp
  src/function/table/read_csv.cpp
  src/include/duckdb/execution/operator/persistent/buffered_csv_reader.hpp
  test/sql/copy/csv/tsv_copy.test
Labels: bug-fix

#2578 Enable support for multi-dot column references
  src/catalog/catalog_entry/table_catalog_entry.cpp
  src/execution/expression_executor.cpp
  src/function/macro_function.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/function/table/table_scan.hpp
  src/include/duckdb/parser/expression/columnref_expression.hpp
  src/include/duckdb/parser/parsed_expression_iterator.hpp
  src/include/duckdb/planner/bind_context.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/expression_binder.hpp
  src/include/duckdb/planner/operator/logical_get.hpp
  src/include/duckdb/planner/table_binding.hpp
  src/main/relation.cpp
  src/optimizer/statistics/operator/propagate_projection.cpp
  src/parser/expression/columnref_expression.cpp
  src/parser/parsed_expression_iterator.cpp
  src/parser/transform/expression/transform_columnref.cpp
  src/parser/transform/expression/transform_lambda.cpp
  src/planner/bind_context.cpp
  src/planner/binder.cpp
  src/planner/binder/expression/bind_columnref_expression.cpp
  src/planner/binder/expression/bind_macro_expression.cpp
  src/planner/binder/query_node/bind_select_node.cpp
  src/planner/binder/statement/bind_create.cpp
  src/planner/binder/tableref/bind_table_function.cpp
  src/planner/expression_binder.cpp
  src/planner/expression_binder/alter_binder.cpp
  src/planner/expression_binder/check_binder.cpp
  src/planner/expression_binder/column_alias_binder.cpp
  src/planner/expression_binder/group_binder.cpp
  src/planner/expression_binder/order_binder.cpp
  src/planner/expression_binder/select_binder.cpp
  src/planner/operator/logical_get.cpp
  src/planner/table_binding.cpp
  src/storage/storage_info.cpp
  test/sql/alter/alter_type/alter_type_struct.test
  test/sql/catalog/function/struct_extract_macro.test
  test/sql/catalog/function/test_simple_macro.test
  test/sql/constraints/check/check_struct.test
  test/sql/constraints/check/test_check.test
  test/sql/select/test_multi_column_reference.test
  test/sql/select/test_projection_names.test
  test/sql/select/test_schema_reference.test
  test/sql/storage_version/storage_version.db
Labels: feature, ready-to-merge

#2597 Extend Parquet writer support for UNSIGNED types, various timestamp types, and correctly set converted types in more cases
  data/parquet-testing/broken/broken_bigint.parquet
  data/parquet-testing/broken/broken_date.parquet
  data/parquet-testing/broken/broken_int.parquet
  data/parquet-testing/broken/broken_smallint.parquet
  data/parquet-testing/broken/broken_timestamp.parquet
  data/parquet-testing/broken/broken_timestamp_ms.parquet
  data/parquet-testing/broken/broken_tinyint.parquet
  data/parquet-testing/broken/broken_ubigint.parquet
  data/parquet-testing/broken/broken_uinteger.parquet
  data/parquet-testing/broken/broken_usmallint.parquet
  data/parquet-testing/broken/broken_utinyint.parquet
  extension/parquet/column_reader.cpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_writer.cpp
  test/parquet/test_parquet_reader.test
  test/sql/copy/parquet/incorrect_converted_type.test
  test/sql/copy/parquet/test_parquet_scan.test
  test/sql/copy/parquet/writer/parquet_write_date.test
  test/sql/copy/parquet/writer/parquet_write_hugeint.test
  test/sql/copy/parquet/writer/parquet_write_signed.test
  test/sql/copy/parquet/writer/parquet_write_timestamp.test
  test/sql/copy/parquet/writer/parquet_write_unsigned.test
  test/sql/copy/parquet/writer/test_parquet_write.test
  test/sql/copy/parquet/writer/test_parquet_write_complex.test
  tools/pythonpkg/tests/fast/arrow/parquet_write_roundtrip.py
  tools/pythonpkg/tests/fast/types/test_blob.py
Labels: feature, ready-to-merge

#2602 Adding pragma option for parquet binary as string
  extension/parquet/include/parquet_reader.hpp
  extension/parquet/parquet-extension.cpp
  extension/parquet/parquet_metadata.cpp
  src/function/pragma/pragma_functions.cpp
  src/include/duckdb/main/client_context.hpp
  test/sql/copy/parquet/parquet_blob_string.test
  tools/pythonpkg/duckdb_python.cpp
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/tests/fast/test_parquet.py
Labels: feature, ready-to-merge

#2576 Add generate_subscripts macro
  src/catalog/default/default_functions.cpp
  test/sql/function/list/generate_subscripts.test
Labels: feature

#2583 Issue #2549: Support IGNORE NULLS
  .editorconfig
  src/execution/operator/aggregate/physical_window.cpp
  src/include/duckdb/parser/expression/window_expression.hpp
  src/include/duckdb/planner/expression/bound_window_expression.hpp
  src/parser/expression/window_expression.cpp
  src/parser/transform/expression/transform_function.cpp
  src/planner/binder/expression/bind_window_expression.cpp
  src/planner/expression/bound_window_expression.cpp
  src/storage/storage_info.cpp
  test/sql/storage_version/generate_storage_version.sql
  test/sql/storage_version/storage_version.db
  test/sql/storage_version/storage_version.test_slow
  test/sql/window/test_ignore_nulls.test
  third_party/libpg_query/grammar/grammar.y
  third_party/libpg_query/grammar/keywords/unreserved_keywords.list
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/grammar/types/select.yh
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/include/parser/kwlist.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
  third_party/libpg_query/src_backend_parser_scan.cpp
Labels: feature, ready-to-merge
