Repository duckdb/duckdb, pull requests merged in 2022-09, with the labels that each got.

#4543 Fixing silent assertions
  .github/workflows/LinuxRelease.yml
  CMakeLists.txt
  Makefile
  extension/json/include/json_common.hpp
  extension/json/json_functions/json_create.cpp
  extension/json/json_functions/json_merge_patch.cpp
  extension/json/json_functions/json_transform.cpp
  src/common/exception.cpp
  src/common/preserved_error.cpp
  src/common/types/data_chunk.cpp
  src/common/vector_operations/vector_cast.cpp
  src/execution/expression_executor.cpp
  src/function/aggregate/nested/histogram.cpp
  src/function/scalar/list/array_slice.cpp
  src/function/scalar/list/contains_or_position.cpp
  src/function/scalar/list/flatten.cpp
  src/function/scalar/list/list_aggregates.cpp
  src/function/scalar/list/list_lambdas.cpp
  src/function/scalar/list/list_sort.cpp
  src/function/scalar/map/map_from_entries.cpp
  src/function/scalar/string/string_split.cpp
  src/function/scalar/struct/struct_insert.cpp
  src/include/duckdb/common/types/data_chunk.hpp
  src/include/duckdb/planner/logical_operator.hpp
  src/include/duckdb/planner/operator/logical_prepare.hpp
  src/main/client_context.cpp
  src/main/pending_query_result.cpp
  src/parser/parser.cpp
  src/verification/prepared_statement_verifier.cpp
Labels: bug-fix

#4648 Issue #4635: DATE_DIFF Week Boundaries
  src/function/scalar/date/date_diff.cpp
  test/sql/function/timestamp/test_icu_datediff.test
Labels: bug-fix

#4643 Fix bug changing input order on array_sort column
  src/function/scalar/list/list_sort.cpp
  test/sql/function/list/list_sort.test
Labels: bug-fix

#4773 Issue #4764: Window Ignore Nulls
  src/execution/operator/aggregate/physical_window.cpp
  src/include/duckdb/common/types/row_data_collection_scanner.hpp
  test/sql/window/test_ignore_nulls.test
Labels: bug

#4655 Parallelize CREATE INDEX of ART
  src/catalog/catalog_entry/table_catalog_entry.cpp
  src/execution/index/art/art.cpp
  src/execution/index/art/art_key.cpp
  src/execution/index/art/iterator.cpp
  src/execution/index/art/leaf.cpp
  src/execution/index/art/node.cpp
  src/execution/index/art/node16.cpp
  src/execution/index/art/node256.cpp
  src/execution/index/art/node4.cpp
  src/execution/index/art/node48.cpp
  src/execution/index/art/prefix.cpp
  src/execution/operator/schema/physical_create_index.cpp
  src/execution/physical_plan/plan_create_index.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/common/swap.hpp
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/art/art_key.hpp
  src/include/duckdb/execution/index/art/leaf.hpp
  src/include/duckdb/execution/index/art/node.hpp
  src/include/duckdb/execution/index/art/node16.hpp
  src/include/duckdb/execution/index/art/node256.hpp
  src/include/duckdb/execution/index/art/node4.hpp
  src/include/duckdb/execution/index/art/node48.hpp
  src/include/duckdb/execution/index/art/prefix.hpp
  src/include/duckdb/execution/operator/schema/physical_create_index.hpp
  src/include/duckdb/function/table/table_scan.hpp
  src/include/duckdb/parser/parsed_data/create_index_info.hpp
  src/include/duckdb/planner/operator/logical_create_index.hpp
  src/include/duckdb/storage/data_table.hpp
  src/include/duckdb/storage/index.hpp
  src/parser/parsed_data/create_index_info.cpp
  src/planner/binder/statement/bind_create.cpp
  src/planner/logical_operator.cpp
  src/planner/operator/logical_create_index.cpp
  src/storage/data_table.cpp
  src/storage/index.cpp
Labels: enhancement, Index
