Repository duckdb/duckdb, pull requests merged in 2022-04, with the labels that each got.

#3343 Issue #3118: Non-string Formats
  src/function/scalar/date/strftime.cpp
  src/include/duckdb/function/scalar/strftime.hpp
  test/sql/function/date/test_strftime.test
Labels: bug-fix

#3355 Fix #3349: correctly handle empty table case in grouping set
  src/execution/radix_partitioned_hashtable.cpp
  test/issues/fuzz/multi_rollup_assertion.test
Labels: bug-fix

#3358 Fix #3352: fix several bugs with index selection for verifying foreign key constraints
  src/include/duckdb/storage/data_table.hpp
  src/planner/binder/statement/bind_create.cpp
  src/planner/binder/statement/bind_create_table.cpp
  src/storage/data_table.cpp
  test/issues/fuzz/foreign_key_index_selection.test
Labels: bug-fix

#3359 Fix #3353: check if any results are returned in sqlite api wrapper before looking at the chunk
  test/issues/fuzz/sqlite_wrapper_crash.test
  tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp
Labels: bug-fix

#3360 Fix #3354: add missing recursive CTE node traversal in correlated subquery flattening
  src/planner/expression_iterator.cpp
  test/issues/fuzz/recursive_view_expression_assertion.test
Labels: bug-fix

#3356 Fix #3350: correctly update statistics after a SINGLE join, since SINGLE joins may introduce NULL values
  src/execution/operator/join/physical_comparison_join.cpp
  src/optimizer/statistics/operator/propagate_join.cpp
  test/issues/fuzz/encode_string_data_crash.test
Labels: bug-fix

#3357 Fix #3351: avoid double-binding functions in subqueries after an initial binding error
  src/planner/binder/expression/bind_columnref_expression.cpp
  src/planner/binder/expression/bind_function_expression.cpp
  src/planner/binder/expression/bind_operator_expression.cpp
  test/issues/fuzz/function_pointer_crash_in_subquery.test
Labels: bug-fix

#3378 Correctly handle rowid scans in Julia DataFrame scan (for COUNT(*))
  tools/juliapkg/src/data_frame_scan.jl
  tools/juliapkg/test/test_df_scan.jl
Labels: bug-fix

#3380 ArgMinMax: correctly manage memory of strings in both values and arguments
  src/function/aggregate/distributive/arg_min_max.cpp
  test/issues/fuzz/argminmax_strings.test
  test/sql/aggregate/aggregates/test_arg_min_max_strings.test
Labels: bug-fix

#3342 Issue #1423: IEJoin Performance Improvements
  src/execution/operator/join/physical_iejoin.cpp
Labels: enhancement

#3408 Add comma to exported create index sql stmt
  src/catalog/catalog_entry/index_catalog_entry.cpp
  test/sql/index/test_index_import.test
Labels: bug-fix

#3345 Small list aggregate fix
  src/function/aggregate/nested/histogram.cpp
  src/function/scalar/list/list_aggregates.cpp
  test/sql/aggregate/aggregates/test_histogram.test
  test/sql/function/list/aggregates/histogram.test
  test/sql/function/list/aggregates/incorrect.test
  test/sql/function/list/aggregates/max.test
  test/sql/function/list/aggregates/min.test
  test/sql/function/list/aggregates/types.test
Labels: Test, bug-fix

#3427 Fix crash that occurred when performing delete after a DROP COLUMN
  src/storage/data_table.cpp
  test/sql/alter/drop_col/test_drop_col_operations.test
Labels: bug-fix

#3436 Change the granularity of SetAllValid/SetAllInvalid of validity_mask to bit, fix #3127
  src/include/duckdb/common/types/validity_mask.hpp
  test/issues/general/test_3127.test
Labels: bug-fix, Merge After Feature Freeze

#3463 Fixing list_contains bug
  src/function/scalar/list/contains_or_position.cpp
  test/sql/function/list/list_contains.test
Labels: bug-fix

#3472 Fix #3471: correctly detect overflow in statistics propagation of hugeints
  src/function/scalar/operators/subtract.cpp
  src/include/duckdb/common/operator/subtract.hpp
  src/optimizer/statistics/expression/propagate_and_compress.cpp
  test/sql/order/hugeint_order_by_extremes.test
Labels: bug-fix

#3476 Issue #3466: Remove True Statistics
  src/optimizer/statistics/operator/propagate_join.cpp
  test/sql/join/inner/test_join_perfect_hash.test
Labels: bug-fix

#3491 Issue #3486: IEJoin Missing Continue
  src/execution/operator/join/physical_iejoin.cpp
  test/sql/join/iejoin/test_iejoin.test
Labels: bug-fix

#3454 CMake install DLL file on Windows platform
  src/CMakeLists.txt
Labels: Merge After Feature Freeze

#3456 Add C API functions to build list/map types and read map types
  src/include/duckdb.h
  src/main/capi/logical_types-c.cpp
  test/api/capi/test_capi_data_chunk.cpp
Labels: enhancement, Merge After Feature Freeze

#3405 Issue 3403: Logical Type Append
  extension/tpcds/dsdgen/append_info-c.cpp
  src/main/appender.cpp
  test/api/capi/test_capi_appender.cpp
Labels: enhancement, API, Merge After Feature Freeze

#3386 Issue #3384: DATE_TRUNC for INTERVAL
  src/function/scalar/date/date_trunc.cpp
  test/sql/function/interval/test_interval_trunc.test
Labels: enhancement, Merge After Feature Freeze

#3346 list_sort function support
  src/common/types/vector.cpp
  src/common/vector_operations/vector_copy.cpp
  src/function/scalar/list/CMakeLists.txt
  src/function/scalar/list/list_sort.cpp
  src/function/scalar/nested_functions.cpp
  src/include/duckdb/function/scalar/nested_functions.hpp
  test/sql/function/list/list_sort.test
Labels: bug-fix, feature, Merge After Feature Freeze

#3382 Fixing python dependency memory leaks
  .github/workflows/CodeQuality.yml
  .github/workflows/Python.yml
  src/include/duckdb/main/client_context.hpp
  src/include/duckdb/main/external_dependencies.hpp
  src/include/duckdb/main/relation.hpp
  src/main/relation.cpp
  tools/pythonpkg/cibw.toml
  tools/pythonpkg/requirements-dev.txt
  tools/pythonpkg/src/include/duckdb_python/pyconnection.hpp
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/tests/fast/test_relation_dependency_leak.py
Labels: bug-fix, Merge After Feature Freeze

#3464 CSVReader option 'ignore_errors'
  src/execution/operator/persistent/buffered_csv_reader.cpp
  src/function/table/copy_csv.cpp
  src/include/duckdb/execution/operator/persistent/buffered_csv_reader.hpp
  test/sql/copy/csv/data/test/error_invalid_type.csv
  test/sql/copy/csv/data/test/error_too_little.csv
  test/sql/copy/csv/data/test/error_too_little_end_of_filled_chunk.csv
  test/sql/copy/csv/data/test/error_too_little_single.csv
  test/sql/copy/csv/data/test/error_too_many.csv
  test/sql/copy/csv/data/test/test_incompatible_type_with_nullable.csv
  test/sql/copy/csv/test_ignore_errors.test
  test/sql/copy/csv/test_ignore_errors_end_of_chunk.test
Labels: enhancement, Merge After Feature Freeze

#3420 Expose get table names from conn to python
  tools/pythonpkg/src/include/duckdb_python/pyconnection.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/test_get_table_names.py
Labels: enhancement, Merge After Feature Freeze

#3460 Issue #3411: PhysicalRangeJoin
  src/common/sort/sort_state.cpp
  src/execution/operator/join/CMakeLists.txt
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/operator/join/physical_piecewise_merge_join.cpp
  src/execution/operator/join/physical_range_join.cpp
  src/include/duckdb/common/sort/sort.hpp
  src/include/duckdb/execution/operator/join/physical_iejoin.hpp
  src/include/duckdb/execution/operator/join/physical_piecewise_merge_join.hpp
  src/include/duckdb/execution/operator/join/physical_range_join.hpp
Labels: enhancement

#3389 Issue #3187: Implement strptime_icu
  extension/icu/CMakeLists.txt
  extension/icu/icu-datefunc.cpp
  extension/icu/icu-extension.cpp
  extension/icu/icu-makedate.cpp
  extension/icu/icu-strptime.cpp
  extension/icu/icu_config.py
  extension/icu/include/icu-datefunc.hpp
  extension/icu/include/icu-strptime.hpp
  src/function/scalar/date/strftime.cpp
  src/include/duckdb/function/scalar/strftime.hpp
  test/sql/function/timestamp/test_icu_strftime.test
  test/sql/function/timestamp/test_icu_strptime.test
  test/sql/function/timestamp/test_strptime.test
Labels: enhancement

#3435 Add support for reading newline-delimited JSON
  data/json/example.ndjson
  extension/json/json-extension.cpp
  src/catalog/default/default_functions.cpp
  src/execution/operator/persistent/buffered_csv_reader.cpp
  src/include/duckdb/catalog/default/default_functions.hpp
  src/include/duckdb/function/table_macro_function.hpp
  src/include/duckdb/parser/tableref/table_function_ref.hpp
  src/parser/tableref/table_function.cpp
  src/planner/binder/tableref/bind_table_function.cpp
  test/sql/json/read_ndjson.test
Labels: enhancement, Merge After Feature Freeze

#3375 Rebind prepared statements in case of type ambiguities, rather than default to VARCHAR
  extension/icu/icu-dateadd.cpp
  extension/icu/icu-strptime.cpp
  src/common/symbols.cpp
  src/execution/physical_plan/plan_execute.cpp
  src/function/cast_rules.cpp
  src/function/function.cpp
  src/function/scalar/list/array_slice.cpp
  src/function/scalar/list/contains_or_position.cpp
  src/function/scalar/list/flatten.cpp
  src/function/scalar/list/list_aggregates.cpp
  src/function/scalar/list/list_concat.cpp
  src/function/scalar/list/list_extract.cpp
  src/function/scalar/list/list_value.cpp
  src/function/scalar/string/printf.cpp
  src/function/scalar/struct/struct_pack.cpp
  src/include/duckdb/execution/operator/helper/physical_execute.hpp
  src/include/duckdb/function/aggregate_function.hpp
  src/include/duckdb/function/function.hpp
  src/include/duckdb/function/scalar_function.hpp
  src/include/duckdb/main/client_context.hpp
  src/include/duckdb/main/prepared_statement_data.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/expression_binder.hpp
  src/include/duckdb/planner/planner.hpp
  src/main/client_context.cpp
  src/main/prepared_statement_data.cpp
  src/planner/binder.cpp
  src/planner/binder/expression/bind_aggregate_expression.cpp
  src/planner/binder/expression/bind_case_expression.cpp
  src/planner/binder/expression/bind_comparison_expression.cpp
  src/planner/binder/expression/bind_operator_expression.cpp
  src/planner/binder/expression/bind_parameter_expression.cpp
  src/planner/binder/expression/bind_subquery_expression.cpp
  src/planner/expression_binder.cpp
  src/planner/planner.cpp
  test/api/test_prepared_api.cpp
  test/issues/fuzz/prepared_statement_crash.test
  test/issues/general/test_2416.test
  test/sql/prepared/prepare_default_varchar.test
  test/sql/prepared/prepare_list_functions.test
  test/sql/prepared/prepare_window_functions.test
  test/sql/prepared/test_prepare_ambiguous_type.test
  tools/juliapkg/test/test_prepare.jl
  tools/pythonpkg/tests/fast/test_ambiguous_prepare.py
  tools/rpkg/src/statement.cpp
  tools/rpkg/tests/testthat/test_ambiguous_prepare.R
Labels: enhancement

#3514 Issue #3453: Window Partition Collections
  benchmark/micro/window/window_partition.benchmark
  src/execution/operator/aggregate/physical_window.cpp
Labels: enhancement
