Repository duckdb/duckdb, pull requests merged in 2022-11, with the labels that each got.

#5147 String to struct cast
  benchmark/micro/cast/cast_string_struct.benchmark
  benchmark/micro/cast/cast_string_struct_missing_val.benchmark
  src/function/cast/string_cast.cpp
  src/function/cast/struct_cast.cpp
  src/function/cast/vector_cast_helpers.cpp
  src/include/duckdb/function/cast/default_casts.hpp
  src/include/duckdb/function/cast/vector_cast_helpers.hpp
  test/common/test_cast_struct.test
  test/sql/cast/string_to_list_cast.test
  test/sql/cast/string_to_nested_types_cast.test_slow
  test/sql/cast/string_to_struct_cast.test
Labels: Merge After Feature Freeze

#5216 Adding total_uncompressed_size to parquet column chunk metadata
  extension/parquet/column_writer.cpp
  test/sql/copy/parquet/parquet_5209.test
Labels: bug-fix

#5260 Issue #5258: Inverse Percentile NULLs
  src/planner/binder/expression/bind_aggregate_expression.cpp
  test/sql/aggregate/aggregates/test_ordered_aggregates.test
Labels: bug-fix

#5229 Issue #5205: TIMESTAMPTZ Casting
  extension/icu/icu-strptime.cpp
  src/common/operator/cast_operators.cpp
  src/common/types/date.cpp
  src/common/types/timestamp.cpp
  src/include/duckdb/common/types/date.hpp
  src/include/duckdb/common/types/timestamp.hpp
  test/sql/function/timestamp/current_timestamp.test
  test/sql/function/timestamp/test_icu_age.test
  test/sql/function/timestamp/test_icu_dateadd.test
  test/sql/function/timestamp/test_icu_datediff.test
  test/sql/function/timestamp/test_icu_datepart.test
  test/sql/function/timestamp/test_icu_datetrunc.test
  test/sql/function/timestamp/test_icu_makedate.test
  test/sql/function/timestamp/test_icu_strftime.test
  test/sql/function/timestamp/test_icu_strptime.test
  test/sql/timezone/test_icu_calendar.test
  test/sql/timezone/test_icu_timezone.test
  tools/pythonpkg/tests/fast/test_all_types.py
Labels: bug-fix

#5333 Shared ColumnDataAllocator: hold lock for just a bit longer
  src/common/types/column_data_allocator.cpp
  src/include/duckdb/common/types/column_data_allocator.hpp
Labels: bug-fix

#4961 Use structs to avoid confusing C pointer wrappers
  src/include/duckdb.h
  src/main/capi/data_chunk-c.cpp
  src/main/capi/duckdb_value-c.cpp
  src/main/capi/logical_types-c.cpp
  src/main/capi/result-c.cpp
  src/main/capi/table_function-c.cpp
Labels: Merge After Feature Freeze

#5185 R: code format
  tools/rpkg/R/Connection.R
  tools/rpkg/R/Driver.R
  tools/rpkg/R/Viewer.R
  tools/rpkg/R/backend-dbplyr__duckdb_connection.R
  tools/rpkg/R/dbConnect__duckdb_driver.R
  tools/rpkg/R/register.R
  tools/rpkg/R/relational.R
  tools/rpkg/R/substrait.R
  tools/rpkg/tests/regression/helpers.R
  tools/rpkg/tests/regression/perf_regression.R
  tools/rpkg/tests/testthat/test-DBItest.R
  tools/rpkg/tests/testthat/test_arrow.R
  tools/rpkg/tests/testthat/test_arrow_stream.R
  tools/rpkg/tests/testthat/test_backend-dbplyr__duckdb_connection.R
  tools/rpkg/tests/testthat/test_config_keyvalue.R
  tools/rpkg/tests/testthat/test_extensions.R
  tools/rpkg/tests/testthat/test_factor.R
  tools/rpkg/tests/testthat/test_fetch.R
  tools/rpkg/tests/testthat/test_fetch_arrow.R
  tools/rpkg/tests/testthat/test_integer64.R
  tools/rpkg/tests/testthat/test_interval.R
  tools/rpkg/tests/testthat/test_register.R
  tools/rpkg/tests/testthat/test_register_arrow.R
  tools/rpkg/tests/testthat/test_relational.R
  tools/rpkg/tests/testthat/test_struct.R
Labels: Merge After Feature Freeze

#5382 Issue #5342: DATE_PART Struct Indexing
  extension/icu/icu-datepart.cpp
  src/function/scalar/date/date_part.cpp
  test/sql/copy/csv/auto/test_csv_auto.test
  test/sql/function/date/test_date_part.test
  test/sql/function/timestamp/test_icu_datepart.test
Labels: bug, Silver Foundation Member

#5334 Add starts_with function and operator
  src/function/scalar/string/CMakeLists.txt
  src/function/scalar/string/starts_with.cpp
  src/function/scalar/string_functions.cpp
  src/include/duckdb/function/scalar/string_functions.hpp
  test/sql/function/string/test_starts_with_function.test
  test/sql/function/string/test_starts_with_function_utf8.test
  test/sql/function/string/test_starts_with_operator.test
  test/sql/function/string/test_starts_with_operator_utf8.test
Labels: feature

#5337 Feature: Allow binary-formatted strings to be cast to integers
  src/common/operator/cast_operators.cpp
  test/sql/cast/test_string_binary_cast.test
Labels: feature, Merge After Feature Freeze

#5442 Issue #5366: QUANTILE_DISC Intervals
  src/function/aggregate/holistic/quantile.cpp
  test/sql/aggregate/aggregates/test_quantile_disc.test
  test/sql/aggregate/aggregates/test_quantile_disc_list.test
  test/sql/types/nested/list/list_aggr_parameter.test
  test/sql/types/timestamp/test_infinite_time.test
  test/sql/window/test_quantile_window.test
Labels: bug-fix

#5456 Issue #5277: Sorted Aggregate Sorting
  benchmark/micro/aggregate/quantile/quantile_many.benchmark
  src/common/types/chunk_collection.cpp
  src/function/aggregate/sorted_aggregate_function.cpp
  src/include/duckdb/common/types/chunk_collection.hpp
  src/include/duckdb/planner/bound_result_modifier.hpp
  src/parser/transform/helpers/transform_orderby.cpp
  src/planner/bound_result_modifier.cpp
  test/sql/parser/test_columns.test
Labels: enhancement
