Repository duckdb/duckdb, pull requests merged in 2022-10, with the labels that each got.

#4945 Issue #4942: Check DESC Errors
  src/planner/binder/expression/bind_aggregate_expression.cpp
  test/sql/aggregate/aggregates/test_ordered_aggregates.test
Labels: bug-fix

#4948 Issue #4944: Negative Unpadded Centuries
  src/function/scalar/date/strftime.cpp
  test/sql/function/date/test_strftime_exhaustive.test
Labels: bug-fix

#4910 Bug fix for segmentation fault in list apply
  src/function/scalar/list/list_lambdas.cpp
  test/sql/function/list/lambdas/transform.test
Labels: bug-fix

#4633 [Python] Optional Pandas Date as datetime
  tools/pythonpkg/clean.sh
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/src/include/duckdb_python/pyconnection.hpp
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/include/duckdb_python/pyresult.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/src/pyresult.cpp
  tools/pythonpkg/tests/fast/pandas/test_date_as_datetime.py
  tools/pythonpkg/tests/fast/pandas/test_fetch_df_chunk.py
Labels: Python

#5007 Fix lambda bug for struct extract
  src/planner/binder/expression/bind_columnref_expression.cpp
  test/sql/function/list/lambdas/transform.test
Labels: bug-fix

#5010 Correctly handle NULL values in compound ART keys
  src/execution/index/art/art.cpp
  src/execution/physical_plan/plan_create_index.cpp
  test/sql/index/art/test_art_create_index.test
Labels: bug-fix

#5024 Issue #5023: Fully Parallel Partitioning
  src/execution/operator/aggregate/physical_window.cpp
Labels: enhancement
