Repository duckdb/duckdb, pull requests merged in 2022-06, with the labels that each got.

#3765 Issue #3759: Node Time Zone
  tools/nodejs/src/statement.cpp
  tools/nodejs/test/data_type_support.test.js
Labels: enhancement

#3751 Decreasing the overallocation for list aggregates
  src/common/types/vector.cpp
  src/common/types/vector_buffer.cpp
  src/function/aggregate/nested/list.cpp
  test/sql/aggregate/aggregates/test_list_aggregate.test
Labels: enhancement

#3736 JDBC better error handling
  tools/jdbc/src/jni/duckdb_java.cpp
  tools/jdbc/src/main/java/org/duckdb/DuckDBColumnType.java
  tools/jdbc/src/main/java/org/duckdb/DuckDBNative.java
  tools/jdbc/src/main/java/org/duckdb/DuckDBPreparedStatement.java
  tools/jdbc/src/main/java/org/duckdb/DuckDBResultSet.java
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
Labels: enhancement, JDBC

#3778 More node types
  tools/nodejs/src/statement.cpp
  tools/nodejs/test/data_type_support.test.js
Labels: Type

#3739 DuckDBPyRelation: support `offset` argument for `limit()`
  examples/python/duckdb-python.py
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/tests/fast/test_relation.py
Labels: enhancement, Python

#3749 Query cancellation with CTRL-C for Python client
  tools/pythonpkg/src/pyconnection.cpp
Labels: Python, feature

#3498 Relational API basics for R client
  src/common/enums/expression_type.cpp
  src/common/types.cpp
  src/common/types/value.cpp
  src/common/types/vector.cpp
  src/common/vector_operations/vector_cast.cpp
  src/include/duckdb/common/enums/expression_type.hpp
  src/include/duckdb/common/types.hpp
  src/include/duckdb/parser/transformer.hpp
  src/main/query_result.cpp
  src/main/relation.cpp
  src/parser/transform/expression/transform_operator.cpp
  tools/rpkg/.gitignore
  tools/rpkg/CMakeLists.txt
  tools/rpkg/NAMESPACE
  tools/rpkg/R/Result.R
  tools/rpkg/R/backend-dbplyr__duckdb_connection.R
  tools/rpkg/R/cpp11.R
  tools/rpkg/R/relational.R
  tools/rpkg/clean.sh
  tools/rpkg/man/backend-duckdb.Rd
  tools/rpkg/man/expr_constant.Rd
  tools/rpkg/man/expr_function.Rd
  tools/rpkg/man/expr_reference.Rd
  tools/rpkg/man/expr_set_alias.Rd
  tools/rpkg/man/expr_tostring.Rd
  tools/rpkg/man/rel_aggregate.Rd
  tools/rpkg/man/rel_alias.Rd
  tools/rpkg/man/rel_distinct.Rd
  tools/rpkg/man/rel_explain.Rd
  tools/rpkg/man/rel_filter.Rd
  tools/rpkg/man/rel_from_df.Rd
  tools/rpkg/man/rel_inner_join.Rd
  tools/rpkg/man/rel_order.Rd
  tools/rpkg/man/rel_project.Rd
  tools/rpkg/man/rel_set_alias.Rd
  tools/rpkg/man/rel_sql.Rd
  tools/rpkg/src/Makevars.in
  tools/rpkg/src/cpp11.cpp
  tools/rpkg/src/include/rapi.hpp
  tools/rpkg/src/relational.cpp
  tools/rpkg/src/scan.cpp
  tools/rpkg/src/statement.cpp
  tools/rpkg/src/utils.cpp
  tools/rpkg/tests/testthat/_snaps/explain.md
  tools/rpkg/tests/testthat/_snaps/multi_statement.md
  tools/rpkg/tests/testthat/test_arrow_stream.R
  tools/rpkg/tests/testthat/test_relational.R
Labels: API, R

#3776 Simplify `clangd` target
  .clangd
  Makefile
Labels: feature

#3495 R: support structs
  tools/rpkg/DESCRIPTION
  tools/rpkg/R/Result.R
  tools/rpkg/R/dbBind__duckdb_result.R
  tools/rpkg/R/dbFetch__duckdb_result.R
  tools/rpkg/src/include/rapi.hpp
  tools/rpkg/src/statement.cpp
  tools/rpkg/src/utils.cpp
  tools/rpkg/tests/testthat/test_struct.R
Labels: Type, R

#3620 HTTP read optimization
  extension/httpfs/httpfs.cpp
  extension/httpfs/include/s3fs.hpp
  extension/parquet/column_reader.cpp
  extension/parquet/include/cast_column_reader.hpp
  extension/parquet/include/column_reader.hpp
  extension/parquet/include/list_column_reader.hpp
  extension/parquet/include/parquet_reader.hpp
  extension/parquet/include/struct_column_reader.hpp
  extension/parquet/include/thrift_tools.hpp
  extension/parquet/parquet_reader.cpp
  src/execution/operator/persistent/buffered_csv_reader.cpp
  src/include/duckdb/execution/operator/persistent/buffered_csv_reader.hpp
  test/sql/copy/csv/test_csv_remote.test_slow
  test/sql/copy/csv/test_max_line_size.test_slow
  test/sql/copy/parquet/parquet_http_prefetch.test
  test/sql/copy/parquet/test_parquet_remote_foreign_files.test
  test/sql/copy/s3/parquet_s3_tpcds.test_slow
  test/sql/copy/s3/parquet_s3_tpch.test_slow
Labels: enhancement, Parquet, CSV

#3852 Added support for generated columns to TableCatalogEntry->ToSQL()
  src/catalog/catalog_entry/table_catalog_entry.cpp
  test/sql/export/export_generated_columns.test
Labels: bug-fix

#3842 Allow to use custom memory allocator through DuckDB API on Windows
  src/include/duckdb/common/allocator.hpp
Labels: feature

#3865 Fix #3860: add support for creating foreign keys on temporary tables, and for now disable support for cross-schema foreign keys
  src/catalog/catalog_entry/table_catalog_entry.cpp
  src/planner/binder/statement/bind_create.cpp
  test/sql/constraints/foreignkey/test_fk_cross_schema.test
  test/sql/constraints/foreignkey/test_fk_temporary.test
  test/sql/storage/constraints/foreignkey/foreign_key_persistent.test
Labels: bug-fix

#3899 R: Check query return type instead of query type in dbFetch()
  src/common/enums/statement_type.cpp
  src/include/duckdb/common/enums/statement_type.hpp
  tools/rpkg/R/dbFetch__duckdb_result.R
  tools/rpkg/src/statement.cpp
  tools/rpkg/tests/testthat/test_fetch.R
Labels: R

#3898 Issue #3880: Rebind DATE_TRUNC dates
  src/function/scalar/date/date_trunc.cpp
  test/sql/function/date/test_date_trunc.test
Labels: enhancement

#3901 R: Extract DetectLogicalType() function
  tools/rpkg/src/include/typesr.hpp
  tools/rpkg/src/statement.cpp
  tools/rpkg/src/types.cpp
Labels: R

#3903 Issue #3881: DATE_TRUNC statistics
  src/function/scalar/date/date_trunc.cpp
  test/sql/function/date/test_date_trunc.test
Labels: enhancement

#3909 More fuzzer fixes
  src/common/operator/string_cast.cpp
  src/common/types/interval.cpp
  src/common/types/vector.cpp
  src/function/scalar/date/strftime.cpp
  src/include/duckdb/function/scalar/strftime.hpp
  test/fuzzer/sqlsmith/strptime_nullpointer.test
  test/fuzzer/sqlsmith/struct_verify_crash.test
  test/fuzzer/sqlsmith/timestamp_diff_overflow.test
  test/sql/function/timestamp/test_strptime.test
  test/sql/types/timestamp/test_infinite_time.test
Labels: bug

#3939 Issue #3937: Casting infinite times
  src/common/operator/cast_operators.cpp
  src/common/operator/string_cast.cpp
  src/common/types/date.cpp
  src/common/types/timestamp.cpp
  src/include/duckdb/common/types/date.hpp
  test/sql/types/timestamp/test_infinite_time.test
Labels: bug

#3618 Struct Types for Node.js UDFs
  tools/CMakeLists.txt
  tools/nodejs/CMakeLists.txt
  tools/nodejs/Makefile
  tools/nodejs/binding.gyp
  tools/nodejs/lib/duckdb.js
  tools/nodejs/src/connection.cpp
  tools/nodejs/src/data_chunk.cpp
  tools/nodejs/src/database.cpp
  tools/nodejs/src/duckdb_node.hpp
  tools/nodejs/src/statement.cpp
  tools/nodejs/test/udf.test.js
Labels: Type, feature
