Repository duckdb/duckdb, pull requests merged in 2022-02, with the labels that each got.

#3012 Fix #2999: Support ANY_JOIN in flattening correlated subqueries
  src/optimizer/statistics/operator/propagate_filter.cpp
  src/planner/subquery/flatten_dependent_join.cpp
  test/sql/subquery/any_all/issue_2999.test
  test/sql/subquery/scalar/test_subquery_any_join.test
Labels: bug-fix

#3000 Lookup parent frames for replacement scans
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/test_replacement_scan.py
Labels: bug-fix

#3013 Fix #3005: correctly normalify vector in array_slice
  src/function/scalar/list/array_slice.cpp
  test/sql/cte/recursive_array_slice.test
Labels: bug-fix

#3014 Issue #2908: UTF8 BOM Headers
  src/execution/operator/persistent/buffered_csv_reader.cpp
  test/sql/copy/csv/auto/test_header_detection.test
  test/sql/copy/csv/data/auto/utf8bom.csv
Labels: CSV, bug-fix

#3024 Issue #3023: Simple filtered aggregates
  src/execution/operator/aggregate/physical_simple_aggregate.cpp
  test/sql/aggregate/aggregates/test_simple_filter.test
Labels: bug-fix

#3028 Install covr from main development branch
  tools/rpkg/dependencies.R
Labels: R

#3021 Move install_extension test to test_slow
  test/extension/install_extension.test_slow
Labels: Test

#3041 Fix #3017: detect recursive view construction and throw an appropriate error
  src/include/duckdb/planner/binder.hpp
  src/planner/binder.cpp
  src/planner/binder/tableref/bind_basetableref.cpp
  test/sql/catalog/view/recursive_view.test
Labels: bug-fix

#3026 Issue #2965: CTE parameter binding
  src/include/duckdb/parser/sql_statement.hpp
  src/include/duckdb/parser/statement/alter_statement.hpp
  src/include/duckdb/parser/statement/call_statement.hpp
  src/include/duckdb/parser/statement/copy_statement.hpp
  src/include/duckdb/parser/statement/create_statement.hpp
  src/include/duckdb/parser/statement/delete_statement.hpp
  src/include/duckdb/parser/statement/drop_statement.hpp
  src/include/duckdb/parser/statement/execute_statement.hpp
  src/include/duckdb/parser/statement/explain_statement.hpp
  src/include/duckdb/parser/statement/export_statement.hpp
  src/include/duckdb/parser/statement/insert_statement.hpp
  src/include/duckdb/parser/statement/load_statement.hpp
  src/include/duckdb/parser/statement/pragma_statement.hpp
  src/include/duckdb/parser/statement/prepare_statement.hpp
  src/include/duckdb/parser/statement/relation_statement.hpp
  src/include/duckdb/parser/statement/select_statement.hpp
  src/include/duckdb/parser/statement/set_statement.hpp
  src/include/duckdb/parser/statement/show_statement.hpp
  src/include/duckdb/parser/statement/transaction_statement.hpp
  src/include/duckdb/parser/statement/update_statement.hpp
  src/include/duckdb/parser/statement/vacuum_statement.hpp
  src/include/duckdb/parser/transformer.hpp
  src/main/prepared_statement_data.cpp
  src/parser/statement/alter_statement.cpp
  src/parser/statement/call_statement.cpp
  src/parser/statement/copy_statement.cpp
  src/parser/statement/create_statement.cpp
  src/parser/statement/delete_statement.cpp
  src/parser/statement/drop_statement.cpp
  src/parser/statement/execute_statement.cpp
  src/parser/statement/explain_statement.cpp
  src/parser/statement/export_statement.cpp
  src/parser/statement/insert_statement.cpp
  src/parser/statement/load_statement.cpp
  src/parser/statement/pragma_statement.cpp
  src/parser/statement/prepare_statement.cpp
  src/parser/statement/relation_statement.cpp
  src/parser/statement/select_statement.cpp
  src/parser/statement/set_statement.cpp
  src/parser/statement/show_statement.cpp
  src/parser/statement/transaction_statement.cpp
  src/parser/statement/update_statement.cpp
  src/parser/statement/vacuum_statement.cpp
  src/parser/transform/statement/transform_rename.cpp
  src/parser/transformer.cpp
  src/planner/planner.cpp
  test/sql/prepared/test_prepare_unused_cte.test
Labels: bug-fix, Foundation Member

#3042 Issue #3029: Prevent CURRENT_QUERY folding
  src/function/scalar/system/system_functions.cpp
  tools/shell/shell-test.py
Labels: bug-fix

#3040 Fix #3015: fix edge case issue with many null values in physical Top N
  data/parquet-testing/orders_small_parquet.test
  src/common/vector_operations/is_distinct_from.cpp
  src/execution/operator/order/physical_top_n.cpp
  test/sql/order/top_n_nulls.test
Labels: bug-fix

#3039 Update Java DuckDBAppender to allow appending null values - fixes issue 3035
  tools/jdbc/src/jni/duckdb_java.cpp
  tools/jdbc/src/main/java/org/duckdb/DuckDBAppender.java
  tools/jdbc/src/main/java/org/duckdb/DuckDBNative.java
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
Labels: bug-fix

#3045 fix for STRING_AGG(...) failing (vector type mismatch) assertion when used with DISTINCT and ORDER BY inside STRING_AGG.
  src/execution/aggregate_hashtable.cpp
  test/sql/aggregate/aggregates/test_aggregate_types.test
  test/sql/aggregate/aggregates/test_aggregate_types_scalar.test
Labels: bug-fix

#3060 Issue #3056: Null list scatter
  src/common/row_operations/row_scatter.cpp
  test/sql/aggregate/distinct/test_distinct.test
Labels: bug-fix

#2998 Support explicit aggregate state export, re-combination and finalisation
  src/common/types.cpp
  src/common/types/vector.cpp
  src/function/scalar/system/CMakeLists.txt
  src/function/scalar/system/aggregate_export.cpp
  src/function/scalar/system/system_functions.cpp
  src/include/duckdb/common/types.hpp
  src/include/duckdb/function/scalar/generic_functions.hpp
  src/include/duckdb/parser/expression/function_expression.hpp
  src/parser/expression/function_expression.cpp
  src/parser/transform/expression/transform_function.cpp
  src/planner/binder/expression/bind_aggregate_expression.cpp
  test/sql/aggregate/aggregates/test_state_export.test
  third_party/libpg_query/grammar/keywords/unreserved_keywords.list
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/grammar/types/select.yh
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/include/parser/kwlist.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: feature

#3007 Feature: Add support for Excel text format (Update #2996)
  .github/workflows/LinuxRelease.yml
  .github/workflows/Main.yml
  .github/workflows/OSX.yml
  .github/workflows/Windows.yml
  CMakeLists.txt
  Makefile
  extension/CMakeLists.txt
  extension/excel/CMakeLists.txt
  extension/excel/excel-extension.cpp
  extension/excel/excel_config.py
  extension/excel/include/excel-extension.hpp
  extension/excel/numformat/CMakeLists.txt
  extension/excel/numformat/LICENSE
  extension/excel/numformat/include/nf_calendar.h
  extension/excel/numformat/include/nf_localedata.h
  extension/excel/numformat/include/nf_zformat.h
  extension/excel/numformat/nf_calendar.cpp
  extension/excel/numformat/nf_localedata.cpp
  extension/excel/numformat/nf_zformat.cpp
  scripts/format.py
  src/main/extension/extension_helper.cpp
  test/extension/install_extension.test_slow
  test/sql/excel/test_excel_numformat.test
  tools/pythonpkg/setup.py
Labels: feature

#3030 Macros for floored division and modulo
  src/catalog/default/default_functions.cpp
  test/sql/function/numeric/test_fdiv_fmod.test
Labels: feature

#3077 Issue 2498: Consistent NULL hashing
  src/common/vector_operations/vector_hash.cpp
  src/function/scalar/generic/CMakeLists.txt
  src/function/scalar/generic/hash.cpp
  src/function/scalar/generic_functions.cpp
  src/include/duckdb/function/scalar/generic_functions.hpp
  test/sql/function/generic/hash_func.test
Labels: enhancement

#2926 DuckDB SQL backend for dbplyr
  tools/rpkg/NAMESPACE
  tools/rpkg/R/backend-dbplyr__duckdb_connection.R
  tools/rpkg/R/s3_register.R
  tools/rpkg/R/zzz.R
  tools/rpkg/man/backend-duckdb.Rd
  tools/rpkg/tests/testthat/_snaps/backend-dbplyr__duckdb_connection.md
  tools/rpkg/tests/testthat/test_backend-dbplyr__duckdb_connection.R
Labels: feature

#3111 Issue #3105: Simple filtered aggregates
  src/execution/operator/aggregate/physical_simple_aggregate.cpp
  test/sql/aggregate/aggregates/test_simple_filter.test
Labels: bug-fix

#2985 Issue #2590: Add overwrite flag to CSV copy, overwrite only if query completes
  extension/parquet/parquet-extension.cpp
  src/common/file_system.cpp
  src/common/local_file_system.cpp
  src/execution/operator/persistent/physical_copy_to_file.cpp
  src/execution/physical_plan/plan_copy_to_file.cpp
  src/function/table/copy_csv.cpp
  src/include/duckdb/common/file_system.hpp
  src/include/duckdb/common/local_file_system.hpp
  src/include/duckdb/common/virtual_file_system.hpp
  src/include/duckdb/execution/operator/persistent/physical_copy_to_file.hpp
  src/include/duckdb/function/copy_function.hpp
  src/include/duckdb/planner/operator/logical_copy_to_file.hpp
  src/planner/binder/statement/bind_copy.cpp
  test/sql/copy/csv/overwrite/test_copy_overwrite.test
  test/sql/copy/csv/overwrite/test_overwrite_pipe_linux.test
  test/sql/copy/csv/overwrite/test_overwrite_pipe_windows.test
  test/sql/copy/csv/test_copy_overwrite.test
  test/sql/copy/parquet/writer/test_copy_overwrite_parquet.test
Labels: feature
