Repository duckdb/duckdb, pull requests merged in 2022-03, with the labels that each got.

#3219 Issue #1423: IEJoin Implementation
  benchmark/micro/join/iejoin_employees.benchmark
  src/common/enums/physical_operator_type.cpp
  src/common/sort/sorted_block.cpp
  src/common/types/data_chunk.cpp
  src/common/vector_operations/null_operations.cpp
  src/execution/operator/join/CMakeLists.txt
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/operator/join/physical_piecewise_merge_join.cpp
  src/execution/physical_plan/plan_comparison_join.cpp
  src/include/duckdb/common/enums/physical_operator_type.hpp
  src/include/duckdb/common/sort/sorted_block.hpp
  src/include/duckdb/common/vector_operations/vector_operations.hpp
  src/include/duckdb/execution/operator/join/physical_iejoin.hpp
  src/main/query_profiler.cpp
  src/parallel/executor.cpp
  test/sql/join/iejoin/overlap.left.csv
  test/sql/join/iejoin/overlap.right.csv
  test/sql/join/iejoin/test_iejoin.test
  test/sql/join/iejoin/test_iejoin_east_west.test
  test/sql/join/iejoin/test_iejoin_events.test
  test/sql/join/iejoin/test_iejoin_overlaps.test
  test/sql/join/iejoin/test_iejoin_sort_tasks.test_slow
Labels: feature

#3308 Cleanup some unused include
  src/execution/aggregate_hashtable.cpp
  src/execution/expression_executor/execute_case.cpp
  src/execution/join_hashtable.cpp
  src/execution/perfect_aggregate_hashtable.cpp
  src/execution/window_segment_tree.cpp
  src/function/scalar_macro_function.cpp
  src/function/table/arrow.cpp
  src/function/table/copy_csv.cpp
  src/function/table/pragma_detailed_profiling_output.cpp
  src/function/table/read_csv.cpp
  src/main/appender.cpp
  src/main/capi/prepared-c.cpp
  src/main/client_context.cpp
  src/main/query_profiler.cpp
  src/main/relation/create_table_relation.cpp
  src/main/relation/create_view_relation.cpp
  src/storage/checkpoint_manager.cpp
  src/storage/wal_replay.cpp
  src/storage/write_ahead_log.cpp
Labels: enhancement

#3311 Fix #3272: avoid incorrectly moving LIMIT to before the ORDER clause in certain cases
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/expression_binder/order_binder.hpp
  src/planner/binder/query_node/bind_select_node.cpp
  src/planner/binder/query_node/plan_select_node.cpp
  src/planner/expression_binder/order_binder.cpp
  test/sql/order/limit_parameter.test
Labels: bug-fix

#3312 Issue #3290: Histogram Temporal Bindings
  src/function/aggregate/nested/histogram.cpp
  test/sql/aggregate/aggregates/test_histogram.test
Labels: bug-fix

#3314 Issue #3262: Dead Code Removal
  src/common/row_operations/row_match.cpp
  src/common/vector_operations/is_distinct_from.cpp
  src/execution/expression_executor/execute_comparison.cpp
  src/include/duckdb/common/vector_operations/vector_operations.hpp
Labels: enhancement

#3179 Change pipe so it doesnt print on terminal
  test/sql/copy/csv/overwrite/test_overwrite_pipe_linux.test
  tools/shell/shell-test.py
Labels: enhancement

#3264 Allow the use of native replacement scan of parquet/csv files with the dbplyr-backend
  tools/rpkg/R/backend-dbplyr__duckdb_connection.R
  tools/rpkg/R/zzz.R
  tools/rpkg/man/db_connection_describe.Rd
  tools/rpkg/man/dbplyr_edition.Rd
  tools/rpkg/man/dbplyr_fill0.Rd
  tools/rpkg/man/sql_escape_date.Rd
  tools/rpkg/man/sql_escape_datetime.Rd
  tools/rpkg/man/sql_expr_matches.Rd
  tools/rpkg/man/sql_translation.Rd
  tools/rpkg/tests/testthat/test_tbl__duckdb_connection.R
Labels: feature

#3274 Implementation of the list aggregate function
  src/catalog/default/default_functions.cpp
  src/function/scalar/list/CMakeLists.txt
  src/function/scalar/list/list_aggregates.cpp
  src/function/scalar/nested_functions.cpp
  src/include/duckdb/function/scalar/nested_functions.hpp
  test/sql/function/list/aggregates/approx_count_distinct.test
  test/sql/function/list/aggregates/avg.test
  test/sql/function/list/aggregates/bigints_sum_avg.test
  test/sql/function/list/aggregates/bit_and.test
  test/sql/function/list/aggregates/bit_or.test
  test/sql/function/list/aggregates/bit_xor.test
  test/sql/function/list/aggregates/bool_and_or.test
  test/sql/function/list/aggregates/count.test
  test/sql/function/list/aggregates/entropy.test
  test/sql/function/list/aggregates/first.test
  test/sql/function/list/aggregates/histogram.test
  test/sql/function/list/aggregates/hugeint.test
  test/sql/function/list/aggregates/incorrect.test
  test/sql/function/list/aggregates/kurtosis.test
  test/sql/function/list/aggregates/last.test
  test/sql/function/list/aggregates/mad.test
  test/sql/function/list/aggregates/max.test
  test/sql/function/list/aggregates/median.test
  test/sql/function/list/aggregates/min.test
  test/sql/function/list/aggregates/mode.test
  test/sql/function/list/aggregates/nested.test
  test/sql/function/list/aggregates/null_or_empty.test
  test/sql/function/list/aggregates/product.test
  test/sql/function/list/aggregates/sem.test
  test/sql/function/list/aggregates/skewness.test
  test/sql/function/list/aggregates/string_agg.test
  test/sql/function/list/aggregates/sum.test
  test/sql/function/list/aggregates/types.test
  test/sql/function/list/aggregates/var_stddev.test
Labels: feature

#3328 Fix #3294: initialize validity mask to correct size in placeholder code
  src/storage/compression/validity_uncompressed.cpp
  test/sql/delete/list_delete.test
Labels: bug-fix

#3329 Fix use after free bug in local storage
  src/include/duckdb/storage/table/scan_state.hpp
  src/include/duckdb/transaction/local_storage.hpp
  src/storage/local_storage.cpp
Labels: bug-fix

#3338 Issue #3298: Nested Unflat MinMax
  src/function/aggregate/distributive/minmax.cpp
  test/sql/aggregate/aggregates/test_minmax.test
Labels: bug-fix
