Repository duckdb/duckdb, pull requests merged in 2022-05, with the labels that each got.

#3550 ICU Extension Rework: clangd for extensions
  Makefile
Labels: Extension

#3481 List distinct and list unique functionality
  src/function/aggregate/nested/histogram.cpp
  src/function/scalar/list/list_aggregates.cpp
  src/function/scalar/nested_functions.cpp
  src/include/duckdb/function/aggregate/nested_functions.hpp
  src/include/duckdb/function/scalar/nested_functions.hpp
  test/sql/function/list/aggregates/types.test
  test/sql/function/list/list_distinct.test
  test/sql/function/list/list_unique.test
Labels: feature

#3512 Issue #3418: Match Multiple Spaces
  src/function/scalar/date/strftime.cpp
  test/sql/function/timestamp/test_strptime.test
Labels: enhancement

#3516 Issue #3497: Round DECIMAL casts
  .github/workflows/Main.yml
  .github/workflows/Windows.yml
  src/common/operator/cast_operators.cpp
  test/sql/cast/decimal_integer_cast.test
  test/sql/cast/test_string_cast.test
  test/sql/order/test_limit.test
  test/sql/storage/test_store_tpch_complex.test_slow
  test/sql/tpch/q01_union.test_slow
Labels: bug-fix

#3575 Issue #3534: Remove TIMESTAMPTZ casts
  src/common/vector_operations/vector_cast.cpp
  test/sql/types/timestamp/test_timestamp_tz.test
Labels: bug-fix

#3603 Fixing ascii bug in histogram strings
  src/function/aggregate/nested/histogram.cpp
  src/function/scalar/list/list_aggregates.cpp
  test/sql/aggregate/aggregates/test_histogram.test
  test/sql/function/list/aggregates/histogram.test
  test/sql/function/list/aggregates/types.test
  test/sql/function/list/list_distinct.test
  test/sql/function/list/list_unique.test
Labels: bug-fix

#3592 Issue #3444: Approximate quantile lists
  src/function/aggregate/holistic/approximate_quantile.cpp
  src/function/aggregate/holistic/reservoir_quantile.cpp
  test/sql/aggregate/aggregates/test_approx_quantile.test
Labels: enhancement

#3604 Equal or null optimization
  src/include/duckdb/optimizer/rule/equal_or_null_simplification.hpp
  src/optimizer/optimizer.cpp
  src/optimizer/rule/CMakeLists.txt
  src/optimizer/rule/equal_or_null_simplification.cpp
  test/sql/optimizer/expression/test_equal_or_null_optimization.test
Labels: Optimizer, feature
