Repository duckdb/duckdb, pull requests merged in 2023-12, with the labels that each got.

#9830 Move Wasm logic to inside CMake
  CMakeLists.txt
  Makefile
  scripts/link-wasm-extensions.sh
Labels: Ready To Merge

#9846 Fix s3fs close issue
  extension/httpfs/include/s3fs.hpp
  extension/httpfs/s3fs.cpp
  test/sql/copy/s3/fully_qualified_s3_url.test
  test/sql/copy/s3/upload_large_file.test_slow
Labels: Ready To Merge

#9884 Capitalize URL in httpfs extension flags
  extension/httpfs/httpfs_extension.cpp
Labels: Ready For Review

#9890 Issue #9869: Strptime Week Start
  src/function/scalar/strftime_format.cpp
  test/sql/function/timestamp/test_strptime.test
  test/sql/function/timestamp/test_try_strptime.test
Labels: Changes Requested

#9842 Safeguard uses of ColumnDefinition::DefaultValue
  .github/patches/extensions/postgres_scanner/default_value.patch
  src/catalog/catalog_entry/table_catalog_entry.cpp
  src/function/table/system/duckdb_columns.cpp
  src/function/table/system/pragma_table_info.cpp
  src/include/duckdb/parser/column_definition.hpp
  src/parser/column_definition.cpp
  src/parser/transform/constraint/transform_constraint.cpp
  src/planner/binder/statement/bind_create_table.cpp
  src/planner/binder/statement/bind_insert.cpp
  test/sql/pragma/test_table_info.test
Labels: Ready For Review

#9357 [ADBC] Add support for windows.
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/arrow/ubsan_fix.patch
  .github/workflows/Main.yml
  .github/workflows/OSX.yml
  .github/workflows/Windows.yml
  scripts/exported_symbols_check.py
  src/common/adbc/adbc.cpp
  src/common/adbc/driver_manager.cpp
  src/function/table/arrow.cpp
  src/include/duckdb/common/adbc/adbc-init.hpp
  src/include/duckdb/common/adbc/adbc.h
  src/include/duckdb/common/adbc/adbc.hpp
  src/include/duckdb/common/adbc/driver_manager.h
  src/include/duckdb/common/adbc/single_batch_array_stream.hpp
  src/include/duckdb/function/table/arrow.hpp
  src/main/capi/arrow-c.cpp
  test/api/adbc/test_adbc.cpp
  test/arrow/arrow_move_children.cpp
  test/arrow/arrow_test_helper.cpp
  test/helpers/test_helpers.cpp
  test/include/arrow/arrow_test_helper.hpp
  test/sql/copy/parquet/kv_metadata.test
  tools/pythonpkg/tests/fast/adbc/test_adbc.py
  tools/pythonpkg/tests/fast/adbc/test_connection_get_info.py
  tools/pythonpkg/tests/fast/adbc/test_statement_bind.py
Labels: CI Failure

#9910 Issue #9887: ISO Format Directives
  src/common/enum_util.cpp
  src/function/scalar/strftime_format.cpp
  src/include/duckdb/function/scalar/strftime_format.hpp
  test/sql/function/date/test_strftime_exhaustive.test
  test/sql/function/timestamp/test_icu_strftime.test
  test/sql/function/timestamp/test_strftime_timestamp.test
  test/sql/function/timestamp/test_strptime.test
  test/sql/function/timestamp/test_try_strptime.test
Labels: Needs Documentation, Ready For Review

#9581 Fix: string to integer cast
  src/common/operator/cast_operators.cpp
  test/common/test_cast.cpp
  test/sql/cast/string_to_integer_decimal_cast.test
  test/sql/cast/string_to_integer_exponent_cast.test
  test/sql/types/decimal/decimal_exponent.test
Labels: Ready To Merge

#9632 User agent in http header
  src/main/extension/extension_install.cpp
Labels: Ready To Merge

#9715 [DependencyManager] Rework internals of the DependencyManager
  src/catalog/CMakeLists.txt
  src/catalog/catalog_entry.cpp
  src/catalog/catalog_entry/CMakeLists.txt
  src/catalog/catalog_entry/dependency/CMakeLists.txt
  src/catalog/catalog_entry/dependency/dependency_dependent_entry.cpp
  src/catalog/catalog_entry/dependency/dependency_entry.cpp
  src/catalog/catalog_entry/dependency/dependency_subject_entry.cpp
  src/catalog/catalog_set.cpp
  src/catalog/dependency_catalog_set.cpp
  src/catalog/dependency_manager.cpp
  src/common/enum_util.cpp
  src/common/enums/catalog_type.cpp
  src/common/string_util.cpp
  src/function/scalar/string/caseconvert.cpp
  src/function/table/system/duckdb_dependencies.cpp
  src/include/duckdb/catalog/catalog_entry.hpp
  src/include/duckdb/catalog/catalog_entry/dependency/dependency_dependent_entry.hpp
  src/include/duckdb/catalog/catalog_entry/dependency/dependency_entry.hpp
  src/include/duckdb/catalog/catalog_entry/dependency/dependency_subject_entry.hpp
  src/include/duckdb/catalog/catalog_set.hpp
  src/include/duckdb/catalog/dependency.hpp
  src/include/duckdb/catalog/dependency_catalog_set.hpp
  src/include/duckdb/catalog/dependency_list.hpp
  src/include/duckdb/catalog/dependency_manager.hpp
  src/include/duckdb/catalog/mapping_value.hpp
  src/include/duckdb/common/case_insensitive_map.hpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/enums/catalog_type.hpp
  src/include/duckdb/common/string_util.hpp
  src/planner/binder/statement/bind_simple.cpp
  src/transaction/cleanup_state.cpp
  src/transaction/commit_state.cpp
  src/transaction/duck_transaction.cpp
  src/transaction/undo_buffer.cpp
  test/fuzzer/pedro/concurrent_catalog_usage.test
  test/sql/alter/rename_col/test_rename_col_transactions.test
  test/sql/alter/rename_table/test_rename_table_case.test
  test/sql/catalog/dependencies/test_alter_dependency_ownership.test
  test/sql/catalog/dependencies/test_alter_owned_by.test
  test/sql/catalog/dependencies/test_alter_owning_table.test
  test/sql/catalog/dependencies/test_concurrent_alter.test
  test/sql/catalog/dependencies/test_concurrent_drop.test
  test/sql/catalog/dependencies/test_concurrent_index_creation.test
  test/sql/catalog/dependencies/test_concurrent_rename.test
  test/sql/catalog/dependencies/test_concurrent_schema_creation.test
  test/sql/catalog/dependencies/test_write_after_rename.test
  test/sql/types/enum/test_enum_structs.test
Labels: Ready For Review

#9936 Internal #873: Empty Aggregate Frames
  src/core_functions/aggregate/nested/list.cpp
  src/execution/window_segment_tree.cpp
  test/sql/window/test_empty_frames.test
  test/sql/window/test_window_exclude.test
Labels: Ready To Merge

#9897 Add support for right_semi and right_anti. PR 2
  .github/workflows/R_CMD_CHECK.yml
  src/common/enum_util.cpp
  src/common/enums/join_type.cpp
  src/execution/column_binding_resolver.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/join/physical_blockwise_nl_join.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/operator/join/physical_join.cpp
  src/execution/operator/join/physical_nested_loop_join.cpp
  src/execution/operator/join/physical_piecewise_merge_join.cpp
  src/execution/physical_plan/plan_comparison_join.cpp
  src/execution/physical_plan/plan_set_operation.cpp
  src/include/duckdb/common/enums/join_type.hpp
  src/include/duckdb/execution/join_hashtable.hpp
  src/include/duckdb/execution/operator/join/physical_blockwise_nl_join.hpp
  src/include/duckdb/execution/operator/join/physical_nested_loop_join.hpp
  src/include/duckdb/execution/operator/join/physical_piecewise_merge_join.hpp
  src/include/duckdb/execution/physical_plan_generator.hpp
  src/include/duckdb/optimizer/join_order/query_graph_manager.hpp
  src/include/duckdb/optimizer/join_order/relation_statistics_helper.hpp
  src/optimizer/join_order/cardinality_estimator.cpp
  src/optimizer/join_order/cost_model.cpp
  src/optimizer/join_order/join_order_optimizer.cpp
  src/optimizer/join_order/query_graph_manager.cpp
  src/optimizer/join_order/relation_manager.cpp
  src/optimizer/join_order/relation_statistics_helper.cpp
  src/optimizer/statistics/operator/propagate_join.cpp
  src/planner/operator/logical_join.cpp
  test/issues/general/test_1290.test
  test/optimizer/column_lifetime_analyzer/no_unnecessary_projections.test
  test/optimizer/pullup_filters.test
  test/optimizer/transitive_filters.test
  test/sql/function/list/list_where.test
  test/sql/function/list/list_zip.test
  test/sql/join/asof/test_asof_join_doubles.test
  test/sql/join/inner/test_eq_ineq_join.test
  test/sql/join/inner/test_join_is_distinct.test
  test/sql/join/semianti/antijoin.test
  test/sql/join/semianti/right_anti.test
  test/sql/join/semianti/right_semi.test
  test/sql/returning/returning_delete.test
  test/sql/subquery/any_all/test_uncorrelated_any_subquery.test
  test/sql/subquery/lateral/pg_lateral.test
  test/sql/subquery/scalar/test_many_correlated_columns.test
  test/sql/types/union/union_struct.test
  tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
  tools/pythonpkg/tests/fast/spark/test_spark_join.py
Labels: Ready To Merge

#9855 Issue#9795 min/max doesn't use collation
  src/core_functions/aggregate/distributive/arg_min_max.cpp
  src/core_functions/aggregate/distributive/minmax.cpp
  test/issues/general/test_9795.test
Labels: Changes Requested

#9568 JDBC - Appender for Decimal
  tools/jdbc/src/jni/duckdb_java.cpp
  tools/jdbc/src/jni/functions.cpp
  tools/jdbc/src/jni/functions.hpp
  tools/jdbc/src/main/java/org/duckdb/DuckDBAppender.java
  tools/jdbc/src/main/java/org/duckdb/DuckDBNative.java
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
Labels: Ready For Review

#9947 [Fix] No duplicates in list_intersect
  src/catalog/default/default_functions.cpp
  test/sql/function/list/list_distinct.test
  test/sql/function/list/list_intersect.test
Labels: CI Failure

#9938 fix regexp_replace bug
  tools/pythonpkg/duckdb/experimental/spark/sql/functions.py
  tools/pythonpkg/tests/fast/spark/test_replace_column_value.py
Labels: Ready To Merge

#9994 Internal #898: Totally Ordered Intervals
  src/common/types/hash.cpp
  src/core_functions/aggregate/holistic/mode.cpp
  src/include/duckdb/common/operator/comparison_operators.hpp
  src/include/duckdb/common/types/interval.hpp
  test/sql/types/interval/test_interval_comparison.test
Labels: Ready For Review

#9984 Issue #9956: Alternative TIME Casts
  src/common/operator/cast_operators.cpp
  src/function/cast/time_casts.cpp
  src/include/duckdb/common/operator/cast_operators.hpp
  test/sql/types/timestamp/alternative_timestamp_casts.test
  test/sql/types/timestamp/test_timestamp_types.test
Labels: Ready For Review

#9973 Make IEJoin code more clear
  src/execution/operator/join/physical_iejoin.cpp
  src/include/duckdb/execution/operator/join/physical_iejoin.hpp
Labels: Ready To Merge

#9974 [Fix] ambiguous lambda parameters
  src/catalog/default/default_functions.cpp
  src/planner/binder/expression/bind_lambda.cpp
  test/sql/function/list/lambdas/incorrect.test
  test/sql/function/list/list_intersect.test
Labels: Needs Documentation

#10006 Increase CLI history's max length to 1000
  tools/shell/linenoise.cpp
Labels: Ready For Review

#9988 Improving error message when trying to open a locked database
  scripts/generate_enum_util.py
  src/CMakeLists.txt
  src/common/enum_util.cpp
  src/common/local_file_system.cpp
  src/include/duckdb/common/enums/tableref_type.hpp
  src/include/duckdb/main/extension_helper.hpp
  src/include/duckdb/parser/tableref/emptytableref.hpp
  src/include/duckdb/planner/tableref/bound_dummytableref.hpp
  src/include/duckdb/storage/serialization/tableref.json
  src/main/extension/extension_load.cpp
  src/parser/parsed_expression_iterator.cpp
  src/parser/query_node/select_node.cpp
  src/planner/binder.cpp
  src/planner/expression_iterator.cpp
  src/storage/serialization/serialize_tableref.cpp
  third_party/pcg/pcg_uint128.hpp
  third_party/thrift/thrift/thrift-config.h
  tools/pythonpkg/setup.py
Labels: Ready For Review

#10014 fix(function): fix ceil function
  src/core_functions/scalar/math/numeric.cpp
  test/sql/types/decimal/test_decimal_ops.test
Labels: Changes Requested

#9954 Issue #9762: Interval Fractional Parts
  src/common/types/interval.cpp
  src/core_functions/scalar/date/functions.json
  src/core_functions/scalar/date/to_interval.cpp
  src/include/duckdb/common/types/cast_helpers.hpp
  src/include/duckdb/core_functions/scalar/date_functions.hpp
  src/parser/transform/expression/transform_interval.cpp
  test/fuzzer/pedro/overflow_parsing_interval.test
  test/sql/function/date/test_time_bucket_date.test
  test/sql/function/interval/test_interval_trunc.test
  test/sql/function/timestamp/age.test
  test/sql/function/timestamp/test_icu_age.test
  test/sql/function/timestamp/test_icu_dateadd.test
  test/sql/function/timestamp/test_icu_time_bucket_timestamptz.test
  test/sql/function/timestamp/test_time_bucket_timestamp.test
  test/sql/types/interval/interval_constants.test
Labels: Ready For Review

#9990 Fix #9380 and #9738
  src/function/function_binder.cpp
  src/include/duckdb/function/macro_function.hpp
  src/include/duckdb/planner/expression_binder.hpp
  src/include/duckdb/storage/serialization/macro_function.json
  src/planner/binder/expression/bind_columnref_expression.cpp
  src/storage/serialization/serialize_macro_function.cpp
  test/issues/general/test_9380.test
  test/issues/general/test_9738.test
Labels: CI Failure

#10025 Fix array subquery
  src/parser/transform/expression/transform_subquery.cpp
  test/sql/subquery/scalar/array_subquery.test
Labels: Changes Requested

#9754 Issue #4545: Windowed Distinct Aggregates
  src/core_functions/aggregate/nested/list.cpp
  src/execution/operator/aggregate/aggregate_object.cpp
  src/execution/window_executor.cpp
  src/execution/window_segment_tree.cpp
  src/function/aggregate/distributive/count.cpp
  src/include/duckdb/execution/merge_sort_tree.hpp
  src/include/duckdb/execution/window_executor.hpp
  src/include/duckdb/execution/window_segment_tree.hpp
  src/include/duckdb/parser/expression/window_expression.hpp
  src/include/duckdb/planner/expression/bound_window_expression.hpp
  src/include/duckdb/storage/serialization/parsed_expression.json
  src/parser/expression/window_expression.cpp
  src/parser/transform/expression/transform_function.cpp
  src/planner/binder/expression/bind_window_expression.cpp
  src/planner/expression/bound_window_expression.cpp
  src/storage/serialization/serialize_parsed_expression.cpp
  test/sql/window/test_empty_frames.test
  test/sql/window/test_naive_aggregation.test
  test/sql/window/test_scalar_window.test
  test/sql/window/test_window_distinct.test
  test/sql/window/test_window_distinct.test_slow
  test/sql/window/test_window_exclude.test
Labels: Ready For Review

#10054 Internal #940: GCC Window Distinct
  src/execution/window_segment_tree.cpp
Labels: Ready For Review

#9544 enable overriding per-query working-memory target.
  src/common/sort/sort_state.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/physical_operator.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/main/database.hpp
  src/include/duckdb/storage/buffer/buffer_pool.hpp
  src/include/duckdb/storage/buffer_manager.hpp
  src/include/duckdb/storage/standard_buffer_manager.hpp
  src/main/database.cpp
  src/storage/buffer/buffer_pool.cpp
  src/storage/buffer_manager.cpp
  src/storage/standard_buffer_manager.cpp
Labels: Changes Requested
