Repository duckdb/duckdb, pull requests merged in 2023-01, with the labels that each got.

#5835 Add non ICU time_bucket function
  src/function/scalar/date/CMakeLists.txt
  src/function/scalar/date/time_bucket.cpp
  src/function/scalar/date_functions.cpp
  src/include/duckdb/function/scalar/date_functions.hpp
  test/sql/function/date/test_time_bucket_date.test
  test/sql/function/timestamp/test_time_bucket_timestamp.test
Labels: feature

#5823 Fix list_sort segmentation fault regression
  data/parquet-testing/list_sort_segfault.parquet
  src/function/scalar/list/list_sort.cpp
  test/sql/function/list/list_sort.test
Labels: bug-fix

#5888 Issue #5887: ICU DateAdd Overflow
  extension/icu/icu-dateadd.cpp
  test/sql/function/timestamp/test_icu_dateadd.test
Labels: bug-fix

#5862 Add signbit function for floating point values
  src/function/scalar/math/numeric.cpp
  src/function/scalar/math_functions.cpp
  src/include/duckdb/function/scalar/math_functions.hpp
  test/sql/function/numeric/test_sign_bit.test
Labels: feature

#5860 Nested/Outer lambda parameters in rhs of inner lambda expressions
  src/common/enums/expression_type.cpp
  src/function/scalar/list/list_lambdas.cpp
  src/include/duckdb/common/enums/expression_type.hpp
  src/include/duckdb/planner/expression/bound_lambdaref_expression.hpp
  src/include/duckdb/planner/expression_binder.hpp
  src/include/duckdb/planner/table_binding.hpp
  src/planner/binder/expression/bind_columnref_expression.cpp
  src/planner/binder/expression/bind_function_expression.cpp
  src/planner/binder/expression/bind_lambda.cpp
  src/planner/expression/CMakeLists.txt
  src/planner/expression/bound_lambdaref_expression.cpp
  src/planner/expression_iterator.cpp
  src/planner/table_binding.cpp
  test/sql/function/list/lambdas/rhs_parameters.test
Labels: enhancement, bug-fix

#5869 Issue #5826: ICUDateFunc SubtractField Fix
  extension/icu/icu-dateadd.cpp
  extension/icu/icu-datefunc.cpp
  extension/icu/third_party/icu/i18n/calendar.cpp
  test/sql/function/timestamp/test_icu_dateadd.test
  test/sql/function/timestamp/test_icu_datesub.test
Labels: bug-fix

#5879 Issue #5870: Nested ArgMinMax Results
  scripts/run_test_list.py
  src/function/aggregate/distributive/arg_min_max.cpp
  test/sql/aggregate/aggregates/test_arg_min_max_nested.test
Labels: enhancement

#5665 Add time bucket function
  extension/icu/CMakeLists.txt
  extension/icu/icu-dateadd.cpp
  extension/icu/icu-extension.cpp
  extension/icu/icu-timebucket.cpp
  extension/icu/icu-timezone.cpp
  extension/icu/include/icu-datefunc.hpp
  extension/icu/include/icu-timebucket.hpp
  src/include/duckdb/common/operator/convert_to_string.hpp
  src/include/duckdb/common/operator/subtract.hpp
  test/sql/function/timestamp/test_icu_time_bucket_timestamptz.test
Labels: feature

#5909 Issue #5023: Window Radix Partitions
  src/common/types/row_data_collection_scanner.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/include/duckdb/common/radix_partitioning.hpp
  src/include/duckdb/common/types/row_data_collection_scanner.hpp
  test/sql/aggregate/qualify/test_qualify.test
  test/sql/aggregate/qualify/test_qualify_view.test
  test/sql/function/list/lambdas/expression_iterator_cases.test
  test/sql/generated_columns/virtual/partition.test
  test/sql/storage_version/storage_version.test_slow
Labels: enhancement
