Repository duckdb/duckdb, pull requests merged in 2023-07, with the labels that each got.

#8111 UNNEST binder fix
  src/planner/expression_binder.cpp
  src/planner/subquery/flatten_dependent_join.cpp
  test/sql/types/list/unnest_table_function.test
Labels: bug-fix

#7875 Add Unittests for ODBC
  .github/workflows/LinuxRelease.yml
  .github/workflows/Main.yml
  .github/workflows/OSX.yml
  tools/odbc/test/CMakeLists.txt
  tools/odbc/test/common.cpp
  tools/odbc/test/common.h
  tools/odbc/test/test_odbc.cpp
  tools/odbc/test/tests/alter.cpp
  tools/odbc/test/tests/basic_usage.cpp
  tools/odbc/test/tests/bind_col.cpp
  tools/odbc/test/tests/bools_as_char.cpp
  tools/odbc/test/tests/catalog_functions.cpp
  tools/odbc/test/tests/col_attribute.cpp
  tools/odbc/test/tests/connect.cpp
  tools/odbc/test/tests/diagnostics.cpp
  tools/odbc/test/tests/row_wise_fetching.cpp
  tools/odbc/test/tests/select.cpp
Labels: Test, ODBC

#8113 CppCheck & CodeQL on master
  extension/httpfs/s3fs.cpp
  extension/parquet/parquet_reader.cpp
  src/common/arrow/arrow_appender.cpp
  src/common/exception.cpp
  src/common/local_file_system.cpp
  src/common/re2_regex.cpp
  src/common/types/uuid.cpp
  src/core_functions/aggregate/holistic/reservoir_quantile.cpp
  src/execution/expression_executor.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/operator/join/physical_asof_join.cpp
  src/execution/operator/join/physical_range_join.cpp
  src/execution/operator/persistent/csv_file_handle.cpp
  src/execution/operator/persistent/physical_insert.cpp
  src/execution/window_segment_tree.cpp
  src/function/function.cpp
  src/include/duckdb/execution/operator/persistent/base_csv_reader.hpp
  src/include/duckdb/main/connection.hpp
  src/include/duckdb/optimizer/join_order/cardinality_estimator.hpp
  src/include/duckdb/planner/constraints/bound_unique_constraint.hpp
  src/main/capi/duckdb_value-c.cpp
  src/main/database.cpp
  src/planner/expression/bound_aggregate_expression.cpp
  src/storage/compression/rle.cpp
Labels: bug-fix

#8127 Issue #8119: TO_TIMESTAMP Returns TIMESTAMP
  src/core_functions/function_list.cpp
  src/core_functions/scalar/date/date_part.cpp
  src/core_functions/scalar/date/epoch.cpp
  src/core_functions/scalar/date/functions.json
  src/include/duckdb/core_functions/scalar/date_functions.hpp
  test/sql/function/timestamp/epoch.test
Labels: bug

#8166 Create NamingConvention.md, with @samansmink
  extension/ExtensionDistribution.md
Labels: Extension

#8092 Issue #7969: Prefer Range Join
  benchmark/micro/join/iejoin_selectivity.benchmark
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/operator/join/physical_piecewise_merge_join.cpp
  src/execution/operator/join/physical_range_join.cpp
  src/execution/physical_plan/plan_asof_join.cpp
  src/execution/physical_plan/plan_comparison_join.cpp
  src/include/duckdb/execution/operator/join/physical_iejoin.hpp
  src/include/duckdb/execution/operator/join/physical_piecewise_merge_join.hpp
  src/include/duckdb/execution/operator/join/physical_range_join.hpp
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/settings/settings.cpp
  test/api/test_reset.cpp
  test/sql/join/iejoin/iejoin_projection_maps.test
Labels: enhancement

#8196 Issue #7595: AsOf Inequalities
  src/execution/operator/join/physical_asof_join.cpp
  src/execution/physical_plan/plan_asof_join.cpp
  src/include/duckdb/execution/operator/join/physical_asof_join.hpp
  src/planner/binder/tableref/plan_joinref.cpp
  test/sql/join/asof/test_asof_join.test
  test/sql/join/asof/test_asof_join_inequalities.test
  test/sql/join/asof/test_asof_join_missing.test_slow
Labels: feature

#8085 Issue #7808: Partition Using PartitionedTupleData
  .github/config/uncovered_files.csv
  src/common/sort/partition_state.cpp
  src/include/duckdb/common/sort/partition_state.hpp
  src/include/duckdb/common/types/row/partitioned_tuple_data.hpp
  test/sql/window/window_partition_paging.test_slow
Labels: enhancement, Execution

#8306 [ODBC] Add Row-Wise Fetching and Bool-to-Char Tests
  tools/odbc/include/descriptor.hpp
  tools/odbc/include/odbc_interval.hpp
  tools/odbc/include/statement_functions.hpp
  tools/odbc/odbc_fetch.cpp
  tools/odbc/odbc_interval.cpp
  tools/odbc/prepared.cpp
  tools/odbc/result.cpp
  tools/odbc/statement.cpp
  tools/odbc/statement_functions.cpp
  tools/odbc/test/common.cpp
  tools/odbc/test/tests/bools_as_char.cpp
  tools/odbc/test/tests/catalog_functions.cpp
  tools/odbc/test/tests/row_wise_fetching.cpp
  tools/odbc/test/tests/select.cpp
Labels: ODBC
