Repository duckdb/duckdb, pull requests merged in 2023-06, with the labels that each got.

#7764 Fuzzer #209: Multiple Scalar Blocks
  src/execution/operator/aggregate/physical_window.cpp
  test/fuzzer/sqlsmith/window_scalar_range.test
Labels: bug-fix

#7770 Fuzzer #206: Fix Cast Overflow
  extension/icu/icu-makedate.cpp
  test/fuzzer/sqlsmith/timestamptz_double_cast.test
Labels: bug-fix

#7774 Issue #7187: AsOf Coverage
  test/sql/join/asof/test_asof_join_merge.test
Labels: Test

#7767 Fuzzer #214: ROWS BETWEEN Overflow
  src/execution/operator/aggregate/physical_window.cpp
  test/fuzzer/sqlsmith/window-rows-overflow.test
Labels: bug-fix

#7800 Add tests to cover issue 5132 and enable force reload
  test/sql/json/test_json_extract.test
  test/sql/prepared/test_prepare_issue_5132.test
  test/sql/types/union/union_tag.test
Labels: Test

#7769 Fuzzer #215: Timestamp Arithmetic Overflow
  .github/config/uncovered_files.csv
  src/common/types/timestamp.cpp
  src/include/duckdb/common/types/timestamp.hpp
  test/fuzzer/sqlsmith/timestamp_overflow.test
  test/sql/types/timestamp/timestamp_limits.test
Labels: bug-fix

#7821 LEFT JOIN ON TRUE support
  src/include/duckdb/optimizer/filter_pushdown.hpp
  src/include/duckdb/optimizer/optimizer.hpp
  src/include/duckdb/planner/operator/logical_comparison_join.hpp
  src/optimizer/filter_pushdown.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/pushdown/pushdown_cross_product.cpp
  src/planner/binder/query_node/plan_subquery.cpp
  src/planner/binder/tableref/plan_joinref.cpp
  test/sql/join/left_outer/test_left_join_on_true.test
  test/sql/subquery/lateral/pg_lateral.test
Labels: feature

#7836 Unnest_rewriter fixes
  src/include/duckdb/optimizer/unnest_rewriter.hpp
  src/optimizer/unnest_rewriter.cpp
  test/optimizer/unnest_rewriter.test
Labels: Optimizer, bug-fix

#7872 More UNNEST fixes
  src/execution/operator/projection/physical_tableinout_function.cpp
  src/execution/operator/projection/physical_unnest.cpp
  test/sql/types/list/unnest_null_empty.test
Labels: bug-fix

#7881 [Docs] Aggregate function README.md
  src/core_functions/aggregate/README.md
Labels: Documentation

#7922 Issue #7879: Missing JDBC TIMESTAMP_TZ
  tools/jdbc/src/jni/duckdb_java.cpp
  tools/jdbc/src/main/java/org/duckdb/DuckDBResultSet.java
  tools/jdbc/src/main/java/org/duckdb/DuckDBVector.java
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
Labels: bug-fix

#7891 Issue #7809: Segment Tree Performance
  .github/config/uncovered_files.csv
  src/common/types/data_chunk.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/window_segment_tree.cpp
  src/include/duckdb/execution/window_segment_tree.hpp
Labels: enhancement

#7996 Issue #7852: Window Vectorisation
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/window_segment_tree.cpp
  src/include/duckdb/execution/window_segment_tree.hpp
Labels: enhancement

#8050 Issue #7852: Window Vectorisation
  src/execution/window_segment_tree.cpp
  src/include/duckdb/execution/window_segment_tree.hpp
  test/sql/window/test_parallel_window.test_slow
Labels: enhancement

#7930 ART prefix refactor
  .github/config/uncovered_files.csv
  src/common/enum_util.cpp
  src/execution/index/art/CMakeLists.txt
  src/execution/index/art/art.cpp
  src/execution/index/art/fixed_size_allocator.cpp
  src/execution/index/art/iterator.cpp
  src/execution/index/art/leaf.cpp
  src/execution/index/art/node.cpp
  src/execution/index/art/node16.cpp
  src/execution/index/art/node256.cpp
  src/execution/index/art/node4.cpp
  src/execution/index/art/node48.cpp
  src/execution/index/art/prefix.cpp
  src/execution/index/art/prefix_segment.cpp
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/art/iterator.hpp
  src/include/duckdb/execution/index/art/leaf.hpp
  src/include/duckdb/execution/index/art/node.hpp
  src/include/duckdb/execution/index/art/node16.hpp
  src/include/duckdb/execution/index/art/node256.hpp
  src/include/duckdb/execution/index/art/node4.hpp
  src/include/duckdb/execution/index/art/node48.hpp
  src/include/duckdb/execution/index/art/prefix.hpp
  src/include/duckdb/execution/index/art/prefix_segment.hpp
  test/fuzzer/pedro/art_concatenate_prefix.test
  test/sql/index/art/memory/test_art_non_linear.test_slow
  test/sql/index/art/nodes/test_art_node_48.test
  test/sql/index/art/nodes/test_art_prefixes.test
  test/sql/index/art/nodes/test_art_prefixes_restart.test
  test/sql/index/art/test_art_coverage_leaf.test
  test/sql/index/art/test_art_coverage_types.test
  test/sql/storage/test_index_checkpoint.test
Labels: enhancement, Index
