Repository duckdb/duckdb, pull requests merged in 2023-11, with the labels that each got.

#8907 Additional list functions
  src/core_functions/function_list.cpp
  src/core_functions/scalar/list/functions.json
  src/core_functions/scalar/list/list_sort.cpp
  src/function/scalar/list/CMakeLists.txt
  src/function/scalar/list/list_select.cpp
  src/function/scalar/list/list_zip.cpp
  src/function/scalar/nested_functions.cpp
  src/include/duckdb/core_functions/scalar/list_functions.hpp
  src/include/duckdb/function/scalar/nested_functions.hpp
  test/sql/function/list/list_grade_up.test
  test/sql/function/list/list_select.test
  test/sql/function/list/list_where.test
  test/sql/function/list/list_zip.test
Labels: feature, Needs Documentation

#9441 Removed artificial `HUGEINT` minimum
  src/common/operator/cast_operators.cpp
  src/common/types/hugeint.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/common/limits.hpp
  src/include/duckdb/common/types/cast_helpers.hpp
  src/include/duckdb/common/types/hugeint.hpp
  src/optimizer/rule/move_constants.cpp
  test/common/test_cast_hugeint.test
  test/sql/aggregate/group/group_by_limits.test
  test/sql/cast/test_bit_cast.test
  test/sql/copy/parquet/writer/parquet_test_all_types.test
  test/sql/copy/parquet/writer/write_stats_min_max.test_slow
  test/sql/function/string/hex.test
  test/sql/join/inner/equality_join_limits.test
  test/sql/optimizer/expression/test_move_constants.test
  test/sql/order/hugeint_order_by_extremes.test
  test/sql/storage/compression/bitpacking/bitpacking_fatal_forced.test_slow
  test/sql/storage_version/storage_version.db
  test/sql/types/hugeint/hugeint_try_cast.test
  test/sql/types/hugeint/test_hugeint_arithmetic.test
  test/sql/types/hugeint/test_hugeint_conversion.test
  test/sql/types/numeric/hugeint_try_cast.test
  test/sql/types/test_all_types.test_slow
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
  tools/juliapkg/src/result.jl
  tools/juliapkg/test/test_all_types.jl
  tools/pythonpkg/duckdb/experimental/spark/sql/types.py
  tools/pythonpkg/tests/fast/test_all_types.py
  tools/swift/duckdb-swift/Tests/DuckDBTests/TypeConversionTests.swift
Labels: Needs Documentation

#9392 Parquet Encryption
  extension/parquet/CMakeLists.txt
  extension/parquet/column_reader.cpp
  extension/parquet/column_writer.cpp
  extension/parquet/include/parquet.json
  extension/parquet/include/parquet_crypto.hpp
  extension/parquet/include/parquet_reader.hpp
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/parquet_config.py
  extension/parquet/parquet_crypto.cpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_writer.cpp
  extension/parquet/serialize_parquet.cpp
  src/execution/operator/persistent/physical_export.cpp
  src/include/duckdb/main/extension_entries.hpp
  src/parser/transform/expression/transform_constant.cpp
  test/parquet/encrypted_parquet.test
  test/sql/copy/parquet/parquet_encryption.test_slow
  third_party/mbedtls/CMakeLists.txt
  third_party/mbedtls/include/mbedtls/aes.h
  third_party/mbedtls/include/mbedtls/aes_alt.h
  third_party/mbedtls/include/mbedtls/aria.h
  third_party/mbedtls/include/mbedtls/aria_alt.h
  third_party/mbedtls/include/mbedtls/camellia.h
  third_party/mbedtls/include/mbedtls/camellia_alt.h
  third_party/mbedtls/include/mbedtls/ccm.h
  third_party/mbedtls/include/mbedtls/ccm_alt.h
  third_party/mbedtls/include/mbedtls/chacha20.h
  third_party/mbedtls/include/mbedtls/chachapoly.h
  third_party/mbedtls/include/mbedtls/cipher.h
  third_party/mbedtls/include/mbedtls/cmac.h
  third_party/mbedtls/include/mbedtls/entropy.h
  third_party/mbedtls/include/mbedtls/gcm.h
  third_party/mbedtls/include/mbedtls/gcm_alt.h
  third_party/mbedtls/include/mbedtls/mbedtls_config.h
  third_party/mbedtls/include/mbedtls/nist_kw.h
  third_party/mbedtls/include/mbedtls/timing.h
  third_party/mbedtls/include/mbedtls_wrapper.hpp
  third_party/mbedtls/library/aes.cpp
  third_party/mbedtls/library/aesni.h
  third_party/mbedtls/library/aria.cpp
  third_party/mbedtls/library/camellia.cpp
  third_party/mbedtls/library/cipher.cpp
  third_party/mbedtls/library/cipher_wrap.cpp
  third_party/mbedtls/library/cipher_wrap.h
  third_party/mbedtls/library/entropy.cpp
  third_party/mbedtls/library/entropy_poll.cpp
  third_party/mbedtls/library/entropy_poll.h
  third_party/mbedtls/library/gcm.cpp
  third_party/mbedtls/library/padlock.h
  third_party/mbedtls/mbedtls_wrapper.cpp
Labels: Needs Documentation, Ready For Review

#9600 Issue #9589: Prefer strict TIMESTAMPs
  src/common/multi_file_reader.cpp
  test/sql/copy/parquet/hive_timestamps.test
Labels: Ready To Merge

#8788 CAPI: Make it possible to create enum types
  src/include/duckdb.h
  src/main/capi/logical_types-c.cpp
  test/api/capi/test_capi_complex_types.cpp
Labels: Ready To Merge

#9621 bump extension versions as prep for 0.9.2
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#9603 feat: duckdb_api and custom_user_agent options
  src/function/pragma/pragma_queries.cpp
  src/function/table/system/CMakeLists.txt
  src/function/table/system/pragma_user_agent.cpp
  src/function/table/system_functions.cpp
  src/include/duckdb/function/table/system_functions.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/capi/config-c.cpp
  src/main/capi/duckdb-c.cpp
  src/main/config.cpp
  src/main/database.cpp
  src/main/settings/settings.cpp
  test/api/capi/test_capi.cpp
  test/api/test_reset.cpp
  test/sql/settings/user_agent.test
  tools/jdbc/src/jni/duckdb_java.cpp
  tools/jdbc/src/main/java/org/duckdb/DuckDBDriver.java
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
  tools/odbc/driver.cpp
  tools/odbc/include/duckdb_odbc.hpp
  tools/odbc/test/tests/connect.cpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/api/test_config.py
Labels: Ready For Review

#9620 Revert "fix(jdbc): combine jar publish steps"
  scripts/jdbc_maven_deploy.py
Labels: Ready To Merge

#9623 Read JSON bugfix
  extension/json/buffered_json_reader.cpp
Labels: Ready To Merge

#9622 Add support for proper scoping (catalog + schema) to custom types
  src/common/extra_type_info.cpp
  src/common/types.cpp
  src/include/duckdb/common/extra_type_info.hpp
  src/include/duckdb/common/types.hpp
  src/include/duckdb/storage/serialization/types.json
  src/parser/transform/helpers/transform_typename.cpp
  src/parser/transform/statement/transform_drop.cpp
  src/planner/binder/statement/bind_create.cpp
  src/storage/serialization/serialize_types.cpp
  test/sql/attach/attach_enums.test
  test/sql/types/enum/test_enum_schema.test
  third_party/libpg_query/grammar/statements/drop.y
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/grammar/types/select.yh
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Ready To Merge

#9626 Fix #9548 - Throw a more clear error when using parameters inside of the source of a top-level PIVOT statement
  src/include/duckdb/parser/transformer.hpp
  src/parser/transform/statement/transform_pivot_stmt.cpp
  test/sql/pivot/pivot_prepare.test
Labels: Ready To Merge

#9613 Add SQL:2016 listagg
  src/core_functions/aggregate/distributive/functions.json
  src/core_functions/function_list.cpp
  src/include/duckdb/core_functions/aggregate/distributive_functions.hpp
Labels: Needs Documentation, Ready To Merge

#9580 [ODBC] Reorganize the SQLColAttribute Tests
  tools/odbc/test/CMakeLists.txt
  tools/odbc/test/tests/col_attribute.cpp
  tools/odbc/test/tests/col_attribute/char_query.cpp
  tools/odbc/test/tests/col_attribute/col_attribute.cpp
  tools/odbc/test/tests/col_attribute/int_query.cpp
  tools/odbc/test/tests/col_attribute/utils.cpp
  tools/odbc/test/tests/col_attribute/utils.h
Labels: Ready To Merge

#9615 Internal #576: strptime strftime infinities
  extension/icu/icu-strptime.cpp
  src/common/types/date.cpp
  src/function/scalar/strftime_format.cpp
  src/include/duckdb/common/types/date.hpp
  src/include/duckdb/function/scalar/strftime_format.hpp
  test/sql/function/date/test_strftime.test
  test/sql/function/timestamp/test_icu_strftime.test
  test/sql/function/timestamp/test_icu_strptime.test
  test/sql/function/timestamp/test_strptime.test
Labels: Ready For Review

#9627 ATTACH IF NOT EXISTS
  src/common/enum_util.cpp
  src/execution/operator/schema/physical_attach.cpp
  src/include/duckdb/common/enums/on_create_conflict.hpp
  src/include/duckdb/parser/parsed_data/attach_info.hpp
  src/include/duckdb/parser/parsed_data/create_info.hpp
  src/include/duckdb/storage/serialization/parse_info.json
  src/parser/parsed_data/attach_info.cpp
  src/parser/transform/statement/transform_attach.cpp
  src/parser/transform/statement/transform_create_table.cpp
  src/storage/serialization/serialize_parse_info.cpp
  test/sql/attach/attach_if_not_exists.test
  third_party/libpg_query/grammar/grammar.cpp
  third_party/libpg_query/grammar/statements/attach.y
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation, Ready To Merge

#9647 fix 9232
  extension/json/buffered_json_reader.cpp
  src/common/file_system.cpp
  src/include/duckdb/common/file_system.hpp
  src/include/duckdb/common/pipe_file_system.hpp
Labels: Ready To Merge

#9655 Shell: Set `globalDb` to `NULL` after closing database
  tools/shell/shell.c
Labels: Next Release

#9654 Fix #9308 - avoid pruning plan for ANTI join with filter that is always true
  src/optimizer/statistics/operator/propagate_join.cpp
  test/sql/subquery/exists/test_issue_9308.test
Labels: Ready To Merge

#9648 add option for keep_alive setting
  extension/httpfs/httpfs.cpp
  extension/httpfs/httpfs_extension.cpp
  extension/httpfs/include/httpfs.hpp
  src/include/duckdb/main/extension_entries.hpp
  test/sql/copy/s3/download_config.test
Labels: Ready To Merge

#9653 Serialize decimal quantiles
  src/common/enum_util.cpp
  src/core_functions/aggregate/holistic/quantile.cpp
  src/function/function_set.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/core_functions/aggregate/quantile_enum.hpp
  test/sql/aggregate/quantile_fun.test
Labels: Next Release

#9660 Partial revert of #9624: test seemed to cause some memory leaks in CI
  test/CMakeLists.txt
  test/tpch/CMakeLists.txt
  test/tpch/test_tpch.cpp
Labels: Next Release

#9670 Julia release
  tools/juliapkg/Project.toml
  tools/juliapkg/release.py
Labels: CI Failure

#9658 In set operations ORDER BY columns refer to the first set operation in SQL - so the reference is not ambiguous
  src/planner/binder/query_node/bind_setop_node.cpp
  test/sql/order/test_order_by_exceptions.test
  test/sql/setops/ambiguous_order_by.test
  test/sql/setops/test_union_all_by_name.test
  test/sql/setops/test_union_binding.test
  test/sql/setops/test_union_by_name.test
Labels: Ready To Merge

#9674 Replace old logos
  logo/DuckDB-Logo-horizontal.png
  logo/DuckDB-Logo-horizontal.svg
  logo/DuckDB_Logo-stacked.png
  logo/DuckDB_Logo-stacked.svg
  logo/DuckDB_Logo.jpg
  logo/DuckDB_Logo.pdf
  logo/DuckDB_Logo.png
  logo/DuckDB_Logo.svg
  tools/swift/duckdb-swift/README.md
Labels: Ready To Merge

#9688 [Python] Fix lossy `datetime.timedelta` to INTERVAL conversion
  src/core_functions/scalar/date/to_interval.cpp
  src/include/duckdb/core_functions/to_interval.hpp
  tools/pythonpkg/src/include/duckdb_python/python_objects.hpp
  tools/pythonpkg/src/native/python_objects.cpp
  tools/pythonpkg/tests/fast/pandas/test_timedelta.py
Labels: Ready For Review

#9711 Issue template: Report vulnerabilities via dedicated channel
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready For Review

#9430 feat(c): add functions for determining statement/return types
  src/include/duckdb.h
  src/include/duckdb/main/capi/capi_internal.hpp
  src/main/capi/helper-c.cpp
  src/main/capi/logical_types-c.cpp
  src/main/capi/prepared-c.cpp
  src/main/capi/result-c.cpp
  test/api/capi/test_capi_complex_types.cpp
  test/api/capi/test_capi_data_chunk.cpp
Labels: Ready To Merge

#9705 Issue #9673: ICU DST Truncation
  extension/icu/icu-datetrunc.cpp
  test/sql/function/timestamp/test_icu_datediff.test
  test/sql/function/timestamp/test_icu_datetrunc.test
Labels: Ready To Merge

#9687 Deserialize header fields
  src/include/duckdb/storage/storage_info.hpp
  src/storage/single_file_block_manager.cpp
Labels: Ready To Merge

#9671 Constant time attach path lookup and locking to ensure unique file handles
  benchmark/micro/CMakeLists.txt
  benchmark/micro/attach.cpp
  benchmark/micro/storage.cpp
  benchmark/micro/view/many_values.benchmark
  src/catalog/catalog_set.cpp
  src/execution/operator/schema/physical_attach.cpp
  src/include/duckdb/common/constants.hpp
  src/include/duckdb/main/attached_database.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/database.hpp
  src/include/duckdb/main/database_manager.hpp
  src/main/attached_database.cpp
  src/main/database.cpp
  src/main/database_manager.cpp
  src/main/db_instance_cache.cpp
  src/storage/storage_manager.cpp
  test/sql/attach/attach_filepath_roundtrip.test
Labels: Ready For Review

#9481 Fix expanding structs in queries with ORDER BY
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/expression_binder/order_binder.hpp
  src/planner/binder/expression/bind_unnest_expression.cpp
  src/planner/binder/query_node/bind_select_node.cpp
  src/planner/expression_binder/order_binder.cpp
  test/sql/aggregate/distinct/test_distinct_on.test
  test/sql/order/test_order_by.test
  test/sql/order/test_order_unnest.test
Labels: Ready To Merge

#9702 Only emit batch indices valid within the current pipeline
  src/parallel/pipeline_executor.cpp
Labels: CI Failure

#9734 Fixes to warning and rendering of bar()
  src/core_functions/scalar/string/bar.cpp
  src/include/duckdb/common/types/string_type.hpp
  test/sql/function/string/test_bar.test
Labels: Ready To Merge

#9735 Wasm: Add wasm_threads as a class of built extensions
  .github/workflows/Wasm.yml
  Makefile
Labels: Ready To Merge

#9636 Support EXCEPT ALL and INTERSECT ALL
  src/execution/physical_plan/plan_set_operation.cpp
  src/include/duckdb/main/relation/setop_relation.hpp
  src/include/duckdb/parser/query_node/set_operation_node.hpp
  src/include/duckdb/planner/operator/logical_set_operation.hpp
  src/include/duckdb/planner/query_node/bound_set_operation_node.hpp
  src/include/duckdb/storage/serialization/logical_operator.json
  src/include/duckdb/storage/serialization/query_node.json
  src/main/relation.cpp
  src/main/relation/setop_relation.cpp
  src/parser/query_node/set_operation_node.cpp
  src/parser/transform/statement/transform_select_node.cpp
  src/planner/binder/query_node/bind_setop_node.cpp
  src/planner/binder/query_node/plan_recursive_cte_node.cpp
  src/planner/binder/query_node/plan_setop.cpp
  src/planner/binder/statement/bind_export.cpp
  src/storage/serialization/serialize_logical_operator.cpp
  src/storage/serialization/serialize_query_node.cpp
  test/sql/setops/test_pg_union.test
  test/sql/setops/test_setops.test
Labels: Ready To Merge

#9772 Internal #766: SkipList Coin Toss
  third_party/skiplist/Node.h
  third_party/skiplist/SkipList.h
Labels: Ready For Review

#9773 Issue #9762: Interval Fractional Seconds
  src/common/types/interval.cpp
  src/core_functions/scalar/date/functions.json
  src/core_functions/scalar/date/to_interval.cpp
  src/include/duckdb/core_functions/scalar/date_functions.hpp
  src/include/duckdb/core_functions/to_interval.hpp
  src/parser/transform/expression/transform_interval.cpp
  test/sql/types/interval/interval_constants.test
  test/sql/window/test_window_wide_frame.test_slow
Labels: Ready For Review

#9774 Internal #716: Summarize approx_unique BIGINT
  src/planner/binder/statement/bind_summarize.cpp
Labels: Ready For Review

#9769 Issue #9755: TIMESTAMP_XX DOUBLE Parts
  src/core_functions/scalar/date/date_part.cpp
  test/sql/function/timestamp/test_date_part.test
Labels: Ready For Review

#9765 Add support for COPY FROM DATABASE statement
  src/common/enum_util.cpp
  src/common/enums/logical_operator_type.cpp
  src/common/enums/physical_operator_type.cpp
  src/common/enums/statement_type.cpp
  src/common/symbols.cpp
  src/execution/operator/persistent/CMakeLists.txt
  src/execution/operator/persistent/physical_copy_database.cpp
  src/execution/operator/persistent/physical_export.cpp
  src/execution/operator/set/physical_union.cpp
  src/execution/physical_plan/CMakeLists.txt
  src/execution/physical_plan/plan_copy_database.cpp
  src/execution/physical_plan/plan_set_operation.cpp
  src/execution/physical_plan_generator.cpp
  src/function/pragma/pragma_queries.cpp
  src/include/duckdb/catalog/catalog_entry/list.hpp
  src/include/duckdb/common/enums/logical_operator_type.hpp
  src/include/duckdb/common/enums/physical_operator_type.hpp
  src/include/duckdb/common/enums/statement_type.hpp
  src/include/duckdb/execution/operator/persistent/physical_copy_database.hpp
  src/include/duckdb/execution/operator/persistent/physical_export.hpp
  src/include/duckdb/execution/operator/set/physical_union.hpp
  src/include/duckdb/execution/physical_plan_generator.hpp
  src/include/duckdb/parser/statement/copy_database_statement.hpp
  src/include/duckdb/parser/statement/list.hpp
  src/include/duckdb/parser/tokens.hpp
  src/include/duckdb/parser/transformer.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/logical_tokens.hpp
  src/include/duckdb/planner/operator/list.hpp
  src/include/duckdb/planner/operator/logical_copy_database.hpp
  src/include/duckdb/planner/operator/logical_set_operation.hpp
  src/include/duckdb/storage/serialization/logical_operator.json
  src/parser/statement/CMakeLists.txt
  src/parser/statement/copy_database_statement.cpp
  src/parser/transform/statement/CMakeLists.txt
  src/parser/transform/statement/transform_copy_database.cpp
  src/parser/transformer.cpp
  src/planner/binder.cpp
  src/planner/binder/statement/CMakeLists.txt
  src/planner/binder/statement/bind_copy_database.cpp
  src/planner/operator/CMakeLists.txt
  src/planner/operator/logical_copy_database.cpp
  src/planner/planner.cpp
  src/storage/serialization/serialize_logical_operator.cpp
  test/sql/copy_database/copy_database_different_types.test
  test/sql/copy_database/copy_database_errors.test
  test/sql/copy_database/copy_database_fk.test
  test/sql/copy_database/copy_database_simple.test
  test/sql/copy_database/copy_database_tpch.test_slow
  third_party/libpg_query/grammar/statements/copy.y
  third_party/libpg_query/grammar/types/copy.yh
  third_party/libpg_query/include/nodes/nodes.hpp
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation

#9779 chore: move links duckdblabs -> duckdb
  .github/config/extensions.csv
  .github/patches/extensions/README.md
  .github/workflows/ExtensionRebuild.yml
  .github/workflows/ExtensionTrigger.yml
  extension/README.md
Labels: Ready To Merge

#9356 Extention template: Enable DuckDB-Wasm extensions
  .github/config/distribution_matrix.json
  .github/workflows/_extension_distribution.yml
  scripts/modify_distribution_matrix.py
Labels: Ready To Merge

#9736 format_bytes rework, moving from decimal multipliers to binary ones
  src/common/string_util.cpp
  src/core_functions/function_list.cpp
  src/core_functions/scalar/string/format_bytes.cpp
  src/core_functions/scalar/string/functions.json
  src/include/duckdb/common/string_util.hpp
  src/include/duckdb/core_functions/scalar/string_functions.hpp
  src/main/config.cpp
  test/api/test_reset.cpp
  test/sql/function/string/format_bytes.test
  test/sql/index/art/memory/test_art_linear.test_slow
  test/sql/index/art/memory/test_art_non_linear.test_slow
  test/sql/index/art/memory/test_art_varchar.test_slow
  test/sql/index/art/vacuum/test_art_vacuum_integers.test_slow
  test/sql/index/art/vacuum/test_art_vacuum_strings.test_slow
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
Labels: Ready For Review

#9790 Make FORCE CHECKPOINT abort transactions of concurrently running queries
  src/include/duckdb/transaction/meta_transaction.hpp
  src/transaction/duck_transaction_manager.cpp
  src/transaction/meta_transaction.cpp
  test/sql/storage/force_checkpoint_abort.test
  test/sql/storage/multiple_clients_checkpoing_dependents.test_slow
  test/sql/storage/multiple_clients_checkpoint_pending_updates.test
Labels: Ready To Merge

#9237 Cleanup raw pointers from transaction manager
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/postgres_scanner/transaction_rework.patch
  .github/patches/extensions/sqlite_scanner/transaction_rework.patch
  src/include/duckdb/common/helper.hpp
  src/include/duckdb/transaction/duck_transaction_manager.hpp
  src/include/duckdb/transaction/meta_transaction.hpp
  src/include/duckdb/transaction/transaction_manager.hpp
  src/transaction/duck_transaction_manager.cpp
  src/transaction/meta_transaction.cpp
Labels: Ready To Merge

#9518 Partially fix #4182 - write distinct stats for string dictionary columns
  extension/parquet/column_writer.cpp
  test/sql/copy/parquet/writer/parquet_write_string_distinct.test
Labels: Ready To Merge

#9793 Implement #2534 - add parquet_file_metadata function that supports scanning top-level file metadata
  extension/parquet/include/parquet_metadata.hpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_metadata.cpp
  src/include/duckdb/main/extension_entries.hpp
  test/sql/copy/parquet/file_metadata.test
  test/sql/copy/parquet/kv_metadata.test
Labels: Needs Documentation

#9792 Correctly clean up database path when an error is thrown in attach
  src/main/attached_database.cpp
  src/main/database_manager.cpp
  test/sql/attach/attach_filepath_roundtrip.test
Labels: CI Failure

#9799 Fix cotangent(0.0): should also throw OutOfRange
  src/core_functions/scalar/math/numeric.cpp
Labels: Ready To Merge

#9815 Add duckdb_optimizers function
  src/common/enums/optimizer_type.cpp
  src/function/table/system/CMakeLists.txt
  src/function/table/system/duckdb_optimizers.cpp
  src/function/table/system_functions.cpp
  src/include/duckdb/common/enums/optimizer_type.hpp
  src/include/duckdb/function/table/system_functions.hpp
  test/sql/table_function/duckdb_optimizers.test
Labels: Needs Documentation

#9811 [Python] Pandas Analyzer no longer trips up when the `pandas_analyze_sample` would only let it find nulls.
  tools/pythonpkg/src/pandas/analyzer.cpp
  tools/pythonpkg/tests/fast/pandas/test_df_object_resolution.py
Labels: Ready For Review

#9730 [Upsert] Do not require ON CONFLICT clause on INSERT OR REPLACE in some situations.
  src/planner/binder/statement/bind_insert.cpp
  test/sql/upsert/insert_or_replace_ambiguity.test
Labels: Ready For Review

#9643 Issue #9631: Time/Interval Hours
  src/common/types/interval.cpp
  src/common/types/time.cpp
  src/common/types/value.cpp
  src/include/duckdb/common/types/time.hpp
  test/sql/cast/string_to_nested_types_cast.test_slow
  test/sql/copy/parquet/writer/parquet_test_all_types.test
  test/sql/storage_version/storage_version.db
  test/sql/types/interval/test_interval.test
  test/sql/types/test_all_types.test_slow
  test/sql/types/time/time_try_cast.test
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
  tools/juliapkg/test/test_all_types.jl
  tools/pythonpkg/tests/fast/test_all_types.py
  tools/swift/duckdb-swift/Tests/DuckDBTests/TypeConversionTests.swift
Labels: bug, Python, JDBC, Needs Documentation, Ready For Review

#9438 feat(c): support creating nested values in C API
  src/common/types/value.cpp
  src/include/duckdb.h
  src/include/duckdb/common/types/value.hpp
  src/main/capi/duckdb_value-c.cpp
  test/api/capi/test_capi_complex_types.cpp
  test/include/capi_tester.hpp
Labels: Ready For Review

#9796 Issue #9785: Missing Interval Parts
  src/core_functions/function_list.cpp
  src/core_functions/scalar/date/functions.json
  src/core_functions/scalar/date/to_interval.cpp
  src/include/duckdb/core_functions/scalar/date_functions.hpp
  src/parser/transform/expression/transform_interval.cpp
  test/sql/types/interval/interval_constants.test
  third_party/libpg_query/grammar/keywords/unreserved_keywords.list
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/include/parser/kwlist.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Ready For Review

#9724 Issue#604 Support collations during IN/NOT IN operations.
  src/planner/binder/expression/bind_operator_expression.cpp
  test/sql/binder/test_in_with_collate.test
Labels: Changes Requested

#9844 Fix: Undefined behaviour in Bitpacking compression
  src/storage/compression/bitpacking.cpp
Labels: Ready For Review

#9847 Add ORDER BY to List_Select test
  test/sql/function/list/list_select.test
Labels: Ready To Merge

#9531 Expand Progress API
  src/common/progress_bar/progress_bar.cpp
  src/include/duckdb.h
  src/include/duckdb/common/progress_bar/progress_bar.hpp
  src/include/duckdb/execution/executor.hpp
  src/include/duckdb/main/capi/capi_internal.hpp
  src/include/duckdb/main/client_context.hpp
  src/main/capi/duckdb-c.cpp
  src/main/client_context.cpp
  src/parallel/executor.cpp
  test/api/capi/test_capi_streaming.cpp
  test/api/test_progress_bar.cpp
Labels: Ready To Merge
