Repository duckdb/duckdb, pull requests merged in 2024-06, with the labels that each got.

#12337 Make `dbgen` generate data in parallel
  extension/tpch/dbgen/bm_utils.cpp
  extension/tpch/dbgen/build.cpp
  extension/tpch/dbgen/dbgen.cpp
  extension/tpch/dbgen/include/dbgen/dss.h
  extension/tpch/dbgen/permute.cpp
  src/include/duckdb/main/appender.hpp
  src/main/appender.cpp
  test/api/capi/test_capi_prepared.cpp
Labels: Needs Documentation

#12311 Issue #12171: Streaming Windowed DISTINCT
  src/execution/operator/aggregate/physical_streaming_window.cpp
  test/sql/window/test_streaming_window.test
  test/sql/window/test_streaming_window_distinct.test
Labels: Ready For Review

#12300 Remove sqlsmith extension
  .github/config/bundled_extensions.cmake
  .github/config/in_tree_extensions.cmake
  .github/config/out_of_tree_extensions.cmake
  .github/workflows/coverity.yml
  Makefile
  extension/sqlsmith/CMakeLists.txt
  extension/sqlsmith/fuzzyduck.cpp
  extension/sqlsmith/include/fuzzyduck.hpp
  extension/sqlsmith/include/sqlsmith_extension.hpp
  extension/sqlsmith/include/statement_generator.hpp
  extension/sqlsmith/include/statement_simplifier.hpp
  extension/sqlsmith/sqlsmith_extension.cpp
  extension/sqlsmith/statement_generator.cpp
  extension/sqlsmith/statement_simplifier.cpp
  extension/sqlsmith/third_party/CMakeLists.txt
  extension/sqlsmith/third_party/sqlsmith/CMakeLists.txt
  extension/sqlsmith/third_party/sqlsmith/duckdb.cc
  extension/sqlsmith/third_party/sqlsmith/dump.cc
  extension/sqlsmith/third_party/sqlsmith/expr.cc
  extension/sqlsmith/third_party/sqlsmith/grammar.cc
  extension/sqlsmith/third_party/sqlsmith/impedance.cc
  extension/sqlsmith/third_party/sqlsmith/include/duckdb.hh
  extension/sqlsmith/third_party/sqlsmith/include/dump.hh
  extension/sqlsmith/third_party/sqlsmith/include/dut.hh
  extension/sqlsmith/third_party/sqlsmith/include/expr.hh
  extension/sqlsmith/third_party/sqlsmith/include/grammar.hh
  extension/sqlsmith/third_party/sqlsmith/include/impedance.hh
  extension/sqlsmith/third_party/sqlsmith/include/log.hh
  extension/sqlsmith/third_party/sqlsmith/include/prod.hh
  extension/sqlsmith/third_party/sqlsmith/include/random.hh
  extension/sqlsmith/third_party/sqlsmith/include/relmodel.hh
  extension/sqlsmith/third_party/sqlsmith/include/schema.hh
  extension/sqlsmith/third_party/sqlsmith/include/sqlsmith.hh
  extension/sqlsmith/third_party/sqlsmith/include/util.hh
  extension/sqlsmith/third_party/sqlsmith/log.cc
  extension/sqlsmith/third_party/sqlsmith/prod.cc
  extension/sqlsmith/third_party/sqlsmith/random.cc
  extension/sqlsmith/third_party/sqlsmith/relmodel.cc
  extension/sqlsmith/third_party/sqlsmith/schema.cc
  extension/sqlsmith/third_party/sqlsmith/sqlsmith.cc
  src/main/extension/extension_helper.cpp
  test/fuzzer/duckfuzz/array_hash.test
  test/fuzzer/duckfuzz/duckfuzz_tests/test_duckfuzz.test
  test/sqlsmith/sql_reduce.test
Labels: Needs Documentation

#11815 Reorder semi and anti joins.
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/substrait/pushdown_semi_anti.patch
  src/include/duckdb/common/enums/join_type.hpp
  src/include/duckdb/optimizer/join_order/cardinality_estimator.hpp
  src/include/duckdb/optimizer/join_order/cost_model.hpp
  src/include/duckdb/optimizer/join_order/query_graph.hpp
  src/include/duckdb/optimizer/join_order/query_graph_manager.hpp
  src/include/duckdb/optimizer/join_order/relation_manager.hpp
  src/optimizer/column_lifetime_analyzer.cpp
  src/optimizer/join_order/cardinality_estimator.cpp
  src/optimizer/join_order/join_relation_set.cpp
  src/optimizer/join_order/plan_enumerator.cpp
  src/optimizer/join_order/query_graph_manager.cpp
  src/optimizer/join_order/relation_manager.cpp
  src/optimizer/join_order/relation_statistics_helper.cpp
  src/optimizer/statistics/operator/propagate_filter.cpp
  test/api/test_reset.cpp
  test/fuzzer/duckfuzz/duck_fuzz_column_binding_tests.test
  test/optimizer/column_lifetime_analyzer/must_visit_operator_expressions_first.test
  test/optimizer/deliminator.test
  test/optimizer/joins/pushdown_semi_anti.test
  test/sqlite/select4.test_slow
Labels: Ready For Review

#12352 Issue #12351: implicit cast to `TIMESTAMP_MS`, `TIMESTAMP_S`, `TIMESTAMP_NS` from `DATE` values
  src/function/cast_rules.cpp
  test/sql/types/date/date_implicit_cast.test
Labels: Ready For Review

#12355 Issue #10023: Approx_Count_Distinct Memory Usage
  src/core_functions/aggregate/distributive/approx_count.cpp
  src/core_functions/aggregate/distributive/functions.json
  src/core_functions/function_list.cpp
  src/include/duckdb/core_functions/aggregate/distributive_functions.hpp
  test/sql/aggregate/aggregates/test_approximate_distinct_count.test
  test/sql/function/list/aggregates/approx_count_distinct.test
  test/sql/parallelism/intraquery/test_aggregations_parallelism.test_slow
  third_party/hyperloglog/hyperloglog.hpp
Labels: Ready For Review

#12383 Fix a small typo in dev instructions for swift setup
  tools/swift/duckdb-swift/README.md
Labels: Ready To Merge

#12391 Release lock before returning `BufferHandle` in `StandardBufferManager::Pin`
  src/storage/standard_buffer_manager.cpp
Labels: Ready To Merge

#12393 Remote attach autoload
  src/common/file_system.cpp
  src/execution/operator/schema/physical_attach.cpp
  src/include/duckdb/common/file_system.hpp
  test/sql/attach/attach_remote.test
Labels: Ready For Review

#12222 Add JSON type to Parquet reader/writer
  data/json/12188.ndjson
  data/parquet-testing/parquet_with_json.parquet
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_writer.cpp
  test/sql/json/issues/issue12188.test
Labels: Ready For Review

#12220 Add `RETURN_FILES` parameter to `COPY TO`
  src/common/enum_util.cpp
  src/execution/operator/persistent/physical_batch_copy_to_file.cpp
  src/execution/operator/persistent/physical_copy_to_file.cpp
  src/execution/physical_plan/plan_copy_to_file.cpp
  src/function/CMakeLists.txt
  src/function/copy_function.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/execution/operator/persistent/physical_batch_copy_to_file.hpp
  src/include/duckdb/execution/operator/persistent/physical_copy_to_file.hpp
  src/include/duckdb/function/copy_function.hpp
  src/include/duckdb/planner/operator/logical_copy_to_file.hpp
  src/planner/binder/statement/bind_copy.cpp
  src/planner/operator/logical_copy_to_file.cpp
  test/sql/copy/return_files.test
Labels: Needs Documentation, Ready For Review

#11472 Updated JoinHashTable to use linear probing to resolve hash collisions
  .github/regression/micro_extended.csv
  .sanitizer-thread-suppressions.txt
  benchmark/micro/join/hashjoin_dups_rhs.benchmark
  src/common/row_operations/row_matcher.cpp
  src/common/types/row/tuple_data_collection.cpp
  src/execution/aggregate_hashtable.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/common/row_operations/row_matcher.hpp
  src/include/duckdb/common/types/row/tuple_data_collection.hpp
  src/include/duckdb/execution/aggregate_hashtable.hpp
  src/include/duckdb/execution/ht_entry.hpp
  src/include/duckdb/execution/join_hashtable.hpp
Labels: Ready To Merge

#11905 [Appender] Add `AppendDefault`
  src/common/types/selection_vector.cpp
  src/include/duckdb.h
  src/include/duckdb/common/types/selection_vector.hpp
  src/include/duckdb/main/appender.hpp
  src/main/appender.cpp
  src/main/capi/appender-c.cpp
  src/main/client_context.cpp
  test/api/capi/test_capi_appender.cpp
  test/appender/test_appender.cpp
Labels: Ready For Review

#12161 [Python Dev] Push CTE internally for every (python) replacement scan that occurred.
  src/common/enum_util.cpp
  src/include/duckdb/function/replacement_scan.hpp
  src/include/duckdb/main/relation/query_relation.hpp
  src/include/duckdb/parser/tableref.hpp
  src/include/duckdb/parser/tableref/basetableref.hpp
  src/include/duckdb/parser/tableref/pivotref.hpp
  src/include/duckdb/parser/tableref/subqueryref.hpp
  src/include/duckdb/parser/tableref/table_function_ref.hpp
  src/include/duckdb/planner/binder.hpp
  src/main/relation/query_relation.cpp
  src/planner/binder.cpp
  src/planner/binder/tableref/bind_basetableref.cpp
  tools/pythonpkg/src/python_replacement_scan.cpp
  tools/pythonpkg/tests/fast/test_replacement_scan.py
Labels: Ready For Review

#12423 Write zero-length list offsets for NULL values when serializing vectors
  scripts/run_tests_one_by_one.py
  src/common/types/vector.cpp
Labels: Ready To Merge

#12420 jemalloc: Identify GNU source code properly
  extension/jemalloc/jemalloc/include/jemalloc/internal/jemalloc_internal_defs.h
Labels: Ready To Merge

#12426 Revert duckdb/duckdb#10865
  .github/actions/build_extensions/action.yml
Labels: Ready For Review

#12447 Work-around for broken github windows runner
  CMakeLists.txt
Labels: Ready To Merge

#12436 Prevents clearing of the types of the LogicalExecute operator
  src/include/duckdb/planner/operator/logical_execute.hpp
  test/api/test_api.cpp
Labels: Ready To Merge

#12448 Issue #12412: AsOf Filter Push
  src/optimizer/filter_pullup.cpp
  src/optimizer/pushdown/pushdown_cross_product.cpp
  src/planner/binder/tableref/plan_joinref.cpp
  test/sql/join/asof/test_asof_join_pushdown.test
Labels: Ready For Review

#12461 By default attach remote databases as READ_ONLY
  src/execution/operator/schema/physical_attach.cpp
  test/sql/attach/attach_remote.test
Labels: Ready For Review

#12470 Issue #12464: Windowed Order By All
  src/parser/transform/expression/transform_function.cpp
  test/sql/window/test_order_by_all.test
Labels: Ready For Review

#12482 [Fix] access_mode now lives in AttachOptions
  src/execution/operator/schema/physical_attach.cpp
Labels: Ready To Merge

#12440 Internal #2186: Nanosecond Functionality
  extension/parquet/column_reader.cpp
  extension/parquet/column_writer.cpp
  extension/parquet/include/parquet_timestamp.hpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_statistics.cpp
  extension/parquet/parquet_timestamp.cpp
  extension/parquet/parquet_writer.cpp
  src/common/operator/cast_operators.cpp
  src/common/operator/string_cast.cpp
  src/common/types/time.cpp
  src/common/types/timestamp.cpp
  src/common/types/value.cpp
  src/core_functions/function_list.cpp
  src/core_functions/scalar/date/date_part.cpp
  src/core_functions/scalar/date/functions.json
  src/function/cast/string_cast.cpp
  src/function/cast/time_casts.cpp
  src/include/duckdb/common/operator/cast_operators.hpp
  src/include/duckdb/common/operator/string_cast.hpp
  src/include/duckdb/common/types/time.hpp
  src/include/duckdb/common/types/timestamp.hpp
  src/include/duckdb/core_functions/scalar/date_functions.hpp
  test/sql/cast/string_to_nested_types_cast.test_slow
  test/sql/copy/parquet/writer/parquet_test_all_types.test
  test/sql/copy/parquet/writer/parquet_write_timestamp.test
  test/sql/function/date/test_date_part.test
  test/sql/function/interval/test_date_part.test
  test/sql/function/time/test_date_part.test
  test/sql/function/timestamp/test_date_part.test
  test/sql/function/timetz/test_date_part.test
  test/sql/storage/types/test_timestamp_storage.test
  test/sql/storage_version/storage_version.db
  test/sql/types/test_all_types.test_slow
  test/sql/types/timestamp/test_timestamp_types.test
  test/sql/types/timestamp/timestamp_precision.test
  tools/juliapkg/test/test_all_types.jl
  tools/swift/duckdb-swift/Tests/DuckDBTests/TypeConversionTests.swift
Labels: Ready For Review

#12465 [C-API] Fix leak in `duckdb_create_config`
  src/include/duckdb.h
  src/main/capi/config-c.cpp
Labels: Ready To Merge

#12486 throw binder error for comment on system catalog
  src/planner/binder/statement/bind_simple.cpp
  test/sql/catalog/comment_on.test
Labels: Ready To Merge

#12478 Parquet reader performance
  extension/parquet/column_reader.cpp
  extension/parquet/column_writer.cpp
  extension/parquet/include/boolean_column_reader.hpp
  extension/parquet/include/column_reader.hpp
  extension/parquet/include/column_writer.hpp
  extension/parquet/include/parquet_rle_bp_decoder.hpp
  extension/parquet/include/parquet_rle_bp_encoder.hpp
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/include/resizable_buffer.hpp
  extension/parquet/include/string_column_reader.hpp
  extension/parquet/include/templated_column_reader.hpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_writer.cpp
  src/common/serializer/memory_stream.cpp
  src/include/duckdb/common/serializer/memory_stream.hpp
  third_party/snappy/snappy-stubs-internal.h
Labels: Ready To Merge

#12489 Operators the Optimizer can skip
  src/optimizer/optimizer.cpp
Labels: Ready To Merge

#12445 Allow parquet encryption/decryption keys to be passed in as base64 encoded strings
  extension/parquet/parquet_crypto.cpp
  test/sql/copy/parquet/parquet_encryption.test
Labels: Ready For Review

#12481 [Block Size] Introducing CompressionInfo
  src/function/compression_config.cpp
  src/include/duckdb/common/fsst.hpp
  src/include/duckdb/common/optional_ptr.hpp
  src/include/duckdb/common/serializer/deserialization_data.hpp
  src/include/duckdb/function/compression/compression.hpp
  src/include/duckdb/function/compression_function.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/storage/block.hpp
  src/include/duckdb/storage/buffer_manager.hpp
  src/include/duckdb/storage/checkpoint/string_checkpoint_state.hpp
  src/include/duckdb/storage/compression/alp/alp_analyze.hpp
  src/include/duckdb/storage/compression/alp/alp_compress.hpp
  src/include/duckdb/storage/compression/alprd/alprd_analyze.hpp
  src/include/duckdb/storage/compression/alprd/alprd_compress.hpp
  src/include/duckdb/storage/data_pointer.hpp
  src/include/duckdb/storage/standard_buffer_manager.hpp
  src/include/duckdb/storage/storage_info.hpp
  src/include/duckdb/storage/string_uncompressed.hpp
  src/include/duckdb/storage/table/column_segment.hpp
  src/storage/block.cpp
  src/storage/buffer_manager.cpp
  src/storage/compression/alp/alp.cpp
  src/storage/compression/alprd.cpp
  src/storage/compression/bitpacking.cpp
  src/storage/compression/chimp/chimp.cpp
  src/storage/compression/dictionary_compression.cpp
  src/storage/compression/fixed_size_uncompressed.cpp
  src/storage/compression/fsst.cpp
  src/storage/compression/numeric_constant.cpp
  src/storage/compression/patas.cpp
  src/storage/compression/rle.cpp
  src/storage/compression/string_uncompressed.cpp
  src/storage/compression/uncompressed.cpp
  src/storage/compression/validity_uncompressed.cpp
  src/storage/data_pointer.cpp
  src/storage/metadata/metadata_manager.cpp
  src/storage/partial_block_manager.cpp
  src/storage/single_file_block_manager.cpp
  src/storage/standard_buffer_manager.cpp
  src/storage/storage_info.cpp
  src/storage/table/column_checkpoint_state.cpp
  src/storage/table/column_data.cpp
  src/storage/table/column_data_checkpointer.cpp
  src/storage/table/column_segment.cpp
  src/storage/table/standard_column_data.cpp
  test/sql/attach/attach_custom_block_size.test
  test/sql/function/list/lambdas/lambda_scope.test
  test/sql/outofcore/leftover_temp_files_issue_6420.test_slow
  test/sql/storage/issue7582_list_storage.test
  test/sql/storage/reclaim_space/test_reclaim_space_update.test_slow
  test/sql/storage/storage_types.test
  test/sql/storage/temp_directory/max_swap_space_persistent.test
  test/sql/storage/test_empty_table.test
  test/sql/storage/vacuum/test_truncate_after_delete.test_slow
  test/sql/vacuum/test_analyze.test
Labels: Ready For Review

#12509 CMake: use GNUInstallDirs as defaults for INSTALL_{BIN,LIB,INCLUDE}_DIR
  CMakeLists.txt
Labels: Ready To Merge

#12516 More formatting and fix to stddev
  scripts/format.py
  src/include/duckdb/core_functions/aggregate/algebraic/stddev.hpp
  src/include/duckdb/core_functions/aggregate/regression/regr_slope.hpp
Labels: Ready For Review

#12429 Linux Extensions CI: Attempt at fix missing dependencies
  .github/actions/ubuntu_18_setup/action.yml
Labels: Ready For Review

#12366 Fix checkouts
  .github/actions/ubuntu_18_setup/action.yml
  .github/workflows/LinuxRelease.yml
Labels: Ready For Review

#12333 Etag if none match for extension install
  src/include/duckdb/main/extension_install_info.hpp
  src/include/duckdb/storage/serialization/extension_install_info.json
  src/main/extension/extension_install.cpp
  src/storage/serialization/serialize_extension_install_info.cpp
Labels: Ready For Review

#12514 [Block Size] FixedSizeAllocator, MetadataManager, PartialBlockManager
  src/execution/index/fixed_size_allocator.cpp
  src/execution/index/fixed_size_buffer.cpp
  src/include/duckdb/storage/metadata/metadata_manager.hpp
  src/include/duckdb/storage/partial_block_manager.hpp
  src/storage/metadata/metadata_manager.cpp
  src/storage/metadata/metadata_reader.cpp
  src/storage/metadata/metadata_writer.cpp
  src/storage/partial_block_manager.cpp
  src/storage/single_file_block_manager.cpp
  test/sql/storage/parallel/memory_limit_batch_load.test_slow
Labels: Ready To Merge

#12511 [Python] Skip the PandasAnalyzer if dtype is `'string'`
  tools/pythonpkg/src/include/duckdb_python/numpy/numpy_type.hpp
  tools/pythonpkg/src/numpy/numpy_bind.cpp
  tools/pythonpkg/src/numpy/numpy_scan.cpp
  tools/pythonpkg/src/numpy/type.cpp
  tools/pythonpkg/src/pandas/scan.cpp
  tools/pythonpkg/tests/fast/pandas/test_pandas_na.py
Labels: Ready For Review

#12512 [Python] Remove busy-spin during execution
  src/include/duckdb/main/pending_query_result.hpp
  src/main/pending_query_result.cpp
  tools/pythonpkg/src/pyconnection.cpp
Labels: Ready To Merge

#12550 Build Android Binaries
  .github/actions/build_extensions/action.yml
  .github/workflows/Android.yml
Labels: Ready To Merge

#12036 Internal #2017: DECIMAL Downcast Rounding
  src/function/cast/decimal_cast.cpp
  src/include/duckdb/common/operator/decimal_cast_operators.hpp
  test/sql/types/decimal/decimal_automatic_cast.test
  test/sql/types/decimal/test_decimal.test
  test/sql/types/decimal/test_decimal_from_string.test
Labels: Ready For Review

#12297 Issue #12204: Summarize Temporal Quantiles
  src/common/types.cpp
  src/core_functions/aggregate/holistic/approximate_quantile.cpp
  src/include/duckdb/common/types.hpp
  src/planner/binder/statement/bind_summarize.cpp
  test/sql/show_select/test_summarize.test
Labels: Ready For Review

#12551 Internal #2186: Nanosecond StrTimeFormat
  extension/icu/icu-strptime.cpp
  src/common/types/time.cpp
  src/core_functions/scalar/date/strftime.cpp
  src/function/scalar/strftime_format.cpp
  src/include/duckdb/common/types/time.hpp
  src/include/duckdb/function/scalar/strftime_format.hpp
  test/sql/function/timestamp/test_strftime_timestamp_ns.test
  test/sql/function/timestamp/test_strptime.test
Labels: Ready For Review

#12501 add support for casting 'yes'/'no' strings to boolean values
  src/common/operator/cast_operators.cpp
  test/sql/cast/test_boolean_cast.test
Labels: CI Failure

#12170 ICU noaccent collation
  extension/icu/icu_extension.cpp
  src/include/duckdb/main/extension_entries.hpp
  test/sql/collate/test_icu_collate.test
Labels: Ready To Merge

#11872 [FriendlySQL] Unpacked COLUMNS() Expression
  src/include/duckdb/parser/expression/star_expression.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/storage/serialization/parsed_expression.json
  src/parser/expression/star_expression.cpp
  src/parser/transform/expression/transform_columnref.cpp
  src/planner/binder/expression/CMakeLists.txt
  src/planner/binder/expression/bind_star_expression.cpp
  src/planner/binder/expression/bind_unpacked_star_expression.cpp
  src/storage/serialization/serialize_parsed_expression.cpp
  test/sql/parser/test_columns_lists.test
  test/sql/parser/test_columns_unpacked.test
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
  third_party/libpg_query/src_backend_parser_scan.cpp
Labels: Ready For Review

#12583 [Python] Don't use `np.nan`, deprecated alias starting with NumPy 2.0
  tools/pythonpkg/tests/fast/types/test_nan.py
Labels: Ready To Merge

#12460 [C-API] Add `table_description` struct to query various information about the table.
  src/include/duckdb.h
  src/include/duckdb/main/capi/capi_internal.hpp
  src/main/capi/CMakeLists.txt
  src/main/capi/table_description-c.cpp
  test/api/capi/CMakeLists.txt
  test/api/capi/test_capi_table_description.cpp
Labels: Ready For Review

#12598 Change new micro benchmark script to only look for `.benchmark` files
  .github/workflows/Regression.yml
Labels: Ready To Merge

#12608 Add HTTP error code to extension install failures
  src/main/extension/extension_install.cpp
Labels: Ready For Review

#12573 Feature #1272: Window Executor State
  src/execution/operator/aggregate/aggregate_object.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/window_executor.cpp
  src/execution/window_segment_tree.cpp
  src/include/duckdb/execution/operator/aggregate/aggregate_object.hpp
  src/include/duckdb/execution/window_executor.hpp
  src/include/duckdb/execution/window_segment_tree.hpp
Labels: Ready For Review

#12609 Issue #12600: Streaming Positive LAG
  .github/regression/micro_extended.csv
  benchmark/micro/window/streaming_lag.benchmark
  src/execution/operator/aggregate/physical_streaming_window.cpp
  src/execution/physical_plan/plan_window.cpp
  src/include/duckdb/execution/operator/aggregate/physical_streaming_window.hpp
  test/sql/window/test_streaming_lead_lag.test
  test/sql/window/test_streaming_window.test
Labels: Ready For Review

#12628 Feature #1272: Window Group Preparation
  src/common/enum_util.cpp
  src/common/sort/partition_state.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/include/duckdb/common/sort/partition_state.hpp
  test/extension/test_custom_type_modifier.test_slow
Labels: Ready For Review

#12629 Feature 1272: Window Payload Preallocation
  src/execution/window_executor.cpp
  src/include/duckdb/execution/window_executor.hpp
Labels: Ready For Review

#12643 Remove custom logic to detect main vs feature
  .github/workflows/Regression.yml
Labels: Ready For Review

#12612 Use lowercase in 'html' output mode
  tools/shell/shell.c
  tools/shell/tests/test_shell_basics.py
Labels: CI Failure

#12652 Internal #2361: Window ROWS Overflow
  src/execution/window_executor.cpp
  test/fuzzer/duckfuzz/window_negate_stats.test
  test/fuzzer/sqlsmith/window-rows-overflow.test
Labels: Ready For Review

#12642 Quantile: Fix variable used only in D_ASSERT
  src/core_functions/aggregate/holistic/quantile.cpp
Labels: Ready To Merge

#12645 Skip pytorch test, it fails spuriously in CI
  tools/pythonpkg/tests/fast/test_pytorch.py
Labels: Ready For Review

#12659 Regression workflow on newly introduced benchmarks: remove for now
  .github/workflows/Regression.yml
Labels: Ready For Review

#12658 Add != operators on string_t and interval_t
  src/include/duckdb/common/types/interval.hpp
  src/include/duckdb/common/types/string_type.hpp
Labels: Ready For Review

#12653 Add `approx_top_k` aggregate based on the (Filtered) Space-Saving algorithm, and use it in histogram
  src/catalog/default/default_table_functions.cpp
  src/core_functions/aggregate/holistic/CMakeLists.txt
  src/core_functions/aggregate/holistic/approx_top_k.cpp
  src/core_functions/aggregate/holistic/functions.json
  src/core_functions/function_list.cpp
  src/include/duckdb/core_functions/aggregate/holistic_functions.hpp
  test/sql/aggregate/aggregates/approx_top_k.test
  test/sql/aggregate/aggregates/approx_top_k_big.test_slow
  test/sql/aggregate/aggregates/histogram_tpch.test_slow
Labels: Needs Documentation

#12669 Fix std::sort requirements, from greater_equal to greater
  src/optimizer/join_order/plan_enumerator.cpp
Labels: Ready To Merge

#12692 Dont load spatial unless geoparquet metata is present
  extension/parquet/geo_parquet.cpp
  extension/parquet/include/geo_parquet.hpp
  extension/parquet/parquet_reader.cpp
Labels: Ready To Merge

#12717 Support thousand separator for floating point numbers
  test/sql/function/string/test_format_extensions.test
  third_party/fmt/include/fmt/format.h
Labels: Needs Documentation

#12708 Partitioned write - keep only up until 100 files open, when this limit is exceeded close the file and create a new file if more data for this partition appears
  benchmark/micro/copy/to_parquet_partition_by_many.benchmark
  src/execution/operator/persistent/physical_copy_to_file.cpp
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/settings/settings.cpp
  test/api/test_reset.cpp
  test/sql/copy/parquet/parquet_hive2.test
Labels: Needs Documentation

#12678 Support for variadic arguments in scalar UDFs in the C API
  src/include/duckdb.h
  src/main/capi/scalar_function-c.cpp
  test/api/capi/capi_scalar_functions.cpp
Labels: Ready To Merge

#12599 [Relation API] Dont push DISTINCT modifier for EXCEPT/INTERSECT ALL
  src/main/relation/setop_relation.cpp
  test/api/test_relation_api.cpp
  tools/pythonpkg/tests/fast/test_relation.py
Labels: Ready For Review

#12586 Builds for Windows on ARM64
  .github/workflows/Windows.yml
Labels: Ready To Merge

#12738 Add repeat(LIST[], INT) that allows repetition of lists similar to how this is allowed in Python
  src/core_functions/scalar/string/repeat.cpp
  test/sql/function/list/repeat_list.test
Labels: Needs Documentation

#12770 Issue #12600: Batched LEAD/LAG
  src/execution/window_executor.cpp
  src/include/duckdb/execution/window_executor.hpp
Labels: Ready For Review

#12685 Issue #12600: Streaming Positive LEAD
  .github/regression/micro_extended.csv
  benchmark/micro/window/streaming_lead.benchmark
  src/execution/operator/aggregate/physical_streaming_window.cpp
  src/include/duckdb/execution/operator/aggregate/physical_streaming_window.hpp
  test/sql/window/test_streaming_lead_lag.test
  test/sql/window/test_streaming_lead_lag.test_slow
  test/sql/window/test_streaming_window.test
Labels: Ready For Review
