Repository duckdb/duckdb, pull requests merged in 2024-10, with the labels that each got.

#13994 Fix some warnings found while compiling duckdb-node
  extension/parquet/include/parquet_rle_bp_decoder.hpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_writer.cpp
Labels: Ready For Review

#14059 PySpart df.drop() to support expressions
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
  tools/pythonpkg/src/include/duckdb_python/expression/pyexpression.hpp
  tools/pythonpkg/src/pyexpression.cpp
  tools/pythonpkg/src/pyexpression/initialize.cpp
  tools/pythonpkg/tests/fast/spark/test_spark_dataframe.py
Labels: Ready For Review

#14190 Issue 14189: Fix build when threads are disabled
  src/parallel/task_scheduler.cpp
Labels: Changes Requested

#14194 Overhaul Parquet dictionary handling
  benchmark/parquet/dictionary_read-long-100.benchmark
  benchmark/parquet/dictionary_read-long-1000000.benchmark
  benchmark/parquet/dictionary_read-short-100.benchmark
  benchmark/parquet/dictionary_read-short-1000000.benchmark
  benchmark/parquet/dictionary_read.benchmark.in
  data/parquet-testing/bug14120-dict-nulls-only.parquet
  extension/parquet/column_reader.cpp
  extension/parquet/include/boolean_column_reader.hpp
  extension/parquet/include/column_reader.hpp
  extension/parquet/include/null_column_reader.hpp
  extension/parquet/include/string_column_reader.hpp
  extension/parquet/include/templated_column_reader.hpp
  extension/parquet/parquet_reader.cpp
  test/parquet/test_parquet_reader.test_slow
  test/sql/copy/parquet/afl.test
Labels: Ready For Review

#13692 [Feature] Allow passing the catalog (database name) to appender
  src/include/duckdb/main/appender.hpp
  src/include/duckdb/main/client_context.hpp
  src/include/duckdb/main/connection.hpp
  src/include/duckdb/main/table_description.hpp
  src/main/appender.cpp
  src/main/client_context.cpp
  src/main/connection.cpp
  test/appender/test_appender.cpp
Labels: Ready For Review

#14181 Feature #3036: Window Spooling
  extension/core_functions/aggregate/holistic/mad.cpp
  extension/core_functions/aggregate/holistic/mode.cpp
  extension/core_functions/aggregate/holistic/quantile.cpp
  extension/core_functions/include/core_functions/aggregate/quantile_sort_tree.hpp
  extension/core_functions/include/core_functions/aggregate/quantile_state.hpp
  src/common/types/column/column_data_collection.cpp
  src/execution/window_executor.cpp
  src/execution/window_segment_tree.cpp
  src/function/aggregate/distributive/count.cpp
  src/include/duckdb/common/types/column/column_data_collection.hpp
  src/include/duckdb/common/vector_operations/aggregate_executor.hpp
  src/include/duckdb/execution/window_executor.hpp
  src/include/duckdb/execution/window_segment_tree.hpp
  src/include/duckdb/function/aggregate_function.hpp
  test/sql/window/test_custom_spooling.test_slow
  test/sql/window/test_window_distinct.test_slow
Labels: Ready For Review

#13987 Small C Extension API changes
  extension/demo_capi/capi_demo.cpp
  scripts/generate_c_api.py
  src/include/duckdb_extension.h
  src/main/extension/extension_load.cpp
Labels: Ready For Review

#14226 remove redundant Bit::SetBit
  src/common/types/bit.cpp
Labels: Changes Requested

#14048 Fix #13064: offer more suggestions with same score
  src/catalog/catalog.cpp
  src/include/duckdb/catalog/catalog.hpp
  test/sql/catalog/did_you_mean.test
Labels: Merge Conflict

#14093 Making client context lock optional for relation binding
  src/include/duckdb/main/client_context.hpp
  src/include/duckdb/main/client_context_wrapper.hpp
  src/include/duckdb/main/relation.hpp
  src/include/duckdb/main/relation/delete_relation.hpp
  src/include/duckdb/main/relation/table_function_relation.hpp
  src/include/duckdb/main/relation/table_relation.hpp
  src/include/duckdb/main/relation/update_relation.hpp
  src/include/duckdb/main/relation/value_relation.hpp
  src/include/duckdb/main/relation/view_relation.hpp
  src/main/client_context.cpp
  src/main/client_context_wrapper.cpp
  src/main/relation.cpp
  src/main/relation/aggregate_relation.cpp
  src/main/relation/create_table_relation.cpp
  src/main/relation/create_view_relation.cpp
  src/main/relation/cross_product_relation.cpp
  src/main/relation/delete_relation.cpp
  src/main/relation/delim_get_relation.cpp
  src/main/relation/distinct_relation.cpp
  src/main/relation/explain_relation.cpp
  src/main/relation/filter_relation.cpp
  src/main/relation/insert_relation.cpp
  src/main/relation/join_relation.cpp
  src/main/relation/order_relation.cpp
  src/main/relation/projection_relation.cpp
  src/main/relation/query_relation.cpp
  src/main/relation/setop_relation.cpp
  src/main/relation/subquery_relation.cpp
  src/main/relation/table_function_relation.cpp
  src/main/relation/table_relation.cpp
  src/main/relation/update_relation.cpp
  src/main/relation/value_relation.cpp
  src/main/relation/view_relation.cpp
  src/main/relation/write_csv_relation.cpp
  src/main/relation/write_parquet_relation.cpp
  tools/pythonpkg/src/pyrelation.cpp
Labels: Ready To Merge

#14268 Removing overzealous check in Parquet
  extension/parquet/include/templated_column_reader.hpp
  test/sql/copy/parquet/afl.test
  test/sql/copy/parquet/broken_parquet.test
Labels: Ready For Review

#14267 Make test random output ordered
  test/issues/general/test_14232.test
Labels: Ready To Merge

#14289 Only slice initialized vectors in `PhysicalHashAggregate::SinkDistinctGrouping`
  src/execution/operator/aggregate/physical_hash_aggregate.cpp
  test/issues/general/test_14232.test
  test/issues/general/test_14286.test
Labels: Ready To Merge

#14296 fix macro name with the same function name in it which causing repeat…
  src/catalog/default/default_functions.cpp
  test/sql/catalog/test_set_search_path.test
Labels: Ready To Merge

#14288 Json bugfixes
  data/json/internal_3197.json
  data/json/issue14259.json
  extension/json/include/json_common.hpp
  extension/json/json_functions/json_structure.cpp
  test/sql/json/issues/internal_issue3146.test
  test/sql/json/issues/internal_issue3197.test
  test/sql/json/issues/issue14245.test
  test/sql/json/issues/issue14259.test
Labels: Ready For Review

#13524 Implement PullUp Empty Results optimizer
  src/common/enum_util.cpp
  src/common/enums/metric_type.cpp
  src/common/enums/optimizer_type.cpp
  src/include/duckdb/common/enums/metric_type.hpp
  src/include/duckdb/common/enums/optimizer_type.hpp
  src/include/duckdb/optimizer/empty_result_pullup.hpp
  src/optimizer/CMakeLists.txt
  src/optimizer/empty_result_pullup.cpp
  src/optimizer/optimizer.cpp
  test/fuzzer/duckfuzz/duck_fuzz_column_binding_tests.test
  test/fuzzer/duckfuzz/semi_join_has_correct_left_right_relations.test
Labels: feature

#14254 [Fix] Don't initialize reference, constant, and parameter children in intermediate chunk
  src/common/types/data_chunk.cpp
  src/common/types/vector_cache.cpp
  src/execution/expression_executor.cpp
  src/execution/expression_executor/execute_between.cpp
  src/execution/expression_executor/execute_case.cpp
  src/execution/expression_executor/execute_cast.cpp
  src/execution/expression_executor/execute_comparison.cpp
  src/execution/expression_executor/execute_conjunction.cpp
  src/execution/expression_executor/execute_function.cpp
  src/execution/expression_executor/execute_operator.cpp
  src/execution/expression_executor/execute_reference.cpp
  src/execution/expression_executor_state.cpp
  src/execution/reservoir_sample.cpp
  src/include/duckdb/common/types/data_chunk.hpp
  src/include/duckdb/common/types/vector_cache.hpp
  src/include/duckdb/execution/expression_executor_state.hpp
  test/sql/types/struct/unnest_big_struct.test_slow
Labels: Ready To Merge

#14290 Profiling - correct settings per node type and minor renaming for clarity
  src/common/enum_util.cpp
  src/common/render_tree.cpp
  src/include/duckdb/common/enums/metric_type.hpp
  src/include/duckdb/main/profiling_info.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/main/capi/profiling_info-c.cpp
  src/main/profiling_info.cpp
  src/main/query_profiler.cpp
  test/api/capi/test_capi_profiling.cpp
  test/issues/general/test_14232.test
  test/sql/pragma/profiling/test_custom_profiling_blocked_thread_time.test
  test/sql/pragma/profiling/test_custom_profiling_disable_metrics.test
  test/sql/pragma/profiling/test_custom_profiling_errors.test
  test/sql/pragma/profiling/test_custom_profiling_optimizer.test
  test/sql/pragma/profiling/test_custom_profiling_planner.test_slow
  test/sql/pragma/profiling/test_custom_profiling_result_set_size.test
  test/sql/pragma/profiling/test_custom_profiling_rows_scanned.test
  test/sql/pragma/profiling/test_default_profiling_settings.test
  test/sql/pragma/profiling/test_empty_profiling_settings.test
  test/sql/pragma/test_custom_optimizer_profiling.test_slow
  test/sql/pragma/test_custom_profiling_settings.test
Labels: Needs Documentation, Ready For Review

#14185 Fix extension size increase
  .github/workflows/Regression.yml
  scripts/regression_test_extension_size.py
  src/include/duckdb.h
  src/include/duckdb/main/capi/header_generation/header_base.hpp.template
  src/include/duckdb/main/database.hpp
  src/main/database.cpp
  src/main/extension/extension_load.cpp
Labels: Ready To Merge

#14297 Add option to ignore GeoParquet, disable spatial autoloading when reading GeoParquet
  data/geoparquet/LICENSE
  data/geoparquet/data-linestring-encoding_native.parquet
  data/geoparquet/data-linestring-encoding_wkb.parquet
  data/geoparquet/data-linestring-wkt.csv
  data/geoparquet/data-multilinestring-encoding_native.parquet
  data/geoparquet/data-multilinestring-encoding_wkb.parquet
  data/geoparquet/data-multilinestring-wkt.csv
  data/geoparquet/data-multipoint-encoding_native.parquet
  data/geoparquet/data-multipoint-encoding_wkb.parquet
  data/geoparquet/data-multipoint-wkt.csv
  data/geoparquet/data-multipolygon-encoding_native.parquet
  data/geoparquet/data-multipolygon-encoding_wkb.parquet
  data/geoparquet/data-multipolygon-wkt.csv
  data/geoparquet/data-point-encoding_native.parquet
  data/geoparquet/data-point-encoding_wkb.parquet
  data/geoparquet/data-point-wkt.csv
  data/geoparquet/data-polygon-encoding_native.parquet
  data/geoparquet/data-polygon-encoding_wkb.parquet
  data/geoparquet/data-polygon-wkt.csv
  data/geoparquet/generate_test_data.py
  extension/parquet/column_writer.cpp
  extension/parquet/geo_parquet.cpp
  extension/parquet/include/geo_parquet.hpp
  extension/parquet/parquet_extension.cpp
  src/include/duckdb/main/extension_entries.hpp
  test/geoparquet/disabled.test
  test/geoparquet/mixed.test
  test/geoparquet/no_spatial.test
  test/geoparquet/roundtrip.test
  test/geoparquet/unsupported.test
Labels: Ready To Merge

#14316 Change Makefile to correctly handle DISABLE_SANITIZER and DISABLE_UBSAN
  Makefile
Labels: Ready To Merge

#14196 [Export/Import] Use the DependencyManager to (stable) sort the entries before export
  src/catalog/catalog.cpp
  src/catalog/catalog_entry/duck_schema_entry.cpp
  src/catalog/dependency_manager.cpp
  src/execution/operator/persistent/physical_export.cpp
  src/include/duckdb/catalog/catalog.hpp
  src/include/duckdb/catalog/catalog_entry/type_catalog_entry.hpp
  src/include/duckdb/catalog/dependency_manager.hpp
  src/include/duckdb/common/serializer/serialization_traits.hpp
  src/storage/checkpoint_manager.cpp
  test/fuzzer/pedro/concurrent_catalog_usage.test
  test/sql/attach/attach_export_import.test
  test/sql/attach/attach_index.test
  test/sql/constraints/foreignkey/test_fk_export.test
  test/sql/constraints/foreignkey/test_foreignkey.test
  test/sql/export/export_generated_columns.test
  test/sql/export/export_indexes.test
  test/sql/export/export_macros.test
  test/sql/storage/store_group_order_all.test
Labels: Ready To Merge

#14336 Avoid throwing InternalException on reading secret
  src/main/secret/secret_manager.cpp
Labels: Ready For Review

#14338 Internal #3251: DateDiff Across Epoch
  src/core_functions/scalar/date/date_diff.cpp
  test/sql/function/timestamp/test_date_diff_epoch.test
Labels: Ready For Review

#14350 Bump azure and delta extensions commits
  .github/config/out_of_tree_extensions.cmake
Labels: Ready For Review

#14351 Bump spatial to 3f94d52aa9f7d67b1a30e6cea642bbb790c04aa2
  .github/config/out_of_tree_extensions.cmake
Labels: Ready For Review

#14352 Bump more extensions: iceberg, vss and sqlite_scanner
  .github/config/out_of_tree_extensions.cmake
Labels: Ready For Review

#14063 Add df.unionByName to PySpark API
  tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
  tools/pythonpkg/tests/fast/spark/test_spark_union_by_name.py
Labels: Ready For Review

#14359 [Feature + Fix] Support ALTER TABLE tbl ALTER col TYPE USING and fix null handling in struct_insert
  extension/core_functions/scalar/struct/struct_insert.cpp
  src/catalog/catalog_entry/duck_table_entry.cpp
  src/parser/parsed_data/alter_table_info.cpp
  src/parser/transform/statement/transform_alter_table.cpp
  src/parser/transform/statement/transform_create_table.cpp
  test/sql/alter/alter_type/test_alter_type.test
  test/sql/function/nested/test_struct_insert.test
  third_party/libpg_query/grammar/statements/alter_table.y
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation

#14285 [C API] Add table_description_create_ext and table_description_get_column_name
  src/include/duckdb.h
  src/include/duckdb/main/capi/extension_api.hpp
  src/include/duckdb/main/capi/header_generation/apis/v0/dev/dev.json
  src/include/duckdb/main/capi/header_generation/functions/table_description.json
  src/include/duckdb_extension.h
  src/main/capi/table_description-c.cpp
  test/api/capi/test_capi_table_description.cpp
Labels: Ready For Review

#14367 Increase bounds for `test/sql/copy/file_size_bytes.test`
  test/sql/copy/file_size_bytes.test
Labels: Ready To Merge

#14368 Move _rtools platform to be equivalent to _mingw
  .github/config/distribution_matrix.json
  .github/workflows/R.yml
  src/include/duckdb/common/platform.hpp
Labels: Needs Documentation, Ready For Review

#14370 Use table-level locking when acquiring shared locks
  src/include/duckdb/transaction/duck_transaction.hpp
  src/transaction/duck_transaction.cpp
Labels: Ready To Merge

#14258 Update Parquet Thrift to latest version
  extension/parquet/CMakeLists.txt
  extension/parquet/column_reader.cpp
  extension/parquet/column_writer.cpp
  extension/parquet/geo_parquet.cpp
  extension/parquet/include/column_reader.hpp
  extension/parquet/include/column_writer.hpp
  extension/parquet/include/geo_parquet.hpp
  extension/parquet/include/parquet_decimal_utils.hpp
  extension/parquet/include/parquet_file_metadata_cache.hpp
  extension/parquet/include/parquet_reader.hpp
  extension/parquet/include/parquet_statistics.hpp
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/parquet_config.py
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_metadata.cpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_statistics.cpp
  extension/parquet/parquet_writer.cpp
  third_party/parquet/generate.sh
  third_party/parquet/parquet.thrift
  third_party/parquet/parquet_constants.cpp
  third_party/parquet/parquet_constants.h
  third_party/parquet/parquet_types.cpp
  third_party/parquet/parquet_types.h
Labels: Ready To Merge

#14394 Tidy Check to do complete run also on feature
  .github/workflows/CodeQuality.yml
Labels: Ready To Merge

#14395 [Arrow] Fix scanning of BOOL columns when offsets are involved
  src/function/table/arrow_conversion.cpp
  tools/pythonpkg/tests/fast/arrow/test_arrow_offsets.py
Labels: Ready To Merge

#12631 Improvement the speed of table sample systems
  src/common/enum_util.cpp
  src/common/enums/metric_type.cpp
  src/common/enums/optimizer_type.cpp
  src/execution/operator/scan/physical_table_scan.cpp
  src/function/table/table_scan.cpp
  src/function/table_function.cpp
  src/include/duckdb/common/enums/metric_type.hpp
  src/include/duckdb/common/enums/optimizer_type.hpp
  src/include/duckdb/common/extra_operator_info.hpp
  src/include/duckdb/execution/operator/scan/physical_table_scan.hpp
  src/include/duckdb/function/table_function.hpp
  src/include/duckdb/optimizer/sampling_pushdown.hpp
  src/include/duckdb/planner/operator/logical_get.hpp
  src/include/duckdb/storage/table/scan_state.hpp
  src/optimizer/CMakeLists.txt
  src/optimizer/optimizer.cpp
  src/optimizer/sampling_pushdown.cpp
  src/planner/operator/logical_get.cpp
  src/storage/table/row_group.cpp
  src/storage/table/scan_state.cpp
  test/optimizer/sampling_pushdown.test
  test/optimizer/sampling_pushdown.test_slow
Labels: Changes Requested

#14397 avoid unnecessary file list materialization when pruning readers
  src/include/duckdb/common/multi_file_reader.hpp
Labels: Ready To Merge

#14399 Fixing type pushdown on the CSV Scanner
  src/planner/binder/query_node/plan_setop.cpp
  test/sql/copy/csv/except.test
Labels: Ready To Merge

#14327 Support defining column names in CTAS
  src/catalog/catalog_entry/table_catalog_entry.cpp
  src/include/duckdb/catalog/catalog_entry/table_catalog_entry.hpp
  src/parser/parsed_data/create_table_info.cpp
  src/parser/transform/statement/transform_create_table_as.cpp
  src/planner/binder/statement/bind_create_table.cpp
  test/sql/create/create_as.test
Labels: Ready To Merge

#14403 Fix pointer indirection in pyrelation.cpp
  tools/pythonpkg/src/pyrelation.cpp
Labels: Ready For Review

#14402 Fix idx_t to int64_t implicit conversion flagged by clang-tidy
  extension/core_functions/scalar/list/array_slice.cpp
Labels: Ready To Merge

#14409 Issue #14398: Lead Shift Defaults
  src/execution/window_executor.cpp
  test/sql/window/test_lead_lag.test
Labels: Ready For Review

#14418 Escape should default to quoted
  data/csv/struct.csv
  src/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.cpp
  test/sql/copy/csv/struct.test
Labels: Ready To Merge

#14417 Sniff CSV rejects options and small sniffer fix for ignore_errors
  data/csv/ignore_errors.csv
  data/csv/quoted_values_delimited.csv
  data/csv/rejects_sniffer.csv
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/function/table/read_csv.cpp
  src/function/table/sniff_csv.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_reader_options.hpp
  test/sql/copy/csv/test_ignore_errors.test
  test/sql/copy/csv/test_read_csv.test
  test/sql/copy/csv/test_segfault.test
  test/sql/copy/csv/test_sniff_csv_options.test
Labels: Ready To Merge

#14437 Use corrent container to produce BinderErrors
  src/planner/expression_binder.cpp
Labels: Ready For Review

#14433 Try auto-casting for mismatching data chunks in the Appender API
  src/main/appender.cpp
  src/main/capi/appender-c.cpp
  test/api/capi/CMakeLists.txt
  test/api/capi/test_capi_append_data_chunk.cpp
  test/api/capi/test_capi_data_chunk.cpp
Labels: Ready For Review

#14257 Implement `DELTA_BINARY_PACKED` compression in Parquet writer
  extension/parquet/column_writer.cpp
  extension/parquet/include/decode_utils.hpp
  extension/parquet/include/parquet_crypto.hpp
  extension/parquet/include/parquet_dbp_decoder.hpp
  extension/parquet/include/parquet_dbp_encoder.hpp
  extension/parquet/include/parquet_extension.hpp
  extension/parquet/include/parquet_statistics.hpp
  extension/parquet/include/resizable_buffer.hpp
  extension/parquet/include/thrift_tools.hpp
  test/sql/copy/file_size_bytes.test
  test/sql/copy/parquet/parquet_5209.test
  third_party/snappy/snappy-stubs-internal.h
Labels: Ready For Review

#14375 Eviction Queue Partitioning
  extension/json/json_scan.cpp
  src/common/radix_partitioning.cpp
  src/common/types/column/column_data_allocator.cpp
  src/common/types/column/column_data_collection.cpp
  src/common/types/row/partitioned_tuple_data.cpp
  src/common/types/row/tuple_data_allocator.cpp
  src/common/types/row/tuple_data_collection.cpp
  src/execution/aggregate_hashtable.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/function/aggregate/distributive/first.cpp
  src/include/duckdb/common/file_buffer.hpp
  src/include/duckdb/common/radix_partitioning.hpp
  src/include/duckdb/common/types/column/column_data_allocator.hpp
  src/include/duckdb/common/types/column/column_data_collection.hpp
  src/include/duckdb/common/types/row/partitioned_tuple_data.hpp
  src/include/duckdb/common/types/row/tuple_data_allocator.hpp
  src/include/duckdb/common/types/row/tuple_data_collection.hpp
  src/include/duckdb/execution/aggregate_hashtable.hpp
  src/include/duckdb/storage/buffer/block_handle.hpp
  src/include/duckdb/storage/buffer/buffer_pool.hpp
  src/include/duckdb/storage/buffer_manager.hpp
  src/include/duckdb/storage/standard_buffer_manager.hpp
  src/storage/buffer/block_handle.cpp
  src/storage/buffer/block_manager.cpp
  src/storage/buffer/buffer_pool.cpp
  src/storage/standard_buffer_manager.cpp
  test/sql/aggregate/aggregates/first_memory_usage.test_slow
Labels: Ready For Review

#14175 Implement `map_extract_first`
  data/json/14167.json
  extension/core_functions/scalar/map/map_extract.cpp
  src/planner/binder/expression/bind_operator_expression.cpp
  test/extension/test_tags.test
  test/sql/aggregate/aggregates/histogram_test_all_types.test_slow
  test/sql/cast/string_to_map_cast.test_slow
  test/sql/copy/parquet/struct_column_reader_skip.test
  test/sql/function/list/list_grade_up.test_slow
  test/sql/function/list/list_sort.test
  test/sql/json/issues/issue14167.test
  test/sql/types/nested/map/map_from_entries/data_types.test
  test/sql/types/nested/map/test_map_subscript.test
  test/sql/types/nested/map/test_map_subscript_all_types.test_slow
  test/sql/types/nested/map/test_map_subscript_composite.test
  test/sql/types/nested/map/test_map_subscript_from_column.test
  test/sql/types/nested/map/test_map_subscript_vector_types.test
  test/sql/types/nested/map/test_map_subscript_where.test
  test/sql/types/nested/map/test_map_vector_types.test
  test/sql/types/nested/map/test_null_map_interaction.test
Labels: Needs Documentation, Ready For Review

#14477 acosh: Change example to avoid returning NaN
  src/core_functions/scalar/math/functions.json
  src/include/duckdb/core_functions/scalar/math_functions.hpp
Labels: Ready To Merge

#14347 [PySpark] Add withColumns, withColumnsRenamed, cos, acos, any_value, approx_count_distinct and various array functions
  tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
  tools/pythonpkg/duckdb/experimental/spark/sql/functions.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_array.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_numeric.py
  tools/pythonpkg/tests/fast/spark/test_spark_group_by.py
  tools/pythonpkg/tests/fast/spark/test_spark_with_columns.py
  tools/pythonpkg/tests/fast/spark/test_spark_with_columns_renamed.py
Labels: Ready For Review

#14450 Internal #3273: Shared Window Expressions
  extension/core_functions/aggregate/holistic/mad.cpp
  extension/core_functions/aggregate/holistic/mode.cpp
  extension/core_functions/aggregate/holistic/quantile.cpp
  extension/core_functions/include/core_functions/aggregate/quantile_sort_tree.hpp
  extension/core_functions/include/core_functions/aggregate/quantile_state.hpp
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/window_executor.cpp
  src/execution/window_segment_tree.cpp
  src/function/aggregate/distributive/count.cpp
  src/include/duckdb/execution/window_executor.hpp
  src/include/duckdb/execution/window_segment_tree.hpp
  src/include/duckdb/function/aggregate_function.hpp
  test/fuzzer/sqlsmith/window-leadlag-overflow.test
  test/sql/window/test_ignore_nulls.test
  test/sql/window/test_volatile_independence.test
Labels: Ready For Review

#14176 Avoid recompilations of duckdb when there are no actual changes
  CMakeLists.txt
  src/main/extension/CMakeLists.txt
Labels: Ready For Review, feature

#14272 Avoid throwing on failure to open extensions's .info file (when force installing)
  src/main/extension/extension_install.cpp
Labels: Ready For Review

#14509 Add `-safe` mode to shell which disables external access, and remove SQLite UDFs from the shell
  extension/autocomplete/autocomplete_extension.cpp
  tools/shell/shell.cpp
  tools/shell/tests/conftest.py
  tools/shell/tests/test_safe_mode.py
  tools/shell/tests/test_shell_basics.py
Labels: Needs Documentation

#14510 Python 3.7 tests are particularly brittle, we will keep building wheels but avoid testing them
  .github/workflows/Python.yml
Labels: Ready To Merge

#14454 [PySpark] Add functions covar_pop, covar_samp, call_functions, endswith, startswith, exp, factorial, log2, ln, degrees, radians, atan, atan2, tan, round, bround
  tools/pythonpkg/duckdb/experimental/spark/sql/functions.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_miscellaneous.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_numeric.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_string.py
  tools/pythonpkg/tests/fast/spark/test_spark_group_by.py
Labels: Merge Conflict

#14531 Remove most BUILD_ options for extensions, using CORE_EXTENSIONS
  .github/workflows/ExtendedTests.yml
  .github/workflows/ExtraTests.yml
  .github/workflows/Julia.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/Main.yml
  .github/workflows/NightlyTests.yml
  .github/workflows/Regression.yml
  .github/workflows/Windows.yml
  .github/workflows/coverity.yml
Labels: Ready For Review

#14527 CI: Mirror 'reproduced' / 'under review' to the internal repository
  .github/workflows/InternalIssuesCreateMirror.yml
Labels: Ready For Review

#14568 Manage `enable_external_access` at the FileSystem level, and add `allowed_paths` and `allowed_directories` option
  scripts/settings_scripts/config.py
  scripts/settings_scripts/update_settings_header_file.py
  src/common/CMakeLists.txt
  src/common/multi_file_reader.cpp
  src/common/opener_file_system.cpp
  src/common/settings.json
  src/execution/operator/helper/physical_set.cpp
  src/execution/physical_plan/plan_export.cpp
  src/function/built_in_functions.cpp
  src/function/pragma/pragma_queries.cpp
  src/function/table/sniff_csv.cpp
  src/function/table/system/duckdb_settings.cpp
  src/include/duckdb/common/opener_file_system.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/database_manager.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/database.cpp
  src/main/database_manager.cpp
  src/main/settings/custom_settings.cpp
  src/planner/binder/statement/bind_copy.cpp
  src/planner/binder/statement/bind_export.cpp
  src/storage/storage_manager.cpp
  test/api/test_reset.cpp
  test/sql/attach/attach_enable_external_access.test
  test/sql/attach/attach_external_access.test
  test/sql/copy/csv/csv_external_access.test
  test/sql/settings/allowed_directories.test
  test/sql/settings/allowed_paths.test
  test/sql/storage/storage_enable_external_access.test
  test/sql/storage/temp_directory/temp_directory_enable_external_access.test
Labels: Needs Documentation

#14507 feat(iejoin): use sort to replace binary search in iejoin
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/operator/join/physical_range_join.cpp
Labels: Ready To Merge

#14544 Internal #3273: Shared Window Frames
  src/execution/window_executor.cpp
  src/execution/window_segment_tree.cpp
  src/include/duckdb/execution/window_executor.hpp
Labels: Ready For Review

#12079 Expose threshold argument of Jaro-Winkler similarity
  extension/core_functions/function_list.cpp
  extension/core_functions/include/core_functions/scalar/string_functions.hpp
  extension/core_functions/scalar/string/functions.json
  extension/core_functions/scalar/string/jaro_winkler.cpp
  test/sql/function/string/test_jaro_winkler.test
Labels: Merge Conflict

#14588 Issue template: Add Swift redirect
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready To Merge

#13729 Implement `left_projection_map` for joins
  src/execution/join_hashtable.cpp
  src/execution/operator/join/perfect_hash_join_executor.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/physical_plan/plan_comparison_join.cpp
  src/execution/physical_plan/plan_filter.cpp
  src/execution/physical_plan/plan_order.cpp
  src/include/duckdb/execution/operator/join/perfect_hash_join_executor.hpp
  src/include/duckdb/execution/operator/join/physical_hash_join.hpp
  src/include/duckdb/execution/physical_plan_generator.hpp
  src/include/duckdb/optimizer/build_probe_side_optimizer.hpp
  src/include/duckdb/optimizer/column_lifetime_analyzer.hpp
  src/include/duckdb/optimizer/common_aggregate_optimizer.hpp
  src/include/duckdb/planner/logical_operator.hpp
  src/include/duckdb/planner/logical_operator_visitor.hpp
  src/include/duckdb/planner/operator/logical_comparison_join.hpp
  src/include/duckdb/planner/operator/logical_filter.hpp
  src/include/duckdb/planner/operator/logical_join.hpp
  src/include/duckdb/planner/operator/logical_order.hpp
  src/include/duckdb/storage/serialization/logical_operator.json
  src/optimizer/build_probe_side_optimizer.cpp
  src/optimizer/column_lifetime_analyzer.cpp
  src/optimizer/common_aggregate_optimizer.cpp
  src/optimizer/filter_pushdown.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/pullup/pullup_filter.cpp
  src/optimizer/pushdown/pushdown_filter.cpp
  src/optimizer/remove_unused_columns.cpp
  src/planner/logical_operator.cpp
  src/planner/logical_operator_visitor.cpp
  src/planner/operator/logical_comparison_join.cpp
  src/planner/operator/logical_order.cpp
  src/storage/serialization/serialize_logical_operator.cpp
  test/sql/join/external/tpch_all_tables.test_slow
Labels: Ready For Review

#14458 [PySpark] Add dataframe methods drop_duplicates, intersectAll, exceptAll, toArrow
  tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
  tools/pythonpkg/tests/fast/spark/test_spark_arrow_table.py
  tools/pythonpkg/tests/fast/spark/test_spark_drop_duplicates.py
  tools/pythonpkg/tests/fast/spark/test_spark_except.py
  tools/pythonpkg/tests/fast/spark/test_spark_intersect.py
Labels: Ready To Merge

#14446 [bufferpool] Fix PurgeAgedBlocksInternal() evictions
  src/storage/buffer/buffer_pool.cpp
Labels: CI Failure

#14608 CI: Fix and simplify 'needs reproducible example' labelling
  .github/workflows/InternalIssuesCreateMirror.yml
  .github/workflows/needs-reproducible-example-comment.md
Labels: Ready For Review

#14609 CI: Fix and simplify 'needs reproducible example' labelling
  .github/workflows/InternalIssuesCreateMirror.yml
Labels: Ready For Review

#14593 Test fixes for new arrow release
  tools/pythonpkg/tests/arrow_canonical_extensions.py
  tools/pythonpkg/tests/fast/arrow/test_canonical_extensions.py
  tools/pythonpkg/tests/fast/test_replacement_scan.py
  tools/pythonpkg/tests/fast/udf/test_null_filtering.py
  tools/pythonpkg/tests/fast/udf/test_scalar.py
Labels: CI Failure

#14611 CI: Fix labelling bot
  .github/workflows/InternalIssuesCreateMirror.yml
Labels: Ready For Review

#14599 Internal #3381: Window Race Condition
  src/execution/window_executor.cpp
Labels: Ready To Merge

#14391 Rework generated EnumUtil code
  scripts/generate_enum_util.py
  src/common/enum_util.cpp
  src/common/string_util.cpp
  src/include/duckdb/common/string_util.hpp
  test/sql/settings/setting_exhaustive.test
Labels: Ready To Merge

#14371 Storage info update
  src/storage/storage_info.cpp
  src/storage/version_map.json
Labels: Ready For Review

#14610 Fix #14542
  src/include/duckdb/optimizer/unnest_rewriter.hpp
  src/optimizer/unnest_rewriter.cpp
  test/optimizer/unnest_rewriter_issue_14542.test
Labels: Ready To Merge

#14511 add index plan callback to IndexType
  src/execution/index/art/CMakeLists.txt
  src/execution/index/art/plan_art.cpp
  src/execution/index/index_type_set.cpp
  src/execution/physical_plan/plan_create_index.cpp
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/index_type.hpp
Labels: Ready To Merge

#14634 FIX: Discrepancy Between Count and Sum Queries in SQL
  src/common/vector_operations/comparison_operators.cpp
  src/optimizer/pushdown/pushdown_left_join.cpp
  test/optimizer/misc/test_count_and_sum.test
  test/sql/types/struct/unnamed_struct_comparison.test
Labels: Ready To Merge

#14465 Temp directory compression
  CMakeLists.txt
  extension/parquet/CMakeLists.txt
  extension/parquet/column_writer.cpp
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/include/zstd_file_system.hpp
  extension/parquet/parquet_config.py
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_writer.cpp
  extension/parquet/zstd_file_system.cpp
  scripts/generate_enum_util.py
  scripts/package_build.py
  scripts/plan_cost_runner.py
  src/CMakeLists.txt
  src/common/enum_util.cpp
  src/include/duckdb/common/chrono.hpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/storage/temporary_file_manager.hpp
  src/storage/temporary_file_manager.cpp
  test/sql/copy/parquet/writer/parquet_write_compression_level.test
  test/sql/storage/temp_directory/max_swap_space_error.test
  test/sql/table_function/duckdb_memory.test
  third_party/CMakeLists.txt
  third_party/zstd/CMakeLists.txt
  third_party/zstd/common/xxhash.cpp
  third_party/zstd/decompress/zstd_ddict.cpp
  third_party/zstd/decompress/zstd_decompress.cpp
  third_party/zstd/include/zstd.h
  third_party/zstd/include/zstd/common/allocations.h
  third_party/zstd/include/zstd/common/debug.h
  third_party/zstd/include/zstd/common/fse.h
  third_party/zstd/include/zstd/common/zstd_deps.h
  third_party/zstd/include/zstd/deprecated/zbuff.h
  tools/pythonpkg/setup.py
Labels: Ready To Merge

#14650 Add support for SELECT * RENAME
  src/include/duckdb/parser/expression/star_expression.hpp
  src/include/duckdb/parser/qualified_name_set.hpp
  src/include/duckdb/storage/serialization/parsed_expression.json
  src/parser/expression/star_expression.cpp
  src/parser/transform/expression/transform_columnref.cpp
  src/planner/bind_context.cpp
  src/storage/serialization/serialize_parsed_expression.cpp
  test/sql/attach/attach_multi_identifiers.test
  test/sql/projection/select_star_rename.test
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/grammar/types/select.yh
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation

#14577 [PySpark] Add autocompletion for column names to dataframes
  tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
Labels: Ready For Review

#14654 Add serialization for bitstring_agg function
  src/core_functions/aggregate/distributive/bitstring_agg.cpp
  test/sql/window/test_empty_frames.test
Labels: Ready To Merge

#14374 Sampling respects seed from random number generator if no seed is given.
  src/common/enum_util.cpp
  src/execution/operator/helper/physical_reservoir_sample.cpp
  src/execution/physical_plan/plan_sample.cpp
  src/include/duckdb/parser/parsed_data/sample_options.hpp
  src/include/duckdb/parser/tokens.hpp
  src/include/duckdb/storage/serialization/nodes.json
  src/parser/parsed_data/sample_options.cpp
  src/parser/query_node/select_node.cpp
  src/parser/tableref.cpp
  src/parser/transform/helpers/transform_sample.cpp
  src/storage/serialization/serialize_nodes.cpp
  test/sql/function/numeric/set_seed_for_sample.test
Labels: Changes Requested
