Repository duckdb/duckdb, pull requests merged in 2024-04, with the labels that each got.

#11459 [CI] Skip ccache for R.yml
  .github/workflows/R.yml
Labels: Ready To Merge

#11176 [Block Size] Move the block allocation size into the block manager
  src/execution/operator/schema/physical_attach.cpp
  src/include/duckdb/main/attached_database.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/include/duckdb/parser/parsed_data/attach_info.hpp
  src/include/duckdb/storage/block_manager.hpp
  src/include/duckdb/storage/single_file_block_manager.hpp
  src/include/duckdb/storage/storage_info.hpp
  src/include/duckdb/storage/storage_manager.hpp
  src/main/attached_database.cpp
  src/main/client_data.cpp
  src/main/config.cpp
  src/main/database.cpp
  src/main/database_manager.cpp
  src/main/settings/settings.cpp
  src/parser/parsed_data/attach_info.cpp
  src/storage/buffer/block_manager.cpp
  src/storage/checkpoint_manager.cpp
  src/storage/single_file_block_manager.cpp
  src/storage/standard_buffer_manager.cpp
  src/storage/storage_info.cpp
  src/storage/storage_manager.cpp
  test/api/test_reset.cpp
  test/sql/attach/attach_custom_block_size.test
  test/sql/storage/compact_block_size/compact_block_size.test
  test/sql/storage/compact_block_size/default_block_size.test
Labels: Ready To Merge

#11402 Move BindCreateIndex from Catalog to Binder
  src/include/duckdb/catalog/catalog.hpp
  src/include/duckdb/planner/binder.hpp
  src/planner/binder/statement/bind_create.cpp
Labels: Changes Requested

#11458 Removing abort() from RE2 again because Google refuses to use exceptions
  third_party/re2/util/logging.h
  third_party/re2/util/mutex.h
Labels: Ready To Merge

#11378 Defer allocation in read_json
  data/json/11407.json
  extension/json/buffered_json_reader.cpp
  extension/json/include/buffered_json_reader.hpp
  extension/json/include/json_scan.hpp
  extension/json/json_scan.cpp
  test/sql/json/issues/read_json_memory_usage.test
  tools/shell/tests/test_read_from_stdin.py
Labels: Ready For Review

#11432 [ODBC] Add escape character to ParseStringFilter to support Power Query ('table_name' is escaped to 'table\_name')
  tools/odbc/src/common/odbc_utils.cpp
Labels: Ready To Merge

#11476 Bump to post-portfile change for duckdb_azure
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#11464 [Arrow] Throw on invalid STRUCT type
  src/function/table/arrow.cpp
  tools/pythonpkg/tests/fast/arrow/test_arrow_types.py
Labels: Ready To Merge

#11408 [Dev] Do not use CatalogEntry references inside Dependency objects.
  src/catalog/catalog.cpp
  src/catalog/catalog_entry.cpp
  src/catalog/catalog_entry/duck_schema_entry.cpp
  src/catalog/catalog_set.cpp
  src/catalog/dependency_catalog_set.cpp
  src/catalog/dependency_list.cpp
  src/catalog/dependency_manager.cpp
  src/catalog/duck_catalog.cpp
  src/execution/physical_plan_generator.cpp
  src/function/scalar/sequence/nextval.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/catalog/catalog.hpp
  src/include/duckdb/catalog/catalog_entry.hpp
  src/include/duckdb/catalog/catalog_entry/duck_schema_entry.hpp
  src/include/duckdb/catalog/catalog_set.hpp
  src/include/duckdb/catalog/dependency.hpp
  src/include/duckdb/catalog/dependency_list.hpp
  src/include/duckdb/catalog/dependency_manager.hpp
  src/include/duckdb/catalog/standard_entry.hpp
  src/include/duckdb/execution/physical_plan_generator.hpp
  src/include/duckdb/function/scalar_function.hpp
  src/include/duckdb/function/table_function.hpp
  src/include/duckdb/main/attached_database.hpp
  src/include/duckdb/parser/parsed_data/create_info.hpp
  src/include/duckdb/planner/parsed_data/bound_create_table_info.hpp
  src/main/attached_database.cpp
  src/main/database_manager.cpp
  src/main/secret/secret_storage.cpp
  src/planner/binder/statement/bind_create_table.cpp
Labels: Ready To Merge

#11486 Fix extension builds
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/postgres_scanner/rebind.patch
  .github/patches/extensions/sqlite_scanner/wrap_idx_t.patch
  .github/patches/extensions/substrait/substrait.patch
  src/include/duckdb/storage/table_storage_info.hpp
Labels: Ready To Merge

#11247 [Fix] Throw BinderException for UNNEST expressions in WINDOW expressions
  src/include/duckdb/planner/expression_binder/base_select_binder.hpp
  src/planner/binder/expression/bind_unnest_expression.cpp
  src/planner/binder/expression/bind_window_expression.cpp
  src/planner/expression_binder/base_select_binder.cpp
  src/planner/expression_binder/having_binder.cpp
  src/planner/expression_binder/qualify_binder.cpp
  test/fuzzer/duckfuzz/window_order_bind_failure.test
  test/sql/window/test_window_unnest_error.test
Labels: Changes Requested

#11401 Add serialization for `LogicalCopyDatabase` operator
  src/common/enum_util.cpp
  src/execution/operator/persistent/physical_copy_database.cpp
  src/include/duckdb/parser/parsed_data/copy_database_info.hpp
  src/include/duckdb/parser/parsed_data/parse_info.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/operator/logical_copy_database.hpp
  src/include/duckdb/storage/serialization/logical_operator.json
  src/include/duckdb/storage/serialization/parse_info.json
  src/planner/binder/statement/bind_copy_database.cpp
  src/planner/operator/logical_copy_database.cpp
  src/storage/serialization/serialize_logical_operator.cpp
  src/storage/serialization/serialize_parse_info.cpp
  test/sql/copy_database/copy_database_errors.test
  test/sql/copy_database/copy_database_fk.test
  test/sql/copy_database/copy_database_simple.test
Labels: Changes Requested

#11446 [Fix][ADBC] Implement required ADBCConnectionGetObjects schema
  src/common/adbc/adbc.cpp
  test/api/adbc/test_adbc.cpp
  tools/pythonpkg/tests/fast/adbc/test_adbc.py
Labels: Ready For Review

#11513 [RE2] Add includes and remove potential throw from destructor
  third_party/re2/util/logging.h
  third_party/re2/util/mutex.h
Labels: Ready For Review

#11496 Issue #11292: Nested Boolean Compares
  src/common/row_operations/row_matcher.cpp
  src/common/vector_operations/comparison_operators.cpp
  src/common/vector_operations/is_distinct_from.cpp
  src/execution/expression_executor/execute_comparison.cpp
  src/execution/nested_loop_join/nested_loop_join_mark.cpp
  src/include/duckdb/common/vector_operations/vector_operations.hpp
  test/sql/aggregate/aggregates/test_list_aggregate_function.test_slow
  test/sql/function/list/list_reverse.test
  test/sql/types/list/list_null_members.test
  test/sql/types/nested/array/array_storage.test
  test/sql/types/nested/map/test_map_subscript_vector_types.test
  test/sql/types/struct/struct_null_members.test
Labels: Needs Documentation, Ready For Review

#11530 Move assertion in `json_scan.cpp`
  extension/json/json_scan.cpp
Labels: Ready For Review

#11519 Issue #11518: TryParseTime
  src/function/scalar/strftime_format.cpp
  src/include/duckdb/function/scalar/strftime_format.hpp
Labels: Ready For Review

#11556 [CI] Move from default GITHUB_TOKEN to specific one
  .github/workflows/DraftPR.yml
Labels: Ready For Review

#11553 [CI] Fix Deploy step to execute only for duckdb organization
  scripts/upload-assets-to-staging.sh
Labels: Ready For Review

#11473 BUGFIX: IN () filter with one argument should translate to = filter.
  .github/regression/micro_extended.csv
  benchmark/micro/filter/in_conversion.benchmark
  src/optimizer/filter_combiner.cpp
  test/optimizer/pushdown/pushdown_in_to_parquet.test
  test/sql/copy/parquet/writer/parquet_test_all_types.test
Labels: Ready For Review

#11558 Rework `vector_hash` for ARRAYs
  src/common/vector_operations/vector_hash.cpp
  test/sql/types/nested/array/array_fuzzer_failures.test
  test/sql/types/nested/array/array_joins_2.test
Labels: Ready For Review

#11267 [Dev] Add assertions around Uncompressed String storage
  src/include/duckdb/storage/string_uncompressed.hpp
Labels: Ready To Merge

#10382 python: Add missing global options to write_csv
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/src/pyrelation/initialize.cpp
  tools/pythonpkg/tests/fast/api/test_to_csv.py
Labels: Ready For Review

#11382 ODBC driver should ignore "driver" and "trusted_connection" keywords in connection string
  tools/odbc/include/connect.hpp
  tools/odbc/src/connect/connect.cpp
  tools/odbc/test/common.cpp
  tools/odbc/test/tests/connect.cpp
Labels: Ready To Merge

#11423 [ODBC] Fix: Support loading UTF-8 encoded data with Power BI
  tools/odbc/src/connect/connection.cpp
  tools/odbc/src/statement/statement.cpp
  tools/odbc/test/common.cpp
Labels: Ready To Merge

#11576 CI: Remove 'needs reproducible example' when 'reproduced' label is applied
  .github/workflows/InternalIssuesCreateMirror.yml
Labels: Ready For Review

#11577 Update issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready For Review

#11593 [CI] Remove GITHUB_PAT variable from R-CMD-check
  .github/workflows/R_CMD_CHECK.yml
Labels: Ready To Merge

#11595 Bump-back duckdb_azure to pre-lzma custom vcpkg-port
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#11551 initializes unknown indexes on catalog lookup
  src/catalog/catalog_entry/duck_schema_entry.cpp
  src/function/table/table_scan.cpp
  src/storage/data_table.cpp
  src/storage/local_storage.cpp
Labels: Ready For Review

#11273 Fix Progress Bar for many large CSV Files + Adjustment to not store buffers from compressed files over single threaded scans
  src/execution/operator/csv_scanner/buffer_manager/csv_buffer.cpp
  src/execution/operator/csv_scanner/buffer_manager/csv_buffer_manager.cpp
  src/execution/operator/csv_scanner/buffer_manager/csv_file_handle.cpp
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/function/table/read_csv.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_buffer.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_buffer_manager.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_handle.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/global_csv_state.hpp
  test/sql/copy/csv/test_big_compressed.test_slow
  test/sql/copy/csv/test_multiple_big_compressed_csvs.test_slow
Labels: Ready For Review

#11601 Fix topn placement
  src/optimizer/optimizer.cpp
  test/optimizer/topn/complex_top_n.test
  test/optimizer/topn/topn_optimizer.test
Labels: Ready To Merge

#11531 Add pyodide wheel building github action
  .github/workflows/Pyodide.yml
  .gitignore
  tools/pythonpkg/pyodide.md
  tools/pythonpkg/setup.py
  tools/pythonpkg/src/native/python_objects.cpp
Labels: Ready To Merge

#11619 Move away from dynamic_cast to Cast<> infrastructure
  src/include/duckdb/catalog/catalog.hpp
  src/include/duckdb/catalog/catalog_entry.hpp
  src/include/duckdb/common/allocator.hpp
  src/include/duckdb/common/extra_type_info.hpp
  src/include/duckdb/common/helper.hpp
  src/include/duckdb/common/types/column/partitioned_column_data.hpp
  src/include/duckdb/common/types/row/partitioned_tuple_data.hpp
  src/include/duckdb/common/types/vector_buffer.hpp
  src/include/duckdb/execution/expression_executor_state.hpp
  src/include/duckdb/execution/physical_operator_states.hpp
  src/include/duckdb/execution/window_executor.hpp
  src/include/duckdb/execution/window_segment_tree.hpp
  src/include/duckdb/function/cast/default_casts.hpp
  src/include/duckdb/function/compression_function.hpp
  src/include/duckdb/function/copy_function.hpp
  src/include/duckdb/function/function.hpp
  src/include/duckdb/function/scalar_function.hpp
  src/include/duckdb/function/table_function.hpp
  src/include/duckdb/main/relation.hpp
  src/include/duckdb/parallel/event.hpp
  src/include/duckdb/parser/parsed_data/extra_drop_info.hpp
  src/include/duckdb/parser/parsed_data/parse_info.hpp
  src/include/duckdb/storage/data_pointer.hpp
  src/include/duckdb/storage/index.hpp
  src/include/duckdb/storage/storage_manager.hpp
  src/include/duckdb/storage/table/column_checkpoint_state.hpp
  src/include/duckdb/storage/table/scan_state.hpp
  src/include/duckdb/transaction/transaction.hpp
  src/planner/operator/logical_delete.cpp
  src/planner/operator/logical_insert.cpp
  src/planner/operator/logical_update.cpp
Labels: Ready For Review

#11515 Extension Metadata
  CMakeLists.txt
  extension/fts/fts_extension.cpp
  extension/icu/icu_extension.cpp
  extension/tpcds/tpcds_extension.cpp
  extension/tpch/tpch_extension.cpp
  scripts/append_metadata.cmake
  scripts/create_local_extension_repo.py
  scripts/extension-upload-single.sh
  scripts/null.txt
  src/function/table/system/duckdb_extensions.cpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/database.hpp
  src/include/duckdb/main/extension_helper.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/database.cpp
  src/main/extension/extension_load.cpp
  src/main/settings/settings.cpp
  test/api/test_reset.cpp
  test/extension/CMakeLists.txt
  test/extension/load_extension.test
  test/sql/extensions/checked_load.test
  tools/utils/test_platform.cpp
Labels: Needs Documentation, Ready To Merge

#11626 Upload pyodide
  .github/workflows/Pyodide.yml
  tools/pythonpkg/setup.py
Labels: Ready To Merge

#11490 Add docker alpine build to check on builds
  scripts/test_docker_images.sh
Labels: Ready To Merge

#11614 Add Vector Similarity Search (VSS) Extension
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/vss/vss_depenency.patch
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#11629 Metadata fix
  CMakeLists.txt
Labels: Ready To Merge

#11635 Make path to append_metadata.cmake relative to top-level CMakeLists.txt
  CMakeLists.txt
Labels: Ready To Merge

#11650 Bump spatial
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/spatial/open_file.patch
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#11652 Avoid performing Apple codesign on extensions
  .github/workflows/OSX.yml
Labels: Ready To Merge

#11465 Fix `last_value` in the `duckdb_sequences` metadata function
  src/catalog/catalog_entry/sequence_catalog_entry.cpp
  src/function/table/system/duckdb_sequences.cpp
  test/sql/catalog/sequence/test_duckdb_sequences.test
Labels: Ready For Review

#11656 [Vacuum] Fix serialization and Copy of the VacuumStatement
  src/execution/operator/helper/physical_vacuum.cpp
  src/execution/physical_plan/CMakeLists.txt
  src/execution/physical_plan/plan_simple.cpp
  src/execution/physical_plan/plan_vacuum.cpp
  src/execution/physical_plan_generator.cpp
  src/include/duckdb/execution/operator/helper/physical_vacuum.hpp
  src/include/duckdb/execution/physical_plan_generator.hpp
  src/include/duckdb/parser/parsed_data/vacuum_info.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/logical_tokens.hpp
  src/include/duckdb/planner/operator/list.hpp
  src/include/duckdb/planner/operator/logical_vacuum.hpp
  src/include/duckdb/storage/serialization/logical_operator.json
  src/include/duckdb/storage/serialization/parse_info.json
  src/parser/parsed_data/vacuum_info.cpp
  src/planner/binder/statement/bind_vacuum.cpp
  src/planner/operator/CMakeLists.txt
  src/planner/operator/logical_vacuum.cpp
  src/storage/serialization/serialize_logical_operator.cpp
  src/storage/serialization/serialize_parse_info.cpp
  test/fuzzer/pedro/vacuum_unsupported_type.test
  test/sql/explain/explain_all_statements.test
  test/sql/vacuum/test_analyze.test
Labels: Ready For Review

#11662 Bump extension versions, remove patches
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/azure/open_file.patch
  .github/patches/extensions/iceberg/open_file.patch
  .github/patches/extensions/vss/vss_depenency.patch
Labels: Ready To Merge

#10978 Add setting to control the maximum swap space
  src/common/file_system.cpp
  src/include/duckdb/common/file_system.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/database.hpp
  src/include/duckdb/main/settings.hpp
  src/include/duckdb/storage/buffer_manager.hpp
  src/include/duckdb/storage/standard_buffer_manager.hpp
  src/include/duckdb/storage/temporary_file_manager.hpp
  src/main/config.cpp
  src/main/database.cpp
  src/main/settings/settings.cpp
  src/storage/buffer_manager.cpp
  src/storage/standard_buffer_manager.cpp
  src/storage/temporary_file_manager.cpp
  test/api/test_api.cpp
  test/api/test_reset.cpp
  test/sql/storage/temp_directory/max_swap_space_error.test
  test/sql/storage/temp_directory/max_swap_space_explicit.test
  test/sql/storage/temp_directory/max_swap_space_inmemory.test
  test/sql/storage/temp_directory/max_swap_space_persistent.test
  test/sql/storage/temp_directory/max_swap_space_unlimited.test
  test/sql/storage/test_buffer_manager.cpp
Labels: Ready For Review

#11202 [Python][Dev] Dynamically generate the Connection wrapper methods
  Makefile
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb/__init__.py
  tools/pythonpkg/duckdb_python.cpp
  tools/pythonpkg/scripts/connection_methods.json
  tools/pythonpkg/scripts/connection_wrapper_methods.json
  tools/pythonpkg/scripts/generate_connection_code.py
  tools/pythonpkg/scripts/generate_connection_methods.py
  tools/pythonpkg/scripts/generate_connection_stubs.py
  tools/pythonpkg/scripts/generate_connection_wrapper_methods.py
  tools/pythonpkg/scripts/generate_connection_wrapper_stubs.py
  tools/pythonpkg/src/include/duckdb_python/connection_wrapper.hpp
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/src/pyconnection/type_creation.cpp
  tools/pythonpkg/src/pyduckdb/connection_wrapper.cpp
  tools/pythonpkg/tests/fast/api/test_duckdb_connection.py
  tools/pythonpkg/tests/fast/test_non_default_conn.py
Labels: Ready For Review

#11713 Properly avoid build-time dependency on Python
  CMakeLists.txt
Labels: Ready To Merge

#11708 Test dockerized compilation in Alpine:latest and Ubuntu:20.04
  .github/workflows/DockerTests.yml
  CMakeLists.txt
  scripts/test_docker_images.sh
  src/common/local_file_system.cpp
Labels: Ready For Review

#11725 More docker tests, fix compilation up to C++23 standard
  CMakeLists.txt
  Makefile
  scripts/test_docker_images.sh
  src/include/duckdb/common/shared_ptr.hpp
  src/include/duckdb/parser/base_expression.hpp
  third_party/mbedtls/library/constant_time.cpp
Labels: Ready To Merge

#11715 Upload staging: from 'git describe --tags' to 'git log -1'
  .github/workflows/OnTag.yml
  .github/workflows/Python.yml
  .github/workflows/StagedUpload.yml
  .github/workflows/TwineUpload.yml
  scripts/upload-assets-to-staging.sh
Labels: Ready To Merge

#11702 Internal #1848: Window Progress
  src/execution/operator/aggregate/physical_window.cpp
  src/include/duckdb/execution/operator/aggregate/physical_window.hpp
Labels: Ready To Merge

#11730 [Map] Rework `MAP` creation method behavior when input is NULL
  src/common/enum_util.cpp
  src/common/types/vector.cpp
  src/core_functions/scalar/map/map.cpp
  src/function/table/arrow_conversion.cpp
  src/include/duckdb/common/types/vector.hpp
  test/sql/types/map/map_null.test
  test/sql/types/nested/map/map_error.test
  test/sql/types/nested/map/test_map_subscript.test
  tools/pythonpkg/src/native/python_conversion.cpp
  tools/pythonpkg/src/numpy/numpy_scan.cpp
  tools/pythonpkg/src/pandas/analyzer.cpp
  tools/pythonpkg/tests/fast/arrow/test_nested_arrow.py
  tools/pythonpkg/tests/fast/pandas/test_df_object_resolution.py
Labels: Ready For Review

#11717 Getting Rid of Value.TryCast in the CSV Sniffer
  .github/regression/csv.csv
  .github/regression/micro_extended.csv
  benchmark/micro/csv/multiple_small_files.benchmark
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/header_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_sniffer.hpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
Labels: Ready To Merge

#11759 Add missing space in error message
  src/catalog/catalog_entry/duck_schema_entry.cpp
Labels: Ready To Merge

#11596 No Mark to Semi join conversion in statistics propagation
  src/include/duckdb/optimizer/filter_pushdown.hpp
  src/optimizer/filter_pushdown.cpp
  src/optimizer/pushdown/pushdown_aggregate.cpp
  src/optimizer/pushdown/pushdown_cross_product.cpp
  src/optimizer/pushdown/pushdown_left_join.cpp
  src/optimizer/pushdown/pushdown_mark_join.cpp
  src/optimizer/pushdown/pushdown_projection.cpp
  src/optimizer/pushdown/pushdown_semi_anti_join.cpp
  src/optimizer/pushdown/pushdown_set_operation.cpp
  src/optimizer/pushdown/pushdown_single_join.cpp
  src/optimizer/statistics/operator/propagate_join.cpp
  test/optimizer/pushdown/pushdown_after_statistics.test
Labels: Ready For Review

#10932 Pushdown filters on window partitions
  .github/regression/micro_extended.csv
  benchmark/micro/pushdown/window_partition_pushdown.benchmark
  src/include/duckdb/optimizer/filter_pushdown.hpp
  src/optimizer/filter_pushdown.cpp
  src/optimizer/pushdown/CMakeLists.txt
  src/optimizer/pushdown/pushdown_aggregate.cpp
  src/optimizer/pushdown/pushdown_window.cpp
  test/optimizer/pushdown/pushdown_window_partition_filter.test
Labels: Ready For Review

#11763 Only store CSV Errors if we are doing rejects table, otherwise just ignore it.
  .github/regression/csv.csv
  .github/regression/micro_extended.csv
  benchmark/micro/csv/ignore_errors.benchmark
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_reader_options.hpp
Labels: Ready For Review

#11625 [StatementVerifier] Fix up issues in ToString implementations of classes derived from SQLStatement
  src/catalog/catalog_entry/index_catalog_entry.cpp
  src/catalog/catalog_entry/table_catalog_entry.cpp
  src/catalog/catalog_entry/view_catalog_entry.cpp
  src/common/types.cpp
  src/execution/operator/persistent/physical_export.cpp
  src/function/table/system/duckdb_tables.cpp
  src/include/duckdb/parser/parsed_data/create_info.hpp
  src/include/duckdb/parser/parsed_data/create_schema_info.hpp
  src/include/duckdb/parser/parsed_data/create_sequence_info.hpp
  src/include/duckdb/parser/parsed_data/create_view_info.hpp
  src/include/duckdb/parser/parsed_data/parse_info.hpp
  src/include/duckdb/parser/sql_statement.hpp
  src/include/duckdb/parser/statement/copy_statement.hpp
  src/include/duckdb/parser/statement/insert_statement.hpp
  src/include/duckdb/parser/statement/select_statement.hpp
  src/main/client_context.cpp
  src/parser/constraints/foreign_key_constraint.cpp
  src/parser/expression/star_expression.cpp
  src/parser/parsed_data/CMakeLists.txt
  src/parser/parsed_data/create_index_info.cpp
  src/parser/parsed_data/create_schema_info.cpp
  src/parser/parsed_data/create_sequence_info.cpp
  src/parser/parsed_data/create_table_info.cpp
  src/parser/parsed_data/create_type_info.cpp
  src/parser/parsed_data/create_view_info.cpp
  src/parser/parsed_data/parse_info.cpp
  src/parser/statement/copy_statement.cpp
  test/sql/binder/test_null_type_propagation.test
  test/sql/generated_columns/virtual/group_by.test
  test/sql/table_function/sqlite_master.test
  test/sql/types/test_null_type.test
  test/sql/types/union/struct_to_union.test
  tools/pythonpkg/tests/fast/test_type.py
Labels: Ready For Review

#11787 Hive partitioning: make OVERWRITE_OR_IGNORE remove files on local file systems
  src/execution/operator/persistent/physical_copy_to_file.cpp
  test/sql/copy/format_uuid.test
  test/sql/copy/parquet/parquet_hive_null.test
  test/sql/copy/partitioned/hive_partitioning_overwrite.test
  test/sql/copy/s3/README.md
Labels: Needs Documentation

#11791 Add a configurable compression_level parameter to the parquet writer
  extension/parquet/column_writer.cpp
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_writer.cpp
  test/sql/copy/parquet/writer/parquet_write_compression_level.test
Labels: Needs Documentation

#11818 Python CI fixes: skip two tests
  tools/pythonpkg/tests/fast/api/test_to_csv.py
  tools/pythonpkg/tests/fast/test_pytorch.py
Labels: Ready For Review

#11829 Fixing performance regression in [u]hugeint cast
  src/common/operator/cast_operators.cpp
Labels: Ready To Merge

#11529 [Benchmark] Enable benchmarking result collection
  .github/regression/micro_extended.csv
  benchmark/include/interpreted_benchmark.hpp
  benchmark/interpreted_benchmark.cpp
  benchmark/micro/result_collection/batched_stream_query.benchmark
Labels: Ready For Review

#11524 [DependencyManager] Create dependencies between foreign key tables and primary key tables.
  src/catalog/catalog_entry/duck_schema_entry.cpp
  src/catalog/catalog_set.cpp
  src/catalog/dependency_manager.cpp
  src/include/duckdb/catalog/dependency_manager.hpp
  test/sql/constraints/foreignkey/test_fk_alter.test
  test/sql/constraints/foreignkey/test_fk_multiple.test
Labels: Ready For Review

#11861 Internal #1888 TIMETZ Collation Keys
  src/core_functions/function_list.cpp
  src/core_functions/scalar/date/epoch.cpp
  src/core_functions/scalar/date/functions.json
  src/include/duckdb/common/types/datetime.hpp
  src/include/duckdb/core_functions/scalar/date_functions.hpp
  test/sql/types/time/test_time_tz_collate.test
Labels: Ready For Review

#11797 Use `ToSQLString()` in `ConstantFilter` for escaped filter output
  src/planner/filter/constant_filter.cpp
  test/sql/filter/test_struct_pushdown.test
  tools/pythonpkg/tests/fast/arrow/test_filter_pushdown.py
Labels: CI Failure

#11792 Pushdown Tables Types to CSV Scanner
  data/csv/file_error.csv
  data/csv/glob/f_1.csv
  data/csv/glob/f_2.csv
  data/csv/glob/f_3.csv
  data/csv/timestamp.csv
  data/csv/union-by-name/type_mismatch/f_1.csv
  data/csv/union-by-name/type_mismatch/f_2.csv
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/function/table/read_csv.cpp
  src/function/table_function.cpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  src/include/duckdb/function/table_function.hpp
  src/planner/binder/query_node/plan_setop.cpp
  test/sql/copy/csv/test_csv_error_message_type.test
  test/sql/copy/csv/test_insert_into_types.test
  test/sql/copy/csv/test_mixed_line_endings.test
  test/sql/copy/csv/test_mixed_lines.test_slow
Labels: Ready For Review

#11794 Join order optimizer asan bug Follow up
  .github/config/uncovered_files.csv
  src/common/symbols.cpp
  src/include/duckdb/execution/adaptive_filter.hpp
  src/include/duckdb/optimizer/join_order/estimated_properties.hpp
  src/include/duckdb/optimizer/join_order/join_node.hpp
  src/include/duckdb/optimizer/join_order/join_order_optimizer.hpp
  src/include/duckdb/optimizer/join_order/plan_enumerator.hpp
  src/include/duckdb/optimizer/join_order/query_graph_manager.hpp
  src/include/duckdb/planner/logical_operator.hpp
  src/optimizer/join_order/CMakeLists.txt
  src/optimizer/join_order/estimated_properties.cpp
  src/optimizer/join_order/join_node.cpp
  src/optimizer/join_order/join_order_optimizer.cpp
  src/optimizer/join_order/plan_enumerator.cpp
  src/optimizer/join_order/query_graph_manager.cpp
  test/optimizer/joins/update_nodes_in_full_path.test_slow
  test/optimizer/joins/updating_the_join_node_hash_map_has_no_errors.test_slow
Labels: Ready For Review

#11812 BugFix: Introducing Introducing Delim Joins and Delim_Get(s) should respect positionally
  src/planner/binder/query_node/plan_subquery.cpp
  src/planner/subquery/flatten_dependent_join.cpp
  test/sql/subquery/exists/test_exists_union_by_name.test
Labels: Ready For Review

#11746 Provide the native OID of PG type in pg_type
  src/catalog/default/default_functions.cpp
  src/catalog/default/default_views.cpp
  test/sql/pg_catalog/pg_type.test
  test/sql/pg_catalog/sqlalchemy.test
Labels: Changes Requested

#11290 Add TopN optimization in physical plan mapping
  .github/regression/micro_extended.csv
  benchmark/micro/optimizer/topn_optimization.benchmark
  src/optimizer/topn_optimizer.cpp
  test/optimizer/topn/topn_optimizer.test
Labels: Ready For Review

#11882 fix complex top n test case for constant vector verification
  test/optimizer/topn/complex_top_n.test
Labels: Ready For Review
