Repository duckdb/duckdb, pull requests merged in 2024-03, with the labels that each got.

#10931 Set duckdb_api to 'python jupyter' if in Jupyter notebook
  tools/pythonpkg/src/pyconnection.cpp
Labels: Ready To Merge

#10957 Internal #1428: Interval Subtract Overflow
  src/function/scalar/operators/subtract.cpp
  test/fuzzer/sqlsmith/interval_diff_overflow.test
Labels: Ready For Review

#10958 Fuzzer #1445: Trap MAKE_DATE/TIME Overflows
  src/core_functions/scalar/date/make_date.cpp
  test/fuzzer/sqlsmith/makedate_overflow.test
Labels: Ready For Review

#10970 Python.yml: Revert to macos-latest for OSX workflow
  .github/workflows/Python.yml
Labels: Ready To Merge

#10594 Purge queue refactor
  src/include/duckdb/storage/buffer/buffer_pool.hpp
  src/storage/buffer/block_handle.cpp
  src/storage/buffer/block_manager.cpp
  src/storage/buffer/buffer_pool.cpp
  src/storage/standard_buffer_manager.cpp
  test/sql/storage/test_purge_queue.test
Labels: Ready For Review

#10974 Add require block_sizes 262144 on tests reading db files
  test/sql/storage/bc/test_view_v092.test
  test/sql/storage/compression/chimp/chimp_read.test
  test/sql/storage/compression/patas/patas_read.test
Labels: Ready To Merge

#10971 [duckdb-fuzzer/#1368] - overflow in bitstring_agg on hugeint & uhugei…
  src/core_functions/aggregate/distributive/bitstring_agg.cpp
  test/fuzzer/duckfuzz/bitstring_agg_minmax.test
  test/fuzzer/duckfuzz/bitstring_agg_uhugeint.test
Labels: Ready For Review

#10973 Fix LIST->ARRAY TRY_CAST when list sizes mismatch
  src/function/cast/list_casts.cpp
  test/sql/types/nested/array/array_cast.test
Labels: Ready To Merge

#10943 Add a micro extended benchmark.
  .github/regression/micro_extended.csv
Labels: Ready For Review

#10938 [Dev] Move `TemporaryFileManager` and friends out of StandardBufferManager
  src/include/duckdb/storage/standard_buffer_manager.hpp
  src/include/duckdb/storage/temporary_file_manager.hpp
  src/storage/CMakeLists.txt
  src/storage/standard_buffer_manager.cpp
  src/storage/temporary_file_manager.cpp
Labels: Ready For Review

#10985 Internal #1385: Window Partition Collation
  src/planner/binder/expression/bind_window_expression.cpp
  test/sql/window/test_window_order_collate.test
Labels: Ready For Review

#10987 Fuzzer #1471: Trap MAKE_DATE Overflows
  src/core_functions/scalar/date/make_date.cpp
  test/fuzzer/sqlsmith/makedate_overflow.test
Labels: Ready For Review

#10948 Autoload INET and ICU (and add back sqlite and postgres as autoloadable)
  .github/workflows/LinuxRelease.yml
  scripts/generate_extensions_function.py
  src/include/duckdb/main/extension_entries.hpp
  test/api/test_results.cpp
  test/arrow/arrow_roundtrip.cpp
  test/extension/autoloading_filesystems.test
  test/extension/wrong_function_type.test
  test/sql/copy/csv/timestamp_with_tz.test
  test/sql/function/generic/test_between_sideeffects.test
  test/sql/inet/test_inet_storage.test
Labels: Ready To Merge

#10990 Fuzzer #1468: Window RANGE Types
  src/planner/binder/expression/bind_window_expression.cpp
  test/fuzzer/sqlsmith/window_scalar_range.test
Labels: Ready For Review

#10983 Fuzzer #1446: Quantile Hugeint Interpolation
  src/core_functions/aggregate/holistic/quantile.cpp
  test/fuzzer/sqlsmith/mad_overflow.test
Labels: Ready For Review

#10994 Various fixes: CMake + generated extension_entries.hpp checks
  .github/workflows/LinuxRelease.yml
  CMakeLists.txt
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready For Review

#10997 Add correct table bindings for window relations.
  src/optimizer/join_order/relation_manager.cpp
  test/optimizer/joins/joins_with_correlated_subqueries.test
Labels: Ready For Review

#11008 Fix warnings in ALP and logical_insert
  src/include/duckdb/planner/operator/logical_insert.hpp
  src/include/duckdb/storage/compression/alprd/algorithm/alprd.hpp
Labels: Ready To Merge

#11007 Check IsLoaded() before importing cached item
  scripts/regression_test_python.py
  tools/pythonpkg/src/python_import_cache.cpp
Labels: Ready For Review

#11002 Issue #10995: ICU VARCHAR TIMETZ
  extension/icu/icu-strptime.cpp
  src/common/operator/cast_operators.cpp
  src/common/types/time.cpp
  src/include/duckdb/common/types/time.hpp
  test/sql/function/timetz/test_icu_cast.test
Labels: Ready For Review

#11024 Issue #10995: TIMETZ DST Fix
  test/sql/function/timetz/test_icu_cast.test
Labels: Ready For Review

#11022 Fixup LinuxRelease.yml release: unittester was not invoked correctly
  .github/workflows/LinuxRelease.yml
Labels: Ready For Review

#11036 [Block Size Nightly] Enable more block size nightly tests
  test/sql/storage/optimistic_write/optimistic_write_cyclic_dictionary.test_slow
  test/sql/storage/optimistic_write/optimistic_write_cyclic_scan.test_slow
  test/sql/storage/parallel/memory_limit_batch_load_list.test_slow
Labels: Ready For Review

#11043 Add missing pipeline dependencies in recursive CTE
  src/execution/operator/set/physical_recursive_cte.cpp
Labels: Ready For Review

#11031 feat(jdbc): expose comments via jdbc methods
  src/catalog/default/default_views.cpp
  tools/jdbc/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java
  tools/jdbc/src/main/java/org/duckdb/DuckDBResultSetMetaData.java
  tools/jdbc/src/test/java/org/duckdb/TestDuckDBJDBC.java
Labels: Ready For Review

#11038 [ODBC] Allow multiple statements to be executed using SQLExecDirect
  tools/odbc/include/statement_functions.hpp
  tools/odbc/src/statement/statement.cpp
  tools/odbc/src/statement/statement_functions.cpp
  tools/odbc/test/tests/data_execution.cpp
Labels: Ready To Merge

#10831 [CI] Add patch argument to patch the extension's sources before building
  .github/workflows/_extension_distribution.yml
Labels: Merge Conflict

#10707 fix(jdbc): support fractional seconds in getTime
  .gitignore
  tools/jdbc/src/jni/duckdb_java.cpp
  tools/jdbc/src/main/java/org/duckdb/DuckDBVector.java
  tools/jdbc/src/test/java/org/duckdb/TestDuckDBJDBC.java
Labels: Ready For Review

#11073 Add ipv6 inet + minor fixes
  extension/inet/include/inet_functions.hpp
  extension/inet/include/ipaddress.hpp
  extension/inet/inet_extension.cpp
  extension/inet/inet_functions.cpp
  extension/inet/ipaddress.cpp
  src/include/duckdb/main/extension_entries.hpp
  test/sql/inet/test_inet_functions.test
  test/sql/inet/test_inet_table.test
  test/sql/inet/test_inet_type.test
  test/sql/inet/test_ipv6_inet_functions.test
  test/sql/inet/test_ipv6_inet_nested.test
  test/sql/inet/test_ipv6_inet_operations.test
  test/sql/inet/test_ipv6_inet_storage.test
  test/sql/inet/test_ipv6_inet_type.test
  test/sql/timezone/test_icu_timezone.test
Labels: Ready To Merge

#10664 [CI] Add step to verify C API enum integrity.
  .github/workflows/CodeQuality.yml
  scripts/verify_enum_integrity.py
Labels: Ready For Review

#10826 [Python] Improve performance of conversion to Numpy/Pandas for nested lists
  CMakeLists.txt
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/scripts/cache_data.json
  tools/pythonpkg/scripts/imports.py
  tools/pythonpkg/src/include/duckdb_python/import_cache/modules/numpy_module.hpp
  tools/pythonpkg/src/include/duckdb_python/numpy/array_wrapper.hpp
  tools/pythonpkg/src/include/duckdb_python/numpy/numpy_result_conversion.hpp
  tools/pythonpkg/src/native/python_conversion.cpp
  tools/pythonpkg/src/numpy/array_wrapper.cpp
  tools/pythonpkg/src/numpy/numpy_result_conversion.cpp
  tools/pythonpkg/src/pandas/analyzer.cpp
  tools/pythonpkg/src/pandas/scan.cpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/src/pyrelation/initialize.cpp
  tools/pythonpkg/src/pyresult.cpp
  tools/pythonpkg/tests/fast/pandas/test_df_object_resolution.py
  tools/pythonpkg/tests/fast/pandas/test_fetch_nested.py
  tools/pythonpkg/tests/fast/pandas/test_pandas_update.py
  tools/pythonpkg/tests/fast/test_all_types.py
Labels: Ready For Review

#11100 Fuzzer #2376: INTERVAL Muliply Overflow
  src/function/scalar/operators/multiply.cpp
  test/fuzzer/sqlsmith/interval_multiply_overflow.test
Labels: Ready For Review

#11083 [CSV Scan] Implement ignore_erros for Dates/Timestamps/Decimals
  data/csv/mixed_dates.csv
  data/csv/mixed_decimal.csv
  data/csv/mixed_decimal_delimiter.csv
  data/csv/mixed_double.csv
  data/csv/mixed_timestamps.csv
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_casting.hpp
  test/sql/copy/csv/test_csv_mixed_casts.test
Labels: CI Failure

#11130 Disable jemalloc for ARM distributions and clean up when closing DB
  extension/extension_config.cmake
  extension/jemalloc/include/jemalloc_extension.hpp
  extension/jemalloc/jemalloc/include/jemalloc/internal/jemalloc_internal_defs.h
  extension/jemalloc/jemalloc_extension.cpp
  src/common/allocator.cpp
  src/include/duckdb/common/allocator.hpp
  src/main/database.cpp
  src/parallel/task_scheduler.cpp
Labels: Ready To Merge

#11128 Case senstivity issue secret manager
  src/main/secret/secret_manager.cpp
  src/main/secret/secret_storage.cpp
  test/secrets/test_custom_secret_storage.cpp
Labels: Ready To Merge

#11127 Bump az aw vcpkg
  .github/actions/build_extensions/action.yml
  .github/actions/manylinux_2014_setup/action.yml
  .github/actions/ubuntu_18_setup/action.yml
  .github/config/out_of_tree_extensions.cmake
  .github/workflows/Wasm.yml
  .github/workflows/_extension_distribution.yml
  scripts/merge_vcpkg_deps.py
  scripts/setup_manylinux2014.sh
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#11133 Refactor OSX.yml, now inputs can be provided
  .github/workflows/InvokeCI.yml
  .github/workflows/OSX.yml
  CMakeLists.txt
  scripts/upload-assets-to-staging.sh
Labels: Ready For Review

#11132 Bump spatial
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#11161 More Array and Union fixes
  src/common/types/row/tuple_data_collection.cpp
  src/common/types/vector.cpp
  src/function/cast/list_casts.cpp
  src/function/cast/union_casts.cpp
  src/include/duckdb/common/types/vector.hpp
  test/fuzzer/duckfuzz/array_hash.test
  test/sql/index/art/types/test_art_union.test
  test/sql/types/nested/array/array_cast.test
  test/sql/types/nested/array/array_try_cast.test
  test/sql/types/union/union_cast.test
  test/sql/types/union/union_join.test
  test/sql/types/union/union_limit_offset.test
  test/sql/types/union/union_validity.test
Labels: Ready To Merge

#11156 Refactor upload logic (towards staged releases)
  .github/workflows/InvokeCI.yml
  .github/workflows/Java.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/OSX.yml
  .github/workflows/Python.yml
  .github/workflows/Windows.yml
  scripts/upload-assets-to-staging.sh
Labels: Ready To Merge

#11143 Fuzzer #2490: Generate NULL TIMESTAMPTZ
  extension/icu/icu-table-range.cpp
  test/fuzzer/sqlsmith/timestamptz_null_range.test
Labels: Ready For Review

#11169 Add folder parameter to upload logic and upload also twine artifacts
  .github/workflows/Java.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/OSX.yml
  .github/workflows/Python.yml
  .github/workflows/Windows.yml
  scripts/upload-assets-to-staging.sh
Labels: Ready To Merge

#11170 CI: Find mirror issues among all issues, not just open issues
  .github/workflows/InternalIssuesUpdateMirror.yml
Labels: Ready For Review

#11179 Allow overriding of git describe also in scripts (via OVERRIDE_GIT_DESCRIBE environment variable)
  scripts/amalgamation.py
  scripts/package_build.py
  src/include/duckdb/common/allocator.hpp
Labels: Ready For Review

#11187 Python staged releases: centralized staged upload
  .github/workflows/Python.yml
  .github/workflows/TwineUpload.yml
  tools/pythonpkg/setup.py
Labels: Ready For Review

#11193 TwineUpload: Add awscli dependency + minor rework
  .github/workflows/TwineUpload.yml
Labels: Ready To Merge

#11198 Fix warning on unused utf_type
  src/common/types/string_type.cpp
Labels: Ready To Merge

#11204 CI: Create/label mirror issue job should list all internal issues
  .github/workflows/InternalIssuesCreateMirror.yml
  .github/workflows/NeedsDocumentation.yml
  .github/workflows/PRNeedsMaintainerApproval.yml
Labels: Ready For Review

#11209 [Dev] Fix py override describe
  .github/workflows/InvokeCI.yml
  .github/workflows/Python.yml
  .github/workflows/TwineUpload.yml
  scripts/package_build.py
  tools/pythonpkg/setup.py
Labels: Ready To Merge

#11106 Sanitize CSV Newline identifier for writing CSV files
  src/function/table/copy_csv.cpp
  test/sql/copy/csv/test_copy.test
Labels: Ready For Review

#11212 Review of CI on tags + add R extensions CI to InvokeCI.yml
  .github/workflows/CodeQuality.yml
  .github/workflows/ExtendedTests.yml
  .github/workflows/InvokeCI.yml
  .github/workflows/Java.yml
  .github/workflows/Julia.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/Main.yml
  .github/workflows/NightlyTests.yml
  .github/workflows/OSX.yml
  .github/workflows/Python.yml
  .github/workflows/R.yml
  .github/workflows/R_CMD_CHECK.yml
  .github/workflows/Regression.yml
  .github/workflows/StagedUpload.yml
  .github/workflows/Swift.yml
  .github/workflows/TwineUpload.yml
  .github/workflows/Windows.yml
  .github/workflows/cifuzz.yml
  scripts/amalgamation.py
  scripts/package_build.py
  tools/pythonpkg/setup.py
Labels: Ready To Merge

#11217 Fix python and apply patches + bump extensions
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
  .github/workflows/Python.yml
Labels: Ready To Merge

#11139 ORDER BY ColumnNumber with Collations
  src/planner/expression_binder/order_binder.cpp
  test/sql/collate/test_collate_orderby_column_number.test
Labels: Changes Requested

#11135 Fix differences to implementation for to_parquet, write_parquet, to_csv, write_csv, Expression.alias, DuckDBPyRelation.map
  tools/pythonpkg/duckdb-stubs/__init__.pyi
Labels: Ready For Review

#11192 Issue template: Ask for MWEs
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready For Review

#11245 R_CMD_CHECK: Pin to duckdb/duckdb-r 0ed106a71c
  .github/workflows/R_CMD_CHECK.yml
Labels: Ready To Merge

#11242 Remove no_vector_verification in Map Subscript Test
  test/sql/types/nested/map/test_map_subscript_all_types.test_slow
Labels: Ready For Review

#11220 [Parquet] Support for LZ4 Compression
  extension/parquet/CMakeLists.txt
  extension/parquet/column_reader.cpp
  extension/parquet/column_writer.cpp
  extension/parquet/parquet_config.py
  extension/parquet/parquet_extension.cpp
  scripts/package_build.py
  test/parquet/test_parquet_reader_compression.test
  test/sql/copy/parquet/parquet_write_codecs.test
  third_party/lz4/LICENSE
  third_party/lz4/lz4.cpp
  third_party/lz4/lz4.hpp
  third_party/parquet/parquet_types.cpp
  third_party/parquet/parquet_types.h
Labels: Ready To Merge

#11233 Issue #10867: AsOf Predicate Pushdown
  src/optimizer/pushdown/pushdown_cross_product.cpp
  src/optimizer/pushdown/pushdown_inner_join.cpp
  test/sql/join/asof/test_asof_join_pushdown.test
Labels: Ready For Review

#11082 [Dev] Fix compilation issues on `feature`
  src/include/duckdb/common/arrow/appender/varchar_data.hpp
  src/include/duckdb/common/operator/numeric_cast.hpp
  src/include/duckdb/common/types/arrow_string_view_type.hpp
  tools/pythonpkg/tests/fast/arrow/test_arrow_string_view.py
Labels: Ready For Review

#10586 add query() and query_table() functions
  src/function/table/CMakeLists.txt
  src/function/table/query_function.cpp
  src/function/table/range.cpp
  src/include/duckdb/function/table/range.hpp
  test/sql/catalog/function/query_function.test
Labels: Needs Documentation, Ready To Merge

#11203 Perform direct write operation if input data are larger than buffer size
  src/common/serializer/buffered_file_writer.cpp
Labels: Changes Requested

#11291 Compile spatial also for rtools
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#11320 Issue #11279: TIMESTAMP => TIMESTAMPTZ
  extension/icu/icu-timezone.cpp
  src/function/cast_rules.cpp
  test/sql/types/timestamp/timestamp_timezone_cast.test
Labels: Ready To Merge

#11321 Issue #11269: DISTINCT Sorted Aggregates
  src/planner/binder/expression/bind_aggregate_expression.cpp
  test/sql/aggregate/aggregates/test_aggregate_types.test
  test/sql/aggregate/aggregates/test_aggregate_types_scalar.test
  test/sql/aggregate/aggregates/test_order_by_aggregate.test
  test/sql/aggregate/aggregates/test_string_agg.test
  test/sql/aggregate/distinct/grouped/string_agg.test
  test/sql/function/list/list_sort.test
Labels: Ready For Review

#11345 fix duckdb-r script
  .github/workflows/R_CMD_CHECK.yml
Labels: Ready For Review

#11346 Fix regression_test_runner.py
  scripts/regression_test_runner.py
Labels: Ready For Review

#11347 Issue #11234: IEJoin Scan Reset
  src/execution/operator/join/physical_iejoin.cpp
  test/sql/join/iejoin/predicate_expressions.test
Labels: Ready For Review

#11341 TPC-H: Use BIGINT for ID fields schema where required by the specification
  extension/tpch/dbgen/dbgen.cpp
  test/api/serialized_plans/serialized_plans.binary
Labels: Ready For Review

#11342 Another round of polishing staged releases
  .github/workflows/Java.yml
  .github/workflows/Python.yml
  .github/workflows/Windows.yml
  scripts/upload-assets-to-staging.sh
Labels: Ready For Review

#11355 CI: Remove issue labeling workflow
  .github/workflows/Labels.yml
Labels: Ready For Review

#11252 RE2 upgrade to version 2023-02-01
  src/function/scalar/string/regexp/regexp_extract_all.cpp
  third_party/catch/catch.hpp
  third_party/fmt/include/fmt/core.h
  third_party/lz4/lz4.cpp
  third_party/re2/CMakeLists.txt
  third_party/re2/re2/bitmap256.cc
  third_party/re2/re2/bitmap256.h
  third_party/re2/re2/bitstate.cc
  third_party/re2/re2/compile.cc
  third_party/re2/re2/dfa.cc
  third_party/re2/re2/filtered_re2.cc
  third_party/re2/re2/filtered_re2.h
  third_party/re2/re2/mimics_pcre.cc
  third_party/re2/re2/nfa.cc
  third_party/re2/re2/onepass.cc
  third_party/re2/re2/parse.cc
  third_party/re2/re2/perl_groups.cc
  third_party/re2/re2/pod_array.h
  third_party/re2/re2/prefilter.cc
  third_party/re2/re2/prefilter.h
  third_party/re2/re2/prefilter_tree.cc
  third_party/re2/re2/prefilter_tree.h
  third_party/re2/re2/prog.cc
  third_party/re2/re2/prog.h
  third_party/re2/re2/re2.cc
  third_party/re2/re2/re2.h
  third_party/re2/re2/regexp.cc
  third_party/re2/re2/regexp.h
  third_party/re2/re2/set.cc
  third_party/re2/re2/set.h
  third_party/re2/re2/simplify.cc
  third_party/re2/re2/sparse_array.h
  third_party/re2/re2/sparse_set.h
  third_party/re2/re2/stringpiece.cc
  third_party/re2/re2/stringpiece.h
  third_party/re2/re2/tostring.cc
  third_party/re2/re2/unicode_casefold.cc
  third_party/re2/re2/unicode_casefold.h
  third_party/re2/re2/unicode_groups.cc
  third_party/re2/re2/unicode_groups.h
  third_party/re2/re2/walker-inl.h
  third_party/re2/util/logging.h
  third_party/re2/util/mix.h
  third_party/re2/util/mutex.h
  third_party/re2/util/rune.cc
  third_party/re2/util/strutil.cc
  third_party/re2/util/strutil.h
  third_party/re2/util/utf.h
  third_party/re2/util/util.h
Labels: Ready To Merge

#11366 README: Display different logo for light/dark mode
  README.md
  logo/DuckDB_Logo-horizontal-dark-mode.png
  logo/DuckDB_Logo-horizontal-dark-mode.svg
  logo/DuckDB_Logo-horizontal.png
  logo/DuckDB_Logo-horizontal.svg
  logo/DuckDB_Logo-stacked-dark-mode.png
  logo/DuckDB_Logo-stacked-dark-mode.svg
Labels: Ready For Review

#11368 Fix bug in duckdb_bind_blob
  tools/juliapkg/src/api.jl
  tools/juliapkg/test/test_prepare.jl
Labels: Ready To Merge

#11372 Issue #10965: RESPECT IGNORE NULLS
  src/parser/transform/expression/transform_function.cpp
  test/sql/window/test_ignore_nulls.test
  third_party/libpg_query/grammar/grammar.y
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/grammar/types/select.yh
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
  third_party/libpg_query/src_backend_parser_scan.cpp
Labels: Ready For Review

#11357 Update README.md
  src/README.md
Labels: Ready For Review

#11390 Issue #10885: Negative Window RANGEs
  src/execution/window_executor.cpp
  test/sql/window/test_negative_range.test
Labels: Ready For Review

#11392 Issue #11377: Invertible TIMESTAMP_XXX Casts
  src/planner/expression/bound_cast_expression.cpp
  test/sql/cast/timestamp_date_cast.test
Labels: Ready For Review

#11396 Internal #1657: Stricter STRUCT Casts
  src/common/types.cpp
  test/sql/types/struct/struct_different_names.test
Labels: Ready For Review

#11420 CI: Also label PRs as 'stale' and close them when there's no activity
  .github/workflows/IssuesCloseStale.yml
Labels: Ready For Review

#11415 Remove redundant default descriptions
  extension/httpfs/httpfs_extension.cpp
  src/include/duckdb/main/settings.hpp
Labels: Ready To Merge

#11428 Issue #11419: Quantile Order By
  src/planner/binder/expression/bind_aggregate_expression.cpp
  test/sql/aggregate/aggregates/test_quantile_cont.test
  test/sql/aggregate/aggregates/test_quantile_disc.test
Labels: Ready For Review

#11429 add readonly to duckdb_databases()
  src/function/table/system/duckdb_databases.cpp
  test/sql/table_function/duckdb_databases.test
Labels: Changes Requested
