Repository duckdb/duckdb, pull requests merged in 2024-12, with the labels that each got.

#15070 Issue #15067: Postgres Age Compatibility
  extension/core_functions/scalar/date/age.cpp
  extension/icu/icu-dateadd.cpp
  extension/icu/icu-datetrunc.cpp
  extension/icu/include/icu-datefunc.hpp
Labels: Ready For Review

#15081 IEJoin GetProgress: Normalize to 0-100
  src/execution/operator/join/physical_iejoin.cpp
Labels: Ready To Merge

#15085 Avoid building for Python 3.7 on Windows
  .github/workflows/Python.yml
Labels: Ready To Merge

#15082 Allow inputting a base hash in Regression workflow
  .github/workflows/Regression.yml
Labels: Ready To Merge

#15025 Fix aggregate regression
  extension/jemalloc/jemalloc_extension.cpp
  src/execution/aggregate_hashtable.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/execution/aggregate_hashtable.hpp
Labels: Ready For Review

#15088 Sum Rewriter: correctly match only Sum aggregations in sum rewriter
  src/optimizer/sum_rewriter.cpp
Labels: Ready To Merge

#15090 new answers for some JOIN benchmarks
  benchmark/micro/join/asof_join_small_probe.benchmark
  benchmark/micro/join/left_outer_join_right_big.benchmark
  benchmark/micro/join/positional_join.benchmark
  benchmark/micro/join/right_outer_join_left_big.benchmark
Labels: Ready To Merge

#15066 Issue #15056: DISTINCT Insensitive Aggregation
  extension/core_functions/aggregate/distributive/bool.cpp
  src/common/enum_util.cpp
  src/function/aggregate/distributive/first_last_any.cpp
  src/function/aggregate/distributive/minmax.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/function/aggregate_function.hpp
  src/include/duckdb/function/aggregate_state.hpp
  src/include/duckdb/optimizer/rule/distinct_aggregate_optimizer.hpp
  src/optimizer/optimizer.cpp
  src/optimizer/rule/CMakeLists.txt
  src/optimizer/rule/distinct_aggregate_optimizer.cpp
  test/sql/optimizer/expression/test_indistinct_aggregates.test
Labels: Ready For Review

#14597 Bloom Filter Support in Parquet Reader/Writer
  extension/core_functions/aggregate/holistic/mode.cpp
  extension/parquet/column_writer.cpp
  extension/parquet/include/column_writer.hpp
  extension/parquet/include/parquet_dbp_encoder.hpp
  extension/parquet/include/parquet_metadata.hpp
  extension/parquet/include/parquet_statistics.hpp
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_metadata.cpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_statistics.cpp
  extension/parquet/parquet_writer.cpp
  src/common/multi_file_reader.cpp
  src/function/cast/union/from_struct.cpp
  src/include/duckdb/common/hugeint.hpp
  src/include/duckdb/common/types/interval.hpp
  src/include/duckdb/common/types/string_type.hpp
  src/include/duckdb/common/uhugeint.hpp
  src/include/duckdb/main/extension_entries.hpp
  src/include/duckdb/planner/table_filter.hpp
  test/sql/copy/parquet/alltypes-dictionaries.test
  test/sql/copy/parquet/bloom_filters.test
  test/sql/copy/parquet/dictionary_compression_ratio_threshold.test
  test/sql/copy/parquet/writer/parquet_write_strings.test
  test/sql/copy/parquet/writer/write_stats_min_max.test_slow
Labels: Needs Documentation, Ready For Review

#14972 Provide support for continuous profiling
  src/include/duckdb/main/query_profiler.hpp
  src/main/query_profiler.cpp
  src/parallel/executor_task.cpp
Labels: Changes Requested

#15093 fix bundle-library step
  Makefile
Labels: Ready To Merge

#15100 Internal #861: Value Function SubFrames
  src/function/window/window_value_function.cpp
  src/include/duckdb/function/window/window_aggregator.hpp
Labels: Ready For Review

#15105 Do not swap `RIGHT` joins to `LEFT` when `BuildProbeSideOptimizer` is disabled
  src/include/duckdb/optimizer/optimizer.hpp
  src/optimizer/optimizer.cpp
  src/planner/binder.cpp
  src/planner/binder/tableref/plan_joinref.cpp
  test/sql/optimizer/plan/test_disable_build_side_probe_side.test
Labels: Ready To Merge

#15084 Operator's GetProgress to return ProgressData instead of double
  .github/patches/extensions/vss/progress_data.patch
  src/common/progress_bar/progress_bar.cpp
  src/execution/operator/aggregate/physical_hash_aggregate.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/operator/scan/physical_positional_scan.cpp
  src/execution/operator/scan/physical_table_scan.cpp
  src/execution/physical_operator.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/execution/executor.hpp
  src/include/duckdb/execution/operator/aggregate/physical_hash_aggregate.hpp
  src/include/duckdb/execution/operator/aggregate/physical_window.hpp
  src/include/duckdb/execution/operator/join/physical_hash_join.hpp
  src/include/duckdb/execution/operator/join/physical_iejoin.hpp
  src/include/duckdb/execution/operator/scan/physical_positional_scan.hpp
  src/include/duckdb/execution/operator/scan/physical_table_scan.hpp
  src/include/duckdb/execution/physical_operator.hpp
  src/include/duckdb/execution/progress_data.hpp
  src/include/duckdb/execution/radix_partitioned_hashtable.hpp
  src/include/duckdb/parallel/pipeline.hpp
  src/parallel/executor.cpp
  src/parallel/pipeline.cpp
Labels: Ready For Review

#15126 Skip building azure extension due to problems installing libxml
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#15134 Avoid cleaning up past releases if we have not just uploaded a new one
  .github/workflows/Python.yml
Labels: Ready For Review

#15116 Implement struct projection pushdown for JSON reads
  extension/json/include/json_scan.hpp
  extension/json/include/json_transform.hpp
  extension/json/json_functions/json_transform.cpp
  extension/json/json_functions/read_json.cpp
  extension/json/json_functions/read_json_objects.cpp
  extension/json/json_scan.cpp
  test/sql/json/table/test_json_nested_struct_projection_pushdown.test
  test/sql/json/test_json_struct_projection_pushdown.test_slow
Labels: Ready For Review

#15131 Update the `.clang-format` file to disable sorting includes
  .clang-format
Labels: Ready To Merge

#15136 Fixup deployment of extensions for build_extensions_dockerized
  .github/actions/build_extensions_dockerized/action.yml
Labels: Ready For Review

#15139 Issue #15138: Friendlier ICU Settings
  extension/icu/icu_extension.cpp
  test/sql/settings/settings_icu.test
Labels: Ready For Review

#15146 Execute test/sql/aggregate/aggregates/first_memory_usage.test_slow single threaded
  test/sql/aggregate/aggregates/first_memory_usage.test_slow
Labels: Ready To Merge

#15159 Refactor signing linux extensions
  .github/actions/build_extensions_dockerized/action.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/Python.yml
  .github/workflows/_sign_deploy_extensions.yml
  scripts/extension-upload-all.sh
Labels: Ready For Review

#15157 Fix wrong type append of base vector
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
Labels: Ready To Merge

#15161 Add cross-version testing CI
  .github/workflows/CrossVersion.yml
Labels: Ready For Review

#15167 Fix wrongly used github.ref to sha
  .github/workflows/Python.yml
Labels: Ready For Review

#15165 Fix Regression workflow running against itself
  .github/workflows/Regression.yml
Labels: Ready To Merge

#15169 Fix ci issues
  scripts/extension-upload-all.sh
  test/sql/copy/csv/rejects/csv_buffer_size_rejects.test_slow
  tools/pythonpkg/tests/fast/arrow/test_filter_pushdown.py
Labels: Ready For Review

#14878 [Compression] Add RoaringBitmap Compression
  benchmark/micro/compression/roaring/roaring_array_read.benchmark
  benchmark/micro/compression/roaring/roaring_array_store.benchmark
  benchmark/micro/compression/roaring/roaring_bitset_read.benchmark
  benchmark/micro/compression/roaring/roaring_bitset_store.benchmark
  benchmark/micro/compression/roaring/roaring_inverted_array_read.benchmark
  benchmark/micro/compression/roaring/roaring_inverted_array_store.benchmark
  benchmark/micro/compression/roaring/roaring_inverted_run_read.benchmark
  benchmark/micro/compression/roaring/roaring_inverted_run_store.benchmark
  benchmark/micro/compression/roaring/roaring_run_read.benchmark
  benchmark/micro/compression/roaring/roaring_run_store.benchmark
  benchmark/micro/limit/parallel_limit.benchmark
  scripts/generate_enum_util.py
  src/common/enum_util.cpp
  src/common/enums/compression_type.cpp
  src/common/types/validity_mask.cpp
  src/function/compression_config.cpp
  src/include/duckdb/common/enums/compression_type.hpp
  src/include/duckdb/common/types/validity_mask.hpp
  src/include/duckdb/function/compression/compression.hpp
  src/include/duckdb/storage/compression/alp/alp_compress.hpp
  src/include/duckdb/storage/compression/alprd/alprd_compress.hpp
  src/include/duckdb/storage/compression/roaring/appender.hpp
  src/include/duckdb/storage/compression/roaring/roaring.hpp
  src/include/duckdb/storage/segment/uncompressed.hpp
  src/include/duckdb/storage/table/column_segment.hpp
  src/storage/compression/CMakeLists.txt
  src/storage/compression/bitpacking.cpp
  src/storage/compression/dictionary_compression.cpp
  src/storage/compression/fixed_size_uncompressed.cpp
  src/storage/compression/fsst.cpp
  src/storage/compression/rle.cpp
  src/storage/compression/roaring/CMakeLists.txt
  src/storage/compression/roaring/analyze.cpp
  src/storage/compression/roaring/common.cpp
  src/storage/compression/roaring/compress.cpp
  src/storage/compression/roaring/metadata.cpp
  src/storage/compression/roaring/scan.cpp
  src/storage/compression/validity_uncompressed.cpp
  src/storage/compression/zstd.cpp
  src/storage/table/column_data.cpp
  src/storage/table/column_segment.cpp
  test/sql/storage/compression/roaring/fetch_row.test
  test/sql/storage/compression/roaring/roaring_array_simple.test
  test/sql/storage/compression/roaring/roaring_bitset_simple.test
  test/sql/storage/compression/roaring/roaring_compression_ratio.test_slow
  test/sql/storage/compression/roaring/roaring_inverted_array_simple.test
  test/sql/storage/compression/roaring/roaring_inverted_run_simple.test
  test/sql/storage/compression/roaring/roaring_run_simple.test
  test/sql/storage/parallel/insert_many_compressible_batches.test_slow
Labels: Ready For Review

#15158 bump spatial + VCPKG Commit
  .github/actions/build_extensions/action.yml
  .github/actions/build_extensions_dockerized/action.yml
  .github/actions/manylinux_2014_setup/action.yml
  .github/actions/ubuntu_18_setup/action.yml
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/spatial/random_test_fix.patch
  .github/patches/extensions/spatial/support_multiple_function_descriptions.patch
  .github/patches/extensions/spatial/table_fun_to_string.patch
  .github/workflows/Wasm.yml
  scripts/merge_vcpkg_deps.py
  scripts/setup_manylinux2014.sh
Labels: Ready To Merge

#15178 Fix various ci nightly
  .github/workflows/NightlyTests.yml
  extension/core_functions/core_functions_extension.cpp
  src/function/register_function_list.cpp
  src/include/duckdb/function/register_function_list_helper.hpp
  src/storage/compression/zstd.cpp
Labels: Ready For Review

#15125 Issue #15069: Postgres CURRENT_XXX Compatibility
  extension/core_functions/function_list.cpp
  extension/core_functions/include/core_functions/scalar/date_functions.hpp
  extension/core_functions/scalar/date/current.cpp
  extension/core_functions/scalar/date/functions.json
  extension/icu/icu-timezone.cpp
  src/catalog/default/default_functions.cpp
  src/include/duckdb/main/extension_entries.hpp
  test/optimizer/misc/test_count_and_sum.test
  test/sql/export/export_functions.test
  test/sql/function/timestamp/current_time.test
  test/sql/parser/test_value_functions.test
  test/sql/pivot/pivot_errors.test
  test/sql/sample/reservoir_testing_percentage.test_slow
  test/sql/sample/reservoir_testing_rows_value.test_slow
  test/sql/sample/same_seed_same_sample.test_slow
  test/sql/table_function/range_non_foldable.test
  tools/pythonpkg/tests/fast/api/test_native_tz.py
Labels: Ready For Review

#14727 Move httpfs to external repository
  .github/config/in_tree_extensions.cmake
  .github/config/out_of_tree_extensions.cmake
  Makefile
  extension/httpfs/CMakeLists.txt
  extension/httpfs/README.md
  extension/httpfs/create_secret_functions.cpp
  extension/httpfs/crypto.cpp
  extension/httpfs/hffs.cpp
  extension/httpfs/http_state.cpp
  extension/httpfs/httpfs.cpp
  extension/httpfs/httpfs_config.py
  extension/httpfs/httpfs_extension.cpp
  extension/httpfs/include/create_secret_functions.hpp
  extension/httpfs/include/crypto.hpp
  extension/httpfs/include/hffs.hpp
  extension/httpfs/include/http_metadata_cache.hpp
  extension/httpfs/include/http_state.hpp
  extension/httpfs/include/httpfs.hpp
  extension/httpfs/include/httpfs_extension.hpp
  extension/httpfs/include/s3fs.hpp
  extension/httpfs/s3fs.cpp
  extension/httpfs/vcpkg.json
  src/main/extension/extension_helper.cpp
Labels: Ready For Review

#15191 Review no_extension_autoloading requires in tests: either remove, add FIXME or add EXPECTED
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/aws/require_autoloading.patch
  .github/patches/extensions/inet/require_autoloading.patch
  test/extension/duckdb_extensions.test
  test/extension/update_extensions.test
  test/extension/wrong_function_type.test
  test/fuzzer/sqlsmith/timestamptz_null_range.test
  test/sql/attach/attach_icu_collation.test
  test/sql/catalog/test_extension_suggestion.test
  test/sql/copy/csv/test_partition_compression.test
  test/sql/copy/csv/timestamp_with_tz.test
  test/sql/copy/csv/zstd_crash.test
  test/sql/copy/csv/zstd_fs.test
  test/sql/error/extension_function_error.test
  test/sql/function/generic/test_between_sideeffects.test
  test/sql/function/timetz/timetz_group_by.test
  test/sql/json/table/read_json_objects.test
  test/sql/parser/test_value_functions.test
  test/sql/secrets/create_secret_hffs_autoload.test
  test/sql/secrets/secret_autoloading_errors.test
  test/sql/settings/allowed_directories.test
  test/sql/settings/allowed_paths.test
  test/sql/settings/test_disabled_file_system_httpfs.test
  test/sql/storage/icu_collation.test
  test/sql/table_function/duckdb_extensions.test
  test/sql/table_function/range_non_foldable.test
  test/sqlite/sqllogic_test_runner.cpp
Labels: Ready For Review

#15223 Rework Wasm extensions CI, and use out_of_tree_extensions.cmake
  .github/config/out_of_tree_extensions.cmake
  .github/workflows/Wasm.yml
  extension/extension_config.cmake
Labels: Ready For Review

#15237 Skip spatial on MinGW, given otherwise mingw extensions CI will fail
  .github/config/out_of_tree_extensions.cmake
Labels: Ready For Review

#15241 Add filter on repository_dispatch to Regression nightly run
  .github/workflows/Regression.yml
Labels: Ready To Merge

#15243 Rework upload ci via reusable workflow
  .github/workflows/OSX.yml
  .github/workflows/R.yml
  .github/workflows/Wasm.yml
Labels: Ready For Review

#15222 Bump excel extension
  .github/config/out_of_tree_extensions.cmake
  scripts/generate_extensions_function.py
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#15219 `OR`/`IN` filter pushdown for `VARCHAR`
  benchmark/micro/pushdown/in_varchar_pushdown.benchmark
  benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark
  benchmark/micro/pushdown/or_varchar_pushdown.benchmark
  src/optimizer/filter_combiner.cpp
  src/optimizer/join_order/relation_statistics_helper.cpp
  src/storage/table/row_group.cpp
  test/sql/filter/test_or_pushdown.test
Labels: Ready For Review

#15251 Grouped aggregation performance improvements
  extension/core_functions/aggregate/holistic/mode.cpp
  extension/jemalloc/jemalloc/include/jemalloc/internal/jemalloc_internal_defs.h
  src/common/types/row/tuple_data_collection.cpp
  src/execution/aggregate_hashtable.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/execution/aggregate_hashtable.hpp
  test/sql/aggregate/external/simple_external_aggregate.test_slow
  test/sql/aggregate/external/small_external_aggregate.test_coverage
Labels: Ready To Merge

#15270 Feature #12699: XXX_VALUE Secondary Sorts
  extension/core_functions/aggregate/holistic/mad.cpp
  extension/core_functions/aggregate/holistic/quantile.cpp
  extension/core_functions/include/core_functions/aggregate/quantile_sort_tree.hpp
  extension/core_functions/include/core_functions/aggregate/quantile_state.hpp
  src/function/window/CMakeLists.txt
  src/function/window/window_index_tree.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/execution/merge_sort_tree.hpp
  src/include/duckdb/function/window/window_executor.hpp
  src/include/duckdb/function/window/window_index_tree.hpp
  src/include/duckdb/function/window/window_value_function.hpp
  src/include/duckdb/parser/expression/window_expression.hpp
  src/include/duckdb/planner/expression/bound_window_expression.hpp
  src/include/duckdb/storage/serialization/parsed_expression.json
  src/optimizer/statistics/operator/propagate_window.cpp
  src/parser/expression/window_expression.cpp
  src/parser/parsed_expression_iterator.cpp
  src/parser/transform/expression/transform_function.cpp
  src/planner/binder/expression/bind_window_expression.cpp
  src/planner/expression/bound_window_expression.cpp
  src/planner/expression_iterator.cpp
  src/storage/serialization/serialize_parsed_expression.cpp
  test/sql/json/issues/internal_issue391.test
  test/sql/window/test_value_orderby.test
Labels: Ready For Review

#15230 Join order bugs
  src/optimizer/build_probe_side_optimizer.cpp
  src/optimizer/join_order/cardinality_estimator.cpp
  test/optimizer/joins/join_bug.test
Labels: Ready For Review

#15101 Don't decode special characters on redirect
  third_party/httplib/httplib.hpp
Labels: Ready For Review

#15304 Fix 2 unconnected small problems in CI
  .github/workflows/CrossVersion.yml
  .github/workflows/OSX.yml
  .github/workflows/Wasm.yml
Labels: Ready For Review

#15309 Move away from upload-artifacts@v3 / download-artifacts@v3
  .github/workflows/Android.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/NightlyTests.yml
Labels: Ready For Review

#15324 Pass down DUCKDB_EXTENSION_SIGNING_PK as env
  .github/workflows/LinuxRelease.yml
  .github/workflows/OSX.yml
  .github/workflows/Python.yml
  .github/workflows/_sign_deploy_extensions.yml
Labels: Ready For Review

#15372 CI: Use mirror for Spark binaries
  tools/pythonpkg/scripts/install_spark_in_cibuildwheels_linux_container.sh
Labels: Ready To Merge

#15359 Fix skip CSV Rejects test
  test/sql/copy/csv/rejects/csv_buffer_size_rejects.test_slow
Labels: Ready To Merge

#15382 Bump azure and remove patches
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/azure/reformat_string_functions.patch
Labels: Ready To Merge

#15367 Fix conditional jump or move depends on uninitialised value(s)
  src/include/duckdb/function/table/read_csv.hpp
Labels: Ready To Merge

#15346 [Python] Allow use of `DuckDBPyType` as child objects in implicit conversions
  tools/pythonpkg/src/typing/pytype.cpp
  tools/pythonpkg/tests/fast/test_type.py
Labels: Ready To Merge

#15347 [Dev] Made `reference<CompressionFunction> function` private in `ColumnSegment`
  src/include/duckdb/storage/compression/alp/alp_compress.hpp
  src/include/duckdb/storage/compression/alprd/alprd_compress.hpp
  src/include/duckdb/storage/table/column_data.hpp
  src/include/duckdb/storage/table/column_segment.hpp
  src/storage/compression/bitpacking.cpp
  src/storage/compression/dictionary/compression.cpp
  src/storage/compression/fsst.cpp
  src/storage/compression/rle.cpp
  src/storage/compression/roaring/compress.cpp
  src/storage/compression/zstd.cpp
  src/storage/table/column_checkpoint_state.cpp
  src/storage/table/column_data.cpp
  src/storage/table/column_segment.cpp
Labels: Ready To Merge

#15383 [Dev] Reset to the vector cache so the vectors are clean for the scan
  src/execution/operator/persistent/physical_update.cpp
  test/issues/rigger/test_609.test
Labels: Ready To Merge

#15361 Fix tests not to use compatibility version latest
  test/sql/catalog/function/test_macro_default_arg_with_dependencies.test
  test/sql/catalog/view/recursive_view_with_dependencies.test
  test/sql/catalog/view/test_view_schema_change_with_dependencies.test
  test/sql/catalog/view/test_view_sql_with_dependencies.test
  test/sql/copy/parquet/parquet_copy_type_mismatch.test
Labels: Ready For Review

#15331 Feature #12699: RANK Secondary Sorts
  src/function/window/CMakeLists.txt
  src/function/window/window_boundaries_state.cpp
  src/function/window/window_index_tree.cpp
  src/function/window/window_merge_sort_tree.cpp
  src/function/window/window_rank_function.cpp
  src/function/window/window_token_tree.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/execution/merge_sort_tree.hpp
  src/include/duckdb/function/window/window_index_tree.hpp
  src/include/duckdb/function/window/window_merge_sort_tree.hpp
  src/include/duckdb/function/window/window_rank_function.hpp
  src/include/duckdb/function/window/window_token_tree.hpp
  src/include/duckdb/function/window/window_value_function.hpp
  src/parser/transform/expression/transform_function.cpp
  test/sql/window/test_rank_orderby.test
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Ready For Review

#15387 [Fix] Uninitialised values in list_reverse
  src/common/row_operations/row_radix_scatter.cpp
Labels: Ready To Merge

#15385 [Dev] Check in `insert` if the InsertionOrderPreservingMap contains the key, do nothing in that case
  src/include/duckdb/common/insertion_order_preserving_map.hpp
  test/api/CMakeLists.txt
  test/api/test_insertion_order_preserving_map.cpp
Labels: Ready To Merge

#15235 feat: refactor getting tie_break_offset in SelectBestMatch
  src/include/duckdb/main/secret/secret_storage.hpp
  src/main/secret/secret_manager.cpp
  src/main/secret/secret_storage.cpp
  test/secrets/test_custom_secret_storage.cpp
Labels: CI Failure

#15397 Fix JSON reader hang found by fuzzer
  data/json/fuzzer_hang.json
  extension/json/json_scan.cpp
  test/sql/json/table/multi_file_hang.test
Labels: Ready To Merge

#15389 Better partition selection for external hash joins
  benchmark/micro/join/external_join_partition_selection.benchmark
  src/common/radix_partitioning.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/include/duckdb/common/radix_partitioning.hpp
  src/include/duckdb/common/types/validity_mask.hpp
  src/include/duckdb/common/vector_operations/unary_executor.hpp
  src/include/duckdb/execution/join_hashtable.hpp
Labels: Ready To Merge

#15403 Feature #12699: ROW_NUMBER Secondary Sorts
  src/function/window/window_boundaries_state.cpp
  src/function/window/window_executor.cpp
  src/function/window/window_merge_sort_tree.cpp
  src/function/window/window_rank_function.cpp
  src/function/window/window_rownumber_function.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/execution/merge_sort_tree.hpp
  src/include/duckdb/function/window/window_executor.hpp
  src/include/duckdb/function/window/window_merge_sort_tree.hpp
  src/include/duckdb/function/window/window_rank_function.hpp
  src/include/duckdb/function/window/window_rownumber_function.hpp
  src/include/duckdb/function/window/window_token_tree.hpp
  src/include/duckdb/function/window/window_value_function.hpp
  src/parser/transform/expression/transform_function.cpp
  test/sql/window/test_rownumber_orderby.test
Labels: Ready To Merge

#15408 Improve hash combining
  src/common/vector_operations/vector_hash.cpp
  test/sql/function/generic/hash_func.test
Labels: Ready For Review

#15401 allow multifilereaders to delete entire chunks in FinalizeChunk
  extension/parquet/parquet_extension.cpp
Labels: Ready To Merge

#15411 Fix issue #14659
  data/csv/repromarket.csv
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  test/sql/copy/csv/auto/test_csv_auto.test
Labels: Ready To Merge

#15409 Fix for issue #14648
  data/csv/comments/14648.csv
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  test/sql/copy/csv/test_comment_midline.test
Labels: Ready To Merge

#15414 [Fix] Adjust reclaim space test to smaller block size nightly
  test/sql/storage/parallel/reclaim_space_insert_unique_idx_optimistic.test_slow
Labels: Ready To Merge

#15413 Feature #12699: CUME_DIST Secondary Sorts
  src/execution/operator/aggregate/physical_window.cpp
  src/function/window/CMakeLists.txt
  src/function/window/window_boundaries_state.cpp
  src/function/window/window_cumedist_function.cpp
  src/function/window/window_rank_function.cpp
  src/function/window/window_token_tree.cpp
  src/include/duckdb/function/window/window_cumedist_function.hpp
  src/include/duckdb/function/window/window_rank_function.hpp
  src/include/duckdb/function/window/window_token_tree.hpp
  src/parser/transform/expression/transform_function.cpp
  test/sql/window/test_cume_dist_orderby.test
Labels: Ready To Merge

#15358 Fix issue with cleanup of buffers when reading same file multiple times
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_scanner.hpp
  test/sql/copy/csv/test_15211.test
Labels: Ready To Merge

#15433 [Fix] Track correct allocation size of evicted memory
  src/common/file_buffer.cpp
  src/function/table/system/duckdb_memory.cpp
  src/include/duckdb/common/file_buffer.hpp
  src/storage/single_file_block_manager.cpp
  src/storage/standard_buffer_manager.cpp
  src/storage/temporary_file_manager.cpp
  test/sql/index/art/storage/test_art_mem_limit.test
Labels: Ready For Review

#15487 Fix InFilter::ToString, visible via EXPLAIN ANALYZE for example
  src/planner/filter/in_filter.cpp
Labels: Ready For Review

#15482 Fix the seed of RandomLocalState to be 64bit instead of 32bits
  extension/core_functions/scalar/random/random.cpp
  src/common/random_engine.cpp
  src/include/duckdb/common/random_engine.hpp
  test/api/test_api.cpp
  test/issues/general/test_9399.test_slow
  test/optimizer/topn/complex_top_n.test
  test/sql/copy/parquet/hive_timestamps.test
  test/sql/join/iejoin/iejoin_projection_maps.test
  test/sql/join/iejoin/test_iejoin_events.test
  test/sql/window/test_volatile_independence.test
Labels: Ready For Review

#14944 C API header generation for Go bindings
  extension/demo_capi/add_numbers.cpp
  extension/demo_capi/capi_demo.cpp
  scripts/generate_c_api.py
  src/include/duckdb.h
  src/include/duckdb/main/capi/header_generation/header_base.hpp.template
  src/include/duckdb_extension.h
Labels: Ready To Merge
