Repository duckdb/duckdb, pull requests merged in 2024-09, with the labels that each got.

#13681 Fix delta commit: revert https://github.com/duckdb/duckdb/pull/13665 and bump to relevant commit
  .github/config/out_of_tree_extensions.cmake
Labels: Ready For Review

#13677 Fix Arrow's extension types test to depend on JSON extension
  test/arrow/arrow_roundtrip.cpp
Labels: Ready For Review

#13683 Internal #2865: Streaming Lead Split
  src/execution/operator/aggregate/physical_streaming_window.cpp
  src/include/duckdb/execution/operator/aggregate/physical_streaming_window.hpp
Labels: Ready For Review

#13687 Throw on null select nodes in `json_deserialize_sql`
  extension/json/json_functions/json_serialize_sql.cpp
  test/sql/json/test_json_serialize_sql.test
Labels: Ready To Merge

#13691 [Fix] Apply array multiplier to child vector when slicing by offset
  src/common/types/vector.cpp
  test/sql/types/nested/array/array_list_aggregate.test
Labels: Ready To Merge

#13693 [Fix] Eagerly Plan subqueries even if they are not correlated
  src/planner/binder/query_node/plan_subquery.cpp
  test/fuzzer/duckfuzz/correlated_subqueries.test
Labels: Ready To Merge

#13695 CI fixes
  extension/jemalloc/jemalloc_extension.cpp
  test/sql/cte/materialized/test_cte_in_cte_materialized.test
  test/sql/cte/test_cte.test
  test/sql/cte/test_issue_5673.test
Labels: Ready To Merge

#13700 make force install actually force install in presence of etags
  src/main/extension/extension_install.cpp
Labels: Ready To Merge

#13701 Fix array segment fetch offset
  src/storage/table/array_column_data.cpp
  test/sql/types/nested/array/array_rowgroup.test
Labels: Ready To Merge

#13686 Fix logic error in `TemporaryMemoryManager`
  src/storage/temporary_memory_manager.cpp
  test/sql/join/external/many_external_joins.test_slow
Labels: Ready For Review

#13519 Add cross join to Python Relational and PySpark API
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/src/pyrelation/initialize.cpp
  tools/pythonpkg/tests/fast/relational_api/test_joins.py
  tools/pythonpkg/tests/fast/spark/test_spark_join.py
Labels: Changes Requested, feature

#13710 Suppress TSAN false positive
  .sanitizer-thread-suppressions.txt
  extension/jemalloc/jemalloc_extension.cpp
Labels: Ready For Review

#13709 Python package docs
  tools/pythonpkg/README.md
Labels: Ready For Review

#13713 Restore etag mechanism
  src/execution/operator/helper/physical_load.cpp
  src/include/duckdb/main/extension_helper.hpp
  src/main/extension/extension_helper.cpp
  src/main/extension/extension_install.cpp
  src/main/extension/extension_load.cpp
  tools/pythonpkg/src/pyconnection.cpp
Labels: Ready To Merge

#13658 Internal #2907: Validate Time Zones
  extension/icu/icu-datefunc.cpp
  extension/icu/icu-timezone.cpp
  extension/icu/icu_extension.cpp
  test/sql/function/timestamp/test_icu_makedate.test
  tools/pythonpkg/tests/fast/pandas/test_datetime_timestamp.py
Labels: Ready For Review

#13727 Change test results so that they would pass also with 0.01% of tollerance
  test/sql/aggregate/aggregates/test_median.test
  test/sql/function/interval/test_date_part.test
  test/sql/function/interval/test_extract.test
  test/sql/function/string/test_jaro_winkler.test
  test/sql/setops/union_shared_scan.test
Labels: Ready For Review

#13730 [build] Fix binaries version for linux arm64
  .github/workflows/LinuxRelease.yml
Labels: Ready To Merge

#13731 [Metrics] Remove `BLOCKED_THREAD_TIME` from Operator Nodes
  src/main/query_profiler.cpp
Labels: Ready To Merge

#13756 Propagate schema in CreateIndexInfo
  src/parser/parsed_data/create_index_info.cpp
  src/planner/binder/statement/bind_create.cpp
Labels: Ready To Merge

#13759 [Upsert] Fix issues surfaced by mixing in virtual columns
  src/planner/binder/statement/bind_insert.cpp
  test/sql/upsert/test_generated_column.test
Labels: Ready To Merge

#13762 Issue template updates
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready For Review

#13733 Improve block size nightly
  .github/workflows/NightlyTests.yml
  scripts/test_block_sizes.py
  scripts/test_vector_sizes.py
Labels: Ready For Review

#13761 Fix `hive_partitioning`/`hive_types` for `read_json_objects`
  data/json/13725/month=07/mytest.json
  extension/json/json_functions/read_json_objects.cpp
  test/sql/json/issues/issue13725.test
Labels: Ready To Merge

#13768 [Python] The GIL should not be held during the bind of a Relation
  tools/pythonpkg/src/include/duckdb_python/pyfilesystem.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/test_filesystem.py
Labels: Ready To Merge

#13770 Silence `jemalloc_write` in non-debug mode
  extension/jemalloc/jemalloc/README.md
  extension/jemalloc/jemalloc/src/malloc_io.c
Labels: Ready To Merge

#13773 [Python] Ensure GIL is not held when an interaction with the PyFileSystem is done
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/src/pyfilesystem.cpp
Labels: Ready To Merge

#13771 Bump Substrait before release
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#13529 Add estimated cardinality to logical plans
  src/include/duckdb/planner/logical_operator.hpp
  src/planner/logical_operator.cpp
  src/planner/operator/logical_aggregate.cpp
  src/planner/operator/logical_any_join.cpp
  src/planner/operator/logical_comparison_join.cpp
  src/planner/operator/logical_cteref.cpp
  src/planner/operator/logical_distinct.cpp
  src/planner/operator/logical_get.cpp
  src/planner/operator/logical_materialized_cte.cpp
  src/planner/operator/logical_order.cpp
  test/optimizer/estimated_cardinalities_are_in_logical_plan.test
Labels: Ready For Review

#13812 bump spatial
  .github/config/out_of_tree_extensions.cmake
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#13797 Update C API headers
  src/include/duckdb.h
  src/include/duckdb/main/capi/header_generation/functions/aggregate_functions.json
  src/include/duckdb/main/capi/header_generation/functions/safe_fetch_functions.json
  src/include/duckdb/main/capi/header_generation/functions/scalar_functions.json
Labels: Ready For Review

#13820 Issue #13813: TIMETZ Uninvertible Casts
  src/planner/expression/bound_cast_expression.cpp
  test/sql/types/time/test_time_tz_icu.test
Labels: Ready For Review

#13883 Explicit windows-2019 instead of windows-latest
  .github/workflows/R.yml
  .github/workflows/Windows.yml
Labels: Ready For Review

#13874 CI/Windows: Drop redundant package
  .github/workflows/Windows.yml
Labels: Ready To Merge

#13724 Update description of 'max_temp_directory_size'
  src/include/duckdb/main/settings.hpp
Labels: Ready To Merge

#13894 Handle extension ABI mismatches in a forward & backward compatible way
  src/include/duckdb/main/extension.hpp
  src/include/duckdb/main/extension_helper.hpp
  src/main/extension.cpp
  src/main/extension/extension_load.cpp
Labels: Ready For Review

#13895 Remove buffer_manager_allocate.patch and bump spatial
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/spatial/buffer_manager_allocate.patch
Labels: Ready For Review

#13929 Improve logic for remote extension install on Windows
  src/main/extension/extension_install.cpp
Labels: Ready For Review

#13937 CI: Trigger actions for labeled discussions
  .github/workflows/InternalIssuesCreateMirror.yml
  .github/workflows/InternalIssuesUpdateMirror.yml
  .github/workflows/NeedsDocumentation.yml
Labels: Ready For Review

#13969 [Fix] Throw exception for UNNEST in lambdas
  src/include/duckdb/planner/expression_binder.hpp
  src/include/duckdb/planner/expression_binder/select_binder.hpp
  src/planner/binder/expression/bind_function_expression.cpp
  src/planner/binder/expression/bind_lambda.cpp
  src/planner/binder/expression/bind_unnest_expression.cpp
  test/sql/function/list/lambdas/expression_iterator_cases.test
  test/sql/function/list/lambdas/incorrect.test
Labels: Ready To Merge

#13999 [C API] Add SQLNULL to the duckdb types
  src/include/duckdb.h
  src/include/duckdb/main/capi/header_generation/header_base.hpp.template
  src/main/capi/helper-c.cpp
  test/api/capi/capi_scalar_functions.cpp
  test/api/capi/test_capi_any_invalid_type.cpp
Labels: Ready For Review, Ready To Merge

#13983 Fix crash in the shell caused by printing blobs that failed to cast
  tools/shell/shell.c
  tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp
Labels: Ready To Merge

#13995 [Binding] Always try binding with the schema of the `UserType` first if it's set
  src/planner/binder/statement/bind_create.cpp
  test/sql/types/alias/type_with_schema.test
Labels: Changes Requested

#13982 Bugfixes
  extension/jemalloc/jemalloc/README.md
  extension/jemalloc/jemalloc/src/jemalloc.c
  extension/json/include/json_common.hpp
  extension/json/include/json_executors.hpp
  extension/json/json_extension.cpp
  extension/json/json_functions.cpp
  src/common/types/column/column_data_allocator.cpp
  src/common/types/row/tuple_data_segment.cpp
  src/execution/operator/join/physical_piecewise_merge_join.cpp
  src/include/duckdb/common/types/column/column_data_allocator.hpp
  src/include/duckdb/storage/buffer/buffer_pool.hpp
  src/optimizer/filter_pushdown.cpp
  src/optimizer/join_order/cardinality_estimator.cpp
  src/planner/binder.cpp
  src/storage/buffer/buffer_pool.cpp
  test/issues/general/test_13938.test
  test/sql/cte/materialized/annotated_and_auto_materialized.test
  test/sql/json/issues/issue13948.test
  test/sql/json/scalar/test_json_extract.test
  test/sql/json/scalar/test_json_value.test
  test/sql/optimizer/plan/test_filter_pushdown_materialized_cte.test
Labels: Ready For Review

#14024 Adds Julia support for scalar UDFs
  tools/juliapkg/src/api.jl
  tools/juliapkg/test/runtests.jl
  tools/juliapkg/test/test_scalar_udf.jl
Labels: Changes Requested

#14003 fix: make ArrowArrayWrapper::GetNextChunk() virtual
  src/include/duckdb/common/arrow/arrow_wrapper.hpp
Labels: Changes Requested

#13722 Issue #13655: MEDIAN Even Tests
  test/sql/aggregate/aggregates/test_median.test
Labels: Ready For Review

#13975 Issue #13899: AsOf Unrelated Pushdown
  src/optimizer/filter_pushdown.cpp
  src/optimizer/pushdown/pushdown_cross_product.cpp
  src/optimizer/pushdown/pushdown_inner_join.cpp
  src/optimizer/pushdown/pushdown_left_join.cpp
  src/planner/binder/tableref/plan_joinref.cpp
  test/sql/join/asof/test_asof_join_pushdown.test
Labels: Ready For Review

#14065 Fixup StagedUpload invocation via workflow_call
  .github/workflows/OnTag.yml
  .github/workflows/StagedUpload.yml
Labels: Ready For Review

#14066 Skip polars test in 3.7 due to missing PanicException
  tools/pythonpkg/tests/fast/arrow/test_polars.py
Labels: Ready For Review

#14067 Add building, testing and distributing for Python 3.13
  .github/workflows/Python.yml
Labels: Ready For Review

#14055 bump substrait
  .github/config/out_of_tree_extensions.cmake
Labels: Ready For Review

#14074 CIBW_SKIP also musllinux on Python 3.7 or Python 3.8
  .github/workflows/Python.yml
Labels: Ready For Review

#14031 [CI] Re-enable ART zero initialisation verification
  scripts/test_zero_initialize.py
  src/include/duckdb/common/bitpacking.hpp
  src/storage/compression/bitpacking.cpp
  test/sql/storage/nested/struct_of_lists_unaligned.test
Labels: Ready To Merge

#14089 Bump minimum required cmake version
  scripts/append_metadata.cmake
Labels: Ready For Review

#14097 Format CSV error messages
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/sniffer/header_detection.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
Labels: Ready To Merge
