Repository duckdb/duckdb, pull requests merged in 2024-05, with the labels that each got.

#11785 Bugfixes
  src/core_functions/aggregate/distributive/arg_min_max.cpp
  src/execution/operator/scan/physical_expression_scan.cpp
  src/execution/physical_plan/plan_distinct.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/execution/operator/scan/physical_expression_scan.hpp
  test/issues/general/test_11391.test
  test/issues/general/test_11566.test
  test/sql/aggregate/aggregates/test_state_export.test
Labels: Ready For Review

#11745 [Map] Rework interaction (entries, keys, values, extract) of NULL MAPs
  src/core_functions/scalar/map/map_entries.cpp
  src/core_functions/scalar/map/map_extract.cpp
  src/core_functions/scalar/map/map_keys_values.cpp
  test/sql/types/nested/map/test_map_entries.test
  test/sql/types/nested/map/test_map_keys.test
  test/sql/types/nested/map/test_map_subscript.test
  test/sql/types/nested/map/test_map_values.test
  test/sql/types/nested/map/test_null_map_interaction.test
Labels: Ready To Merge

#11898 Internal #11892: Interval Quarter Keyword
  src/core_functions/function_list.cpp
  src/core_functions/scalar/date/functions.json
  src/core_functions/scalar/date/to_interval.cpp
  src/include/duckdb/core_functions/scalar/date_functions.hpp
  src/parser/transform/expression/transform_interval.cpp
  test/sql/function/date/test_extract.test
  test/sql/types/interval/test_interval.test
  third_party/libpg_query/grammar/keywords/unreserved_keywords.list
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/include/parser/kwlist.hpp
  third_party/libpg_query/include/utils/datetime.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Ready To Merge

#11714 [Dev] Use strings in the SQLLogicTest `REQUIRE` calls so they are visible with `-s`
  test/sqlite/result_helper.cpp
Labels: Ready For Review

#11902 [Dev] Fix a SerializationException on CopyInfo
  extension/json/json_functions/copy_json.cpp
  src/planner/binder/statement/bind_copy.cpp
  src/planner/planner.cpp
Labels: Ready To Merge

#11806 MultiFileReader refactor
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/spatial/multi_file_list.patch
  extension/json/json_functions/read_json.cpp
  extension/json/json_functions/read_json_objects.cpp
  extension/json/json_scan.cpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_metadata.cpp
  extension/parquet/parquet_reader.cpp
  src/common/CMakeLists.txt
  src/common/enum_util.cpp
  src/common/multi_file_list.cpp
  src/common/multi_file_reader.cpp
  src/common/string_util.cpp
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/function/table/copy_csv.cpp
  src/function/table/glob.cpp
  src/function/table/read_csv.cpp
  src/function/table/read_file.cpp
  src/function/table_function.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/multi_file_list.hpp
  src/include/duckdb/common/multi_file_reader.hpp
  src/include/duckdb/common/multi_file_reader_options.hpp
  src/include/duckdb/common/string_util.hpp
  src/include/duckdb/function/table/read_csv.hpp
  src/include/duckdb/function/table_function.hpp
  src/main/relation/read_csv_relation.cpp
  src/planner/binder/tableref/bind_table_function.cpp
  src/planner/operator/logical_get.cpp
  test/sql/copy/parquet/recursive_parquet_union_by_name.test
  tools/pythonpkg/src/python_udf.cpp
Labels: Changes Requested

#11109 Prefer Final projected columns on probe side if cardinalities are similar
  .github/regression/micro_extended.csv
  benchmark/micro/update/update_with_join.benchmark
  src/common/enum_util.cpp
  src/common/enums/optimizer_type.cpp
  src/include/duckdb/common/enums/optimizer_type.hpp
  src/include/duckdb/optimizer/build_probe_side_optimizer.hpp
  src/include/duckdb/optimizer/join_order/query_graph_manager.hpp
  src/optimizer/CMakeLists.txt
  src/optimizer/build_probe_side_optimizer.cpp
  src/optimizer/join_order/join_order_optimizer.cpp
  src/optimizer/join_order/query_graph_manager.cpp
  src/optimizer/optimizer.cpp
  test/optimizer/prefer_final_projected_columns_on_probe_side.test
  test/sql/cte/materialized/test_correlated_recursive_cte_materialized.test
  test/sql/cte/test_correlated_recursive_cte.test
Labels: Ready For Review

#11006 Propagate unused columns to distinct on
  .github/regression/micro_extended.csv
  benchmark/micro/distinct/distinct_on_pushdown.benchmark
  src/optimizer/column_lifetime_analyzer.cpp
  src/optimizer/remove_unused_columns.cpp
  test/optimizer/unused_columns/distinct_on_projection_pushdown.test
  test/sql/binder/order_by_view.test
Labels: Ready For Review

#11912 Issue #11894: MIN/MAX_BY DECIMAL Casting
  src/core_functions/aggregate/distributive/arg_min_max.cpp
  test/sql/aggregate/aggregates/test_arg_min_max.test
Labels: Ready For Review

#11441 Enable purging of BufferPool pages based on time-since-last-unpinned
  src/include/duckdb/main/config.hpp
  src/include/duckdb/storage/buffer/block_handle.hpp
  src/include/duckdb/storage/buffer/buffer_pool.hpp
  src/main/database.cpp
  src/storage/buffer/block_handle.cpp
  src/storage/buffer/buffer_pool.cpp
Labels: Changes Requested

#11951 CMake: Handle git failures on invalid inputs better
  CMakeLists.txt
Labels: Ready For Review

#11967 Internal #2005: DISTINCT ORDER BY
  src/planner/binder/expression/bind_aggregate_expression.cpp
  test/sql/aggregate/aggregates/test_string_agg.test
Labels: Ready For Review

#11969 Fix overlooked function argument rename that leads to seg faults.
  src/storage/table/column_data.cpp
  test/sql/create/create_as_issue_11968.test
Labels: Ready To Merge

#11761 [Python] Keep referenced Python objects alive
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/spatial/replacement_scan.patch
  extension/json/include/json_functions.hpp
  extension/json/json_functions.cpp
  extension/parquet/parquet_extension.cpp
  src/common/enum_util.cpp
  src/function/table/arrow.cpp
  src/function/table/read_csv.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/function/function.hpp
  src/include/duckdb/function/replacement_scan.hpp
  src/include/duckdb/function/table/arrow.hpp
  src/include/duckdb/function/table_function.hpp
  src/include/duckdb/main/external_dependencies.hpp
  src/include/duckdb/main/relation.hpp
  src/include/duckdb/parser/tableref.hpp
  src/include/duckdb/parser/tableref/table_function_ref.hpp
  src/include/duckdb/planner/binder.hpp
  src/main/capi/replacement_scan-c.cpp
  src/main/relation.cpp
  src/main/relation/query_relation.cpp
  src/parser/tableref.cpp
  src/planner/binder/tableref/bind_basetableref.cpp
  src/planner/binder/tableref/bind_table_function.cpp
  src/planner/operator/logical_get.cpp
  tools/pythonpkg/src/CMakeLists.txt
  tools/pythonpkg/src/arrow/arrow_array_stream.cpp
  tools/pythonpkg/src/dataframe.cpp
  tools/pythonpkg/src/include/duckdb_python/pybind11/dataframe.hpp
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/include/duckdb_python/python_dependency.hpp
  tools/pythonpkg/src/include/duckdb_python/python_replacement_scan.hpp
  tools/pythonpkg/src/pandas/scan.cpp
  tools/pythonpkg/src/path_like.cpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/src/python_dependency.cpp
  tools/pythonpkg/src/python_replacement_scan.cpp
  tools/pythonpkg/src/python_udf.cpp
  tools/pythonpkg/tests/fast/arrow/test_5547.py
  tools/pythonpkg/tests/fast/arrow/test_arrow_recordbatchreader.py
  tools/pythonpkg/tests/fast/relational_api/test_rapi_query.py
  tools/pythonpkg/tests/fast/test_relation.py
  tools/pythonpkg/tests/fast/test_replacement_scan.py
  tools/pythonpkg/tests/fast/test_runtime_error.py
Labels: Ready For Review

#11999 Move mysql_scanner into main duckdb CI
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/mysql_scanner/shared_ptr.patch
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#12014 Issue #12009: APPROX_QUANTILE NULL List
  src/core_functions/aggregate/holistic/approximate_quantile.cpp
  test/sql/aggregate/aggregates/test_approx_quantile.test
Labels: Ready For Review

#12012 Issue #12003: TIMESTAMP Stack Overflow
  src/common/types/timestamp.cpp
  test/sql/types/timestamp/test_timestamp.test
Labels: Ready For Review

#11994 fix extension load error message grammar
  src/main/extension/extension_load.cpp
  test/sql/extensions/checked_load.test
Labels: Ready To Merge

#11987 Issue #11959: TIMESTAMPTZ >= DATE
  src/function/cast_rules.cpp
  test/sql/function/timestamp/test_icu_datetrunc.test
Labels: Ready For Review

#12013 Issue #12005: RESERVOIR_QUANTILE DECIMAL Binding
  src/core_functions/aggregate/holistic/reservoir_quantile.cpp
  test/sql/aggregate/aggregates/test_approx_quantile.test
Labels: Ready For Review

#11831 Add support for HuggingFace to httpfs
  extension/httpfs/CMakeLists.txt
  extension/httpfs/create_secret_functions.cpp
  extension/httpfs/hffs.cpp
  extension/httpfs/httpfs.cpp
  extension/httpfs/httpfs_extension.cpp
  extension/httpfs/include/create_secret_functions.hpp
  extension/httpfs/include/hffs.hpp
  extension/httpfs/include/httpfs.hpp
  scripts/generate_extensions_function.py
  src/common/file_system.cpp
  src/include/duckdb/common/file_opener.hpp
  src/include/duckdb/main/extension_entries.hpp
  src/main/client_context_file_opener.cpp
  test/sql/httpfs/hffs.test
  test/sql/httpfs/hffs.test_slow
  test/sql/secrets/create_secret_hffs.test
Labels: Ready To Merge

#11976 [Fix] lambda binding in ALTER TABLE statements
  src/include/duckdb/planner/expression_binder/alter_binder.hpp
  src/include/duckdb/planner/table_binding.hpp
  src/planner/expression_binder/alter_binder.cpp
  test/sql/function/list/lambdas/table_functions.test
Labels: Ready For Review

#11867 Rework index binding
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/vss/bound_index.patch
  .github/patches/extensions/vss/data_table_rework.patch
  src/common/types/conflict_info.cpp
  src/execution/index/CMakeLists.txt
  src/execution/index/art/art.cpp
  src/execution/index/bound_index.cpp
  src/execution/index/unbound_index.cpp
  src/execution/index/unknown_index.cpp
  src/execution/operator/schema/physical_create_art_index.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/execution/expression_executor.hpp
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/bound_index.hpp
  src/include/duckdb/execution/index/index_type.hpp
  src/include/duckdb/execution/index/unbound_index.hpp
  src/include/duckdb/execution/index/unknown_index.hpp
  src/include/duckdb/main/extension_entries.hpp
  src/include/duckdb/planner/expression_binder/index_binder.hpp
  src/include/duckdb/storage/index.hpp
  src/include/duckdb/storage/table/append_state.hpp
  src/include/duckdb/storage/table/data_table_info.hpp
  src/include/duckdb/storage/table/table_index_list.hpp
  src/include/duckdb/transaction/local_storage.hpp
  src/planner/expression_binder/index_binder.cpp
  src/storage/checkpoint_manager.cpp
  src/storage/data_table.cpp
  src/storage/index.cpp
  src/storage/local_storage.cpp
  src/storage/table/row_group_collection.cpp
  src/storage/table_index_list.cpp
  src/storage/write_ahead_log.cpp
  src/transaction/undo_buffer.cpp
  test/sql/attach/attach_checkpoint_deadlock.test_slow
  test/sqlite/sqllogic_command.cpp
  test/sqlite/sqllogic_command.hpp
  test/sqlite/sqllogic_test_runner.cpp
  test/sqlite/sqllogic_test_runner.hpp
Labels: Ready To Merge

#12011 Issue #11995: TIMESTAMP Rounding
  src/common/operator/cast_operators.cpp
  src/common/types/timestamp.cpp
  src/common/types/value.cpp
  src/include/duckdb/common/types/timestamp.hpp
  test/sql/types/timestamp/alternative_timestamp_casts.test
  test/sql/types/timestamp/test_timestamp_types.test
Labels: CI Failure

#12027 Correctly skipping errors when ignore_errors is set and we have columns with escaped values
  data/csv/test_ignore_errors.csv
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  test/sql/copy/csv/test_ignore_errors.test
Labels: Ready To Merge

#11937 Fix ordering issue with nested list type
  src/common/row_operations/row_radix_scatter.cpp
  test/sql/order/issue_11936.test
Labels: Ready To Merge

#12028 Bugfixes + large allocation hardening
  src/common/error_data.cpp
  src/common/types/string_heap.cpp
  src/common/types/vector.cpp
  src/common/types/vector_buffer.cpp
  src/core_functions/scalar/string/repeat.cpp
  src/execution/operator/projection/physical_unnest.cpp
  src/function/scalar/list/list_resize.cpp
  src/function/scalar/list/list_select.cpp
  src/include/duckdb/common/types/string_type.hpp
  src/planner/expression_binder/order_binder.cpp
  test/sql/function/list/list_resize.test
  test/sql/function/list/list_select.test
  test/sql/function/list/list_where.test
Labels: Ready For Review

#12039 Ensure HT capacity is greater than lower bound
  src/execution/radix_partitioned_hashtable.cpp
Labels: Ready To Merge

#11874 Fix materialized CTE plan issue
  .github/regression/micro_extended.csv
  benchmark/micro/cte/stacked_materialized_cte.benchmark
  extension/sqlsmith/statement_generator.cpp
  src/include/duckdb/common/insertion_order_preserving_map.hpp
  src/include/duckdb/common/serializer/deserializer.hpp
  src/include/duckdb/common/serializer/serialization_traits.hpp
  src/include/duckdb/common/serializer/serializer.hpp
  src/include/duckdb/parser/query_node.hpp
  src/include/duckdb/storage/serialization/nodes.json
  src/parser/query_node.cpp
  src/parser/transformer.cpp
  src/storage/serialization/serialize_nodes.cpp
Labels: Ready To Merge

#12035 [Fix] Return NULL for deprecated getter calls in the C API
  src/include/duckdb.h
  src/include/duckdb/main/capi/cast/generic.hpp
  src/main/capi/helper-c.cpp
  src/main/capi/result-c.cpp
  test/api/capi/test_capi.cpp
Labels: CI Failure

#12052 Issue #12041: TIMETZ Parquet Nanoseconds
  data/parquet-testing/timetz-nanos.parquet
  extension/parquet/parquet_statistics.cpp
  test/parquet/timetz_parquet.test
Labels: Ready To Merge

#12051 [Fix] Silent constraint violation error when destroying the appender in the C API
  src/include/duckdb.h
  src/main/capi/appender-c.cpp
  test/api/capi/test_capi_appender.cpp
  test/api/capi/test_capi_data_chunk.cpp
Labels: Ready For Review

#12044 Add "Tags" support to catalog entries
  src/catalog/catalog_entry/duck_table_entry.cpp
  src/catalog/catalog_entry/index_catalog_entry.cpp
  src/catalog/catalog_entry/macro_catalog_entry.cpp
  src/catalog/catalog_entry/schema_catalog_entry.cpp
  src/catalog/catalog_entry/sequence_catalog_entry.cpp
  src/catalog/catalog_entry/table_catalog_entry.cpp
  src/catalog/catalog_entry/type_catalog_entry.cpp
  src/catalog/catalog_entry/view_catalog_entry.cpp
  src/common/types/value.cpp
  src/function/table/system/duckdb_databases.cpp
  src/function/table/system/duckdb_functions.cpp
  src/function/table/system/duckdb_indexes.cpp
  src/function/table/system/duckdb_schemas.cpp
  src/function/table/system/duckdb_sequences.cpp
  src/function/table/system/duckdb_tables.cpp
  src/function/table/system/duckdb_types.cpp
  src/function/table/system/duckdb_views.cpp
  src/include/duckdb/catalog/catalog_entry.hpp
  src/include/duckdb/common/types/value.hpp
  src/include/duckdb/parser/column_definition.hpp
  src/include/duckdb/parser/parsed_data/create_info.hpp
  src/include/duckdb/storage/serialization/create_info.json
  src/include/duckdb/storage/serialization/nodes.json
  src/parser/column_definition.cpp
  src/parser/parsed_data/create_info.cpp
  src/storage/serialization/serialize_create_info.cpp
  src/storage/serialization/serialize_nodes.cpp
  test/api/adbc/test_adbc.cpp
  test/extension/loadable_extension_demo.cpp
  test/extension/test_tags.test
Labels: Ready For Review

#11935 [Python] Add pyspark hash and organize unit tests
  tools/pythonpkg/duckdb/experimental/spark/sql/functions.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_hash.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_numeric.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_string.py
Labels: Ready For Review

#12026 Test docker images: improvement and connected fixes
  CMakeLists.txt
  examples/embedded-c++/CMakeLists.txt
  examples/embedded-c/CMakeLists.txt
  examples/standalone-window/CMakeLists.txt
  extension/autocomplete/CMakeLists.txt
  extension/excel/CMakeLists.txt
  extension/fts/CMakeLists.txt
  extension/httpfs/CMakeLists.txt
  extension/icu/CMakeLists.txt
  extension/inet/CMakeLists.txt
  extension/jemalloc/CMakeLists.txt
  extension/json/CMakeLists.txt
  extension/parquet/CMakeLists.txt
  extension/sqlsmith/CMakeLists.txt
  extension/tpcds/CMakeLists.txt
  extension/tpch/CMakeLists.txt
  scripts/append_metadata.cmake
  scripts/test_docker_images.sh
  src/execution/index/art/art.cpp
  third_party/imdb/CMakeLists.txt
  third_party/libpg_query/CMakeLists.txt
  third_party/re2/CMakeLists.txt
  third_party/snowball/CMakeLists.txt
  third_party/tpce-tool/CMakeLists.txt
  tools/pythonpkg/requirements-dev.txt
Labels: Ready For Review

#12045 More fuzzer fixes
  src/core_functions/scalar/array/array_functions.cpp
  src/core_functions/scalar/debug/vector_type.cpp
  test/fuzzer/duckfuzz/array_distance.test
  test/fuzzer/duckfuzz/vector_type.test
Labels: CI Failure

#12083 CI fixes: unused variable & toolchain version
  .github/actions/build_extensions/action.yml
  src/storage/storage_manager.cpp
Labels: Ready To Merge

#12031 S3FileHandle Destructor should call `Close()` conditionally
  extension/httpfs/s3fs.cpp
Labels: Changes Requested

#12085 Fixed Parquet crash on missing dictionary
  extension/parquet/include/templated_column_reader.hpp
  test/sql/copy/parquet/broken/broken_structure.parquet
  test/sql/copy/parquet/broken_parquet.test
Labels: Ready To Merge

#12070 [Fix] Add lambda binding to the HAVING binder
  src/include/duckdb/planner/expression_binder/having_binder.hpp
  src/planner/expression_binder/having_binder.cpp
  test/sql/function/list/lambdas/lambdas_and_group_by.test
Labels: Ready For Review

#11848 Decimal/Time implicit casting + Multi-Error store in Flush
  data/csv/rejects/dr_who.csv
  src/common/enum_util.cpp
  src/common/operator/cast_operators.cpp
  src/execution/operator/csv_scanner/scanner/base_scanner.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/header_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/operator/decimal_cast_operators.hpp
  src/include/duckdb/execution/operator/csv_scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_sniffer.hpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  test/sql/copy/csv/rejects/csv_buffer_size_rejects.test
  test/sql/copy/csv/rejects/csv_incorrect_columns_amount_rejects.test
  test/sql/copy/csv/rejects/csv_rejects_flush_message.test
  test/sql/copy/csv/rejects/csv_rejects_read.test
Labels: Ready For Review

#12088 [Testing Infra Fix] Make input data chunks immutable in the vector verification tests
  src/execution/operator/helper/physical_verify_vector.cpp
  test/sql/join/test_nested_keys.test
  test/sql/storage/compression/string/blob.test
  test/sql/storage/concurrent_table_insertion.test_slow
  test/sql/subquery/complex/nested_correlated_list.test_slow
Labels: Ready To Merge

#12094 Change ExtensionOptimizer input
  .github/patches/extensions/mysql_scanner/z_optimizer.patch
  .github/patches/extensions/postgres_scanner/z_optimizer.patch
  .github/patches/extensions/spatial/z_optimizer.patch
  .github/patches/extensions/vss/z_optimizer.patch
  scripts/apply_extension_patches.py
  src/include/duckdb/optimizer/optimizer_extension.hpp
  src/optimizer/optimizer.cpp
  test/extension/loadable_extension_optimizer_demo.cpp
Labels: Ready To Merge

#11493 [Dev] Collect CatalogEntry Dependencies during Binding
  src/catalog/CMakeLists.txt
  src/catalog/catalog_entry/duck_schema_entry.cpp
  src/catalog/catalog_entry/duck_table_entry.cpp
  src/catalog/catalog_entry/index_catalog_entry.cpp
  src/catalog/catalog_entry/macro_catalog_entry.cpp
  src/catalog/catalog_entry/sequence_catalog_entry.cpp
  src/catalog/catalog_entry/table_catalog_entry.cpp
  src/catalog/catalog_entry/type_catalog_entry.cpp
  src/catalog/catalog_entry/view_catalog_entry.cpp
  src/catalog/catalog_entry_retriever.cpp
  src/catalog/dependency_manager.cpp
  src/execution/operator/persistent/physical_export.cpp
  src/include/duckdb/catalog/catalog_entry/function_entry.hpp
  src/include/duckdb/catalog/catalog_entry_retriever.hpp
  src/include/duckdb/catalog/dependency_list.hpp
  src/include/duckdb/catalog/standard_entry.hpp
  src/include/duckdb/execution/operator/persistent/physical_export.hpp
  src/include/duckdb/parser/parsed_data/comment_on_column_info.hpp
  src/include/duckdb/parser/parsed_data/create_info.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/expression_binder.hpp
  src/parser/parsed_data/comment_on_column_info.cpp
  src/parser/parsed_data/create_info.cpp
  src/planner/binder.cpp
  src/planner/binder/expression/bind_cast_expression.cpp
  src/planner/binder/expression/bind_function_expression.cpp
  src/planner/binder/statement/bind_copy_database.cpp
  src/planner/binder/statement/bind_create.cpp
  src/planner/binder/statement/bind_create_table.cpp
  src/planner/binder/statement/bind_export.cpp
  src/planner/binder/statement/bind_simple.cpp
  src/planner/binder/tableref/bind_basetableref.cpp
  src/planner/binder/tableref/bind_table_function.cpp
  src/planner/expression/bound_expression.cpp
  src/planner/expression_binder.cpp
  test/fuzzer/pedro/view_not_rebound_error.test
  test/sql/aggregate/qualify/test_qualify_view.test
  test/sql/alter/rename_table/test_rename_table_with_dependency_check.test
  test/sql/catalog/comment_on_dependencies.test
  test/sql/catalog/dependencies/test_alter_dependency_ownership.test
  test/sql/catalog/function/test_recursive_macro.test
  test/sql/copy/csv/batched_write/batch_csv_mixed_batches.test_slow
  test/sql/copy/parquet/batched_write/parquet_write_mixed_batches.test_slow
  test/sql/copy_database/copy_database_different_types.test
  test/sql/storage/catalog/test_view_explicit_aliases.test
  test/sql/storage/catalog/test_view_storage.test
  test/sql/storage/parallel/batch_insert_mix_batches.test_slow
  test/sql/storage/parallel/batch_insert_small_batches.test_slow
  test/sql/storage/wal/wal_view_explicit_aliases.test
  test/sql/storage/wal/wal_view_storage.test
  tools/pythonpkg/tests/fast/relational_api/test_rapi_query.py
Labels: Ready For Review

#12077 Internal #2040: ICU Collation Serialisation
  extension/icu/icu_extension.cpp
  src/include/duckdb/main/extension_entries.hpp
  src/main/extension/extension_util.cpp
Labels: Ready For Review

#12081 Add support for type modifiers on extension types
  src/catalog/catalog.cpp
  src/catalog/catalog_entry/type_catalog_entry.cpp
  src/common/box_renderer.cpp
  src/common/extra_type_info.cpp
  src/common/types.cpp
  src/include/duckdb/catalog/catalog.hpp
  src/include/duckdb/catalog/catalog_entry/type_catalog_entry.hpp
  src/include/duckdb/common/extra_type_info.hpp
  src/include/duckdb/common/types.hpp
  src/include/duckdb/main/extension_util.hpp
  src/include/duckdb/parser/parsed_data/create_type_info.hpp
  src/include/duckdb/parser/transformer.hpp
  src/include/duckdb/storage/serialization/types.json
  src/main/extension/extension_util.cpp
  src/parser/parsed_data/create_type_info.cpp
  src/parser/transform/helpers/transform_typename.cpp
  src/planner/binder/statement/bind_create.cpp
  src/planner/binder/tableref/bind_pivot.cpp
  src/storage/serialization/serialize_types.cpp
  test/extension/loadable_extension_demo.cpp
  test/extension/test_custom_type_modifier.test
Labels: Ready To Merge

#12107 Bump extensions
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/aws/0001-update-tests.patch
  .github/patches/extensions/aws/shared_ptr.patch
  .github/patches/extensions/azure/shared_ptr.patch
  .github/patches/extensions/iceberg/iceberg_yyjson.patch
  .github/patches/extensions/mysql_scanner/shared_ptr.patch
  .github/patches/extensions/mysql_scanner/z_optimizer.patch
  .github/patches/extensions/postgres_scanner/shared_ptr.patch
  .github/patches/extensions/postgres_scanner/z_optimizer.patch
  .github/patches/extensions/sqlite_scanner/binder_update.patch
Labels: Ready For Review

#12099 Change type of columns from sniff_csv to list of structs
  data/csv/headers/escaped_quote.csv
  data/csv/headers/unescaped_quote.csv
  src/function/table/sniff_csv.cpp
  test/sql/copy/csv/test_csv_remote.test
  test/sql/copy/csv/test_headers_12089.test
  test/sql/copy/csv/test_sniff_csv.test
  test/sql/copy/csv/test_sniff_csv_options.test
Labels: Ready For Review

#12131 Internal #2078: Nested Nulls First
  src/common/vector_operations/is_distinct_from.cpp
Labels: Ready For Review

#12122 Bump extensions, part 2
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/arrow/shared_ptr.patch
  .github/patches/extensions/spatial/multi_file_list.patch
  .github/patches/extensions/spatial/replacement_scan.patch
  .github/patches/extensions/spatial/z_optimizer.patch
  .github/patches/extensions/substrait/shared_ptr.patch
  .github/patches/extensions/vss/bound_index.patch
  .github/patches/extensions/vss/no_verification.patch
  .github/patches/extensions/vss/z_optimizer.patch
Labels: Ready To Merge

#12130 Internal #2081: Window Distinct Reset
  src/execution/window_segment_tree.cpp
Labels: Ready For Review

#12153 Move pyodide from repository_dispatch to NightlyTests.yml
  .github/workflows/NightlyTests.yml
  .github/workflows/Pyodide.yml
Labels: Ready To Merge

#12033 Allow quotes to be escaped in JSON path
  extension/json/json_common.cpp
  test/sql/json/scalar/test_json_extract.test
Labels: Needs Documentation, Changes Requested

#12158 Higher memory limit for test
  test/sql/join/external/simple_external_join.test_coverage
Labels: Ready To Merge

#12144 Set max vector size to 128GB instead of 4GB
  src/common/types/vector.cpp
  src/include/duckdb/common/constants.hpp
  test/sql/function/list/list_resize.test
Labels: Ready To Merge

#12162 Fixing unchecked malloc() calls in Parser and elsewhere
  src/common/allocator.cpp
  src/common/serializer/memory_stream.cpp
  third_party/libpg_query/pg_functions.cpp
Labels: Ready To Merge

#12097 Modify the pandas analyzer code to always respect the sample size
  scripts/regression_test_python.py
  tools/pythonpkg/src/include/duckdb_python/pandas/pandas_analyzer.hpp
  tools/pythonpkg/src/pandas/analyzer.cpp
  tools/pythonpkg/tests/fast/pandas/test_pandas_object.py
Labels: CI Failure

#12152 Allow community extensions: add setting and keys
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/extension_helper.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/extension/extension_helper.cpp
  src/main/extension/extension_load.cpp
  src/main/settings/settings.cpp
  test/api/test_reset.cpp
Labels: Ready For Review

#12109 Fixing parquet dictionary / data page offset bug
  extension/parquet/column_writer.cpp
  extension/parquet/parquet_writer.cpp
Labels: Ready To Merge

#12165 small fix to extension origin checks and direct installing over http
  scripts/run_extension_medata_tests.sh
  src/main/extension/extension_install.cpp
  test/extension/update_extensions_ci.test
Labels: Ready To Merge

#12168 Remove UnsafeNumericCast in create_sort_key
  src/core_functions/scalar/blob/create_sort_key.cpp
  test/fuzzer/duckfuzz/create_sort_key_strings.test
Labels: Ready To Merge

#12175 Move community keys to proper values
  src/main/extension/extension_helper.cpp
Labels: Ready To Merge

#12173 Internal #2095: Streaming Window Structs
  src/execution/operator/aggregate/physical_streaming_window.cpp
  src/execution/physical_plan/plan_window.cpp
  src/include/duckdb/execution/operator/aggregate/physical_streaming_window.hpp
  test/sql/window/test_streaming_window.test
Labels: Ready To Merge

#12167 [CSV Reader] Bug-fix related to skip parameter over vector size in the sniffer
  src/execution/operator/csv_scanner/scanner/base_scanner.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/include/duckdb/execution/operator/csv_scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_sniffer.hpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  test/sql/copy/csv/test_skip.test
Labels: Ready To Merge

#12056 Expression rewrite filter pushdown for dates
  src/function/scalar/operators/add.cpp
  src/include/duckdb/common/operator/add.hpp
  src/include/duckdb/optimizer/rule/list.hpp
  src/include/duckdb/optimizer/rule/timestamp_comparison.hpp
  src/optimizer/optimizer.cpp
  src/optimizer/rule/CMakeLists.txt
  src/optimizer/rule/timestamp_comparison.cpp
  test/optimizer/pushdown/timestamp_to_date_pushdown.test
Labels: Changes Requested

#12169 [Python] Throw if replacement scan is attempted on cross-connection DuckDBPyRelation
  src/include/duckdb/main/client_context_wrapper.hpp
  src/main/client_context_wrapper.cpp
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/src/python_replacement_scan.cpp
  tools/pythonpkg/tests/fast/test_replacement_scan.py
Labels: Ready To Merge

#12111 [Fix] Correctly allocate the ARRAY target child vector in a MAP function
  src/common/types/vector.cpp
  src/include/duckdb/common/types/vector.hpp
  test/fuzzer/duckfuzz/array_group_by_sample.test
  test/sql/function/array/array_and_map.test
Labels: Ready For Review

#12189 Fix move constants optimization
  src/optimizer/rule/move_constants.cpp
  test/optimizer/issue_12181.test
Labels: Ready To Merge

#12194 Fix cmake install for shared_ptr headers
  scripts/test_docker_images.sh
  src/include/duckdb/common/enable_shared_from_this_ipp.hpp
  src/include/duckdb/common/shared_ptr.hpp
  src/include/duckdb/common/shared_ptr_ipp.hpp
  src/include/duckdb/common/weak_ptr_ipp.hpp
Labels: Ready For Review

#12198 Install .ipp files in addition to the usual .hpp files
  src/CMakeLists.txt
Labels: Ready To Merge

#12200 Removed three reinterpret casts and some rewriting
  src/parser/transform/expression/transform_array_access.cpp
  src/parser/transform/expression/transform_multi_assign_reference.cpp
  test/sql/copy/csv/rejects/csv_buffer_size_rejects.test
  test/sql/types/struct/update_empty_row.test
  test/sql/update/test_multiple_assignment.test
Labels: Ready To Merge

#12207 Set a default value to the `connection` param in stubs
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/scripts/generate_connection_wrapper_stubs.py
Labels: Ready To Merge

#11101 Begin Profiling Rework to move towards Modularity
  scripts/plan_cost_runner.py
  src/common/enum_util.cpp
  src/common/tree_renderer.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/main/profiling_info.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/include/duckdb/main/settings.hpp
  src/main/CMakeLists.txt
  src/main/config.cpp
  src/main/profiling_info.cpp
  src/main/query_profiler.cpp
  src/main/settings/settings.cpp
  src/parallel/thread_context.cpp
  test/api/test_reset.cpp
  test/sql/explain/test_explain_analyze.test
  test/sql/pragma/not_a_valid.json
  test/sql/pragma/test_custom_profiling_settings.test
Labels: Ready For Review

#12208 [Python] Fix replacement scans incorrectly finding duckdb connection method objects
  tools/pythonpkg/scripts/cache_data.json
  tools/pythonpkg/scripts/imports.py
  tools/pythonpkg/src/include/duckdb_python/import_cache/modules/types_module.hpp
  tools/pythonpkg/src/python_replacement_scan.cpp
  tools/pythonpkg/tests/fast/api/test_duckdb_connection.py
Labels: Ready To Merge

#11474 Remove BLOCK_ALLOC_SIZE from the column segment files
  src/include/duckdb/storage/block_manager.hpp
  src/include/duckdb/storage/buffer_manager.hpp
  src/include/duckdb/storage/standard_buffer_manager.hpp
  src/include/duckdb/storage/table/column_segment.hpp
  src/storage/buffer_manager.cpp
  src/storage/standard_buffer_manager.cpp
  src/storage/table/column_segment.cpp
Labels: Ready For Review

#12236 Python: Avoid packaging for both 3.7 on OSX and MacOS 11
  .github/workflows/Python.yml
Labels: Ready To Merge

#12238 Issue #12215: AsOf Predicate Pushdown
  src/include/duckdb/planner/operator/logical_comparison_join.hpp
  src/optimizer/pushdown/pushdown_cross_product.cpp
  src/planner/binder/query_node/plan_subquery.cpp
  src/planner/binder/tableref/plan_joinref.cpp
  test/sql/join/asof/test_asof_join.test
Labels: Ready For Review

#12233 [Python] Add check for 'params' to `table_function`
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/relational_api/test_table_function.py
Labels: Ready To Merge

#12123 Move excel extension out of tree
  .github/config/bundled_extensions.cmake
  .github/config/in_tree_extensions.cmake
  .github/config/out_of_tree_extensions.cmake
  .github/workflows/Main.yml
  .github/workflows/NightlyTests.yml
  Makefile
  extension/excel/CMakeLists.txt
  extension/excel/excel_config.py
  extension/excel/excel_extension.cpp
  extension/excel/include/excel_extension.hpp
  extension/excel/numformat/CMakeLists.txt
  extension/excel/numformat/LICENSE
  extension/excel/numformat/include/nf_calendar.h
  extension/excel/numformat/include/nf_localedata.h
  extension/excel/numformat/include/nf_zformat.h
  extension/excel/numformat/nf_calendar.cpp
  extension/excel/numformat/nf_localedata.cpp
  extension/excel/numformat/nf_zformat.cpp
  src/main/extension/extension_helper.cpp
  test/sql/excel/test_excel_numformat.test
Labels: Ready To Merge

#12245 Fixup staged uploads /3
  .github/workflows/InvokeCI.yml
  .github/workflows/Pyodide.yml
  .github/workflows/StagedUpload.yml
  tools/pythonpkg/tests/fast/test_expression.py
  tools/pythonpkg/tests/fast/test_relation.py
Labels: Ready For Review

#12253 Use --always option of git describe for extension tags.
  CMakeLists.txt
Labels: Ready To Merge

#12266 add missing virtual destructor
  src/common/multi_file_reader.cpp
  src/include/duckdb/common/multi_file_reader.hpp
Labels: Ready To Merge

#12263 Fix Mark Index in the Bound Join Ref
  src/include/duckdb/planner/tableref/bound_joinref.hpp
  src/planner/binder/tableref/bind_joinref.cpp
  src/planner/binder/tableref/plan_joinref.cpp
Labels: Ready To Merge

#12271 Issue #12252: APPROX_QUANTILE Array Argument
  src/core_functions/aggregate/holistic/approximate_quantile.cpp
  src/core_functions/aggregate/holistic/quantile.cpp
  test/sql/aggregate/aggregates/test_approx_quantile.test
  test/sql/aggregate/aggregates/test_quantile_disc_list.test
Labels: Ready For Review

#12267 Add descriptions for vss and delta extensions
  src/main/extension/extension_helper.cpp
Labels: Ready For Review

#12273 Fix for CI Regression Failure
  scripts/plan_cost_runner.py
  src/main/query_profiler.cpp
Labels: Ready To Merge

#12185 Disable `JEMALLOC_RETAIN`
  extension/jemalloc/jemalloc/CMakeLists.txt
  extension/jemalloc/jemalloc/include/jemalloc/internal/jemalloc_internal_defs.h
  extension/jemalloc/jemalloc_config.py
  extension/jemalloc/jemalloc_extension.cpp
Labels: Ready For Review

#11903 Enforce compression extensions for CSV Files
  src/planner/binder/statement/bind_copy.cpp
  test/sql/copy/csv/test_partition_compression.test
Labels: Ready For Review

#12283 [Fix] Block size nightly run
  src/storage/standard_buffer_manager.cpp
Labels: Ready For Review, Ready To Merge

#12280 add expected errors to test/sql/copy/per_thread_output.test
  test/sql/copy/per_thread_output.test
Labels: Ready To Merge

#12295 Issue #12287: ICU Strptime Lists
  extension/icu/icu-strptime.cpp
  test/sql/function/timestamp/test_icu_strptime.test
Labels: Ready For Review

#12250 Issue #12171: Streaming Window FILTER
  src/execution/operator/aggregate/physical_streaming_window.cpp
  src/execution/physical_plan/plan_window.cpp
  test/sql/window/test_streaming_window.test
Labels: Ready For Review

#12315 Use iterator buffer position when storing buffer handles
  src/execution/operator/csv_scanner/scanner/scanner_boundary.cpp
  test/sql/copy/csv/test_12314.test_slow
Labels: Ready To Merge

#12319 [Fix] Only read file size if file handle still exists
  src/storage/standard_buffer_manager.cpp
Labels: Ready To Merge

#12305 Additional check for overlapping CTE names
  src/planner/binder/tableref/bind_basetableref.cpp
  test/sql/cte/materialized/test_cte_in_cte_materialized.test
Labels: Ready For Review

#12164 [Dev] `STANDARD_VECTOR_SIZE` and `BLOCK_ALLOC_SIZE` can now be set through the Makefile
  CMakeLists.txt
  Makefile
  scripts/test_block_sizes.py
  scripts/test_vector_sizes.py
  src/include/duckdb/storage/storage_info.hpp
Labels: Ready For Review

#11866 [Upsert] Fix issue with lambdas in `DO UPDATE SET` expressions
  src/include/duckdb/parser/expression/function_expression.hpp
  src/include/duckdb/planner/expression_binder.hpp
  src/parser/expression/function_expression.cpp
  src/planner/binder/expression/bind_columnref_expression.cpp
  src/planner/binder/expression/bind_function_expression.cpp
  src/planner/binder/expression/bind_macro_expression.cpp
  src/planner/binder/statement/bind_insert.cpp
  src/planner/expression_binder.cpp
  test/sql/upsert/postgres/composite_key.test
  test/sql/upsert/upsert_lambda.test
Labels: Ready For Review

#11706 [Python] Fix scoping issue for `pandas_analyze_sample` setting
  tools/pythonpkg/src/include/duckdb_python/pandas/pandas_analyzer.hpp
  tools/pythonpkg/src/numpy/numpy_bind.cpp
  tools/pythonpkg/src/pandas/bind.cpp
  tools/pythonpkg/tests/fast/pandas/test_df_analyze.py
Labels: Ready For Review

#12278 Allow run_fuzzer to reduce multi statements.
  scripts/reduce_sql.py
  scripts/run_fuzzer.py
  scripts/run_sqlancer.py
Labels: Ready To Merge
