Repository duckdb/duckdb, pull requests merged in 2024-11, with the labels that each got.

#14661 Force error on CSV Sniffer Failure
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
Labels: Ready To Merge

#14573 feature(spark): add hex and unhex functions
  tools/pythonpkg/duckdb/experimental/spark/sql/functions.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_hex.py
Labels: Merge Conflict

#14662 Support `SELECT * LIKE '%col%'` syntax
  src/include/duckdb/common/exception/parser_exception.hpp
  src/include/duckdb/function/aggregate_function.hpp
  src/planner/binder/expression/bind_star_expression.cpp
  test/sql/parser/star_expression.test
  test/sql/parser/test_columns_lists.test
  test/sql/projection/select_star_like.test
Labels: Needs Documentation

#14688 Add fallback for thread count if jemalloc cannot identify
  extension/jemalloc/include/malloc_ncpus.h
  extension/jemalloc/jemalloc/README.md
  extension/jemalloc/jemalloc/src/jemalloc.c
  extension/jemalloc/jemalloc_extension.cpp
Labels: Ready For Review

#14464 csv: parse escape character in unquoted fields
  data/csv/unquoted_escape/basic.tsv
  data/csv/unquoted_escape/human_eval.csv
  data/csv/unquoted_escape/human_eval.tsv
  data/csv/unquoted_escape/identical.csv
  data/csv/unquoted_escape/mixed.csv
  data/csv/unquoted_escape/plain.csv
  src/common/enum_util.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/function/table/copy_csv.cpp
  src/function/table/read_csv.cpp
  src/include/duckdb/execution/operator/csv_scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_reader_options.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state_machine.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state_machine_cache.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine_options.hpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  src/include/duckdb/storage/serialization/nodes.json
  src/storage/serialization/serialize_nodes.cpp
  test/sql/copy/csv/unquoted_escape/32k_rows.test
  test/sql/copy/csv/unquoted_escape/basic.test
  test/sql/copy/csv/unquoted_escape/human_eval.test
  test/sql/copy/csv/unquoted_escape/identical.test
  test/sql/copy/csv/unquoted_escape/mixed.test
Labels: Ready For Review

#14524 copy to operator still write schema for empty rows
  src/execution/operator/persistent/physical_copy_to_file.cpp
  test/sql/copy/parquet/writer/test_parquet_write.test
Labels: Changes Requested

#14757 [Python] Add support for `Expression` to `values` to create a ValueRelation
  src/include/duckdb/main/connection.hpp
  src/include/duckdb/main/relation.hpp
  src/include/duckdb/main/relation/value_relation.hpp
  src/main/connection.cpp
  src/main/relation.cpp
  src/main/relation/value_relation.cpp
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb_python.cpp
  tools/pythonpkg/scripts/connection_methods.json
  tools/pythonpkg/scripts/generate_connection_methods.py
  tools/pythonpkg/scripts/generate_connection_wrapper_methods.py
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/test_relation.py
Labels: Ready For Review

#14660 Initialize the grouping sets when there is a group by all to enable filter pushdown
  src/planner/binder/query_node/bind_select_node.cpp
  test/optimizer/pushdown/test_pushdown_cte_group_by_all.test
  test/sql/aggregate/group/group_by_all_having.test
Labels: Ready To Merge

#14620 [PySpark] Add approxCountDistinct, add_months, and various array functions
  tools/pythonpkg/duckdb/experimental/spark/sql/functions.py
  tools/pythonpkg/tests/fast/spark/test_spark_arrow_table.py
  tools/pythonpkg/tests/fast/spark/test_spark_column.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_array.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_date.py
  tools/pythonpkg/tests/spark_namespace/sql/dataframe.py
Labels: Ready For Review

#14150 [Catalog] Fix issue related to uncaught problems during a COMMIT
  src/catalog/catalog_entry/duck_schema_entry.cpp
  src/catalog/catalog_entry/schema_catalog_entry.cpp
  src/catalog/catalog_set.cpp
  src/catalog/dependency_manager.cpp
  src/catalog/duck_catalog.cpp
  src/include/duckdb/catalog/catalog_entry.hpp
  src/include/duckdb/catalog/catalog_entry/duck_schema_entry.hpp
  src/include/duckdb/catalog/catalog_entry/schema_catalog_entry.hpp
  src/include/duckdb/catalog/catalog_set.hpp
  src/include/duckdb/catalog/dependency_manager.hpp
  src/include/duckdb/catalog/duck_catalog.hpp
  src/transaction/commit_state.cpp
  test/sql/catalog/dependencies/test_concurrent_alter.test
  test/sql/transactions/test_alter_sequence_ownership_conflict.test
  test/sql/transactions/test_alter_sequence_ownership_conflict2.test
  test/sql/transactions/test_alter_sequence_ownership_conflict3.test
  test/sql/transactions/test_create_drop_conflict.test
  test/sql/transactions/test_create_drop_conflict_variation1.test
  test/sql/transactions/test_create_drop_conflict_variation2.test
Labels: Ready For Review

#14293 [Upsert] Support non-distinct values in the inserted data
  src/common/types/conflict_manager.cpp
  src/execution/operator/persistent/physical_insert.cpp
  src/include/duckdb/common/types/conflict_manager.hpp
  src/include/duckdb/execution/operator/persistent/physical_insert.hpp
  src/storage/data_table.cpp
  src/storage/table_index_list.cpp
  test/sql/upsert/upsert_basic.test
  test/sql/upsert/upsert_conflict_in_different_chunk.test
  test/sql/upsert/upsert_global_mixed_conflicts.test
  test/sql/upsert/upsert_inner_conflict_do_nothing.test
  test/sql/upsert/upsert_transaction.test
Labels: Ready For Review

#14693 Fix issue copying a TABLE that references a SEQUENCE
  src/catalog/catalog.cpp
  src/execution/physical_plan_generator.cpp
  src/function/function_binder.cpp
  src/function/scalar/sequence/nextval.cpp
  src/function/scalar_function.cpp
  src/include/duckdb/function/function_binder.hpp
  src/include/duckdb/function/scalar_function.hpp
  src/include/duckdb/planner/binder.hpp
  src/planner/binder/expression/bind_aggregate_expression.cpp
  src/planner/binder/expression/bind_function_expression.cpp
  src/planner/binder/query_node/bind_select_node.cpp
  src/planner/binder/query_node/plan_subquery.cpp
  src/planner/binder/statement/bind_create_table.cpp
  src/planner/binder/statement/bind_insert.cpp
  src/planner/binder/statement/bind_pragma.cpp
  src/planner/binder/statement/bind_update.cpp
  src/planner/binder/tableref/bind_table_function.cpp
  test/fuzzer/pedro/temp_sequence_reconnect.test
  test/sql/attach/attach_sequence.test
  test/sql/copy_database/copy_table_with_sequence.test
Labels: Ready For Review

#14811 LTO CMake setting was not working anymore on MacOS, fixing that
  CMakeLists.txt
Labels: Ready To Merge

#14820 Add syntax highlighting support to the DuckBox query result
  src/common/box_renderer.cpp
  src/include/duckdb/common/box_renderer.hpp
  tools/shell/CMakeLists.txt
  tools/shell/include/shell_highlight.hpp
  tools/shell/include/shell_state.hpp
  tools/shell/shell.cpp
  tools/shell/shell_highlight.cpp
  tools/shell/tests/test_highlighting.py
  tools/shell/tests/test_shell_basics.py
  tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp
Labels: Needs Documentation

#14616 Avoiding unnecessary rebinding
  src/include/duckdb/main/client_context.hpp
  src/include/duckdb/main/connection.hpp
  src/include/duckdb/main/prepared_statement.hpp
  src/include/duckdb/storage/serialization/statement.json
  src/include/duckdb/verification/copied_statement_verifier.hpp
  src/include/duckdb/verification/deserialized_statement_verifier.hpp
  src/include/duckdb/verification/external_statement_verifier.hpp
  src/include/duckdb/verification/fetch_row_verifier.hpp
  src/include/duckdb/verification/no_operator_caching_verifier.hpp
  src/include/duckdb/verification/parsed_statement_verifier.hpp
  src/include/duckdb/verification/prepared_statement_verifier.hpp
  src/include/duckdb/verification/statement_verifier.hpp
  src/include/duckdb/verification/unoptimized_statement_verifier.hpp
  src/main/client_context.cpp
  src/main/client_verify.cpp
  src/main/connection.cpp
  src/storage/serialization/serialize_statement.cpp
  src/verification/copied_statement_verifier.cpp
  src/verification/deserialized_statement_verifier.cpp
  src/verification/external_statement_verifier.cpp
  src/verification/fetch_row_verifier.cpp
  src/verification/no_operator_caching_verifier.cpp
  src/verification/parsed_statement_verifier.cpp
  src/verification/prepared_statement_verifier.cpp
  src/verification/statement_verifier.cpp
  src/verification/unoptimized_statement_verifier.cpp
  test/api/CMakeLists.txt
  test/api/test_pending_with_parameters.cpp
  test/api/test_prepared_api.cpp
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/api/test_3324.py
  tools/pythonpkg/tests/fast/api/test_duckdb_connection.py
  tools/pythonpkg/tests/fast/test_runtime_error.py
  tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp
Labels: Ready To Merge

#14775 Internal #3263: Window Distinct Deadlock
  src/execution/window_segment_tree.cpp
  test/sql/window/test_window_distinct.test_slow
Labels: Ready For Review

#14840 Issue #14737: DISTINCT ORDER Dependency
  src/planner/binder/expression/bind_aggregate_expression.cpp
  test/sql/function/list/list_sort.test
Labels: Ready For Review

#14860 Issue #11557: DECIMAL Downcast Rounding
  src/function/cast/decimal_cast.cpp
  test/sql/types/decimal/test_decimal.test
Labels: Ready For Review

#14809 Use `LogicalTypeId::Unknown` instead of `LogicalTypeId::SQLNULL` for macro binding
  src/common/types.cpp
  src/common/types/column/column_data_collection.cpp
  src/function/function_binder.cpp
  src/function/scalar/list/list_zip.cpp
  src/include/duckdb/common/types.hpp
  src/planner/binder/expression/bind_macro_expression.cpp
  src/planner/binder/query_node/bind_table_macro_node.cpp
Labels: Ready To Merge

#14733 Support default values when appending data chunks
  extension/tpcds/dsdgen/append_info-c.cpp
  src/include/duckdb.h
  src/include/duckdb/execution/expression_executor.hpp
  src/include/duckdb/main/appender.hpp
  src/include/duckdb/main/capi/header_generation/functions/appender.json
  src/include/duckdb/main/client_context.hpp
  src/include/duckdb/storage/data_table.hpp
  src/main/appender.cpp
  src/main/capi/appender-c.cpp
  src/main/client_context.cpp
  src/storage/data_table.cpp
  test/api/capi/test_capi_appender.cpp
  test/appender/test_appender.cpp
Labels: Ready For Review

#14758 [C API] More tests and nits
  src/include/duckdb.h
  src/include/duckdb/common/types/timestamp.hpp
  src/include/duckdb/main/capi/header_generation/functions/prepared_statements.json
  src/include/duckdb/main/capi/header_generation/functions/value_interface.json
  src/include/duckdb/main/capi/header_generation/header_base.hpp.template
  src/main/capi/duckdb_value-c.cpp
  test/api/capi/test_capi_complex_types.cpp
  test/api/capi/test_capi_prepared.cpp
  test/api/capi/test_capi_values.cpp
Labels: Ready To Merge

#14891 Issue #14885: DATEPART Cache Bounds
  src/include/duckdb/common/types/date_lookup_cache.hpp
  test/sql/function/date/test_date_part.test
Labels: Ready To Merge

#14893 Fix arrow table filters
  tools/pythonpkg/src/arrow/arrow_array_stream.cpp
  tools/pythonpkg/tests/fast/arrow/test_filter_pushdown.py
Labels: Ready To Merge

#13149 [Python] Fix various issues uncovered by #12959
  src/include/duckdb/main/relation.hpp
  src/include/duckdb/main/relation/subquery_relation.hpp
  src/main/relation.cpp
  src/main/relation/join_relation.cpp
  src/main/relation/subquery_relation.cpp
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
  tools/pythonpkg/duckdb/experimental/spark/sql/functions.py
  tools/pythonpkg/src/include/duckdb_python/expression/pyexpression.hpp
  tools/pythonpkg/src/pyexpression.cpp
  tools/pythonpkg/src/pyexpression/initialize.cpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/tests/fast/api/test_join.py
  tools/pythonpkg/tests/fast/spark/test_spark_dataframe_sort.py
  tools/pythonpkg/tests/fast/spark/test_spark_join.py
Labels: Ready For Review

#14897 Remove some Snappy definitions
  third_party/snappy/snappy-stubs-internal.h
Labels: Ready To Merge

#14880 [C API] Implement AddColumn and ClearColumns for the Appender
  src/include/duckdb.h
  src/include/duckdb/main/capi/extension_api.hpp
  src/include/duckdb/main/capi/header_generation/apis/v0/dev/dev.json
  src/include/duckdb/main/capi/header_generation/functions/appender.json
  src/include/duckdb_extension.h
  src/main/capi/appender-c.cpp
  test/api/capi/test_capi_appender.cpp
  test/appender/test_appender.cpp
Labels: Ready To Merge

#14853 Add `struct_concat`
  src/function/function_list.cpp
  src/function/scalar/struct/CMakeLists.txt
  src/function/scalar/struct/functions.json
  src/function/scalar/struct/struct_concat.cpp
  src/include/duckdb/function/scalar/struct_functions.hpp
  test/sql/types/struct/struct_concat.test
Labels: Ready To Merge

#14818 Improve timestamp functionality
  extension/core_functions/scalar/date/current.cpp
  extension/core_functions/scalar/date/date_part.cpp
  extension/parquet/parquet_statistics.cpp
  src/common/allocator.cpp
  src/common/operator/cast_operators.cpp
  src/common/operator/string_cast.cpp
  src/common/types/timestamp.cpp
  src/common/types/value.cpp
  src/common/types/vector.cpp
  src/function/scalar/operator/add.cpp
  src/function/table/system/test_all_types.cpp
  src/include/duckdb/common/operator/cast_operators.hpp
  src/include/duckdb/common/types/timestamp.hpp
  src/include/duckdb/common/types/value.hpp
  src/main/capi/prepared-c.cpp
  tools/pythonpkg/src/native/python_objects.cpp
Labels: Ready For Review

#14892 C API: Add Value Relation constructor with RelationContextWrapper and ParsedExpression as argument
  src/include/duckdb/main/relation/value_relation.hpp
  src/main/relation/value_relation.cpp
Labels: Changes Requested

#14908 Issue #14734: Wrap Parquet TIMETZ
  data/parquet-testing/negative-timetz.parquet
  extension/parquet/parquet_timestamp.cpp
  test/parquet/timetz_parquet.test
Labels: Ready To Merge

#14959 Fix casting long to int via explicit cast in parquet
  extension/parquet/column_writer.cpp
Labels: Ready For Review

#14958 Fix script/regression/benchmark.py rework
  scripts/regression/benchmark.py
  scripts/regression/test_runner.py
Labels: Ready For Review

#14947 Improve code generation of storage and serialization version infos
  Makefile
  scripts/generate_serialization.py
  scripts/generate_storage_info.py
  src/storage/storage_info.cpp
  src/storage/version_map.json
Labels: Ready For Review

#14974 Disable row group size bytes default initialization
  extension/parquet/parquet_extension.cpp
Labels: Ready To Merge

#14998 Run containerized builds requiring deprecatd ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION only on main/feature
  .github/workflows/Android.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/NightlyTests.yml
  .github/workflows/Python.yml
Labels: Ready For Review

#14987 Rely on extension-ci-tools workflow to build linux_amd64_gcc4 extensions
  .github/helper_makefile/build_all_extensions
  .github/workflows/Python.yml
Labels: Ready For Review

#15007 Internal #861: Window Code Refactoring
  src/execution/CMakeLists.txt
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/window_executor.cpp
  src/execution/window_segment_tree.cpp
  src/function/CMakeLists.txt
  src/function/window/CMakeLists.txt
  src/function/window/window_aggregate_function.cpp
  src/function/window/window_aggregate_states.cpp
  src/function/window/window_aggregator.cpp
  src/function/window/window_boundaries_state.cpp
  src/function/window/window_collection.cpp
  src/function/window/window_constant_aggregator.cpp
  src/function/window/window_cumedist_function.cpp
  src/function/window/window_custom_aggregator.cpp
  src/function/window/window_distinct_aggregator.cpp
  src/function/window/window_executor.cpp
  src/function/window/window_naive_aggregator.cpp
  src/function/window/window_rank_function.cpp
  src/function/window/window_rownumber_function.cpp
  src/function/window/window_segment_tree.cpp
  src/function/window/window_shared_expressions.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/execution/window_executor.hpp
  src/include/duckdb/execution/window_segment_tree.hpp
  src/include/duckdb/function/window/window_aggregate_function.hpp
  src/include/duckdb/function/window/window_aggregate_states.hpp
  src/include/duckdb/function/window/window_aggregator.hpp
  src/include/duckdb/function/window/window_boundaries_state.hpp
  src/include/duckdb/function/window/window_collection.hpp
  src/include/duckdb/function/window/window_constant_aggregator.hpp
  src/include/duckdb/function/window/window_cumedist_function.hpp
  src/include/duckdb/function/window/window_custom_aggregator.hpp
  src/include/duckdb/function/window/window_distinct_aggregator.hpp
  src/include/duckdb/function/window/window_executor.hpp
  src/include/duckdb/function/window/window_naive_aggregator.hpp
  src/include/duckdb/function/window/window_rank_function.hpp
  src/include/duckdb/function/window/window_rownumber_function.hpp
  src/include/duckdb/function/window/window_segment_tree.hpp
  src/include/duckdb/function/window/window_shared_expressions.hpp
  src/include/duckdb/function/window/window_value_function.hpp
Labels: Ready For Review

#15009 Internal #3574: INTERVAL Normlisation Carries
  src/include/duckdb/common/types/interval.hpp
  test/sql/types/interval/test_interval_comparison.test
Labels: Ready For Review

#15021 Add check_peg_parser to extension_entries
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready For Review

#14810 Re-enable jemalloc on ARM
  extension/extension_config.cmake
  tools/pythonpkg/setup.py
Labels: Ready To Merge

#14971 Dynamically decide whether to do a Perfect Hash Join
  src/execution/operator/join/perfect_hash_join_executor.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/physical_plan/plan_comparison_join.cpp
  src/execution/physical_plan/plan_set_operation.cpp
  src/include/duckdb/execution/operator/join/join_filter_pushdown.hpp
  src/include/duckdb/execution/operator/join/perfect_hash_join_executor.hpp
  src/include/duckdb/execution/operator/join/physical_hash_join.hpp
  src/optimizer/join_filter_pushdown_optimizer.cpp
  test/sql/join/inner/perfect_hash_join.test
Labels: Ready To Merge

#14923 No salt for Android
  .github/workflows/NightlyTests.yml
  CMakeLists.txt
  Makefile
  src/common/types/column/column_data_collection_segment.cpp
  src/execution/aggregate_hashtable.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/include/duckdb/execution/ht_entry.hpp
  src/include/duckdb/execution/join_hashtable.hpp
Labels: Ready To Merge

#15016 Fixup linux_arm64 extension builds
  .github/actions/build_extensions_dockerized/action.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/Python.yml
Labels: Ready For Review

#15022 Issue #14834: INTERVAL Collations
  extension/core_functions/function_list.cpp
  extension/core_functions/include/core_functions/scalar/date_functions.hpp
  extension/core_functions/scalar/date/epoch.cpp
  extension/core_functions/scalar/date/functions.json
  src/include/duckdb/common/types/interval.hpp
  src/planner/collation_binding.cpp
  test/sql/types/interval/test_interval_comparison.test
Labels: Ready For Review

#15006 Spell NULL with uppercase in configuration description and comments
  src/common/settings.json
  src/include/duckdb.h
  src/include/duckdb/main/capi/header_generation/functions/vector_interface.json
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  tools/juliapkg/src/api.jl
  tools/pythonpkg/src/pyrelation/initialize.cpp
Labels: Ready For Review

#14979 Force download doesn't require to do a head request
  extension/httpfs/httpfs.cpp
  extension/httpfs/include/httpfs.hpp
  test/sql/copy/test_remote_head_forbidden.test
Labels: Changes Requested

#14973 More regression tests
  .github/workflows/Regression.yml
Labels: Ready To Merge

#15039 Fix internal error of list_zip with only truncate argument provided
  src/function/scalar/list/list_zip.cpp
  test/sql/function/list/list_zip.test
Labels: Ready To Merge

#15041 BarScalarFunction needs to keep track of width != string.size()
  extension/core_functions/scalar/string/bar.cpp
  test/sql/function/string/test_bar.test
Labels: Ready To Merge

#15042 Add SUM(BOOL) overload
  extension/core_functions/aggregate/distributive/sum.cpp
  test/sql/aggregate/aggregates/test_aggregate_types.test
  test/sql/aggregate/aggregates/test_aggregate_types_scalar.test
  test/sql/function/list/aggregates/sum_bool.test
  test/sql/function/list/aggregates/types.test
Labels: Needs Documentation

#15050 CLI: Add -f [FILE] argument that allows execution of a file
  Makefile
  tools/shell/shell.cpp
  tools/shell/tests/test_shell_basics.py
Labels: Needs Documentation
