Repository duckdb/duckdb, pull requests merged in 2024-07, with the labels that each got.

#12782 Fix stale bot permissions, with @szarnyasg
  .github/workflows/IssuesCloseStale.yml
Labels: Ready To Merge

#12786 [CI] Stale bot: actually add permissions
  .github/workflows/IssuesCloseStale.yml
Labels: Ready For Review

#12781 Fix extended tests in CI
  .github/workflows/ExtendedTests.yml
Labels: Ready For Review

#12754 Allow extensions to optionally add own description (on load)
  src/function/table/system/duckdb_extensions.cpp
  src/include/duckdb/main/database.hpp
  src/include/duckdb/main/extension_install_info.hpp
  src/include/duckdb/main/extension_util.hpp
  src/main/database.cpp
  src/main/extension/extension_util.cpp
  tools/sqlite3_api_wrapper/shell_extension.cpp
Labels: Ready To Merge

#12791 Internal #2429: Shifted LEAD NULLs
  src/execution/window_executor.cpp
Labels: Ready For Review

#12794 Issue #12784: Months Before Days
  extension/icu/icu-dateadd.cpp
  test/sql/function/timestamp/test_icu_dateadd.test
Labels: Ready For Review

#12797 bump vss
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#12575 feat: new inet functions
  Makefile
  extension/inet/include/inet_functions.hpp
  extension/inet/include/ipaddress.hpp
  extension/inet/inet_extension.cpp
  extension/inet/inet_functions.cpp
  extension/inet/ipaddress.cpp
  src/include/duckdb/main/extension_entries.hpp
  test/sql/inet/test_inet_functions.test
  test/sql/inet/test_inet_operations.test
  test/sql/inet/test_inet_type.test
  test/sql/inet/test_ipv6_inet_functions.test
  test/sql/inet/test_ipv6_inet_operations.test
  test/sql/inet/test_ipv6_inet_type.test
Labels: Needs Documentation, Ready To Merge

#12792 Remove micro extended from duckdb/duckdb
  .github/regression/micro_extended.csv
  Makefile
  scripts/generate_micro_extended.sh
Labels: Ready To Merge

#12812 [Python] Accept a list of `Expression` objects in `DuckDBPyRelation.aggregate`
  src/include/duckdb/main/relation.hpp
  src/main/relation.cpp
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb_python.cpp
  tools/pythonpkg/scripts/connection_wrapper_methods.json
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/tests/fast/test_expression.py
Labels: Ready For Review

#12806 [Dev] Change internals of `StringUtil::GenerateRandomName`
  src/common/string_util.cpp
Labels: Ready For Review

#12850 Fix LinuxRelease.yml after bump to Node 20
  .github/workflows/LinuxRelease.yml
Labels: Ready To Merge

#11191 add html_escape and html_unescape functions in inet extension
  .github/workflows/Regression.yml
  benchmark/micro/string/inet_escape_function.benchmark
  benchmark/micro/string/inet_unescape_charrefs.benchmark
  benchmark/micro/string/inet_unescape_codepoints.benchmark
  data/csv/html_unescape_codes.csv
  extension/inet/CMakeLists.txt
  extension/inet/include/html_charref.hpp
  extension/inet/include/inet_extension.hpp
  extension/inet/include/inet_functions.hpp
  extension/inet/inet_escape_functions.cpp
  extension/inet/inet_extension.cpp
  src/include/duckdb/main/extension_entries.hpp
  test/sql/inet/test_inet_escape.test
Labels: Needs Documentation, Ready For Review

#12847 Fix union struct implict cast
  src/function/cast/union_casts.cpp
  src/function/cast_rules.cpp
  test/sql/types/union/union_cast.test
Labels: Ready To Merge

#12849 Update httplib from v0.10.2 to v0.14.3
  test/extension/autoloading_filesystems.test
  third_party/httplib/httplib.hpp
Labels: Ready For Review

#12834 Overload `MIN/MAX/MAX_BY/MIN_BY` to return the "top" `N` values
  benchmark/tpch/aggregate/top_n_in_group_agg.benchmark
  benchmark/tpch/aggregate/top_n_in_group_window.benchmark
  src/core_functions/aggregate/distributive/arg_min_max.cpp
  src/core_functions/aggregate/distributive/minmax.cpp
  src/include/duckdb/core_functions/aggregate/minmax_n_helpers.hpp
  test/sql/aggregate/aggregates/arg_min_max_n.test
  test/sql/aggregate/aggregates/arg_min_max_n_all_types.test_slow
  test/sql/aggregate/aggregates/arg_min_max_n_tpch.test
  test/sql/aggregate/aggregates/max_n_all_types_grouped.test
  test/sql/aggregate/aggregates/test_aggregate_types_scalar.test
Labels: Ready For Review, Friendly SQL

#12859 Fix #12789: list_zip support array
  src/function/scalar/list/list_zip.cpp
  test/sql/function/list/list_zip.test
Labels: CI Failure

#12398 Add a JSON pretty print function
  extension/json/CMakeLists.txt
  extension/json/include/json_functions.hpp
  extension/json/json_config.py
  extension/json/json_functions.cpp
  extension/json/json_functions/CMakeLists.txt
  extension/json/json_functions/json_pretty.cpp
  src/include/duckdb/main/extension_entries.hpp
  test/sql/json/scalar/test_json_pretty.test
Labels: Changes Requested

#12498 Add Metrics Support in the CAPI
  src/common/enum_util.cpp
  src/common/symbols.cpp
  src/common/tree_renderer.cpp
  src/include/duckdb.h
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/enums/profiler_format.hpp
  src/include/duckdb/common/tree_renderer.hpp
  src/include/duckdb/main/client_context.hpp
  src/include/duckdb/main/connection.hpp
  src/include/duckdb/main/profiling_info.hpp
  src/include/duckdb/main/profiling_node.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/main/CMakeLists.txt
  src/main/capi/CMakeLists.txt
  src/main/capi/profiling_info-c.cpp
  src/main/connection.cpp
  src/main/profiling_info.cpp
  src/main/query_profiler.cpp
  src/main/settings/settings.cpp
  test/api/capi/CMakeLists.txt
  test/api/capi/test_capi_profiling.cpp
  test/sql/pragma/not_a_valid.json
Labels: Ready To Merge

#12880 Update issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready For Review

#12751 Improve performance of memory usage counters
  src/include/duckdb/parallel/task_scheduler.hpp
  src/include/duckdb/storage/buffer/buffer_pool.hpp
  src/parallel/task_scheduler.cpp
  src/storage/buffer/buffer_pool.cpp
  src/storage/standard_buffer_manager.cpp
Labels: Changes Requested

#12891 Fix LinuxRelease.yml CI by avoiding upload
  .github/workflows/LinuxRelease.yml
Labels: Ready For Review

#12895 Do not depend on manylinux extension in Python's CI
  .github/workflows/Python.yml
Labels: Ready For Review

#12888 [Python-Dev] Add `DependencyException`, throw earlier if `PendingQuery` fails
  scripts/sqllogictest/result.py
  src/main/client_context.cpp
  test/fuzzer/pedro/in_clause_optimization_error.test
  test/sql/types/map/map_empty.test
  tools/pythonpkg/src/common/exceptions.cpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/api/test_duckdb_connection.py
  tools/pythonpkg/tests/fast/test_runtime_error.py
Labels: Ready For Review

#12887 Fix issue with list radix serialization
  src/common/row_operations/row_radix_scatter.cpp
  test/sql/types/nested/list/internal_issue_2457.test
Labels: Ready For Review

#12851 Respect limit during join order
  benchmark/micro/join/join_order_optimizer_should_respect_limit.benchmark
  src/optimizer/join_order/relation_manager.cpp
  test/optimizer/joins/get_cardinality_from_limit.test
Labels: Ready To Merge

#12883 Count nulls when detecting JSON structure
  extension/json/include/json_structure.hpp
  extension/json/json_functions/json_structure.cpp
  test/sql/json/issues/issue12861.test
Labels: Ready For Review

#12889 Use different versions of snappy depending on the compiler
  third_party/snappy/snappy-internal.h
  third_party/snappy/snappy-sinksource.cc
  third_party/snappy/snappy-sinksource.h
  third_party/snappy/snappy-stubs-internal.cc
  third_party/snappy/snappy-stubs-internal.h
  third_party/snappy/snappy-stubs-public.h
  third_party/snappy/snappy.cc
  third_party/snappy/snappy.h
  third_party/snappy/snappy_version.hpp
Labels: Ready For Review

#12922 Pass 'Unsecure_node_version' to allow node16 for a bit longer
  .github/workflows/LinuxRelease.yml
  .github/workflows/Python.yml
Labels: Ready To Merge

#12890 [Fix] Vector verification for dictionary expressions
  src/function/aggregate/distributive/first.cpp
  src/function/scalar/list/list_resize.cpp
Labels: Ready To Merge

#12937 Make GCC Happy Again
  extension/jemalloc/jemalloc/CMakeLists.txt
  src/include/duckdb/execution/ht_entry.hpp
  third_party/httplib/httplib.hpp
  tools/shell/shell.c
Labels: Ready To Merge

#12935 [Fix] More robust parquet metadata test
  test/sql/copy/parquet/parquet_5209.test
Labels: Ready To Merge

#12885 Make `ErrorData::Message()` and `ErrorData::RawMessage()` const
  src/common/error_data.cpp
  src/include/duckdb/common/error_data.hpp
Labels: Changes Requested

#12787 [Arrow] Add `PhysicalArrowBatchCollector`, a batched result collector for the `ArrowQueryResult`
  benchmark/micro/result_collection/batched_arrow_result.benchmark
  src/common/arrow/CMakeLists.txt
  src/common/arrow/arrow_merge_event.cpp
  src/common/arrow/arrow_query_result.cpp
  src/common/arrow/physical_arrow_batch_collector.cpp
  src/common/arrow/physical_arrow_collector.cpp
  src/common/types/batched_data_collection.cpp
  src/execution/operator/helper/physical_batch_collector.cpp
  src/execution/operator/helper/physical_materialized_collector.cpp
  src/execution/operator/helper/physical_result_collector.cpp
  src/include/duckdb/common/arrow/arrow_merge_event.hpp
  src/include/duckdb/common/arrow/arrow_query_result.hpp
  src/include/duckdb/common/arrow/physical_arrow_batch_collector.hpp
  src/include/duckdb/common/types/batched_data_collection.hpp
  src/include/duckdb/execution/operator/helper/physical_batch_collector.hpp
  src/include/duckdb/execution/operator/helper/physical_materialized_collector.hpp
  src/include/duckdb/main/chunk_scan_state/batched_data_collection.hpp
  src/main/chunk_scan_state/CMakeLists.txt
  src/main/chunk_scan_state/batched_data_collection.cpp
  test/arrow/arrow_roundtrip.cpp
  test/arrow/arrow_test_helper.cpp
  test/include/arrow/arrow_test_helper.hpp
Labels: Ready For Review

#12625 [Python] Rework internals of object registration
  extension/json/json_functions.cpp
  extension/parquet/parquet_extension.cpp
  src/function/table/read_csv.cpp
  src/include/duckdb/function/replacement_scan.hpp
  src/include/duckdb/main/client_context.hpp
  src/include/duckdb/main/client_context_state.hpp
  src/include/duckdb/main/relation/view_relation.hpp
  src/include/duckdb/planner/binder.hpp
  src/main/relation/view_relation.cpp
  src/planner/binder/tableref/bind_basetableref.cpp
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
  tools/pythonpkg/src/include/duckdb_python/python_replacement_scan.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/src/python_replacement_scan.cpp
  tools/pythonpkg/tests/fast/api/test_duckdb_connection.py
  tools/pythonpkg/tests/fast/api/test_relation_to_view.py
  tools/pythonpkg/tests/fast/arrow/test_arrow_case_sensitive.py
  tools/pythonpkg/tests/fast/arrow/test_arrow_types.py
  tools/pythonpkg/tests/fast/arrow/test_view.py
  tools/pythonpkg/tests/fast/pandas/test_same_name.py
  tools/pythonpkg/tests/fast/test_runtime_error.py
Labels: Ready For Review

#12916 Label mark joins with convert to semi
  src/include/duckdb/optimizer/filter_pushdown.hpp
  src/include/duckdb/planner/operator/logical_comparison_join.hpp
  src/optimizer/filter_pushdown.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/pushdown/pushdown_mark_join.cpp
  src/optimizer/pushdown/pushdown_window.cpp
  src/optimizer/statistics/operator/propagate_join.cpp
  test/optimizer/pushdown/no_mark_to_semi_if_mark_index_is_projected.test
Labels: Ready For Review

#12290 Automatically materialize CTEs
  benchmark/tpch/cte/auto_cte_materialization.benchmark
  benchmark/tpch_plan_cost/queries/q15.sql
  extension/tpch/dbgen/include/tpch_constants.hpp
  extension/tpch/dbgen/queries/q15.sql
  src/common/enum_util.cpp
  src/common/enums/optimizer_type.cpp
  src/execution/operator/aggregate/physical_hash_aggregate.cpp
  src/execution/operator/projection/physical_projection.cpp
  src/execution/operator/scan/physical_column_data_scan.cpp
  src/include/duckdb/common/enums/optimizer_type.hpp
  src/include/duckdb/common/insertion_order_preserving_map.hpp
  src/include/duckdb/common/optionally_owned_ptr.hpp
  src/include/duckdb/execution/operator/scan/physical_column_data_scan.hpp
  src/include/duckdb/optimizer/cte_filter_pusher.hpp
  src/include/duckdb/optimizer/join_order/join_order_optimizer.hpp
  src/include/duckdb/optimizer/join_order/query_graph_manager.hpp
  src/include/duckdb/optimizer/join_order/relation_manager.hpp
  src/include/duckdb/parser/parsed_expression_iterator.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/operator/logical_cteref.hpp
  src/include/duckdb/planner/operator/logical_materialized_cte.hpp
  src/optimizer/CMakeLists.txt
  src/optimizer/cte_filter_pusher.cpp
  src/optimizer/join_order/join_order_optimizer.cpp
  src/optimizer/join_order/query_graph_manager.cpp
  src/optimizer/join_order/relation_manager.cpp
  src/optimizer/optimizer.cpp
  src/parser/parsed_expression_iterator.cpp
  src/parser/transform/helpers/transform_cte.cpp
  src/planner/binder.cpp
  src/planner/binder/query_node/bind_select_node.cpp
  src/planner/operator/logical_cteref.cpp
  src/planner/operator/logical_materialized_cte.cpp
  test/optimizer/joins/delim_join_dont_explode.test_slow
  test/sql/cte/materialized/automatic_cte_materialization.test_slow
  tools/pythonpkg/duckdb/query_graph/__main__.py
Labels: Ready To Merge

#12912 [Dev] Uncouple `HTTPState` from core
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/azure/azure_http_state.patch
  .github/patches/extensions/substrait/http_state.patch
  extension/httpfs/CMakeLists.txt
  extension/httpfs/hffs.cpp
  extension/httpfs/http_state.cpp
  extension/httpfs/httpfs.cpp
  extension/httpfs/include/http_state.hpp
  extension/httpfs/include/httpfs.hpp
  extension/httpfs/s3fs.cpp
  src/common/CMakeLists.txt
  src/include/duckdb/main/client_context_state.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/main/client_context.cpp
  src/main/client_data.cpp
  src/main/query_profiler.cpp
Labels: Ready For Review

#12716 [Dev] Clean up TreeRenderer code
  src/common/CMakeLists.txt
  src/common/render_tree.cpp
  src/common/tree_renderer.cpp
  src/include/duckdb/common/render_tree.hpp
  src/include/duckdb/common/tree_renderer.hpp
  src/include/duckdb/main/profiling_node.hpp
Labels: Ready For Review

#12755 Swap build side and probe side base on cardinality AND width of build side.
  .github/workflows/Python.yml
  benchmark/micro/join/skinny_probe_wide_build.benchmark
  src/include/duckdb/optimizer/build_probe_side_optimizer.hpp
  src/optimizer/build_probe_side_optimizer.cpp
  test/optimizer/joins/wide_build_skinny_probe.test
  test/sql/copy/csv/rejects/csv_rejects_read.test
  test/sql/join/semianti/right_anti.test
  test/sql/join/semianti/right_semi.test
  tools/pythonpkg/tests/fast/test_replacement_scan.py
Labels: Ready For Review

#12954 Feature #1272: Window Validity Array
  src/execution/window_segment_tree.cpp
  src/include/duckdb/common/types/validity_mask.hpp
Labels: Ready For Review

#12956 fix incorrect int32 appender
  tools/juliapkg/Project.toml
  tools/juliapkg/src/api.jl
  tools/juliapkg/test/test_appender.jl
Labels: Merge Conflict

#12965 Add Pyodide 0.26.1 (corresponding to Python 3.12)
  .github/workflows/Pyodide.yml
  src/include/duckdb/parallel/task_scheduler.hpp
  src/parallel/task_scheduler.cpp
  src/storage/buffer/buffer_pool.cpp
Labels: Ready For Review

#12974 URL Encode/Decode Hive Partitioning Columns/Filters + add url_encode/url_decode scalar functions
  benchmark/micro/string/url_encode.benchmark
  extension/httpfs/s3fs.cpp
  src/common/hive_partitioning.cpp
  src/common/string_util.cpp
  src/core_functions/function_list.cpp
  src/core_functions/scalar/string/CMakeLists.txt
  src/core_functions/scalar/string/functions.json
  src/core_functions/scalar/string/url_encode.cpp
  src/execution/operator/persistent/physical_copy_to_file.cpp
  src/include/duckdb/common/hive_partitioning.hpp
  src/include/duckdb/common/string_util.hpp
  src/include/duckdb/core_functions/scalar/string_functions.hpp
  test/sql/copy/partitioned/hive_partition_escape.test
  test/sql/function/string/test_url_encode.test
Labels: Needs Documentation

#12984 Internal #2503: Streaming Window Reset
  src/execution/operator/aggregate/physical_streaming_window.cpp
Labels: Ready For Review

#12979 Feature #1272: Window Constant Sink
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/window_executor.cpp
  src/execution/window_segment_tree.cpp
  src/include/duckdb/execution/window_segment_tree.hpp
Labels: Ready For Review

#12929 Remove special case for '+' in URLs in httplib
  test/sql/httpfs/internal_issue_2490.test
  third_party/httplib/httplib.hpp
Labels: Ready To Merge

#12928 Allow string stats larger than our default for parquet row group pruning
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_statistics.cpp
  src/include/duckdb/storage/statistics/string_stats.hpp
  src/storage/statistics/string_stats.cpp
  test/parquet/parquet_long_string_stats.test
Labels: Ready To Merge

#12785 Add the ANY type and special null handling to the C API
  src/include/duckdb.h
  src/main/capi/data_chunk-c.cpp
  src/main/capi/duckdb_value-c.cpp
  src/main/capi/helper-c.cpp
  src/main/capi/logical_types-c.cpp
  src/main/capi/scalar_function-c.cpp
  src/main/capi/table_function-c.cpp
  test/api/capi/CMakeLists.txt
  test/api/capi/capi_scalar_functions.cpp
  test/api/capi/test_capi.cpp
  test/api/capi/test_capi_any_invalid_type.cpp
  test/api/capi/test_capi_complex_types.cpp
Labels: Ready For Review, Ready To Merge

#12994 Make sure that empty and only white space headers have same treatment
  data/csv/headers/empty_1.csv
  data/csv/headers/empty_2.csv
  data/csv/headers/empty_3.csv
  data/csv/headers/empty_4.csv
  src/execution/operator/csv_scanner/sniffer/header_detection.cpp
  test/sql/copy/csv/test_empty_header.test
Labels: Changes Requested

#12728 [CSV] Progress Bar for compressed files.
  extension/parquet/zstd_file_system.cpp
  src/common/compressed_file_system.cpp
  src/common/file_system.cpp
  src/common/gzip_file_system.cpp
  src/execution/operator/csv_scanner/buffer_manager/csv_file_handle.cpp
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/include/duckdb/common/compressed_file_system.hpp
  src/include/duckdb/common/file_system.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_handle.hpp
Labels: Changes Requested

#12627 Decimal to FloatingPoint: Avoid losing precision by splitting operation in two, more fixes and tests
  benchmark/micro/cast/cast_decimal_double_1.benchmark
  benchmark/micro/cast/cast_decimal_double_2.benchmark
  benchmark/micro/cast/cast_decimal_double_3.benchmark
  benchmark/micro/cast/cast_decimal_double_4.benchmark
  src/common/operator/cast_operators.cpp
  src/common/types/hugeint.cpp
  test/sql/cast/decimal_float_cast.test
  test/sql/join/iejoin/iejoin_projection_maps.test
Labels: Ready To Merge

#13002 Feature #1272: Segment Tree Finalize
  src/execution/window_segment_tree.cpp
  test/sql/copy/csv/test_csv_wrong_file.test_slow
  test/sql/copy/csv/test_multiple_big_compressed_csvs.test_slow
  test/sql/tpch/test_tpch_options.test_slow
Labels: Ready For Review

#13024 Fix CTE/noalternativeverify issues
  src/optimizer/column_lifetime_analyzer.cpp
  test/optimizer/topn/topn_optimizer.test
  test/sql/fts/issue_12330.test
Labels: Ready To Merge

#13023 Fix bug in reworked `fixed_size_map_t`
  src/common/types/row/partitioned_tuple_data.cpp
  src/include/duckdb/common/fixed_size_map.hpp
Labels: Ready To Merge

#13028 [Nightly-Bug] [CSV Reader] Use strings on header detection
  src/execution/operator/csv_scanner/sniffer/header_detection.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_sniffer.hpp
Labels: Ready To Merge

#13029 Release GIL during DB instantiation
  tools/pythonpkg/src/pyconnection.cpp
Labels: Ready To Merge

#13030 GCC 4.8: add noexpr to 2 constructors
  src/include/duckdb/common/optional_ptr.hpp
  src/include/duckdb/storage/table/row_version_manager.hpp
  src/storage/table/row_version_manager.cpp
Labels: Ready To Merge

#13050 Internal #2534: IGNORE NULLS Threading
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/window_executor.cpp
  test/sql/window/test_lead_lag.test
Labels: Ready For Review

#12995 Improve EXPLAIN output of Delim Joins and Delim Gets
  src/execution/operator/join/physical_delim_join.cpp
  src/execution/operator/join/physical_left_delim_join.cpp
  src/execution/operator/join/physical_right_delim_join.cpp
  src/execution/operator/scan/physical_column_data_scan.cpp
  src/execution/physical_plan/plan_delim_join.cpp
  src/include/duckdb/execution/operator/join/physical_delim_join.hpp
  src/include/duckdb/execution/operator/join/physical_left_delim_join.hpp
  src/include/duckdb/execution/operator/join/physical_right_delim_join.hpp
  src/include/duckdb/execution/operator/scan/physical_column_data_scan.hpp
  src/include/duckdb/execution/physical_plan_generator.hpp
Labels: Changes Requested

#13057 Only remove the first occurrence of extension prefix
  src/main/database_path_and_type.cpp
Labels: Ready To Merge

#13054 [Relation] ViewRelation could be created without an alias
  src/include/duckdb/main/relation/view_relation.hpp
  src/main/relation/view_relation.cpp
  tools/pythonpkg/src/pyconnection.cpp
Labels: Ready For Review

#12920 Support IN operator for LIST
  src/common/types/value.cpp
  src/function/scalar/string/contains.cpp
  src/include/duckdb/common/types/value.hpp
  src/include/duckdb/function/scalar/string_functions.hpp
  src/include/duckdb/parser/transformer.hpp
  src/optimizer/rule/empty_needle_removal.cpp
  src/optimizer/rule/like_optimizations.cpp
  src/optimizer/rule/regex_optimizations.cpp
  src/parser/transform/expression/transform_operator.cpp
  test/sql/function/generic/test_in.test
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Ready For Review

#13040 [Python] Read from file-like objects with `read_json`
  src/common/multi_file_reader.cpp
  src/include/duckdb/common/multi_file_reader.hpp
  src/include/duckdb/main/relation/read_json_relation.hpp
  src/main/relation/read_csv_relation.cpp
  src/main/relation/read_json_relation.cpp
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb/bytes_io_wrapper.py
  tools/pythonpkg/duckdb/filesystem.py
  tools/pythonpkg/duckdb_python.cpp
  tools/pythonpkg/scripts/connection_methods.json
  tools/pythonpkg/src/include/duckdb_python/filesystem_object.hpp
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
  tools/pythonpkg/src/include/duckdb_python/pyfilesystem.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/src/pyfilesystem.cpp
  tools/pythonpkg/tests/extensions/json/test_read_json.py
  tools/pythonpkg/tests/fast/api/test_read_csv.py
Labels: Ready For Review

#12998 [Python] Fix lifetime issue with MaterializedRelation
  src/include/duckdb/main/relation/materialized_relation.hpp
  src/include/duckdb/parser/tableref/column_data_ref.hpp
  src/include/duckdb/storage/serialization/tableref.json
  src/main/relation/create_view_relation.cpp
  src/main/relation/materialized_relation.cpp
  src/parser/tableref/column_data_ref.cpp
  src/planner/binder/tableref/bind_column_data_ref.cpp
  src/storage/serialization/serialize_tableref.cpp
  tools/pythonpkg/tests/fast/test_relation.py
Labels: Ready For Review

#13065 Internal #2534: IGNORE NULLS Threading
  src/execution/window_executor.cpp
  test/sql/storage/optimistic_write/optimistic_write_alter_type.test_slow
  test/sql/storage/optimistic_write/optimistic_write_drop_column.test_slow
Labels: Ready For Review

#13015 Variable Integer Size Type
  benchmark/cast/double_varint.benchmark
  benchmark/cast/from_varint/varint_double.benchmark
  benchmark/cast/from_varint/varint_varchar.benchmark
  benchmark/cast/from_varint/varint_varchar_100k.benchmark
  benchmark/cast/hugeint_varint.benchmark
  benchmark/cast/integer_varint.benchmark
  benchmark/cast/small_double_varint.benchmark
  benchmark/cast/small_varchar_varint.benchmark
  benchmark/cast/smallint_varint.benchmark
  benchmark/cast/varchar_varint.benchmark
  benchmark/cast/varchar_varint_100k.benchmark
  benchmark/cast/varchar_varint_10M.benchmark
  benchmark/cast/varchar_varint_1M.benchmark
  src/common/arrow/arrow_converter.cpp
  src/common/enum_util.cpp
  src/common/types.cpp
  src/common/types/CMakeLists.txt
  src/common/types/value.cpp
  src/common/types/varint.cpp
  src/common/types/vector.cpp
  src/function/cast/CMakeLists.txt
  src/function/cast/default_casts.cpp
  src/function/cast/numeric_casts.cpp
  src/function/cast/string_cast.cpp
  src/function/cast/varint_casts.cpp
  src/function/cast_rules.cpp
  src/include/duckdb.h
  src/include/duckdb/catalog/default/builtin_types/types.hpp
  src/include/duckdb/catalog/default/builtin_types/types.json
  src/include/duckdb/common/types.hpp
  src/include/duckdb/common/types/value.hpp
  src/include/duckdb/common/types/varint.hpp
  src/include/duckdb/function/cast/default_casts.hpp
  src/main/capi/helper-c.cpp
  test/sql/types/varint/test_big_varint.test
  test/sql/types/varint/test_double_varint.test
  test/sql/types/varint/test_int_varchar_varint_compatibility.test_slow
  test/sql/types/varint/test_int_varint_conversion.test
  test/sql/types/varint/test_varchar_varint_conversion.test
  test/sql/types/varint/test_varchar_varint_unhappy.test
  test/sql/types/varint/test_varint_boundaries.test
  test/sql/types/varint/test_varint_comparisons.test
  test/sql/types/varint/test_varint_double.test
  test/sql/types/varint/test_varint_implicit_cast.test
  test/sql/types/varint/test_varint_not_cast.test
Labels: Ready For Review

#13062 Add support for overloading to macros
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/sqlsmith/macrooverload.patch
  src/catalog/catalog_entry/macro_catalog_entry.cpp
  src/catalog/default/default_functions.cpp
  src/catalog/default/default_table_functions.cpp
  src/function/macro_function.cpp
  src/function/scalar_macro_function.cpp
  src/function/table/system/duckdb_functions.cpp
  src/function/table_macro_function.cpp
  src/include/duckdb/catalog/catalog_entry/macro_catalog_entry.hpp
  src/include/duckdb/catalog/default/default_functions.hpp
  src/include/duckdb/common/array_ptr.hpp
  src/include/duckdb/function/macro_function.hpp
  src/include/duckdb/function/scalar_macro_function.hpp
  src/include/duckdb/function/table_macro_function.hpp
  src/include/duckdb/parser/parsed_data/create_macro_info.hpp
  src/include/duckdb/parser/transformer.hpp
  src/include/duckdb/storage/serialization/create_info.json
  src/parser/parsed_data/create_macro_info.cpp
  src/parser/transform/statement/transform_create_function.cpp
  src/planner/binder/expression/bind_macro_expression.cpp
  src/planner/binder/query_node/bind_table_macro_node.cpp
  src/planner/binder/statement/bind_create.cpp
  src/storage/serialization/serialize_create_info.cpp
  test/sql/catalog/function/test_macro_overloads.test
  test/sql/pg_catalog/pg_privilege.test
  test/sql/storage/catalog/test_macro_storage.test
  third_party/libpg_query/grammar/statements/create_function.y
  third_party/libpg_query/grammar/types/create_function.yh
  third_party/libpg_query/include/nodes/nodes.hpp
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
  third_party/mbedtls/library/sha1.cpp
  third_party/mbedtls/library/sha256.cpp
Labels: Needs Documentation

#13086 Internal #2534: Windowed FILTER Threading
  src/execution/window_executor.cpp
Labels: Ready For Review

#13089 Fixup #12579, remove pessimizing std::move
  third_party/libpg_query/postgres_parser.cpp
Labels: Ready For Review

#13091 Remove test in Pyodide due to weird pandas interactions
  tools/pythonpkg/tests/fast/pandas/test_pandas_na.py
Labels: Ready To Merge

#13084 Add support for SQL-level variables
  src/common/enum_util.cpp
  src/common/enums/physical_operator_type.cpp
  src/execution/operator/helper/CMakeLists.txt
  src/execution/operator/helper/physical_reset.cpp
  src/execution/operator/helper/physical_set_variable.cpp
  src/execution/physical_plan/plan_set.cpp
  src/function/pragma/pragma_queries.cpp
  src/function/scalar/generic/CMakeLists.txt
  src/function/scalar/generic/getvariable.cpp
  src/function/scalar/generic_functions.cpp
  src/function/table/system/CMakeLists.txt
  src/function/table/system/duckdb_variables.cpp
  src/function/table/system_functions.cpp
  src/include/duckdb/common/enums/physical_operator_type.hpp
  src/include/duckdb/common/enums/set_scope.hpp
  src/include/duckdb/execution/operator/helper/physical_set.hpp
  src/include/duckdb/execution/operator/helper/physical_set_variable.hpp
  src/include/duckdb/function/pragma/pragma_functions.hpp
  src/include/duckdb/function/scalar/generic_functions.hpp
  src/include/duckdb/function/table/system_functions.hpp
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/parser/statement/set_statement.hpp
  src/parser/statement/set_statement.cpp
  src/parser/transform/statement/transform_set.cpp
  src/planner/binder/statement/bind_set.cpp
  src/planner/binder/tableref/bind_showref.cpp
  test/sql/copy/csv/read_csv_variable.test
  test/sql/variables/test_variables.test
  third_party/libpg_query/grammar/keywords/unreserved_keywords.list
  third_party/libpg_query/grammar/statements/variable_reset.y
  third_party/libpg_query/grammar/statements/variable_set.y
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/include/parser/kwlist.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation

#13094 Fix wasm CI and add missing template argument
  .github/workflows/NightlyTests.yml
  src/function/aggregate/distributive/first.cpp
Labels: Ready For Review

#13105 Some clang tidy fixes around narrowing casts
  src/core_functions/aggregate/distributive/approx_count.cpp
  src/core_functions/scalar/date/date_trunc.cpp
  src/core_functions/scalar/date/to_interval.cpp
  src/function/scalar/generic/binning.cpp
  src/function/table/version/pragma_version.cpp
  src/include/duckdb/common/platform.hpp
  src/include/duckdb/common/string_util.hpp
  src/include/duckdb/common/types/cast_helpers.hpp
  src/include/duckdb/common/types/datetime.hpp
  src/include/duckdb/common/types/interval.hpp
  src/include/duckdb/core_functions/aggregate/quantile_sort_tree.hpp
  src/optimizer/build_probe_side_optimizer.cpp
  src/optimizer/join_order/relation_manager.cpp
  src/optimizer/join_order/relation_statistics_helper.cpp
  tools/utils/test_platform.cpp
Labels: Ready For Review

#13090 - fix list_distance & list_cosine_similarity execute fail when list i…
  src/core_functions/scalar/list/list_cosine_similarity.cpp
  src/core_functions/scalar/list/list_distance.cpp
  test/sql/function/list/list_cosine_similarity.test
  test/sql/function/list/list_distance.test
Labels: Changes Requested

#12967 [Explain] Add `EXPLAIN (FORMAT JSON)` syntax
  src/common/CMakeLists.txt
  src/common/enum_util.cpp
  src/common/render_tree.cpp
  src/common/tree_renderer.cpp
  src/common/tree_renderer/CMakeLists.txt
  src/common/tree_renderer/json_tree_renderer.cpp
  src/common/tree_renderer/text_tree_renderer.cpp
  src/execution/operator/helper/physical_explain_analyze.cpp
  src/execution/physical_operator.cpp
  src/execution/physical_plan/plan_explain.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/enums/explain_format.hpp
  src/include/duckdb/common/render_tree.hpp
  src/include/duckdb/common/tree_renderer.hpp
  src/include/duckdb/common/tree_renderer/json_tree_renderer.hpp
  src/include/duckdb/common/tree_renderer/text_tree_renderer.hpp
  src/include/duckdb/common/types/string_type.hpp
  src/include/duckdb/execution/operator/helper/physical_explain_analyze.hpp
  src/include/duckdb/execution/physical_operator.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/include/duckdb/parser/statement/explain_statement.hpp
  src/include/duckdb/planner/logical_operator.hpp
  src/include/duckdb/planner/operator/logical_explain.hpp
  src/main/query_profiler.cpp
  src/parallel/pipeline.cpp
  src/parser/statement/explain_statement.cpp
  src/parser/transform/statement/transform_explain.cpp
  src/planner/binder/statement/bind_explain.cpp
  src/planner/logical_operator.cpp
  test/sql/explain/test_explain.test
  test/sql/explain/test_explain_analyze.test
Labels: Ready For Review

#13093 Feature #1272: Windowed DISTINCT Sink
  src/execution/window_segment_tree.cpp
Labels: Ready For Review

#13116 add CORE_EXTENSIONS build flag
  CMakeLists.txt
  Makefile
Labels: Ready To Merge

#12872 [Python] Add missing options for `read_csv`
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_reader_options.hpp
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb/__init__.py
  tools/pythonpkg/duckdb_python.cpp
  tools/pythonpkg/scripts/connection_methods.json
  tools/pythonpkg/scripts/generate_connection_methods.py
  tools/pythonpkg/scripts/generate_connection_wrapper_methods.py
  tools/pythonpkg/src/include/duckdb_python/pybind11/conversions/python_csv_line_terminator_enum.hpp
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/extensions/json/test_read_json.py
  tools/pythonpkg/tests/fast/api/test_read_csv.py
Labels: Ready For Review

#13117 Internal #2577: Window Atomic Finalize
  src/execution/window_segment_tree.cpp
Labels: Ready For Review

#13119 Internal #2577: Window Tree Allocation
  src/execution/window_segment_tree.cpp
Labels: Ready For Review

#12978 Use Slurm env vars to manage cpu and memory allocation if run inside Slurm HPC job
  src/common/CMakeLists.txt
  src/common/cgroups.cpp
  src/include/duckdb/common/cgroups.hpp
  src/include/duckdb/main/config.hpp
  src/main/config.cpp
Labels: Ready For Review

#13124 Test with recent threadsanitizer
  .github/workflows/NightlyTests.yml
Labels: Ready For Review

#13101 clang-tidy: rework Makefile and CI
  .clang-tidy
  .github/workflows/CodeQuality.yml
  Makefile
  src/main/buffered_data/batched_buffered_data.cpp
  third_party/pcg/pcg_extras.hpp
Labels: Ready For Review

#13087 Extension updates to also be logged via enable_http_logging
  src/include/duckdb/main/extension_helper.hpp
  src/main/extension/extension_helper.cpp
Labels: Ready For Review

#13146 Adding option to disable materialized cte optimization
  src/common/enum_util.cpp
  src/common/enums/optimizer_type.cpp
  src/include/duckdb/common/enums/optimizer_type.hpp
  src/planner/binder.cpp
Labels: Ready To Merge

#13147 [Python] Fix issue with `native` UDFs returning STRUCT items
  tools/pythonpkg/src/native/python_conversion.cpp
  tools/pythonpkg/tests/fast/pandas/test_df_recursive_nested.py
  tools/pythonpkg/tests/fast/udf/test_scalar_native.py
Labels: Ready For Review

#13151 CGroups: fix compilation due to UB cast
  src/common/cgroups.cpp
Labels: Ready To Merge

#13157 test_expression.py: Skip throw related test on Windows
  tools/pythonpkg/tests/fast/test_expression.py
Labels: Ready For Review

#13161 Replaced while loop with if statement
  src/parallel/executor.cpp
Labels: Ready For Review

#13179 ThreadSanitizer: Avoid spurious data race in InsertMatchesAndIncrementMisses
  .sanitizer-thread-suppressions.txt
Labels: Ready To Merge

#13160 [C API] Return duckdb_value in duckdb_profiling_info_get_value
  src/include/duckdb.h
  src/main/capi/profiling_info-c.cpp
  test/api/capi/test_capi_profiling.cpp
Labels: Ready To Merge

#13150 Feature #1272: Windowed DISTINCT Sort
  src/execution/window_segment_tree.cpp
Labels: Ready For Review

#13163 Add native `list_has_any` implementation
  benchmark/micro/list/list_has_any.benchmark
  src/catalog/default/default_functions.cpp
  src/core_functions/function_list.cpp
  src/core_functions/scalar/list/CMakeLists.txt
  src/core_functions/scalar/list/functions.json
  src/core_functions/scalar/list/list_has_any.cpp
  src/include/duckdb/core_functions/scalar/list_functions.hpp
Labels: Ready To Merge

#13063 Add pragma extension versions
  src/function/pragma/pragma_queries.cpp
  test/sql/pragma/test_pragma_version.test
Labels: Ready To Merge

#13190 Add test_collate_pivot: used to fail in 1.0.0, add to avoid regressions
  test/sql/collate/test_collate_pivot.test
Labels: Ready For Review

#13191 Add catalog_error_max_schemas setting that toggles how many schemas we look at for "did you mean..." style error messages
  src/catalog/catalog.cpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/settings/settings.cpp
  test/sql/attach/attach_did_you_mean.test
Labels: Needs Documentation

#13194 Fix build error when compiling with -DDISABLE_EXTENSION_LOAD=1
  src/main/extension/extension_install.cpp
  src/main/extension/extension_load.cpp
Labels: Ready To Merge

#13158 Add clang-tidy-diff script, and invoke it on PRs
  .github/workflows/CodeQuality.yml
  Makefile
  scripts/clang-tidy-diff.py
Labels: Ready For Review

#13216 Fixup invocation of clang-tidy
  .github/workflows/CodeQuality.yml
Labels: Ready To Merge

#13156 Linux 32: avoid packaging Jemalloc, due to regression
  .github/workflows/NightlyTests.yml
Labels: Ready For Review

#13170 fix: 13077: use tmp file for secret writes
  src/main/secret/secret_storage.cpp
Labels: Ready For Review

#13220 Filter paths before scripts/clang-tidy-diff.py
  Makefile
Labels: Ready For Review

#13207 [CSV Reader/Progress Bar] Fixes
  data/csv/big_escape.csv
  src/common/progress_bar/progress_bar.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/include/duckdb/common/numeric_utils.hpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  test/sql/copy/csv/auto/test_csv_auto.test
  test/sql/copy/csv/test_escape_long_value.test
Labels: CI Failure

#13162 [CSV Reader] Comment Option
  data/csv/comments/big.csv
  data/csv/comments/empty_space.csv
  data/csv/comments/error.csv
  data/csv/comments/invalid_rows.csv
  data/csv/comments/mid_line.csv
  data/csv/comments/mid_line_header.csv
  data/csv/comments/mid_line_invalid.csv
  data/csv/comments/mid_line_null.csv
  data/csv/comments/mid_line_quote.csv
  data/csv/comments/midline_big.csv
  data/csv/comments/midline_empty_space.csv
  data/csv/comments/mixed_options.csv
  data/csv/comments/only_midline.csv
  data/csv/comments/simple.csv
  data/csv/comments/simple_comma.csv
  data/csv/comments/simple_mid_line.csv
  src/common/enum_util.cpp
  src/execution/operator/csv_scanner/scanner/column_count_scanner.cpp
  src/execution/operator/csv_scanner/scanner/skip_scanner.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.cpp
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/function/table/copy_csv.cpp
  src/function/table/read_csv.cpp
  src/function/table/sniff_csv.cpp
  src/include/duckdb/execution/operator/csv_scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/column_count_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_reader_options.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_sniffer.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state_machine.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state_machine_cache.hpp
  src/include/duckdb/execution/operator/csv_scanner/skip_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine_options.hpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  src/include/duckdb/storage/serialization/nodes.json
  src/storage/serialization/serialize_nodes.cpp
  test/sql/copy/csv/code_cov/csv_type_detection.test
  test/sql/copy/csv/csv_null_padding.test
  test/sql/copy/csv/rejects/csv_rejects_read.test
  test/sql/copy/csv/test_comment_midline.test
  test/sql/copy/csv/test_comment_option.test
  test/sql/copy/csv/test_csv_remote.test
  test/sql/copy/csv/test_skip.test_slow
  test/sql/copy/csv/test_sniff_csv.test
  test/sql/copy/csv/test_sniff_csv_options.test
Labels: Ready To Merge
