Repository duckdb/duckdb, pull requests merged in 2024-01, with the labels that each got.

#9499 [WIP] Support dot notation for JSON
  extension/json/include/json_common.hpp
  extension/json/json_extension.cpp
  extension/json/json_functions.cpp
  extension/json/json_functions/json_array_length.cpp
  extension/json/json_functions/json_contains.cpp
  extension/json/json_functions/json_create.cpp
  extension/json/json_functions/json_extract.cpp
  extension/json/json_functions/json_keys.cpp
  extension/json/json_functions/json_merge_patch.cpp
  extension/json/json_functions/json_serialize_plan.cpp
  extension/json/json_functions/json_serialize_sql.cpp
  extension/json/json_functions/json_structure.cpp
  extension/json/json_functions/json_transform.cpp
  extension/json/json_functions/json_type.cpp
  extension/json/json_functions/json_valid.cpp
  extension/json/json_functions/read_json_objects.cpp
  src/common/types.cpp
  src/include/duckdb/common/types.hpp
  src/planner/binder/expression/bind_operator_expression.cpp
  test/sql/json/scalar/json_nested_casts.test
  test/sql/json/scalar/test_json_dot_syntax.test
Labels: Ready To Merge

#9909 Add list_reduce lambda function
  benchmark/micro/lambdas/list_reduce/complex_expression.benchmark
  benchmark/micro/lambdas/list_reduce/list_length_2.benchmark
  benchmark/micro/lambdas/list_reduce/list_length_5000.benchmark
  benchmark/micro/lambdas/list_reduce/list_variable_length.benchmark
  benchmark/micro/lambdas/list_reduce/varchar.benchmark
  src/core_functions/function_list.cpp
  src/core_functions/lambda_functions.cpp
  src/core_functions/scalar/list/CMakeLists.txt
  src/core_functions/scalar/list/functions.json
  src/core_functions/scalar/list/list_reduce.cpp
  src/execution/expression_executor.cpp
  src/include/duckdb/core_functions/lambda_functions.hpp
  src/include/duckdb/core_functions/scalar/list_functions.hpp
  test/sql/function/list/lambdas/incorrect.test
  test/sql/function/list/lambdas/lambdas_and_macros.test
  test/sql/function/list/lambdas/reduce.test
  test/sql/function/list/lambdas/storage.test
  test/sql/function/list/lambdas/table_functions.test
  test/sql/function/list/lambdas/vector_types.test
Labels: Needs Documentation, Ready For Review

#9918 Handle s3_endpoint that includes path
  extension/httpfs/include/s3fs.hpp
  extension/httpfs/s3fs.cpp
  test/sql/copy/s3/fully_qualified_s3_url.test
Labels: Ready To Merge

#10103 Update year in license file to 2024
  LICENSE
  tools/juliapkg/LICENSE
  tools/swift/duckdb-swift/Examples/SwiftUI/ExoplanetExplorer/ContentView.swift
  tools/swift/duckdb-swift/Examples/SwiftUI/ExoplanetExplorer/ErrorView.swift
  tools/swift/duckdb-swift/Examples/SwiftUI/ExoplanetExplorer/ExoplanetStore.swift
  tools/swift/duckdb-swift/Examples/SwiftUI/ExoplanetExplorer/ExplorerApp.swift
  tools/swift/duckdb-swift/LICENSE
  tools/swift/duckdb-swift/Sources/DuckDB/Appender.swift
  tools/swift/duckdb-swift/Sources/DuckDB/CodingUserInfoKeys.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Column.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Configuration.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Connection.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Database.swift
  tools/swift/duckdb-swift/Sources/DuckDB/DatabaseError.swift
  tools/swift/duckdb-swift/Sources/DuckDB/DatabaseType.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Extensions/Column+TabularData.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Extensions/Date+Foundation.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Extensions/Decimal+IntHuge.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Extensions/Time+Foundation.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Extensions/Timestamp+Foundation.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Internal/CTypeUtilities.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Internal/DataChunk.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Internal/DecimalStorageType.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Internal/Optional+CString.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Internal/PrimitiveDatabaseValue.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Internal/Vector.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Internal/VectorElementDecoder.swift
  tools/swift/duckdb-swift/Sources/DuckDB/LogicalType.swift
  tools/swift/duckdb-swift/Sources/DuckDB/PreparedStatement.swift
  tools/swift/duckdb-swift/Sources/DuckDB/ResultSet.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Types/Date.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Types/Interval.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Types/Time.swift
  tools/swift/duckdb-swift/Sources/DuckDB/Types/Timestamp.swift
  tools/swift/duckdb-swift/Tests/DuckDBTests/AppenderTests.swift
  tools/swift/duckdb-swift/Tests/DuckDBTests/CodingUserInfoKeysTests.swift
  tools/swift/duckdb-swift/Tests/DuckDBTests/DatabaseTests.swift
  tools/swift/duckdb-swift/Tests/DuckDBTests/DecimalUtilityTests.swift
  tools/swift/duckdb-swift/Tests/DuckDBTests/ExtensionTests.swift
  tools/swift/duckdb-swift/Tests/DuckDBTests/LogicalTypeTests.swift
  tools/swift/duckdb-swift/Tests/DuckDBTests/PreparedStatementTests.swift
  tools/swift/duckdb-swift/Tests/DuckDBTests/TypeConversionTests.swift
Labels: Ready To Merge

#10104 Not including stdlib for just size_t, stddef is smaller header
  src/include/duckdb.h
Labels: Ready For Review

#10102 Bump iceberg extension version
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#10055 Internal #783: ICU DatePart Serializers
  extension/icu/icu-datefunc.cpp
  extension/icu/icu-datepart.cpp
  extension/icu/include/icu-datefunc.hpp
Labels: Ready For Review

#10111 CI: Add backlink to original issue when its status changes
  .github/workflows/InternalIssuesUpdateMirror.yml
Labels: Ready For Review

#10116 Streamline handling issues that come with PRs fixing them
  .github/workflows/InternalIssuesCreateMirror.yml
Labels: Ready For Review

#10113 Fix ParquetScanMaxThreads.
  extension/parquet/parquet_extension.cpp
Labels: Ready To Merge

#10119 CI: Create separate job for handling 'PR submitted' label
  .github/workflows/InternalIssuesCreateMirror.yml
Labels: Ready For Review

#10142 Issue #10140: NULL Constant Lists
  src/function/cast/list_casts.cpp
  test/fuzzer/duckfuzz/list_try_cast.test
Labels: Ready To Merge

#10137 Build manylinux_2_28 arm python wheels
  .github/workflows/Python.yml
Labels: Ready To Merge

#9957 Slightly improve performance of the `first` aggregate function
  benchmark/micro/list/string_split_unicode.benchmark
  src/core_functions/scalar/string/string_split.cpp
  src/function/aggregate/distributive/first.cpp
Labels: Ready To Merge

#9672 Add csv & parquet write functions and toPandas to experimental PySpark API
  tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
  tools/pythonpkg/duckdb/experimental/spark/sql/readwriter.py
  tools/pythonpkg/tests/fast/spark/test_spark_pandas_dataframe.py
  tools/pythonpkg/tests/fast/spark/test_spark_to_csv.py
  tools/pythonpkg/tests/fast/spark/test_spark_to_parquet.py
Labels: Changes Requested

#9883 Add handling for duckdb-wasm extensions in extension-upload-from-nightly
  scripts/extension-upload-from-nightly.sh
Labels: Ready For Review

#10146 Serialization for scalar functions nextval and currval
  src/catalog/catalog_entry/sequence_catalog_entry.cpp
  src/function/scalar/sequence/nextval.cpp
  src/include/duckdb/function/scalar/sequence_functions.hpp
Labels: Changes Requested

#10110 Pushdown filters into semi and anti joins
  src/include/duckdb/optimizer/filter_pushdown.hpp
  src/optimizer/filter_pushdown.cpp
  src/optimizer/pushdown/CMakeLists.txt
  src/optimizer/pushdown/pushdown_semi_anti_join.cpp
  test/optimizer/pushdown_semi_anti_join.test
  test/optimizer/pushdown_set_op.test
Labels: Ready For Review

#10045 Issue #9950: Ordered Aggregate Performance
  benchmark/micro/aggregate/ordered_first.benchmark
  src/common/types/list_segment.cpp
  src/execution/operator/aggregate/physical_ungrouped_aggregate.cpp
  src/function/aggregate/sorted_aggregate_function.cpp
  test/sql/types/nested/array/array_list_agg.test
Labels: Ready For Review

#10117 `uhugeint_t`/`hugeint_t` operator changes
  src/common/operator/cast_operators.cpp
  src/common/types/hugeint.cpp
  src/common/types/uhugeint.cpp
  src/core_functions/scalar/math/numeric.cpp
  src/function/scalar/operators/add.cpp
  src/function/scalar/operators/arithmetic.cpp
  src/function/scalar/operators/multiply.cpp
  src/function/scalar/operators/subtract.cpp
  src/include/duckdb/common/types/hugeint.hpp
  src/include/duckdb/common/types/uhugeint.hpp
  src/optimizer/rule/move_constants.cpp
  test/sql/types/hugeint/test_hugeint_arithmetic.test
Labels: Ready To Merge

#10162 Infrastructure: truncate not always available in CI, use dd
  scripts/extension-upload-single.sh
Labels: Ready To Merge

#10151 JSON S3 optimization
  extension/json/buffered_json_reader.cpp
  extension/json/include/buffered_json_reader.hpp
  extension/json/include/json_scan.hpp
  extension/json/json_scan.cpp
  test/sql/copy/s3/upload_large_json_file.test_slow
Labels: Ready To Merge

#10038 Remove chunk collection from reservoir sampler
  .github/config/uncovered_files.csv
  extension/parquet/column_reader.cpp
  extension/parquet/column_writer.cpp
  extension/parquet/include/column_reader.hpp
  extension/parquet/parquet_extension.cpp
  src/common/symbols.cpp
  src/common/types/CMakeLists.txt
  src/common/types/chunk_collection.cpp
  src/common/types/vector_buffer.cpp
  src/common/vector_operations/vector_copy.cpp
  src/core_functions/aggregate/holistic/quantile.cpp
  src/core_functions/aggregate/holistic/reservoir_quantile.cpp
  src/core_functions/scalar/list/list_sort.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/operator/helper/physical_materialized_collector.cpp
  src/execution/operator/helper/physical_reservoir_sample.cpp
  src/execution/operator/join/physical_comparison_join.cpp
  src/execution/reservoir_sample.cpp
  src/function/cast/default_casts.cpp
  src/function/scalar/list/list_extract.cpp
  src/function/table/system/duckdb_optimizers.cpp
  src/function/table/system/duckdb_settings.cpp
  src/include/duckdb/common/types/chunk_collection.hpp
  src/include/duckdb/execution/operator/aggregate/physical_window.hpp
  src/include/duckdb/execution/operator/helper/physical_reservoir_sample.hpp
  src/include/duckdb/execution/operator/join/physical_blockwise_nl_join.hpp
  src/include/duckdb/execution/operator/join/physical_delim_join.hpp
  src/include/duckdb/execution/operator/join/physical_hash_join.hpp
  src/include/duckdb/execution/operator/join/physical_nested_loop_join.hpp
  src/include/duckdb/execution/operator/order/physical_order.hpp
  src/include/duckdb/execution/operator/order/physical_top_n.hpp
  src/include/duckdb/execution/operator/scan/csv/base_csv_reader.hpp
  src/include/duckdb/execution/operator/scan/physical_expression_scan.hpp
  src/include/duckdb/execution/physical_operator.hpp
  src/include/duckdb/execution/reservoir_sample.hpp
  src/include/duckdb/planner/operator/logical_cteref.hpp
  test/sql/sample/reservoir_testing_percentage.test_slow
  test/sql/sample/reservoir_testing_rows_value.test_slow
  test/sql/sample/same_seed_same_sample.test
  test/sql/sample/test_sample.test_slow
Labels: Ready To Merge

#10165 [Python] Fix issue in DataFrame construction where non-deduplicated names were being used mistakenly
  tools/pythonpkg/src/pyresult.cpp
  tools/pythonpkg/tests/fast/pandas/test_timestamp.py
Labels: Ready To Merge

#9993 Fix #9456 and improve Deliminator
  .github/patches/extensions/substrait/disable_tpch.patch
  src/common/enum_util.cpp
  src/common/enums/join_type.cpp
  src/common/enums/physical_operator_type.cpp
  src/common/tree_renderer.cpp
  src/execution/column_binding_resolver.cpp
  src/execution/operator/join/CMakeLists.txt
  src/execution/operator/join/physical_delim_join.cpp
  src/execution/operator/join/physical_join.cpp
  src/execution/operator/join/physical_left_delim_join.cpp
  src/execution/operator/join/physical_right_delim_join.cpp
  src/execution/operator/scan/physical_column_data_scan.cpp
  src/execution/physical_plan/plan_delim_join.cpp
  src/include/duckdb/common/enums/join_type.hpp
  src/include/duckdb/common/enums/physical_operator_type.hpp
  src/include/duckdb/execution/operator/join/physical_delim_join.hpp
  src/include/duckdb/execution/operator/join/physical_join.hpp
  src/include/duckdb/execution/operator/join/physical_left_delim_join.hpp
  src/include/duckdb/execution/operator/join/physical_right_delim_join.hpp
  src/include/duckdb/execution/operator/scan/physical_column_data_scan.hpp
  src/include/duckdb/optimizer/deliminator.hpp
  src/include/duckdb/optimizer/join_order/query_graph_manager.hpp
  src/include/duckdb/planner/operator/logical_comparison_join.hpp
  src/include/duckdb/storage/serialization/logical_operator.json
  src/main/query_profiler.cpp
  src/optimizer/deliminator.cpp
  src/optimizer/join_order/query_graph_manager.cpp
  src/optimizer/unnest_rewriter.cpp
  src/storage/serialization/serialize_logical_operator.cpp
  test/issues/general/test_4950.test
  test/issues/general/test_9456.test
  test/optimizer/deliminator.test
  test/optimizer/deliminator_optimizer.test
  test/optimizer/using_optimizer.test
  test/sql/join/test_nested_keys.test
  test/sql/join/test_nested_payloads.test
  test/sql/order/limit_full_outer_join.test
  test/sql/subquery/scalar/expression_get.test_slow
  test/sql/subquery/scalar/test_nested_correlated_subquery.test_slow
Labels: Ready To Merge

#10147 Temporary Memory Manager
  src/common/types/row/partitioned_tuple_data.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/operator/join/physical_join.cpp
  src/execution/operator/set/physical_union.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/common/optional_idx.hpp
  src/include/duckdb/common/types/row/partitioned_tuple_data.hpp
  src/include/duckdb/execution/aggregate_hashtable.hpp
  src/include/duckdb/execution/executor.hpp
  src/include/duckdb/execution/join_hashtable.hpp
  src/include/duckdb/execution/operator/join/physical_hash_join.hpp
  src/include/duckdb/parallel/event.hpp
  src/include/duckdb/parallel/meta_pipeline.hpp
  src/include/duckdb/storage/buffer/buffer_pool.hpp
  src/include/duckdb/storage/buffer_manager.hpp
  src/include/duckdb/storage/standard_buffer_manager.hpp
  src/include/duckdb/storage/temporary_memory_manager.hpp
  src/parallel/event.cpp
  src/parallel/executor.cpp
  src/parallel/meta_pipeline.cpp
  src/storage/CMakeLists.txt
  src/storage/buffer/buffer_pool.cpp
  src/storage/buffer_manager.cpp
  src/storage/standard_buffer_manager.cpp
  src/storage/temporary_memory_manager.cpp
  test/sql/join/external/many_external_joins.test_slow
  test/sql/join/external/simple_external_join.test_coverage
Labels: Changes Requested

#10107 Internal #425: TIMETZ Functions
  extension/icu/icu-timezone.cpp
  src/common/types/interval.cpp
  src/common/types/time.cpp
  src/common/types/timestamp.cpp
  src/common/types/value.cpp
  src/core_functions/scalar/date/date_part.cpp
  src/function/scalar/operators/add.cpp
  src/function/scalar/operators/arithmetic.cpp
  src/function/scalar/operators/subtract.cpp
  src/include/duckdb/common/operator/add.hpp
  src/include/duckdb/common/operator/subtract.hpp
  src/include/duckdb/common/types/datetime.hpp
  src/include/duckdb/common/types/interval.hpp
  src/include/duckdb/common/types/time.hpp
  src/include/duckdb/common/types/timestamp.hpp
  test/sql/function/date/test_date_part.test
  test/sql/function/operator/test_date_arithmetic.test
  test/sql/function/timetz/test_date_part.test
  test/sql/function/timetz/test_extract.test
  test/sql/storage_version/storage_version.db
  test/sql/timezone/test_icu_calendar.test
  test/sql/timezone/test_icu_timezone.test
  test/sql/types/interval/test_interval_addition.test
  test/sql/types/test_all_types.test_slow
  test/sql/types/time/test_time_tz.test
  tools/jdbc/src/main/java/org/duckdb/DuckDBTimestamp.java
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
  tools/juliapkg/test/test_all_types.jl
  tools/pythonpkg/tests/fast/test_all_types.py
Labels: Ready For Review

#9920 Implement FILE_SIZE_BYTES
  extension/json/json_functions/copy_json.cpp
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/parquet_extension.cpp
  src/execution/operator/persistent/physical_copy_to_file.cpp
  src/execution/physical_plan/plan_copy_to_file.cpp
  src/function/table/copy_csv.cpp
  src/include/duckdb/execution/operator/persistent/physical_copy_to_file.hpp
  src/include/duckdb/function/copy_function.hpp
  src/include/duckdb/planner/operator/logical_copy_to_file.hpp
  src/planner/binder/statement/bind_copy.cpp
  src/planner/operator/logical_copy_to_file.cpp
  test/sql/copy/file_size_bytes.test
  test/sql/copy/file_size_bytes_large.test_slow
  test/sql/copy/parquet/writer/row_group_size_bytes.test
Labels: Needs Documentation, Changes Requested

#10187 Handle 0-list maps (erroring out) and add test-case
  src/core_functions/scalar/map/map.cpp
  test/sql/types/map/map_empty.test
Labels: Ready To Merge

#10197 Internal #1001: SEM Test Determinism
  test/sql/aggregate/aggregates/test_sem.test
Labels: Ready For Review

#10032 More work towards Custom Indexes
  src/common/enum_util.cpp
  src/execution/index/CMakeLists.txt
  src/execution/index/art/art.cpp
  src/execution/index/index_type_set.cpp
  src/execution/index/unknown_index.cpp
  src/execution/physical_plan/plan_create_index.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/enums/index_constraint_type.hpp
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/index_type.hpp
  src/include/duckdb/execution/index/index_type_set.hpp
  src/include/duckdb/execution/index/unknown_index.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/storage/index.hpp
  src/include/duckdb/storage/serialization/create_info.json
  src/include/duckdb/storage/table/data_table_info.hpp
  src/include/duckdb/storage/table/table_index_list.hpp
  src/main/config.cpp
  src/main/database.cpp
  src/parser/transform/statement/transform_select_node.cpp
  src/storage/checkpoint_manager.cpp
  src/storage/data_table.cpp
  src/storage/local_storage.cpp
  src/storage/serialization/serialize_create_info.cpp
  src/storage/table/array_column_data.cpp
  src/storage/table_index_list.cpp
  src/storage/wal_replay.cpp
Labels: Changes Requested

#10199 fix: reject creation of persistent secrets when allow_persistent_secrets=false for storage backends other than local_file
  src/include/duckdb/main/secret/secret_storage.hpp
  src/main/secret/secret_manager.cpp
  test/secrets/test_custom_secret_storage.cpp
  test/sql/secrets/create_secret_storage_backends.test
Labels: Ready To Merge

#10190 prevent physical nested loop join with multiple conditions on semi an…
  src/execution/operator/join/physical_nested_loop_join.cpp
  test/sql/join/semianti/plan_blockwise_NL_join_with_mutliple_conditions.test
Labels: Ready For Review

#10182 chore: add `const` to BaseSecret and KeyValueSecret copy ctrs, fix compilation error
  src/include/duckdb/main/secret/secret.hpp
Labels: Ready For Review

#10220 fix: fix a bug where free_space was incorrectly calculated when flushing partial blocks
  src/storage/partial_block_manager.cpp
  src/storage/table/column_segment.cpp
Labels: Ready For Review

#10123 Fix Issue #10122: wrong result in IEJoin
  src/execution/operator/join/physical_range_join.cpp
  src/include/duckdb/execution/operator/join/physical_range_join.hpp
  test/sql/join/iejoin/test_iejoin_null_keys.test
Labels: Ready To Merge

#9971 Internal #861: Aggregation Absorb API
  src/common/enum_util.cpp
  src/common/row_operations/row_aggregate.cpp
  src/common/types/list_segment.cpp
  src/core_functions/aggregate/README.md
  src/core_functions/aggregate/nested/list.cpp
  src/execution/operator/aggregate/physical_ungrouped_aggregate.cpp
  src/execution/window_segment_tree.cpp
  src/function/scalar/system/aggregate_export.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/types/list_segment.hpp
  src/include/duckdb/function/aggregate_state.hpp
  test/sql/window/test_list_window.test
Labels: Ready For Review

#9976 Better Cardinality estimates for right and left semi/anti joins
  src/optimizer/join_order/join_order_optimizer.cpp
  src/optimizer/join_order/relation_statistics_helper.cpp
Labels: Ready For Review

#10188 Open JSON files lock-free if there are many
  extension/json/include/json.json
  extension/json/include/json_scan.hpp
  extension/json/json_functions/read_json.cpp
  extension/json/json_scan.cpp
  extension/json/serialize_json.cpp
  test/sql/json/table/read_json.test
  test/sql/json/table/read_json_auto.test_slow
Labels: Needs Documentation, Changes Requested

#10195 Bitpacking compression for the `UHUGEINT` type
  src/include/duckdb/common/bitpacking.hpp
  src/include/duckdb/common/hugeint.hpp
  src/include/duckdb/common/numeric_utils.hpp
  src/include/duckdb/common/uhugeint.hpp
  src/storage/compression/bitpacking.cpp
  src/storage/compression/bitpacking_hugeint.cpp
  test/sql/storage/compression/bitpacking/bitpacking_uhugeint.test
Labels: Ready For Review

#10217 fix: drop secret if exists on non-existing secret should not cause ex
  src/main/secret/secret_manager.cpp
  test/sql/secrets/create_secret_defaults.test
Labels: Ready To Merge

#10232 Replace 'embedded' with 'in-process' in the Python package description
  tools/pythonpkg/setup.py
Labels: Ready For Review

#10203 Remove duplicate columns in `PhysicalHashJoin`
  src/execution/join_hashtable.cpp
  src/execution/operator/join/perfect_hash_join_executor.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/include/duckdb/execution/join_hashtable.hpp
  src/include/duckdb/execution/operator/join/physical_hash_join.hpp
Labels: Ready To Merge

#10181 Internal #1022: Window TIME RANGE
  src/planner/binder/expression/bind_window_expression.cpp
  test/sql/window/test_window_range.test
Labels: Ready For Review

#10150 Lambda scoping
  src/include/duckdb/parser/expression/lambda_expression.hpp
  src/include/duckdb/parser/expression/lambdaref_expression.hpp
  src/include/duckdb/planner/expression_binder.hpp
  src/parser/expression/lambda_expression.cpp
  src/parser/expression/lambdaref_expression.cpp
  src/planner/binder/expression/bind_columnref_expression.cpp
  src/planner/binder/expression/bind_function_expression.cpp
  src/planner/binder/expression/bind_lambda.cpp
  src/planner/binder/expression/bind_macro_expression.cpp
  src/planner/binder/query_node/bind_table_macro_node.cpp
  src/planner/expression_binder.cpp
  src/planner/expression_binder/check_binder.cpp
  src/planner/expression_binder/table_function_binder.cpp
  test/sql/function/list/lambdas/incorrect.test
  test/sql/function/list/lambdas/lambda_scope.test
  test/sql/function/list/lambdas/lambdas_and_macros.test
  test/sql/function/list/list_intersect.test
Labels: Needs Documentation, Ready For Review

#10011 Add batch functionality
  tools/jdbc/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java
  tools/jdbc/src/main/java/org/duckdb/DuckDBPreparedStatement.java
  tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
Labels: Needs Documentation, Ready For Review

#10234 Make FILE_SIZE_BYTES test more lenient
  test/sql/copy/file_size_bytes.test
Labels: Ready To Merge

#10246 COPY - allow copy_file_name to be formatted as identifier
  test/sql/copy/parquet/writer/parquet_test_all_types.test
  third_party/libpg_query/grammar/statements/copy.y
  third_party/libpg_query/src_backend_parser_gram.cpp
  tools/shell/tests/test_read_from_stdin.py
Labels: Needs Documentation

#10226 chore: improvements to duckdb_api / user_agent
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/database.cpp
  src/main/settings/settings.cpp
  test/api/test_config.cpp
  tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp
Labels: Changes Requested

#10259 Issue #10249: Window Clause Casing
  src/include/duckdb/parser/transformer.hpp
  src/parser/transform/expression/transform_function.cpp
  test/sql/window/test_window_clause.test
Labels: Ready For Review

#10255 Enable intercepting file copy extension after binding
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/spatial/const_param_ifdeff_patch.patch
  .github/patches/extensions/spatial/copy_bind.patch
  Makefile
  extension/parquet/parquet_extension.cpp
  src/function/table/copy_csv.cpp
  src/include/duckdb/function/copy_function.hpp
  src/include/duckdb/main/extension_entries.hpp
  src/planner/binder/statement/bind_copy.cpp
  src/planner/operator/logical_copy_to_file.cpp
Labels: Ready To Merge

#10274 Issue #10272: DATE + INTERVAL
  benchmark/micro/cast/cast_date_string.benchmark
  src/function/scalar/operators/add.cpp
  src/function/scalar/operators/arithmetic.cpp
  src/function/scalar/operators/subtract.cpp
  src/include/duckdb/common/operator/add.hpp
  src/include/duckdb/common/operator/subtract.hpp
  test/issues/general/test_1933.test
  test/sql/aggregate/aggregates/test_quantile_disc.test
  test/sql/aggregate/aggregates/test_quantile_disc_list.test
  test/sql/function/date/date_add.test
  test/sql/function/date/test_extract_month.test
  test/sql/function/timestamp/date_diff.test_slow
  test/sql/function/timestamp/date_sub.test_slow
  test/sql/types/date/date_limits.test
  test/sql/types/date/test_bc_dates.test
  test/sql/types/interval/test_interval_addition.test
  test/sql/window/test_window_range.test
Labels: Ready For Review

#10208 Add parse_path(), parse_dirname() and parse_filename() functions
  src/core_functions/function_list.cpp
  src/core_functions/scalar/string/CMakeLists.txt
  src/core_functions/scalar/string/functions.json
  src/core_functions/scalar/string/parse_path.cpp
  src/include/duckdb/core_functions/scalar/string_functions.hpp
  test/sql/function/string/parse_path.test
  test/sql/function/string/parse_path_windows.test
Labels: Needs Documentation

#9545 Add function for non-bias-corrected kurtosis
  src/catalog/default/default_functions.cpp
  src/core_functions/aggregate/distributive/functions.json
  src/core_functions/aggregate/distributive/kurtosis.cpp
  src/core_functions/function_list.cpp
  src/include/duckdb/core_functions/aggregate/distributive_functions.hpp
  test/sql/aggregate/aggregates/test_kurtosis.test
  test/sql/function/list/aggregates/kurtosis.test
Labels: Needs Documentation, Ready For Review

#10297 Adapt further for z/OS
  third_party/mbedtls/library/entropy_poll.cpp
  tools/shell/linenoise.cpp
Labels: CI Failure

#10258 CSV Parser Optimizations: Pre-computed skip list. Simpler state machine transition. Flip state machine states and transitions.
  src/common/enum_util.cpp
  src/execution/operator/csv_scanner/scanner/base_scanner.cpp
  src/execution/operator/csv_scanner/scanner/column_count_scanner.cpp
  src/execution/operator/csv_scanner/scanner/skip_scanner.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/column_count_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/skip_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/string_value_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine/csv_state.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine/csv_state_machine.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.hpp
Labels: Ready For Review

#10301 Add table macro_definition to duckdb_functions()
  src/function/table/system/duckdb_functions.cpp
  test/sql/catalog/function/test_table_macro.test
  test/sql/table_function/duckdb_functions.test
Labels: Ready To Merge

#10307 [CSV Parser] Fix regression with dialect detection on quoted values.
  benchmark/micro/csv/sniffer_quotes.benchmark
  src/include/duckdb/execution/operator/csv_scanner/scanner/base_scanner.hpp
Labels: Ready For Review

#10306 CSV Reader making null padding Parallel by default
  .github/regression/csv.csv
  benchmark/micro/csv/null_padding.benchmark
  data/csv/evil_nullpadding.csv
  data/csv/evil_nullpadding_2.csv
  src/common/enum_util.cpp
  src/execution/operator/csv_scanner/scanner/column_count_scanner.cpp
  src/execution/operator/csv_scanner/scanner/skip_scanner.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/execution/operator/csv_scanner/util/csv_error.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/function/table/read_csv.cpp
  src/include/duckdb/execution/operator/csv_scanner/options/csv_reader_options.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/column_count_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/skip_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/string_value_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine/csv_state.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine/csv_state_machine.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.hpp
  src/include/duckdb/execution/operator/csv_scanner/util/csv_error.hpp
  src/include/duckdb/storage/serialization/nodes.json
  src/storage/serialization/serialize_nodes.cpp
  test/sql/copy/csv/test_parallel_nullpadding.test
Labels: Needs Documentation, Ready For Review

#10300 Remove spinlock for closing JSON files
  extension/json/buffered_json_reader.cpp
  extension/json/include/buffered_json_reader.hpp
  extension/json/include/json.json
  extension/json/include/json_scan.hpp
  extension/json/include/json_structure.hpp
  extension/json/json_functions/json_structure.cpp
  extension/json/json_functions/read_json.cpp
  extension/json/json_scan.cpp
  extension/json/serialize_json.cpp
  scripts/generate_serialization.py
  test/sql/json/table/read_json_auto.test_slow
Labels: Needs Documentation, Ready For Review

#10319 Fix NumericLimits<hugeint_t>::Minimum() * 0 case
  src/common/types/hugeint.cpp
  test/sql/types/hugeint/test_hugeint_arithmetic.test
Labels: Ready To Merge

#10243 Improve the check for glob in sniff_csv function.
  src/function/table/sniff_csv.cpp
  test/sql/copy/csv/test_csv_remote.test
Labels: Ready To Merge

#9656 Add an icon to the duckdb.exe shell executable
  logo/DuckDB.ico
  tools/shell/CMakeLists.txt
  tools/shell/rc/duckdb.rc
Labels: CI Failure

#9836 [Arrow] Support scanning REE (Run End Encoded) Arrow arrays
  src/common/types/vector.cpp
  src/function/table/arrow.cpp
  src/function/table/arrow/arrow_duck_schema.cpp
  src/function/table/arrow_conversion.cpp
  src/include/duckdb/common/types/vector.hpp
  src/include/duckdb/function/table/arrow.hpp
  src/include/duckdb/function/table/arrow/arrow_duck_schema.hpp
  tools/pythonpkg/tests/fast/arrow/test_arrow_run_end_encoding.py
Labels: Ready To Merge

#10335 [Compression] Fix Handling of -0.0 in ALP
  src/include/duckdb/storage/compression/alp/algorithm/alp.hpp
  test/sql/storage/compression/alp/alp_negative_numbers.test
Labels: Ready To Merge

#10340 Fail Regression test when difference in cardinalities is detected
  .github/workflows/Regression.yml
Labels: Ready To Merge

#10343 Feature: Digit separators in numeric literals
  src/common/operator/cast_operators.cpp
  src/parser/transform/expression/transform_constant.cpp
  test/sql/parser/digit_separators.test
  third_party/fast_float/fast_float/fast_float.h
  third_party/libpg_query/scan.l
  third_party/libpg_query/src_backend_parser_scan.cpp
Labels: Needs Documentation, Ready To Merge

#10359 Change extension_directory default
  src/function/table/arrow.cpp
  src/include/duckdb/main/extension_helper.hpp
  src/main/extension/extension_install.cpp
  src/main/extension/extension_load.cpp
Labels: Ready For Review

#10386 Fix MATERIALIZED CTE issue #10260
  src/planner/binder/query_node/bind_cte_node.cpp
  test/sql/cte/materialized/test_issue_10260.test
Labels: Ready To Merge

#10378 Add table_sample to TableStatistics (currently saved as nullptr)
  src/execution/reservoir_sample.cpp
  src/include/duckdb/execution/reservoir_sample.hpp
  src/include/duckdb/storage/serialization/nodes.json
  src/include/duckdb/storage/table/table_statistics.hpp
  src/storage/table/table_statistics.cpp
Labels: Ready To Merge

#10329 Extension metadata: detecting the platform
  .github/actions/build_extensions/action.yml
  .github/workflows/Java.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/OSX.yml
  .github/workflows/R.yml
  .github/workflows/_extension_distribution.yml
  CMakeLists.txt
  Makefile
  scripts/create_local_extension_repo.py
  src/function/table/version/pragma_version.cpp
  src/include/duckdb/common/platform.h
  tools/utils/test_platform.cpp
Labels: Ready For Review

#10392 Avoid requiring expected error message on original sqlite tests
  test/sqlite/sqllogic_parser.cpp
  test/sqlite/sqllogic_parser.hpp
  test/sqlite/sqllogic_test_runner.cpp
Labels: Ready For Review

#10380 Case insensitive extensions install & load
  src/include/duckdb/main/extension_helper.hpp
  src/main/extension/extension_alias.cpp
  src/main/extension/extension_install.cpp
  src/main/extension/extension_load.cpp
  test/extension/install_extension.test_slow
Labels: Ready To Merge

#10398 Platform detection: Fix thread sanitizer job passing absolute path
  .github/workflows/NightlyTests.yml
Labels: Ready To Merge

#10390 [CSV Reader] Implicit Casting and Projection Pushdown
  src/common/operator/cast_operators.cpp
  src/execution/operator/csv_scanner/scanner/base_scanner.cpp
  src/execution/operator/csv_scanner/scanner/column_count_scanner.cpp
  src/execution/operator/csv_scanner/scanner/skip_scanner.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/sniffer/header_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_refinement.cpp
  src/execution/operator/csv_scanner/state_machine/csv_state_machine.cpp
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/execution/operator/csv_scanner/util/csv_error.cpp
  src/include/duckdb/common/operator/double_cast_operator.hpp
  src/include/duckdb/common/operator/integer_cast_operator.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/column_count_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/string_value_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine/csv_state_machine.hpp
  src/include/duckdb/execution/operator/csv_scanner/table_function/csv_file_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/table_function/global_csv_state.hpp
  src/include/duckdb/execution/operator/csv_scanner/util/csv_casting.hpp
  src/include/duckdb/execution/operator/csv_scanner/util/csv_error.hpp
  test/parallel_csv/test_parallel_csv.cpp
  test/sql/copy/csv/7702.test
  test/sql/copy/csv/code_cov/csv_type_refinement.test
  test/sql/copy/csv/parallel/csv_parallel_clickbench.test_slow
  test/sql/copy/csv/test_force_not_null.test
  test/sql/copy/csv/test_union_by_name.test
  test/unittest.cpp
Labels: Ready For Review

#10403 CI: Fix workflow to check new issues for code formatting by using heredoc
  .github/workflows/CheckIssueForCodeFormatting.yml
Labels: Ready For Review
