Repository duckdb/duckdb, pull requests merged in 2024-02, with the labels that each got.

#10185 Fix drop secret bug
  src/common/enum_util.cpp
  src/execution/operator/schema/physical_drop.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/main/secret/secret_manager.hpp
  src/include/duckdb/main/secret/secret_storage.hpp
  src/include/duckdb/parser/parsed_data/drop_info.hpp
  src/include/duckdb/parser/parsed_data/extra_drop_info.hpp
  src/include/duckdb/storage/serialization/extra_drop_info.json
  src/include/duckdb/storage/serialization/parse_info.json
  src/main/secret/secret_manager.cpp
  src/main/secret/secret_storage.cpp
  src/parser/parsed_data/CMakeLists.txt
  src/parser/parsed_data/drop_info.cpp
  src/parser/parsed_data/extra_drop_info.cpp
  src/parser/transform/statement/transform_drop.cpp
  src/storage/serialization/CMakeLists.txt
  src/storage/serialization/serialize_extra_drop_info.cpp
  src/storage/serialization/serialize_parse_info.cpp
  test/secrets/test_custom_secret_storage.cpp
  test/sql/secrets/create_secret_name_conflicts.test
  test/sql/secrets/create_secret_r2.test
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Ready For Review

#10405 Issue template: Ask about testing with the nightly build (instead of 'main')
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready For Review

#10411 [CSV Reader] Use array instead of unordered_map in projection pushdown
  .github/regression/csv.csv
  benchmark/micro/csv/projection_pushdown.benchmark
  benchmark/micro/csv/read.benchmark
  benchmark/micro/csv/sniffer.benchmark
  benchmark/micro/csv/sniffer_quotes.benchmark
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/string_value_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/table_function/csv_file_scanner.hpp
  test/sql/copy/csv/rejects/csv_rejects_recovery.test
  test/sql/copy/csv/test_csv_projection_pushdown.test
Labels: Ready For Review

#10401 [C-API] Add duckdb_appender_column_type
  src/include/duckdb.h
  src/main/appender.cpp
  src/main/capi/appender-c.cpp
  test/api/capi/test_capi_data_chunk.cpp
Labels: Ready To Merge

#10376 Add `read_text` and `read_blob` table functions
  src/function/table/CMakeLists.txt
  src/function/table/range.cpp
  src/function/table/read_file.cpp
  src/include/duckdb/function/table/list.hpp
  src/include/duckdb/function/table/range.hpp
  test/sql/table_function/files/four.blob
  test/sql/table_function/files/one.txt
  test/sql/table_function/files/three.txt
  test/sql/table_function/files/two.txt
  test/sql/table_function/read_text_and_blob.test
Labels: Needs Documentation, Changes Requested

#10347 Issue #10224: FIRST ORDER BY
  benchmark/micro/aggregate/sorted_last.benchmark
  src/common/vector_operations/vector_copy.cpp
  src/core_functions/aggregate/distributive/arg_min_max.cpp
  src/core_functions/aggregate/distributive/functions.json
  src/core_functions/function_list.cpp
  src/core_functions/scalar/blob/create_sort_key.cpp
  src/include/duckdb/core_functions/aggregate/distributive_functions.hpp
  src/optimizer/rule/ordered_aggregate_optimizer.cpp
  test/sql/aggregate/aggregates/test_arg_min_max_null.test
  test/sql/aggregate/aggregates/test_arg_min_max_null_nested.test
  test/sql/aggregate/aggregates/test_arg_min_max_null_strings.test
Labels: Ready For Review

#10420 Python: fix exception hierarchy, and also catch std::exception
  tools/pythonpkg/src/common/exceptions.cpp
  tools/pythonpkg/tests/fast/udf/test_scalar_arrow.py
Labels: Ready For Review

#10430 Add cloudflare invalidation to nightly deploy script
  scripts/extension-upload-from-nightly.sh
Labels: Ready For Review

#10445 fix(py): fix building python binding from cmake
  .github/workflows/coverity.yml
  CMakeLists.txt
  scripts/format.py
  tools/pythonpkg/setup.py
Labels: Ready For Review

#10457 Issue #10224: ORDERED FIRST Rewrite
  src/function/aggregate/sorted_aggregate_function.cpp
  src/include/duckdb/planner/bound_result_modifier.hpp
  src/optimizer/rule/ordered_aggregate_optimizer.cpp
  src/planner/bound_result_modifier.cpp
Labels: Ready To Merge

#10449 add support for date, time, timestamp types to the Julia appender api
  tools/juliapkg/src/api.jl
  tools/juliapkg/src/appender.jl
  tools/juliapkg/src/ctypes.jl
  tools/juliapkg/test/test_appender.jl
Labels: CI Failure

#10442 Bugfix/#10441 correctly validate second colon in jdbc url parameter in Java client.
  tools/jdbc/src/main/java/org/duckdb/DuckDBConnection.java
  tools/jdbc/src/test/java/org/duckdb/TestDuckDBJDBC.java
Labels: Changes Requested

#10471 Group together index instantiation parameters into a struct, pass options map as well.
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/index_type.hpp
  src/storage/table_index_list.cpp
  src/storage/wal_replay.cpp
Labels: Ready To Merge

#10473 [Bug Fix] [CSV Reader] Fix to using null_padding in conjunction to one of the multifile reader options
  data/csv/bug_10283.csv
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  test/sql/copy/csv/bug_10283.test
Labels: Ready To Merge

#10484 Use `CMAKE_CURRENT_BINARY_DIR` in CMakeLists
  CMakeLists.txt
Labels: Ready To Merge

#10492 Avoid setting `DUCKDB_NORMALIZED_VERSION` to an empty string
  CMakeLists.txt
Labels: Ready To Merge

#10483 Nested Array Validity Fixes + `RowOperations`
  src/common/row_operations/row_gather.cpp
  src/common/row_operations/row_heap_gather.cpp
  src/common/row_operations/row_heap_scatter.cpp
  src/common/row_operations/row_scatter.cpp
  src/common/types/vector.cpp
  src/common/types/vector_cache.cpp
  src/include/duckdb/common/row_operations/row_operations.hpp
  src/include/duckdb/common/types/validity_mask.hpp
  src/storage/compression/validity_uncompressed.cpp
  test/sql/types/nested/array/array_compression.test_slow
  test/sql/types/nested/array/array_sort.test
Labels: Ready To Merge

#10459 Keep file extension for temporary files
  src/common/file_system.cpp
  src/common/string_util.cpp
  src/execution/operator/persistent/physical_copy_to_file.cpp
  src/execution/physical_plan/plan_copy_to_file.cpp
  src/include/duckdb/common/string_util.hpp
  test/common/test_string_util.cpp
  test/sql/copy/tmp_file.test
Labels: Ready To Merge

#10509 [CSV Reader] Avoid unnecessary writes to temporary file when reading in limited memory cases
  src/execution/operator/csv_scanner/buffer_manager/csv_buffer.cpp
  src/execution/operator/csv_scanner/buffer_manager/csv_buffer_manager.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/include/duckdb/execution/operator/csv_scanner/buffer_manager/csv_buffer.hpp
  src/include/duckdb/execution/operator/csv_scanner/buffer_manager/csv_buffer_manager.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner/string_value_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/table_function/csv_file_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/table_function/global_csv_state.hpp
  test/sql/copy/csv/csv_memory_management.test_slow
Labels: Ready To Merge

#10510 [Dev] Fix ASAN thread limit exceeded issue in CI
  .github/workflows/NightlyTests.yml
Labels: Ready To Merge

#10512 [Dev] Cancel tasks in EndQueryInternal
  src/main/client_context.cpp
Labels: Ready To Merge

#10357 Decorrelation and parallelization of recursive and materialized CTEs
  src/execution/operator/scan/physical_column_data_scan.cpp
  src/execution/operator/set/physical_cte.cpp
  src/execution/operator/set/physical_recursive_cte.cpp
  src/execution/physical_plan/plan_cte.cpp
  src/execution/physical_plan/plan_recursive_cte.cpp
  src/include/duckdb/execution/executor.hpp
  src/include/duckdb/execution/operator/set/physical_cte.hpp
  src/include/duckdb/execution/operator/set/physical_recursive_cte.hpp
  src/include/duckdb/execution/physical_plan_generator.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/operator/logical_cteref.hpp
  src/include/duckdb/planner/operator/logical_recursive_cte.hpp
  src/include/duckdb/planner/subquery/flatten_dependent_join.hpp
  src/include/duckdb/planner/subquery/rewrite_cte_scan.hpp
  src/parallel/executor.cpp
  src/planner/binder/query_node/bind_cte_node.cpp
  src/planner/binder/query_node/bind_recursive_cte_node.cpp
  src/planner/binder/query_node/plan_cte_node.cpp
  src/planner/binder/query_node/plan_recursive_cte_node.cpp
  src/planner/binder/query_node/plan_setop.cpp
  src/planner/binder/query_node/plan_subquery.cpp
  src/planner/binder/tableref/plan_cteref.cpp
  src/planner/expression_iterator.cpp
  src/planner/subquery/CMakeLists.txt
  src/planner/subquery/flatten_dependent_join.cpp
  src/planner/subquery/rewrite_cte_scan.cpp
  test/fuzzer/pedro/recursive_cte_dependent_join.test
  test/issues/general/test_2743.test
  test/sql/cte/materialized/recursive_hang_2745_materialized.test
  test/sql/cte/materialized/test_correlated_recursive_cte_materialized.test
  test/sql/cte/test_correlated_recursive_cte.test
Labels: Ready For Review

#10526 Use null cast instead of reinterpret for NULL -> JSON
  extension/json/json_functions.cpp
Labels: Ready To Merge

#10527 Linenoise: make ENTER behave more similarly to other CLI clients - Ctrl+X can now be used to enter newlines at the cursor position
  tools/shell/linenoise.cpp
  tools/shell/linenoise/LICENSE
  tools/shell/linenoise/linenoise.cpp
  tools/shell/linenoise_LICENSE
Labels: Needs Documentation

#10488 [Python][Dev] Add `PYTHON_EDITABLE_BUILD` to Makefile
  .github/workflows/coverity.yml
  CMakeLists.txt
  Makefile
Labels: Changes Requested

#10408 feat(jdbc): setDate
  tools/jdbc/src/jni/duckdb_java.cpp
  tools/jdbc/src/main/java/org/duckdb/DuckDBDate.java
  tools/jdbc/src/main/java/org/duckdb/DuckDBPreparedStatement.java
  tools/jdbc/src/test/java/org/duckdb/TestDuckDBJDBC.java
Labels: Changes Requested

#10485 Require at least 1 argument when calling ListZip during bind
  src/function/scalar/list/list_zip.cpp
  test/fuzzer/duckfuzz/list_zip_no_args.test
Labels: Ready To Merge

#10487 Simplify binary-search in FindRunIndex
  src/function/table/arrow_conversion.cpp
Labels: Ready For Review

#10557 [CSV Reader] Reset state on quoted/escaped when applying projection pushdown
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
Labels: Ready To Merge

#10560 Fix a few tests failing non-deterministically with ALTERNATIVE_VERIFY=1
  test/sql/cte/recursive_hang_2745.test
  test/sql/function/list/list_reverse.test
  test/sql/join/left_outer/test_left_join_on_true.test
  test/sql/types/list/unnest_null_empty.test
Labels: Ready To Merge

#10582 extension_distribution.yml: Pass DUCKDB_PLATFORM
  .github/workflows/_extension_distribution.yml
Labels: Ready To Merge

#10513 Fix Nested Array TupleData Serialization
  src/common/enum_util.cpp
  src/common/radix_partitioning.cpp
  src/common/row_operations/row_matcher.cpp
  src/common/types.cpp
  src/common/types/row/tuple_data_collection.cpp
  src/common/types/row/tuple_data_scatter_gather.cpp
  src/common/types/vector.cpp
  src/execution/aggregate_hashtable.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/join/perfect_hash_join_executor.cpp
  src/function/cast/list_casts.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/types.hpp
  src/include/duckdb/common/types/row/tuple_data_collection.hpp
  src/include/duckdb/common/types/row/tuple_data_states.hpp
  src/include/duckdb/common/types/vector.hpp
  test/sql/types/nested/array/array_tupleformat.test
Labels: Ready To Merge

#10553 Do not replace filters that evaluate to always true
  src/optimizer/statistics/operator/propagate_filter.cpp
  test/fuzzer/duckfuzz/duck_fuzz_column_binding_tests.test
  test/optimizer/statistics/statistics_between.test
Labels: Ready For Review

#10202 [Dev] Fix triggered assertion in `SortedAggregateState::FlushChunks` caused by a small STANDARD_VECTOR_SIZE
  src/function/aggregate/sorted_aggregate_function.cpp
  src/include/duckdb/common/helper.hpp
Labels: Ready To Merge

#10600 minor secret manager fix
  src/main/database.cpp
  src/main/secret/secret_manager.cpp
  test/secrets/test_custom_secret_storage.cpp
  test/sql/secrets/create_secret_storage_backends.test
  tools/pythonpkg/tests/fast/api/test_config.py
Labels: Ready To Merge

#10592 Point error message to stable link
  src/common/local_file_system.cpp
Labels: Ready For Review

#10604 Fix issue in aggregate HT where a task could be blocked and never be unblocked if the aggregation was interrupted early due to e.g. a limit
  src/execution/radix_partitioned_hashtable.cpp
  test/sql/aggregate/aggregates/aggregate_limit.test_slow
Labels: Ready To Merge

#10607 Secret folder
  src/main/secret/secret_manager.cpp
  test/sql/secrets/create_secret_scope_matching.test
  test/sql/secrets/create_secret_storage_backends.test
Labels: Ready To Merge

#10649 Add explicit numbering to C enums + various compilation/CI fixes
  CMakeLists.txt
  extension/httpfs/httpfs_config.py
  src/common/local_file_system.cpp
  src/include/duckdb.h
  test/sql/secrets/create_secret_non_writable_persistent_dir.test
  tools/juliapkg/src/ctypes.jl
Labels: Ready To Merge

#10650 Disable print method for CSV scanner for R build
  src/execution/operator/csv_scanner/scanner/scanner_boundary.cpp
Labels: Ready To Merge

#10654 Fix #10548 for the DUCKDB_NO_THREADS case
  src/parallel/task_scheduler.cpp
Labels: Ready To Merge

#10643 Allow StorageExtension to extend DuckCatalog implementation in order to integration with observability system
  src/include/duckdb/transaction/duck_transaction_manager.hpp
  src/main/attached_database.cpp
  src/transaction/duck_transaction_manager.cpp
Labels: Ready To Merge

#10660 Update storage info for v0.10.0
  src/storage/storage_info.cpp
Labels: Ready To Merge

#10669 Catch: prominently display skipped tests
  scripts/run_tests_one_by_one.py
  test/sqlite/sqllogic_test_runner.cpp
  third_party/catch/catch.hpp
Labels: Ready To Merge

#10341 Ingestion benchmark framework
  .github/regression/ingestion.csv
  .github/workflows/Regression.yml
  benchmark/include/interpreted_benchmark.hpp
  benchmark/ingestion/in_memory_db/tpcds/csv/ingest_customer_demographics.benchmark
  benchmark/ingestion/in_memory_db/tpcds/csv/ingest_inventory.benchmark
  benchmark/ingestion/in_memory_db/tpcds/csv/ingest_store_sales.benchmark
  benchmark/ingestion/in_memory_db/tpcds/native/ingest_customer_demographics.benchmark
  benchmark/ingestion/in_memory_db/tpcds/native/ingest_inventory.benchmark
  benchmark/ingestion/in_memory_db/tpcds/native/ingest_store_sales.benchmark
  benchmark/ingestion/in_memory_db/tpcds/native/load_native.sql
  benchmark/ingestion/in_memory_db/tpcds/native/tpcds_ingest_native.benchmark.in
  benchmark/ingestion/in_memory_db/tpcds/parquet/ingest_customer_demographics.benchmark
  benchmark/ingestion/in_memory_db/tpcds/parquet/ingest_inventory.benchmark
  benchmark/ingestion/in_memory_db/tpcds/parquet/ingest_store_sales.benchmark
  benchmark/ingestion/in_memory_db/tpcds/tpcds_ingestion_in_memory.benchmark.in
  benchmark/ingestion/in_memory_db/tpch/csv/ingest_lineitem.benchmark
  benchmark/ingestion/in_memory_db/tpch/csv/ingest_orders.benchmark
  benchmark/ingestion/in_memory_db/tpch/native/ingest_lineitem.benchmark
  benchmark/ingestion/in_memory_db/tpch/native/ingest_orders.benchmark
  benchmark/ingestion/in_memory_db/tpch/native/load_native.sql
  benchmark/ingestion/in_memory_db/tpch/native/tpch_ingest_native.benchmark.in
  benchmark/ingestion/in_memory_db/tpch/parquet/ingest_lineitem.benchmark
  benchmark/ingestion/in_memory_db/tpch/parquet/ingest_orders.benchmark
  benchmark/ingestion/in_memory_db/tpch/tpch_ingestion_in_memory.benchmark.in
  benchmark/ingestion/load_tpcds.sql
  benchmark/ingestion/load_tpch.sql
  benchmark/ingestion/persistent_storage/tpcds/csv/ingest_inventory.benchmark
  benchmark/ingestion/persistent_storage/tpcds/csv/ingest_store_sales.benchmark
  benchmark/ingestion/persistent_storage/tpcds/native/ingest_inventory.benchmark
  benchmark/ingestion/persistent_storage/tpcds/native/ingest_store_sales.benchmark
  benchmark/ingestion/persistent_storage/tpcds/parquet/ingest_inventory.benchmark
  benchmark/ingestion/persistent_storage/tpcds/parquet/ingest_store_sales.benchmark
  benchmark/ingestion/persistent_storage/tpcds/tpcds_ingestion_persistent.benchmark.in
  benchmark/ingestion/persistent_storage/tpch/csv/ingest_lineitem.benchmark
  benchmark/ingestion/persistent_storage/tpch/csv/ingest_orders.benchmark
  benchmark/ingestion/persistent_storage/tpch/native/ingest_lineitem.benchmark
  benchmark/ingestion/persistent_storage/tpch/native/ingest_orders.benchmark
  benchmark/ingestion/persistent_storage/tpch/parquet/ingest_lineitem.benchmark
  benchmark/ingestion/persistent_storage/tpch/parquet/ingest_orders.benchmark
  benchmark/ingestion/persistent_storage/tpch/tpch_ingestion_persistent.benchmark.in
  benchmark/interpreted_benchmark.cpp
Labels: Ready For Review

#9539 [ICU] Add casts from Timestamp_* to TimestampTZ
  extension/icu/icu-timezone.cpp
  extension/parquet/column_writer.cpp
  extension/parquet/parquet_timestamp.cpp
  src/common/operator/cast_operators.cpp
  src/common/types/timestamp.cpp
  src/core_functions/scalar/date/date_diff.cpp
  src/core_functions/scalar/date/date_part.cpp
  src/function/cast/time_casts.cpp
  src/include/duckdb/common/types/timestamp.hpp
  src/main/capi/result-c.cpp
  src/optimizer/statistics/expression/propagate_cast.cpp
  test/sql/cast/test_string_cast.test
  test/sql/function/timestamp/test_date_part.test
  test/sql/types/timestamp/infinity_cast_coverage.test
  test/sql/types/timestamp/test_timestamp_to_tz_cast.test
  tools/odbc/statement_functions.cpp
  tools/pythonpkg/src/arrow/arrow_array_stream.cpp
  tools/pythonpkg/src/native/python_objects.cpp
  tools/pythonpkg/src/numpy/array_wrapper.cpp
  tools/pythonpkg/src/numpy/numpy_scan.cpp
  tools/pythonpkg/tests/fast/arrow/test_timestamps.py
  tools/pythonpkg/tests/fast/pandas/test_datetime_timestamp.py
Labels: Ready For Review

#10684 DISTINCT ON - greatly improve performance by rewriting ordered FIRST aggregate into arg_min_null
  benchmark/tpch/aggregate/lineitem_distinct_on_few_groups.benchmark
  benchmark/tpch/aggregate/lineitem_distinct_on_many_groups.benchmark
  src/execution/physical_plan/plan_distinct.cpp
  src/include/duckdb/optimizer/rule/ordered_aggregate_optimizer.hpp
  src/optimizer/rule/ordered_aggregate_optimizer.cpp
  test/sql/aggregate/distinct/distinct_on_nulls.test
  test/sql/aggregate/distinct/issue8505.test
Labels: Ready For Review

#10448 Use assertThrows for throwing assertions in JDBC tests
  tools/jdbc/src/test/java/org/duckdb/TestDuckDBJDBC.java
  tools/jdbc/src/test/java/org/duckdb/test/Assertions.java
Labels: Ready For Review

#10717 Fix duckdb spelling in _extension_deploy.yml
  .github/workflows/_extension_deploy.yml
Labels: Ready To Merge

#10728 Fuzzer #1374: ARG_XXX By Decimal
  src/core_functions/aggregate/distributive/arg_min_max.cpp
  test/fuzzer/duckfuzz/arg_minmax_by_decimal.test
Labels: Ready For Review

#10727 Fuzzer #1372: Order Bind Failure
  src/planner/binder/expression/bind_window_expression.cpp
  test/fuzzer/duckfuzz/window_order_bind_failure.test
Labels: Ready For Review

#10726 Fuzzer #1380: To Weeks Overflow
  src/core_functions/scalar/date/to_interval.cpp
  test/fuzzer/duckfuzz/to_weeks_overflow.test
Labels: Ready For Review

#10708 Various fixes
  .github/workflows/NightlyTests.yml
  .github/workflows/coverity.yml
  scripts/test_vector_sizes.py
  src/main/extension/extension_install.cpp
  src/transaction/commit_state.cpp
Labels: Ready For Review

#10587 Fix OrderPreservationType issue of MATERIALIZED CTEs
  src/core_functions/scalar/list/array_slice.cpp
  src/execution/physical_plan/plan_insert.cpp
  test/sql/cte/recursive_hang_2745.test
  test/sql/function/list/list_reverse.test
  test/sql/join/left_outer/test_left_join_on_true.test
  test/sql/types/list/unnest_null_empty.test
Labels: Ready To Merge

#10436 Map creation fixes and refactoring
  src/common/enum_util.cpp
  src/common/types/vector.cpp
  src/core_functions/scalar/map/map.cpp
  src/include/duckdb/common/types/vector.hpp
  test/parquet/test_parquet_schema.test
  test/sql/cast/string_to_map_cast.test
  test/sql/types/map/map_const_and_col_combination.test
  test/sql/types/nested/map/map_error.test
  test/sql/types/nested/map/test_map.test
  test/sql/types/nested/map/test_map_and_lambdas.test
  test/sql/types/nested/map/test_map_concat.test
  test/sql/types/nested/map/test_map_keys.test
  test/sql/types/nested/map/test_map_subscript_composite.test
Labels: Ready For Review

#10723 Fuzzer #1383: NULL Range Arguments
  src/function/table/range.cpp
  test/fuzzer/duckfuzz/generate_null_timestamp.test
Labels: Ready To Merge

#10725 Fuzzer #1382: Window Stats Overflow
  src/execution/window_executor.cpp
  test/fuzzer/duckfuzz/window_negate_stats.test
Labels: Ready For Review

#10688 Union exclude
  src/optimizer/remove_unused_columns.cpp
  test/optimizer/union_exclude.test
Labels: Ready To Merge

#10739 move the logic for immediate_transaction_mode to the physical operator
  src/execution/operator/helper/physical_transaction.cpp
  src/transaction/transaction_context.cpp
Labels: CI Failure

#10658 Refactor csv reader includes because of r path length limitations
  src/common/enum_util.cpp
  src/execution/operator/csv_scanner/buffer_manager/csv_buffer.cpp
  src/execution/operator/csv_scanner/buffer_manager/csv_buffer_manager.cpp
  src/execution/operator/csv_scanner/buffer_manager/csv_file_handle.cpp
  src/execution/operator/csv_scanner/scanner/base_scanner.cpp
  src/execution/operator/csv_scanner/scanner/column_count_scanner.cpp
  src/execution/operator/csv_scanner/scanner/scanner_boundary.cpp
  src/execution/operator/csv_scanner/scanner/skip_scanner.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/sniffer/header_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_refinement.cpp
  src/execution/operator/csv_scanner/sniffer/type_replacement.cpp
  src/execution/operator/csv_scanner/state_machine/csv_state_machine.cpp
  src/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.cpp
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/execution/operator/csv_scanner/util/csv_error.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/function/table/copy_csv.cpp
  src/function/table/read_csv.cpp
  src/function/table/sniff_csv.cpp
  src/include/duckdb/common/serializer/deserializer.hpp
  src/include/duckdb/execution/operator/csv_scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/column_count_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_buffer.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_buffer_manager.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_casting.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_error.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_handle.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_option.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_reader_options.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_sniffer.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state_machine.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state_machine_cache.hpp
  src/include/duckdb/execution/operator/csv_scanner/global_csv_state.hpp
  src/include/duckdb/execution/operator/csv_scanner/quote_rules.hpp
  src/include/duckdb/execution/operator/csv_scanner/scanner_boundary.hpp
  src/include/duckdb/execution/operator/csv_scanner/skip_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/state_machine_options.hpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  src/include/duckdb/function/table/read_csv.hpp
  src/include/duckdb/main/client_data.hpp
  src/include/duckdb/main/relation/read_csv_relation.hpp
  src/include/duckdb/storage/serialization/nodes.json
  src/main/relation/read_csv_relation.cpp
  src/storage/serialization/serialize_nodes.cpp
  test/helpers/test_helpers.cpp
  test/parallel_csv/test_parallel_csv.cpp
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
Labels: Ready To Merge

#10481 Arrow String View Type
  src/common/arrow/appender/bool_data.cpp
  src/common/arrow/appender/union_data.cpp
  src/common/arrow/arrow_appender.cpp
  src/common/arrow/arrow_converter.cpp
  src/common/enum_util.cpp
  src/function/table/arrow.cpp
  src/function/table/arrow_conversion.cpp
  src/include/duckdb/common/arrow/appender/append_data.hpp
  src/include/duckdb/common/arrow/appender/enum_data.hpp
  src/include/duckdb/common/arrow/appender/list_data.hpp
  src/include/duckdb/common/arrow/appender/map_data.hpp
  src/include/duckdb/common/arrow/appender/scalar_data.hpp
  src/include/duckdb/common/arrow/appender/varchar_data.hpp
  src/include/duckdb/common/types/arrow_string_view_type.hpp
  src/include/duckdb/function/table/arrow/arrow_duck_schema.hpp
  src/include/duckdb/main/client_properties.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/client_context.cpp
  src/main/config.cpp
  src/main/query_result.cpp
  src/main/settings/settings.cpp
  test/api/test_reset.cpp
  test/arrow/arrow_roundtrip.cpp
  tools/pythonpkg/tests/fast/arrow/test_arrow_string_view.py
Labels: Ready For Review

#10758 local_file_system.cpp: minor fix for macOS libproc code
  src/common/local_file_system.cpp
Labels: Ready To Merge

#10776 Fuzzer #1399: Window NULL RANGE
  src/planner/binder/expression/bind_window_expression.cpp
  test/fuzzer/duckfuzz/window_null_range.test
Labels: Ready For Review

#10763 Add large benchmark directory
  .github/regression/large.csv
  benchmark/large/tpch-sf100/load.sql
  benchmark/large/tpch-sf100/q01.benchmark
  benchmark/large/tpch-sf100/q02.benchmark
  benchmark/large/tpch-sf100/q03.benchmark
  benchmark/large/tpch-sf100/q04.benchmark
  benchmark/large/tpch-sf100/q05.benchmark
  benchmark/large/tpch-sf100/q06.benchmark
  benchmark/large/tpch-sf100/q07.benchmark
  benchmark/large/tpch-sf100/q08.benchmark
  benchmark/large/tpch-sf100/q09.benchmark
  benchmark/large/tpch-sf100/q10.benchmark
  benchmark/large/tpch-sf100/q11.benchmark
  benchmark/large/tpch-sf100/q12.benchmark
  benchmark/large/tpch-sf100/q13.benchmark
  benchmark/large/tpch-sf100/q14.benchmark
  benchmark/large/tpch-sf100/q15.benchmark
  benchmark/large/tpch-sf100/q16.benchmark
  benchmark/large/tpch-sf100/q17.benchmark
  benchmark/large/tpch-sf100/q18.benchmark
  benchmark/large/tpch-sf100/q19.benchmark
  benchmark/large/tpch-sf100/q20.benchmark
  benchmark/large/tpch-sf100/q21.benchmark
  benchmark/large/tpch-sf100/q22.benchmark
  benchmark/large/tpch-sf100/tpch_sf100.benchmark.in
  extension/tpch/dbgen/answers/sf100/q01.csv
  extension/tpch/dbgen/answers/sf100/q02.csv
  extension/tpch/dbgen/answers/sf100/q03.csv
  extension/tpch/dbgen/answers/sf100/q04.csv
  extension/tpch/dbgen/answers/sf100/q05.csv
  extension/tpch/dbgen/answers/sf100/q06.csv
  extension/tpch/dbgen/answers/sf100/q07.csv
  extension/tpch/dbgen/answers/sf100/q08.csv
  extension/tpch/dbgen/answers/sf100/q09.csv
  extension/tpch/dbgen/answers/sf100/q10.csv
  extension/tpch/dbgen/answers/sf100/q11.csv
  extension/tpch/dbgen/answers/sf100/q12.csv
  extension/tpch/dbgen/answers/sf100/q13.csv
  extension/tpch/dbgen/answers/sf100/q14.csv
  extension/tpch/dbgen/answers/sf100/q15.csv
  extension/tpch/dbgen/answers/sf100/q16.csv
  extension/tpch/dbgen/answers/sf100/q17.csv
  extension/tpch/dbgen/answers/sf100/q18.csv
  extension/tpch/dbgen/answers/sf100/q19.csv
  extension/tpch/dbgen/answers/sf100/q20.csv
  extension/tpch/dbgen/answers/sf100/q21.csv
  extension/tpch/dbgen/answers/sf100/q22.csv
Labels: Ready For Review

#10773 Improve UNPIVOT error messages, and allow expressions in unpivot
  src/core_functions/function_list.cpp
  src/core_functions/scalar/list/functions.json
  src/core_functions/scalar/list/list_value.cpp
  src/include/duckdb/common/exception/parser_exception.hpp
  src/include/duckdb/core_functions/scalar/list_functions.hpp
  src/include/duckdb/parser/tableref/pivotref.hpp
  src/include/duckdb/parser/transformer.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/storage/serialization/nodes.json
  src/parser/tableref/pivotref.cpp
  src/parser/transform/statement/transform_pivot_stmt.cpp
  src/parser/transform/tableref/transform_pivot.cpp
  src/planner/binder/tableref/bind_pivot.cpp
  src/storage/serialization/serialize_nodes.cpp
  test/sql/pivot/test_unpivot.test
  test/sql/pivot/unpivot_expression.test
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/include/parser/gram.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation

#10782 [WINDOWS] Add "/bigobj" that solves compile issue during debug
  src/CMakeLists.txt
Labels: CI Failure

#10755 [CSV Reader] Spinlock over GetLine Error + New Strategy for dialect candidates
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_replacement.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/execution/operator/csv_scanner/util/csv_error.cpp
  src/function/table/read_csv.cpp
  src/include/duckdb/execution/operator/csv_scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_error.hpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  test/sql/copy/csv/test_bug_9952.test
  test/sql/copy/csv/test_errors.test_slow
  test/sql/copy/csv/test_limit_spinlock.test
  test/sql/copy/csv/test_sniff_csv.test
Labels: Changes Requested

#10816 Trivial fixes
  src/execution/operator/aggregate/aggregate_object.cpp
  test/sql/join/external/simple_external_join.test_coverage
Labels: Ready To Merge

#10744 [Dev] Add an optional time out in seconds to `run_tests_one_by_one.py`
  .github/workflows/NightlyTests.yml
  scripts/run_tests_one_by_one.py
Labels: Ready To Merge

#10774 Maintain names in COLUMNS(*) expression, and allow aliasing multiple columns using {column}
  src/planner/binder/expression/bind_star_expression.cpp
  test/sql/join/inner/test_using_join.test
  test/sql/parser/columns_aliases.test
  test/sql/pivot/unpivot_unnamed_subquery.test
Labels: Needs Documentation, Friendly SQL

#10832 ci: Upgrade workflows to actions/setup-python@v5
  .github/workflows/CheckIssueForCodeFormatting.yml
  .github/workflows/ExtendedTests.yml
  .github/workflows/ExtraTests.yml
  .github/workflows/Java.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/Main.yml
  .github/workflows/NightlyTests.yml
  .github/workflows/OSX.yml
  .github/workflows/Python.yml
  .github/workflows/R.yml
  .github/workflows/Regression.yml
  .github/workflows/Swift.yml
  .github/workflows/Wasm.yml
  .github/workflows/Windows.yml
  .github/workflows/_extension_client_tests.yml
  .github/workflows/_extension_distribution.yml
  .github/workflows/coverity.yml
Labels: Ready To Merge

#10742 Fuzzer #1389: ARG_XXX Decimal Casts
  src/core_functions/aggregate/distributive/arg_min_max.cpp
  test/fuzzer/duckfuzz/arg_minmax_by_decimal.test
  test/sql/aggregate/aggregates/test_arg_min_max.test
Labels: Ready To Merge

#10836 Contributor guide: Fix new issue link
  CONTRIBUTING.md
Labels: Ready For Review

#10446 Fix: correctly calculate the range of build side for perfect hash join
  src/common/types/row/partitioned_tuple_data.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/physical_plan/plan_comparison_join.cpp
  src/include/duckdb/execution/operator/join/physical_hash_join.hpp
  test/sql/join/inner/perfect_hash_join.test
Labels: Ready For Review

#10859 Check if directory exists before removing files in regression test runner
  scripts/regression_test_runner.py
Labels: Ready For Review

#10597 [Extension] Add CatalogType to the list of functions generated in `extension_entries.hpp`
  scripts/generate_extensions_function.py
  src/catalog/catalog.cpp
  src/include/duckdb/main/extension_entries.hpp
  src/include/duckdb/main/extension_helper.hpp
  test/extension/wrong_function_type.test
  test/sql/catalog/test_extension_suggestion.test
Labels: Ready For Review

#10585 Regression test build side probe side
  scripts/plan_cost_runner.py
Labels: Ready For Review

#10610 [Arrow] Fix issue surrounding lifetime of dictionary arrays
  scripts/regression_test_python.py
  src/function/table/arrow/arrow_array_scan_state.cpp
  src/function/table/arrow_conversion.cpp
  src/include/duckdb/function/table/arrow.hpp
  tools/pythonpkg/tests/fast/arrow/test_dictionary_arrow.py
Labels: Ready For Review

#10860 [Extensions] Build fixes
  CMakeLists.txt
  scripts/merge_vcpkg_deps.py
Labels: Ready For Review

#10740 pb/avoid GetSchema opening a transaction
  src/include/duckdb/catalog/catalog.hpp
  src/planner/binder/statement/bind_create.cpp
Labels: Ready To Merge

#10872 [CSV Sniffer] Early out if things go wrong in dialect detection
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  test/sql/copy/csv/test_csv_wrong_file.test_slow
Labels: Ready To Merge

#10646 Parallelize format.py script
  scripts/format.py
Labels: Ready To Merge

#10888 Remove Old PSQLODBC scripts
  tools/odbc/test/psql_supported_tests
  tools/odbc/test/run_psqlodbc_test.py
  tools/odbc/test/run_psqlodbc_tests.sh
Labels: Ready To Merge

#10895 Add update_odbc_path.py to ODBC bundle
  .github/workflows/LinuxRelease.yml
Labels: Ready For Review

#10893 Table name binding does not fail for non-existent tables in DROP TABLE statements
  src/planner/binder/statement/bind_drop.cpp
Labels: Ready To Merge

#10670 Use M1 (ARM) OSX runners
  .github/workflows/ExtraTests.yml
  .github/workflows/Java.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/Main.yml
  .github/workflows/NightlyTests.yml
  .github/workflows/OSX.yml
  .github/workflows/Python.yml
  .github/workflows/R.yml
  .github/workflows/Regression.yml
  .github/workflows/Windows.yml
  .github/workflows/_extension_distribution.yml
  examples/jdbc/pom.xml
Labels: CI Failure

#10828 Issue #10809: RANGE Hint Corrections
  src/execution/window_executor.cpp
  test/sql/window/test_range_optimisation.test
Labels: Ready For Review

#10908 Enable the progress bar (without printing) in unittests
  src/function/table/read_csv.cpp
  src/parallel/executor.cpp
  test/sqlite/sqllogic_test_runner.cpp
Labels: Draft

#10704 feat: exposing ssl ca cert path to httpfs
  extension/httpfs/httpfs.cpp
  extension/httpfs/httpfs_extension.cpp
  extension/httpfs/include/httpfs.hpp
  src/include/duckdb/main/extension_entries.hpp
Labels: Needs Documentation, Ready For Review
