Repository duckdb/duckdb, pull requests merged in 2024-08, with the labels that each got.

#13249 Feature #1272: Window Task Blocking
  src/execution/operator/aggregate/physical_window.cpp
Labels: Ready For Review

#13271 Issue #13250: Zero Time Buckets
  extension/icu/icu-timebucket.cpp
  test/sql/function/timestamp/test_icu_time_bucket_timestamptz.test
Labels: Ready For Review

#13276 Remove outadated test that fails somehow randomly and doesn't add much
  test/sql/extensions/description_is_valid.test
Labels: Ready For Review

#13275 Fix casts logic
  src/core_functions/scalar/math/numeric.cpp
  src/include/duckdb/common/numeric_utils.hpp
  test/sql/types/decimal/test_decimal_ops.test
Labels: Ready For Review

#13279 Avoid clang-tidy-diff to check Python sources or extension folder
  Makefile
Labels: Ready For Review

#13284 Internal #2681: IEJoin Progress
  src/execution/operator/join/physical_iejoin.cpp
  src/include/duckdb/execution/operator/join/physical_iejoin.hpp
Labels: Ready For Review

#13262 [CSV Reader] Properly cleanup invalid rows
  data/csv/error/mid_null.csv
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  test/sql/copy/csv/test_ignore_mid_null_line.test
Labels: CI Failure

#13315 Fix CMake for when folders are not git folders via `git rev-parse --is-inside-work-tree`
  CMakeLists.txt
Labels: Ready For Review

#13320 CAPI extensions: Fixup list of exported functions for wasm
  CMakeLists.txt
Labels: Ready For Review

#13308 Fix #13237: fix .mode insert float column output
  tools/shell/shell.c
  tools/shell/tests/conftest.py
  tools/shell/tests/test_shell_basics.py
Labels: Changes Requested

#13330 Fuzzer #3113: Lead Lag Shift
  src/execution/window_executor.cpp
  test/fuzzer/sqlsmith/window-leadlag-overflow.test
Labels: Ready For Review

#13313 Implemented `list_extract` with `VectorOperations::Copy`
  benchmark/micro/list/list_extract.benchmark
  benchmark/micro/list/list_extract_null.benchmark
  benchmark/micro/list/list_extract_struct.benchmark
  benchmark/micro/list/list_extract_struct_null.benchmark
  src/function/scalar/list/list_extract.cpp
  test/sql/types/nested/list/test_list_extract.test
Labels: Changes Requested

#13333 Issue template: Fix Arrow extension link
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready To Merge

#12886 NO_PARTITION_COLUMNS option to skip partition writes for Parquet copy
  extension/parquet/parquet_extension.cpp
  src/execution/operator/persistent/physical_copy_to_file.cpp
  src/execution/physical_plan/plan_copy_to_file.cpp
  src/include/duckdb/execution/operator/persistent/physical_copy_to_file.hpp
  src/include/duckdb/planner/operator/logical_copy_to_file.hpp
  src/planner/binder/statement/bind_copy.cpp
  src/planner/operator/logical_copy_to_file.cpp
  test/parquet/test_parquet_schema.test
  test/sql/copy/csv/test_partition_compression.test
  test/sql/copy/csv/union_by_name_many_files.test_slow
  test/sql/copy/format_uuid.test
  test/sql/copy/hive_types.test_slow
  test/sql/copy/parquet/hive_partitioning_struct.test
  test/sql/copy/parquet/hive_timestamps.test
  test/sql/copy/parquet/parquet_hive_null.test
  test/sql/copy/parquet/writer/parquet_write_field_id.test
  test/sql/copy/partitioned/hive_partition_compression.test
  test/sql/copy/partitioned/hive_partition_escape.test
  test/sql/copy/partitioned/hive_partitioned_auto_detect.test
  test/sql/copy/partitioned/hive_partitioned_write.test
  test/sql/copy/partitioned/hive_partitioning_overwrite.test
  test/sql/copy/partitioned/partition_issue_6304.test
  test/sql/copy/partitioned/partitioned_write_tpch.test_slow
  test/sql/copy/partitioned/skip_partition_column_writes.test
  test/sql/json/table/json_multi_file_reader.test
  test/sql/secrets/create_secret_persistence_error_handling.test
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb_python.cpp
  tools/pythonpkg/scripts/connection_wrapper_methods.json
  tools/pythonpkg/src/include/duckdb_python/pyrelation.hpp
  tools/pythonpkg/src/pyrelation.cpp
  tools/pythonpkg/src/pyrelation/initialize.cpp
  tools/pythonpkg/tests/fast/api/test_to_csv.py
  tools/pythonpkg/tests/fast/test_filesystem.py
Labels: Changes Requested

#13317 Bug/Regression fixes
  extension/fts/fts_indexing.cpp
  extension/json/include/json_scan.hpp
  extension/json/json_scan.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/scan/physical_column_data_scan.cpp
  src/include/duckdb/execution/ht_entry.hpp
  src/include/duckdb/execution/join_hashtable.hpp
  src/optimizer/filter_pushdown.cpp
  src/parallel/task_scheduler.cpp
  src/parser/transform/statement/transform_create_function.cpp
  src/planner/binder/query_node/plan_cte_node.cpp
  test/sql/catalog/function/test_macro_issue_13104.test
  test/sql/cte/materialized/materialized_cte_modifiers.test
  test/sql/json/issues/issue13212.test
Labels: Ready For Review

#13342 Enable unnesting lists of arrays
  src/execution/operator/projection/physical_unnest.cpp
  test/sql/types/list/unnest_complex_types.test
Labels: Ready To Merge

#13343 Limit relation has wrong relation type
  src/main/relation/limit_relation.cpp
Labels: Ready To Merge

#13341 [Dev] Remove redundant variable from SQLStatement
  src/common/adbc/adbc.cpp
  src/include/duckdb/main/prepared_statement.hpp
  src/include/duckdb/parser/sql_statement.hpp
  src/main/capi/prepared-c.cpp
  src/main/client_context.cpp
  src/main/prepared_statement.cpp
  src/main/prepared_statement_data.cpp
  src/parser/transformer.cpp
  src/planner/binder/statement/bind_execute.cpp
  src/planner/planner.cpp
  src/verification/prepared_statement_verifier.cpp
  test/api/test_prepared_api.cpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp
Labels: Ready To Merge

#13350 Internal #2722: Partition State Threading
  src/common/sort/partition_state.cpp
Labels: Ready For Review

#13355 CSV Sniffer - Error Messages
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/sniffer/header_detection.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/execution/operator/csv_scanner/util/csv_error.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_error.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_sniffer.hpp
  src/include/duckdb/execution/operator/csv_scanner/header_value.hpp
  test/sql/copy/csv/auto/test_auto_column_type_opt.test
  test/sql/copy/csv/auto/test_fallback_all_varchar.test
  test/sql/copy/csv/code_cov/csv_dialect_detection.test
  test/sql/copy/csv/csv_external_access.test
  test/sql/copy/csv/csv_hive_filename_union.test
  test/sql/copy/csv/csv_names.test
  test/sql/copy/csv/glob/copy_csv_glob.test
  test/sql/copy/csv/glob/copy_csv_glob_s3.test
  test/sql/copy/csv/glob/read_csv_glob.test
  test/sql/copy/csv/maximum_line_size.test_slow
  test/sql/copy/csv/null_padding_big.test
  test/sql/copy/csv/overwrite/test_copy_overwrite.test
  test/sql/copy/csv/test_comment_option.test
  test/sql/copy/csv/test_compression_flag.test
  test/sql/copy/csv/test_copy.test
  test/sql/copy/csv/test_copy_null.test
  test/sql/copy/csv/test_csv_httpfs_prepared.test
  test/sql/copy/csv/test_csv_wrong_file.test_slow
  test/sql/copy/csv/test_dateformat.test
  test/sql/copy/csv/test_force_not_null.test
  test/sql/copy/csv/test_force_quote.test
  test/sql/copy/csv/test_ignore_errors.test
  test/sql/copy/csv/test_ignore_errors_end_of_chunk.test
  test/sql/copy/csv/test_read_csv.test
  test/sql/copy/csv/test_sniff_csv_options.test
  test/sql/copy/csv/zstd_crash.test
Labels: Ready For Review

#13267 Time cast: Have same behavior as Postgres
  data/csv/auto/invalid_time.csv
  data/csv/auto/time.csv
  data/csv/auto/various_time_formats.csv
  src/common/types/time.cpp
  test/sql/copy/csv/test_time.test
  test/sql/types/interval/interval_try_cast.test
  test/sql/types/time/test_time.test
  test/sql/types/time/time_try_cast.test
  test/sql/types/timestamp/timestamp_try_cast.test
Labels: Ready For Review

#13356 Fix appian join tests
  .github/regression/appian.csv
  benchmark/appian_benchmarks/appian.benchmark.in
  benchmark/appian_benchmarks/q01.benchmark
  benchmark/appian_benchmarks/q02.benchmark
  benchmark/appian_benchmarks/q03.benchmark
  benchmark/appian_benchmarks/q04.benchmark
  benchmark/appian_benchmarks/q05.benchmark
  benchmark/appian_benchmarks/q06.benchmark
  benchmark/appian_benchmarks/q07.benchmark
  benchmark/appian_benchmarks/q08.benchmark
  benchmark/appian_benchmarks/queries/q01.sql
  benchmark/appian_benchmarks/queries/q02.sql
  benchmark/appian_benchmarks/queries/q03.sql
  benchmark/appian_benchmarks/queries/q04.sql
  benchmark/appian_benchmarks/queries/q05.sql
  benchmark/appian_benchmarks/queries/q06.sql
  benchmark/appian_benchmarks/queries/q07.sql
  benchmark/appian_benchmarks/queries/q08.sql
  benchmark/micro/join/prefer_right_deep_join_trees.benchmark
  scripts/plan_cost_runner.py
  src/include/duckdb/optimizer/build_probe_side_optimizer.hpp
  src/optimizer/build_probe_side_optimizer.cpp
  test/api/adbc/test_adbc.cpp
  tools/pythonpkg/tests/fast/relational_api/test_joins.py
Labels: Changes Requested

#13359 Support Json Types in CSV Reader
  data/csv/error/json.csv
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  test/sql/copy/csv/test_csv_json.test
Labels: Ready For Review

#13329 Feature #1272: Window Distinct Merging
  src/execution/window_segment_tree.cpp
Labels: Ready For Review

#13399 Refine heuristic for flipping join sides
  src/function/scalar/list/list_extract.cpp
  src/include/duckdb/optimizer/build_probe_side_optimizer.hpp
  src/optimizer/build_probe_side_optimizer.cpp
  src/optimizer/join_order/relation_manager.cpp
  test/sql/types/list/list_extract_internal_issue2747.test
Labels: Ready For Review

#13370 Update jemalloc and re-enable opt.retain
  extension/jemalloc/jemalloc/CMakeLists.txt
  extension/jemalloc/jemalloc/README.md
  extension/jemalloc/jemalloc/include/jemalloc/internal/arena_externs.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/arena_inlines_b.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/arena_structs.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/batcher.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/bin.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/bin_info.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/bin_stats.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/cache_bin.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/emap.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/emitter.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/hpa_opts.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/jemalloc_internal_defs.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/jemalloc_internal_macros.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/jemalloc_internal_types.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/private_namespace.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/prof_hook.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/public_namespace.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/public_unnamespace.h
  extension/jemalloc/jemalloc/include/jemalloc/internal/witness.h
  extension/jemalloc/jemalloc/include/jemalloc/jemalloc.h
  extension/jemalloc/jemalloc/include/jemalloc/jemalloc_defs.h
  extension/jemalloc/jemalloc/include/jemalloc/jemalloc_macros.h
  extension/jemalloc/jemalloc/include/jemalloc/jemalloc_mangle.h
  extension/jemalloc/jemalloc/include/jemalloc/jemalloc_mangle_jet.h
  extension/jemalloc/jemalloc/include/jemalloc/jemalloc_rename.h
  extension/jemalloc/jemalloc/src/arena.c
  extension/jemalloc/jemalloc/src/batcher.c
  extension/jemalloc/jemalloc/src/bin.c
  extension/jemalloc/jemalloc/src/bin_info.c
  extension/jemalloc/jemalloc/src/ctl.c
  extension/jemalloc/jemalloc/src/emap.c
  extension/jemalloc/jemalloc/src/hpa.c
  extension/jemalloc/jemalloc/src/jemalloc.c
  extension/jemalloc/jemalloc/src/malloc_io.c
  extension/jemalloc/jemalloc/src/nstime.c
  extension/jemalloc/jemalloc/src/pages.c
  extension/jemalloc/jemalloc/src/prof.c
  extension/jemalloc/jemalloc/src/stats.c
  extension/jemalloc/jemalloc/src/tcache.c
  extension/jemalloc/jemalloc/src/zone.c
  extension/jemalloc/jemalloc_config.py
  extension/jemalloc/jemalloc_extension.cpp
  src/storage/temporary_memory_manager.cpp
Labels: Ready For Review

#13394 Feature #1272: Window Distinct Indices
  src/execution/window_segment_tree.cpp
Labels: Ready For Review

#13402 Compressed materialization for joins
  src/include/duckdb/optimizer/compressed_materialization.hpp
  src/optimizer/compressed_materialization.cpp
  src/optimizer/compressed_materialization/CMakeLists.txt
  src/optimizer/compressed_materialization/compress_comparison_join.cpp
  test/api/test_results.cpp
Labels: Ready For Review

#13358 [Python UDF] Filter `NULL` values before calling the user defined function
  src/common/vector_operations/vector_copy.cpp
  src/include/duckdb/common/vector_operations/vector_operations.hpp
  tools/pythonpkg/src/include/duckdb_python/pybind11/pybind_wrapper.hpp
  tools/pythonpkg/src/python_udf.cpp
  tools/pythonpkg/src/typing/pytype.cpp
  tools/pythonpkg/tests/fast/udf/test_null_filtering.py
Labels: Ready For Review

#13433 Disable jemalloc on 32bit through cmake, not through a CI script
  .github/workflows/NightlyTests.yml
  extension/extension_config.cmake
  src/common/allocator.cpp
Labels: Ready For Review

#13268 Fixing hugeint cast to varint
  src/common/types/hugeint.cpp
  src/function/cast/varint_casts.cpp
  test/sql/function/list/aggregates/hugeint.test
  test/sql/types/varint/test_varint_boundaries.test
  test/sql/types/varint/test_varint_hugeint.test
Labels: CI Failure

#13202 [Explain] Add the `HTML` format for `EXPLAIN` statements
  src/common/enum_util.cpp
  src/common/tree_renderer.cpp
  src/common/tree_renderer/CMakeLists.txt
  src/common/tree_renderer/html_tree_renderer.cpp
  src/include/duckdb/common/enums/explain_format.hpp
  src/include/duckdb/common/tree_renderer/html_tree_renderer.hpp
  src/include/duckdb/main/relation.hpp
  src/include/duckdb/main/relation/explain_relation.hpp
  src/main/query_profiler.cpp
  src/main/relation.cpp
  src/main/relation/explain_relation.cpp
  src/parser/transform/statement/transform_explain.cpp
  test/sql/explain/test_explain.test
  tools/pythonpkg/scripts/cache_data.json
  tools/pythonpkg/scripts/imports.py
  tools/pythonpkg/src/include/duckdb_python/import_cache/modules/ipython_module.hpp
  tools/pythonpkg/src/pyrelation.cpp
Labels: Ready For Review

#13440 fix for the issue 2698
  extension/json/json_functions/json_create.cpp
  test/fuzzer/duckfuzz/fuzzer_issue_2698.test
Labels: Ready To Merge

#13439 Avoid rounding errors and simplify memory assignments in `TemporaryMemoryManager`
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/execution/operator/persistent/batch_memory_manager.hpp
  src/include/duckdb/storage/temporary_memory_manager.hpp
  src/storage/temporary_memory_manager.cpp
Labels: Ready To Merge

#13431 Pull up filters from and through explicit joins
  src/optimizer/filter_pullup.cpp
  test/fuzzer/duckfuzz/semi_join_has_correct_left_right_relations.test
  test/optimizer/pullup_filters.test
Labels: Ready To Merge

#13450 Use LossyNumericCast while reading memory limits
  src/main/config.cpp
  test/sql/pragma/test_memory_limit.test
Labels: Ready For Review

#13326 Prevent the query thread from picking up query unrelated tasks if compiled with DUCKDB_NO_THREADS
  src/include/duckdb/execution/executor.hpp
  src/parallel/task_scheduler.cpp
  test/api/CMakeLists.txt
  test/api/test_threads.cpp
Labels: Changes Requested

#13441 Issue #13380: IN Invertible Casts
  src/optimizer/rule/in_clause_simplification_rule.cpp
  test/sql/optimizer/expression/test_in_clause_simplification.test
Labels: Ready For Review

#13425 [Arrow] Accept objects that provide the `__arrow_c_stream__` producer method
  tools/pythonpkg/src/include/duckdb_python/arrow/arrow_array_stream.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/src/python_replacement_scan.cpp
  tools/pythonpkg/tests/fast/arrow/test_arrow_pycapsule.py
Labels: Ready For Review

#13389 [Lambdas] Support N-ary lambdas in the list comprehension syntax
  test/sql/function/list/lambdas/list_comprehension.test
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/grammar/types/select.yh
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Ready For Review

#13430 [METRICS] Add `blocked_thread_time` Metric
  src/common/enum_util.cpp
  src/common/render_tree.cpp
  src/execution/operator/aggregate/physical_ungrouped_aggregate.cpp
  src/execution/operator/filter/physical_filter.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/operator/join/physical_nested_loop_join.cpp
  src/execution/operator/join/physical_piecewise_merge_join.cpp
  src/execution/operator/persistent/physical_batch_insert.cpp
  src/execution/operator/persistent/physical_insert.cpp
  src/execution/operator/persistent/physical_update.cpp
  src/execution/operator/projection/physical_projection.cpp
  src/execution/operator/scan/physical_table_scan.cpp
  src/include/duckdb.h
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/execution/executor.hpp
  src/include/duckdb/main/capi/extension_api.hpp
  src/include/duckdb/main/capi/header_generation/apis/v0/v0.0/v0.0.2.json
  src/include/duckdb/main/capi/header_generation/functions/profiling_info.json
  src/include/duckdb/main/profiling_info.hpp
  src/include/duckdb/main/profiling_node.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/include/duckdb_extension.h
  src/main/capi/profiling_info-c.cpp
  src/main/profiling_info.cpp
  src/main/query_profiler.cpp
  src/main/settings/settings.cpp
  src/parallel/executor.cpp
  test/api/capi/test_capi_profiling.cpp
  test/sql/explain/test_explain_analyze.test
  test/sql/pragma/test_custom_profiling_settings.test
Labels: Ready To Merge

#13312 Make CMake target exports relocatable
  CMakeLists.txt
Labels: Ready For Review

#13480 [Metrics] Rework Optimizer Metrics
  scripts/generate_metric_enums.py
  src/common/enum_util.cpp
  src/common/enums/CMakeLists.txt
  src/common/enums/metric_type.cpp
  src/execution/physical_plan_generator.cpp
  src/include/duckdb/common/enums/metric_type.hpp
  src/include/duckdb/main/profiling_info.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/main/client_context.cpp
  src/main/profiling_info.cpp
  src/main/query_profiler.cpp
  src/main/settings/settings.cpp
  src/optimizer/optimizer.cpp
  src/planner/planner.cpp
  test/sql/pragma/test_custom_optimizer_profiling.test
  test/sql/pragma/test_custom_profiling_settings.test
Labels: Ready To Merge

#13447 Prefer depth-first plan evaluation for unions and joins
  src/common/types/row/tuple_data_allocator.cpp
  src/common/types/row/tuple_data_segment.cpp
  src/execution/operator/join/physical_join.cpp
  src/execution/operator/join/physical_left_delim_join.cpp
  src/execution/operator/set/physical_union.cpp
  src/execution/physical_operator.cpp
  src/include/duckdb/common/types/row/tuple_data_allocator.hpp
  src/include/duckdb/execution/operator/join/physical_join.hpp
  src/include/duckdb/execution/physical_operator.hpp
  src/include/duckdb/parallel/meta_pipeline.hpp
  src/parallel/executor.cpp
  src/parallel/meta_pipeline.cpp
  test/sql/parallelism/intraquery/depth_first_evaluation.test_slow
  test/sql/parallelism/intraquery/depth_first_evaluation_union_and_join.test
Labels: Ready To Merge

#13376 Make error message more explicit for when trying to parse SQL types.
  src/common/types.cpp
  src/storage/write_ahead_log.cpp
  test/sql/copy/csv/auto/test_type_candidates.test
Labels: CI Failure

#13488 Apply extension patches via 'patch' instead of 'git apply'
  scripts/apply_extension_patches.py
Labels: Ready For Review

#13503 Feature #1272: Window Distinct Tree
  src/execution/window_segment_tree.cpp
  src/include/duckdb/core_functions/aggregate/quantile_sort_tree.hpp
  src/include/duckdb/execution/merge_sort_tree.hpp
Labels: Ready For Review

#13499 Add support for registering custom casts (and types) through c api
  scripts/generate_c_api.py
  src/include/duckdb.h
  src/include/duckdb/main/capi/extension_api.hpp
  src/include/duckdb/main/capi/header_generation/apis/v0/dev/dev.json
  src/include/duckdb/main/capi/header_generation/functions/cast_functions.json
  src/include/duckdb/main/capi/header_generation/functions/logical_type_interface.json
  src/include/duckdb/main/capi/header_generation/header_base.hpp.template
  src/include/duckdb_extension.h
  src/main/capi/CMakeLists.txt
  src/main/capi/cast_function-c.cpp
  src/main/capi/logical_types-c.cpp
  test/api/capi/CMakeLists.txt
  test/api/capi/capi_custom_type.cpp
Labels: Ready For Review

#13515 Bump sqlite & mysql
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/mysql_scanner/params_to_string.patch
  .github/patches/extensions/sqlite_scanner/params_to_string.patch
Labels: Ready To Merge

#13493 Switch floating point division and modulo to use IEEE semantics for division by zero by default, and add ieee_floating_point_ops setting that can be used to revert back to old behavior
  src/function/scalar/operators/arithmetic.cpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/settings/settings.cpp
  src/planner/binder/statement/bind_summarize.cpp
  test/api/test_reset.cpp
  test/issues/rigger/complex_division.test
  test/issues/rigger/division_by_zero_null.test
  test/sql/function/numeric/test_fdiv_fmod.test
  test/sql/optimizer/expression/test_nop_arithmetic.test
  test/sql/types/float/ieee_floating_points.test
  test/sql/types/null/test_null.test
Labels: Needs Documentation

#13516 Feature #1272: Windowed Quantile Tree
  src/include/duckdb/core_functions/aggregate/quantile_sort_tree.hpp
Labels: Ready For Review

#12790 [Auto Loading] Autoload extension settings
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/database.hpp
  src/include/duckdb/main/extension_helper.hpp
  src/main/database.cpp
  src/main/extension/extension_helper.cpp
  test/api/CMakeLists.txt
  test/api/capi/test_capi.cpp
  test/api/test_extension_setting_autoload.cpp
  tools/pythonpkg/tests/fast/api/test_config.py
Labels: Ready For Review

#13481 JSON bugfixes and new functions
  extension/json/CMakeLists.txt
  extension/json/include/json_executors.hpp
  extension/json/include/json_functions.hpp
  extension/json/json_config.py
  extension/json/json_functions.cpp
  extension/json/json_functions/CMakeLists.txt
  extension/json/json_functions/json_array_length.cpp
  extension/json/json_functions/json_exists.cpp
  extension/json/json_functions/json_extract.cpp
  extension/json/json_functions/json_keys.cpp
  extension/json/json_functions/json_pretty.cpp
  extension/json/json_functions/json_structure.cpp
  extension/json/json_functions/json_type.cpp
  extension/json/json_functions/json_value.cpp
  src/include/duckdb/main/extension_entries.hpp
  test/sql/binder/test_alias_map_in_subquery.test
  test/sql/json/issues/issue11804.test
  test/sql/json/scalar/test_json_dot_syntax.test
  test/sql/json/scalar/test_json_exists.test
  test/sql/json/scalar/test_json_extract.test
  test/sql/json/scalar/test_json_path.test
  test/sql/json/scalar/test_json_value.test
Labels: Needs Documentation, Ready To Merge, Needs functions.json entry

#13522 Make changes to relation.hpp backward compatible with older API via default parameters
  src/include/duckdb/main/relation.hpp
Labels: Ready To Merge

#13514 Return an error when multiple rows are returned from a scalar subquery
  src/core_functions/scalar/generic/error.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/include/duckdb/execution/join_hashtable.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/settings/settings.cpp
  src/planner/binder/query_node/plan_subquery.cpp
  test/api/test_reset.cpp
  test/fuzzer/pedro/setop_type_mismatch.test
  test/optimizer/compressed_materialization.test_coverage
  test/optimizer/joins/updating_the_join_node_hash_map_has_no_errors.test_slow
  test/sql/aggregate/distinct/test_distinct_on.test
  test/sql/aggregate/qualify/test_qualify.test
  test/sql/catalog/function/test_complex_macro.test
  test/sql/copy/csv/parallel/csv_parallel_tpcds.test_slow
  test/sql/join/semianti/antijoin.test
  test/sql/join/semianti/right_anti.test
  test/sql/join/semianti/right_semi.test
  test/sql/join/semianti/semijoin.test
  test/sql/order/test_limit.test
  test/sql/subquery/any_all/subquery_in.test
  test/sql/subquery/complex/correlated_list_aggregate.test_slow
  test/sql/subquery/scalar/test_correlated_aggregate_subquery.test_slow
  test/sql/subquery/scalar/test_correlated_subquery.test
  test/sql/subquery/scalar/test_correlated_subquery_cte.test
  test/sql/subquery/scalar/test_issue_6136.test
  test/sql/subquery/scalar/test_scalar_subquery.test
  test/sql/subquery/scalar/test_scalar_subquery_cte.test
  test/sql/subquery/scalar/test_uncorrelated_scalar_subquery.test
  test/sql/tpcds/tpcds_options.test_slow
  test/sql/types/list/unnest_table_function.test
  tools/pythonpkg/tests/fast/test_replacement_scan.py
Labels: Needs Documentation

#13532 Disallow ordering by non-integer literal by default - and add the setting order_by_non_integer_literal to revert to the previous behavior
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/include/duckdb/planner/expression_binder/order_binder.hpp
  src/main/config.cpp
  src/main/settings/settings.cpp
  src/planner/binder/expression/bind_aggregate_expression.cpp
  src/planner/binder/query_node/bind_select_node.cpp
  src/planner/binder/query_node/bind_setop_node.cpp
  src/planner/expression_binder/order_binder.cpp
  test/issues/rigger/assertion_scale.test
  test/issues/rigger/test_544.test
  test/sql/aggregate/distinct/grouped/string_agg.test
  test/sql/copy/parquet/batched_write/batch_memory_usage.test
  test/sql/order/test_order_by.test
  test/sql/order/test_order_by_exceptions.test
  test/sql/subquery/scalar/array_order_subquery.test
Labels: Needs Documentation

#13530 Produce an empty list result for enum_range(NULL::enum_type)
  src/core_functions/scalar/enum/enum_functions.cpp
  test/sql/types/enum/test_enum.test
Labels: Changes Requested

#13518 [CSV Reader] Fix for invalid unicode in header
  data/csv/error/banklist.csv
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  test/sql/copy/csv/test_non_unicode_header.test
Labels: CI Failure

#13538 Issue #13525: Window Local States
  data/csv/issue_13525/stat_bigrams.csv
  data/csv/issue_13525/stat_stat_chars.csv
  src/execution/operator/aggregate/physical_window.cpp
  test/sql/window/test_thread_count.test
Labels: Ready For Review

#13527 Feature #1272: Windowed Distinct Tree
  src/execution/window_segment_tree.cpp
Labels: Ready For Review

#13393 Bump GitHub workflows to their latest versions
  .github/workflows/CheckIssueForCodeFormatting.yml
  .github/workflows/CodeQuality.yml
  .github/workflows/DockerTests.yml
  .github/workflows/DraftMe.yml
  .github/workflows/DraftPR.yml
  .github/workflows/ExtendedTests.yml
  .github/workflows/ExtensionTrigger.yml
  .github/workflows/ExtraTests.yml
  .github/workflows/Julia.yml
  .github/workflows/Main.yml
  .github/workflows/OSX.yml
  .github/workflows/Pyodide.yml
  .github/workflows/R.yml
  .github/workflows/R_CMD_CHECK.yml
  .github/workflows/Regression.yml
  .github/workflows/StagedUpload.yml
  .github/workflows/Swift.yml
  .github/workflows/SwiftRelease.yml
  .github/workflows/TwineUpload.yml
  .github/workflows/Wasm.yml
  .github/workflows/Windows.yml
  .github/workflows/_extension_client_tests.yml
  .github/workflows/cifuzz.yml
Labels: Ready To Merge

#13406 Add `map_contains`, `map_contains_entry` and `map_contains_value` functions, `list_position` now returns null.
  src/catalog/default/default_functions.cpp
  src/core_functions/function_list.cpp
  src/core_functions/scalar/map/CMakeLists.txt
  src/core_functions/scalar/map/functions.json
  src/core_functions/scalar/map/map_contains.cpp
  src/core_functions/scalar/map/map_extract.cpp
  src/function/scalar/list/contains_or_position.cpp
  src/function/scalar/string/contains.cpp
  src/include/duckdb/core_functions/scalar/map_functions.hpp
  src/include/duckdb/function/scalar/list/contains_or_position.hpp
  src/include/duckdb/function/scalar/nested_functions.hpp
  test/sql/function/array/array_list_functions.test
  test/sql/function/list/list_position.test
  test/sql/function/string/test_contains.test
  test/sql/types/nested/map/test_map_contains.test
Labels: Needs Documentation, Ready To Merge

#13546 Numeric casts: forbid NumericCasts for float/double, add Lossy and Exact equivalent to make syntax explicit
  .github/workflows/NightlyTests.yml
  Makefile
  src/include/duckdb/common/limits.hpp
  src/include/duckdb/common/numeric_utils.hpp
  src/include/duckdb/core_functions/aggregate/quantile_sort_tree.hpp
  src/include/duckdb/storage/compression/alp/algorithm/alp.hpp
  src/include/duckdb/storage/compression/alp/alp_utils.hpp
  src/include/duckdb/storage/compression/alprd/algorithm/alprd.hpp
  src/storage/compression/bitpacking.cpp
  src/storage/temporary_memory_manager.cpp
Labels: Ready For Review

#13556 Fix clang-tidy on insertion_order_preserving_map.hpp: Alter order of statements
  src/include/duckdb/common/insertion_order_preserving_map.hpp
Labels: Ready To Merge

#10348 Optimise division by a constant at runtime for integer division
  src/common/types/hugeint.cpp
  src/common/types/uhugeint.cpp
  src/core_functions/function_list.cpp
  src/core_functions/scalar/math/functions.json
  src/core_functions/scalar/math/numeric.cpp
  src/include/duckdb/common/types/hugeint.hpp
  src/include/duckdb/common/types/uhugeint.hpp
  src/include/duckdb/core_functions/scalar/math_functions.hpp
  src/optimizer/rule/arithmetic_simplification.cpp
Labels: Ready For Review, feature

#13085 move the inet extension out-of-tree
  .github/config/bundled_extensions.cmake
  .github/config/in_tree_extensions.cmake
  .github/config/out_of_tree_extensions.cmake
  .github/workflows/Main.yml
  .github/workflows/NightlyTests.yml
  .github/workflows/Regression.yml
  .github/workflows/coverity.yml
  Makefile
  benchmark/micro/string/inet_unescape_charrefs.benchmark
  benchmark/micro/string/inet_unescape_codepoints.benchmark
  data/csv/html_unescape_codes.csv
  extension/inet/CMakeLists.txt
  extension/inet/include/html_charref.hpp
  extension/inet/include/inet_extension.hpp
  extension/inet/include/inet_functions.hpp
  extension/inet/include/ipaddress.hpp
  extension/inet/inet_escape_functions.cpp
  extension/inet/inet_extension.cpp
  extension/inet/inet_functions.cpp
  extension/inet/ipaddress.cpp
  test/sql/inet/test_inet_escape.test
  test/sql/inet/test_inet_functions.test
  test/sql/inet/test_inet_nested.test
  test/sql/inet/test_inet_operations.test
  test/sql/inet/test_inet_storage.test
  test/sql/inet/test_inet_table.test
  test/sql/inet/test_inet_type.test
  test/sql/inet/test_ipv6_inet_functions.test
  test/sql/inet/test_ipv6_inet_nested.test
  test/sql/inet/test_ipv6_inet_operations.test
  test/sql/inet/test_ipv6_inet_storage.test
  test/sql/inet/test_ipv6_inet_type.test
Labels: Needs Documentation, CI Failure, Ready For Review

#13551 Remove patches (vss and substrait), bump other repositories
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/substrait/http_state.patch
  .github/patches/extensions/substrait/private_column_ids.patch
  .github/patches/extensions/substrait/pushdown_semi_anti.patch
  .github/patches/extensions/vss/default_block_size.patch
  .github/patches/extensions/vss/get_storage_info.patch
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#13566 Minor fixes for DuckDB-Wasm
  .github/workflows/Wasm.yml
  src/include/duckdb/common/file_open_flags.hpp
  src/parallel/executor.cpp
Labels: Ready For Review

#13483 Update storage info
  src/storage/storage_info.cpp
  src/storage/version_map.json
Labels: Ready For Review

#13559 Unify task (un)blocking in physical operators
  src/execution/operator/aggregate/physical_hash_aggregate.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/operator/persistent/physical_batch_copy_to_file.cpp
  src/execution/operator/persistent/physical_batch_insert.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/execution/operator/persistent/batch_memory_manager.hpp
  src/include/duckdb/execution/physical_operator_states.hpp
  src/include/duckdb/parallel/interrupt.hpp
  src/parallel/pipeline_executor.cpp
Labels: Changes Requested

#13581 Internal #2850: Window Local States
  src/execution/operator/aggregate/physical_window.cpp
Labels: Ready For Review

#13582 Two steps upload action
  .github/workflows/Windows.yml
Labels: Ready For Review

#13489 Use new HLL implementation in `DistinctStatistics`
  src/common/enum_util.cpp
  src/common/types/hyperloglog.cpp
  src/core_functions/aggregate/distributive/approx_count.cpp
  src/include/duckdb/common/types/hyperloglog.hpp
  src/include/duckdb/storage/compression/alp/alp_compress.hpp
  src/include/duckdb/storage/compression/alprd/alprd_compress.hpp
  src/include/duckdb/storage/statistics/base_statistics.hpp
  src/include/duckdb/storage/statistics/distinct_statistics.hpp
  src/include/duckdb/storage/statistics/numeric_stats.hpp
  src/include/duckdb/storage/statistics/numeric_stats_union.hpp
  src/include/duckdb/storage/table/append_state.hpp
  src/main/attached_database.cpp
  src/storage/compression/bitpacking.cpp
  src/storage/compression/fixed_size_uncompressed.cpp
  src/storage/compression/rle.cpp
  src/storage/statistics/CMakeLists.txt
  src/storage/statistics/column_statistics.cpp
  src/storage/statistics/distinct_statistics.cpp
  src/storage/statistics/numeric_stats.cpp
  src/storage/statistics/numeric_stats_union.cpp
  src/storage/table/row_group_collection.cpp
  src/storage/table/update_segment.cpp
  test/common/test_hyperlog.cpp
  test/fuzzer/pedro/vacuum_table_with_generated_column.test
  test/sql/parallelism/intraquery/depth_first_evaluation.test_slow
  test/sql/vacuum/test_analyze.test
  third_party/hyperloglog/hyperloglog.cpp
  third_party/hyperloglog/hyperloglog.hpp
Labels: Ready For Review

#13590 Automatically call `malloc_trim` to reduce unused outstanding allocations
  extension/json/json_functions/json_create.cpp
  src/common/allocator.cpp
  src/include/duckdb/common/allocator.hpp
  src/parallel/task_scheduler.cpp
  src/storage/buffer/buffer_pool.cpp
  src/storage/standard_buffer_manager.cpp
Labels: Ready For Review

#13595 Casting to Bit is no longer Invertible
  src/optimizer/rule/comparison_simplification.cpp
  src/planner/expression/bound_cast_expression.cpp
  test/sql/optimizer/expression/test_casting_negative_integer_to_bit.test
Labels: Ready To Merge

#13601 Do not include version.rc file on MINGW
  src/CMakeLists.txt
Labels: Ready To Merge

#13597 [Python RelAPI] Throw an error if trying to use a invalid argument in read_csv
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/api/test_read_csv.py
Labels: Changes Requested

#13610 Optimistic write to WAL: we cannot optimistically write block pointers if there are indexes
  src/storage/storage_manager.cpp
Labels: Ready To Merge

#13612 [Test] Tighter ART storage regression boundaries
  test/sql/index/art/memory/test_art_non_linear.test_slow
  test/sql/index/art/memory/test_art_varchar.test_slow
  test/sql/index/art/vacuum/test_art_vacuum_strings.test_slow
Labels: Ready To Merge

#13608 Disable `JEMALLOC_HAVE_MADVISE_HUGE` in jemalloc
  extension/jemalloc/jemalloc/README.md
  extension/jemalloc/jemalloc/include/jemalloc/internal/jemalloc_internal_defs.h
  extension/jemalloc/jemalloc/src/pages.c
Labels: Ready To Merge

#13606 Avoid adding buffers that will be destroyed to the eviction queue
  src/common/enum_util.cpp
  src/common/types/column/column_data_allocator.cpp
  src/common/types/column/column_data_consumer.cpp
  src/common/types/row/tuple_data_allocator.cpp
  src/common/types/row/tuple_data_segment.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/enums/destroy_buffer_upon.hpp
  src/include/duckdb/common/types/column/column_data_allocator.hpp
  src/include/duckdb/common/types/row/tuple_data_allocator.hpp
  src/include/duckdb/storage/block_manager.hpp
  src/include/duckdb/storage/buffer/block_handle.hpp
  src/include/duckdb/storage/standard_buffer_manager.hpp
  src/storage/buffer/block_handle.cpp
  src/storage/buffer/block_manager.cpp
  src/storage/metadata/metadata_manager.cpp
  src/storage/standard_buffer_manager.cpp
Labels: Ready To Merge

#13628 Fix url link of `our installation page` to avoid `Connection not secure`
  README.md
Labels: needs maintainer approval, Ready To Merge

#13637 Issue #13629: Date Diff Weeks
  extension/icu/icu-datesub.cpp
  src/core_functions/scalar/date/date_diff.cpp
  test/sql/function/timestamp/date_diff.test_slow
  test/sql/function/timestamp/test_icu_datediff.test
Labels: Ready For Review

#13624 Fix secret manager issue
  src/include/duckdb/main/secret/secret_manager.hpp
  src/main/extension/extension_install.cpp
  src/main/secret/secret_manager.cpp
  test/sql/secrets/create_secret_persistence_no_client_context.test
Labels: Ready For Review

#13646 CI: Allow stale bot to trigger other GH Actions
  .github/workflows/IssuesCloseStale.yml
Labels: Ready For Review

#13640 Fix HTTP logging
  extension/httpfs/httpfs.cpp
Labels: Ready For Review

#13644 Bump spatial and remove patch
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/spatial/context_state.patch
Labels: Ready For Review

#13647 [Fix] list_reduce and list_resize fixes
  src/common/types/vector.cpp
  src/core_functions/scalar/list/list_reduce.cpp
  src/core_functions/scalar/struct/struct_pack.cpp
  src/function/scalar/list/list_resize.cpp
  src/include/duckdb/core_functions/lambda_functions.hpp
  test/sql/function/list/lambdas/reduce.test
  test/sql/function/list/lambdas/reduce_on_larger_data.test_slow
  test/sql/types/nested/list/test_list_functions_with_null_structs.test
Labels: Ready To Merge

#13648 Fix secret test failure
  test/sql/secrets/create_secret_persistence_no_client_context.test
  test/sql/secrets/create_secret_r2.test
Labels: Ready To Merge

#13649 [Metrics] Add `RESULT_SET_SIZE`
  scripts/generate_metric_enums.py
  src/common/enum_util.cpp
  src/include/duckdb/common/enums/metric_type.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/main/profiling_info.cpp
  src/main/query_profiler.cpp
  test/sql/pragma/test_custom_optimizer_profiling.test
  test/sql/pragma/test_custom_profiling_settings.test
Labels: Ready To Merge

#13650 Move breaking compat flags to ClientConfig instead of DBConfig
  src/execution/join_hashtable.cpp
  src/function/scalar/operators/arithmetic.cpp
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/settings/settings.cpp
  src/planner/binder/expression/bind_aggregate_expression.cpp
  src/planner/binder/query_node/plan_subquery.cpp
  src/planner/expression_binder/order_binder.cpp
Labels: Ready To Merge

#13651 Add split part test on csv cli
  data/csv/split_part.csv
  tools/shell/tests/test_read_from_stdin.py
Labels: Ready To Merge

#13652 [Fix] Set the validity mask when creating sort keys for list search
  src/core_functions/lambda_functions.cpp
  src/core_functions/scalar/blob/create_sort_key.cpp
  src/include/duckdb/core_functions/create_sort_key.hpp
  src/include/duckdb/core_functions/lambda_functions.hpp
  src/include/duckdb/function/scalar/list/contains_or_position.hpp
  test/sql/function/list/list_contains.test
Labels: Ready To Merge

#13659 Issue #13598: Range Preceding Fencepost
  src/execution/window_executor.cpp
  test/sql/window/test_window_range.test
Labels: Ready For Review

#13665 Temporary remove delta (that currently builds only on OSX anyhow)
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge
