Repository duckdb/duckdb, pull requests merged in 2025-09, with the labels that each got.

#18796 Internal #3273: Hashed Sort Callbacks
  src/common/sorting/hashed_sort.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/include/duckdb/common/sorting/hashed_sort.hpp
Labels: Ready For Review

#18786 Typed macro parameters
  src/function/macro_function.cpp
  src/function/table/system/duckdb_functions.cpp
  src/include/duckdb/function/macro_function.hpp
  src/include/duckdb/main/attached_database.hpp
  src/include/duckdb/parser/parser.hpp
  src/include/duckdb/planner/binder.hpp
  src/include/duckdb/planner/expression_binder.hpp
  src/include/duckdb/storage/serialization/macro_function.json
  src/main/attached_database.cpp
  src/parser/parser.cpp
  src/parser/transform/statement/transform_create_function.cpp
  src/planner/binder/expression/bind_macro_expression.cpp
  src/planner/binder/query_node/bind_table_macro_node.cpp
  src/planner/binder/statement/bind_create.cpp
  src/storage/serialization/serialize_macro_function.cpp
  test/sql/catalog/function/test_macro_default_arg.test
  test/sql/catalog/function/test_macro_default_arg_with_dependencies.test
  test/sql/catalog/function/test_macro_overloads.test
  test/sql/catalog/function/test_macro_type_overloads.test
  third_party/libpg_query/grammar/statements/create_function.y
  third_party/libpg_query/grammar/types/create_function.yh
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation, Ready For Review

#18769 [Fix] Bug in fixed-size buffer when throwing out-of-memory
  src/execution/index/fixed_size_buffer.cpp
  test/configs/block_size_16kB.json
  test/configs/wal_verification.json
  test/sql/storage/constraints/foreignkey/foreign_key_persistent_memory_limit.test
Labels: Ready For Review, Ready To Merge

#18830 fix: sanitize input for enable_logging
  src/function/table/system/logging_utils.cpp
  test/sql/logging/logging_call_functions.test
Labels: Ready To Merge

#18721 add appender to concurrent test
  test/sql/parallelism/interquery/concurrent_attach_detach.cpp
Labels: Changes Requested

#18886 Json: no reinterpret<size_t*>
  extension/json/include/json_common.hpp
  extension/json/json_functions/json_pretty.cpp
  extension/json/json_functions/json_serialize_plan.cpp
  extension/json/json_functions/json_serialize_sql.cpp
Labels: Ready To Merge

#18929 [unittester] Allow overriding data/ folder to custom location
  test/helpers/test_config.cpp
  test/include/test_config.hpp
  test/sqlite/result_helper.cpp
  test/sqlite/sqllogic_test_runner.cpp
Labels: Ready For Review

#18970 Support renaming a database - ALTER DATABASE <> RENAME TO <>
  Makefile
  extension/autocomplete/grammar/statements/alter.gram
  src/common/enum_util.cpp
  src/execution/operator/schema/physical_alter.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/main/attached_database.hpp
  src/include/duckdb/main/database_manager.hpp
  src/include/duckdb/parser/parsed_data/alter_database_info.hpp
  src/include/duckdb/parser/parsed_data/alter_info.hpp
  src/include/duckdb/parser/transformer.hpp
  src/main/database_manager.cpp
  src/parser/parsed_data/CMakeLists.txt
  src/parser/parsed_data/alter_database_info.cpp
  src/parser/transform/statement/CMakeLists.txt
  src/parser/transform/statement/transform_alter_database.cpp
  src/parser/transformer.cpp
  src/planner/binder/statement/bind_simple.cpp
  test/catalog/CMakeLists.txt
  test/configs/enable_verification.json
  test/sql/alter/test_alter_database_rename.test
  third_party/libpg_query/grammar/statements.list
  third_party/libpg_query/grammar/statements/alter_database.y
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation, Changes Requested

#19000 CI: Increase stale bot timeout to 1 year
  .github/workflows/IssuesCloseStale.yml
Labels: Ready To Merge

#19130 Fix typo
  CONTRIBUTING.md
Labels: Ready For Review

#19139 Properly initialize `StringStats` in Parquet reader
  data/parquet-testing/internal_5994.parquet
  extension/parquet/parquet_statistics.cpp
  src/include/duckdb/storage/statistics/string_stats.hpp
  src/storage/statistics/string_stats.cpp
  test/issues/internal/test_5994.test
Labels: Ready To Merge

#19141 Allow implicit casts from `JSON[]` to `JSON` again
  extension/json/json_functions.cpp
  test/sql/json/scalar/test_json_type.test
Labels: Ready To Merge

#19153 Delay throwing `NotImplementedException` in `ExpressionBinder`
  src/planner/expression_binder.cpp
  test/sql/catalog/function/test_macro_issue_19119.test
Labels: Ready For Review

#19173 Issue #18303: AsOf NLJ Nulls
  src/execution/physical_plan/plan_asof_join.cpp
  test/sql/join/asof/test_asof_join_timestamps.test
Labels: Ready For Review

#19159 Fix missing replacement scan code for CTEs
  src/planner/binder/tableref/bind_basetableref.cpp
  test/sql/cte/cte_with_replacement_scan.test
Labels: Ready To Merge

#19179 HTTPUtil: response might be null, perform check
  src/main/http/http_util.cpp
Labels: Ready To Merge

#19196 Check for unresolved parameters when binding `CREATE MACRO ... AS TABLE`
  src/planner/binder/statement/bind_create.cpp
  src/planner/binder/tableref/bind_pivot.cpp
  src/planner/binder/tableref/bind_table_function.cpp
  src/planner/expression_binder/table_function_binder.cpp
  test/configs/enable_verification.json
  test/sql/catalog/function/test_table_macro_args.test
  test/sql/error/error_position.test
Labels: Ready For Review

#19080 Common Subplan Elimination
  src/common/enum_util.cpp
  src/common/enums/metric_type.cpp
  src/common/enums/optimizer_type.cpp
  src/common/types/column/column_data_collection.cpp
  src/include/duckdb/common/enums/metric_type.hpp
  src/include/duckdb/common/enums/optimizer_type.hpp
  src/include/duckdb/optimizer/common_subplan_optimizer.hpp
  src/include/duckdb/optimizer/cte_inlining.hpp
  src/optimizer/CMakeLists.txt
  src/optimizer/common_subplan_optimizer.cpp
  src/optimizer/cte_inlining.cpp
  src/optimizer/optimizer.cpp
  test/optimizer/common_subplan.test
  test/sql/cte/materialized/automatic_cte_materialization.test_slow
Labels: Ready For Review
