Repository duckdb/duckdb, pull requests merged in 2025-02, with the labels that each got.

#16038 Fix gcc 4.8 compilation
  third_party/fmt/include/fmt/format.h
Labels: Ready For Review

#16039 Replace `FormatException` with `InvalidInputException` in Parquet reader
  extension/parquet/include/parquet_reader.hpp
  extension/parquet/parquet_reader.cpp
Labels: Ready To Merge

#16020 Install errors to point to documentation
  src/include/duckdb/main/extension_helper.hpp
  src/main/extension/extension_install.cpp
  test/extension/install_extension.test
Labels: Ready For Review

#15927 [Dev] Fix issue with UPSERT updating rows in the transaction-local storage
  src/execution/operator/persistent/physical_insert.cpp
  test/sql/upsert/test_big_insert.test
Labels: Ready For Review

#16053 unittests: clear test directory after every test
  src/storage/buffer/block_handle.cpp
  test/helpers/test_helpers.cpp
  test/include/test_helpers.hpp
  test/sql/secrets/create_secret_r2_serialization.test
  test/sql/secrets/create_secret_s3_serialization.test
  test/sql/storage/temp_directory/max_swap_space_inmemory.test
  test/sql/storage/temp_directory/max_swap_space_persistent.test
  test/sqlite/test_sqllogictest.cpp
Labels: Ready To Merge

#16054 Benchmark runner: catch and log errors + add support for `retry load N` syntax
  benchmark/benchmark_runner.cpp
  benchmark/h2oai/group/h2oai.benchmark.in
  benchmark/h2oai/join/h2oai.benchmark.in
  benchmark/h2oai/join/queries/load.sql
  benchmark/include/interpreted_benchmark.hpp
  benchmark/interpreted_benchmark.cpp
Labels: Ready To Merge

#16009 Throw an error when unsupported commands are used in concurrentloop
  test/sqlite/sqllogic_command.cpp
  test/sqlite/sqllogic_command.hpp
  test/sqlite/sqllogic_test_runner.cpp
Labels: Ready To Merge

#15955 Remove extension definitions to prevent re-compilation of the entire system on commit
  CMakeLists.txt
Labels: Ready To Merge, feature

#15815 Display schema information of currently selected database only
  src/catalog/default/default_views.cpp
  test/sql/pg_catalog/sqlalchemy.test
Labels: Ready To Merge

#15864 Issue #14366: Average Intervals
  extension/core_functions/aggregate/algebraic/avg.cpp
  extension/core_functions/include/core_functions/aggregate/sum_helpers.hpp
  test/sql/aggregate/aggregates/test_aggregate_types_scalar.test
  test/sql/aggregate/aggregates/test_avg.test
  test/sql/function/list/aggregates/types.test_slow
  test/sql/types/timestamp/test_timestamp.test
Labels: Ready For Review

#15484 Fix #15466 Transform LIMIT or OFFSET first based on order specified in prepared statement
  src/parser/transform/statement/transform_select_node.cpp
  test/sql/prepared/prepare_offset_first.test
  third_party/libpg_query/grammar/grammar.cpp
  third_party/libpg_query/grammar/grammar.hpp
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Ready To Merge

#15623 Bitpacking mode info
  src/include/duckdb/function/compression_function.hpp
  src/include/duckdb/storage/string_uncompressed.hpp
  src/storage/compression/bitpacking.cpp
  src/storage/table/column_data.cpp
  test/sql/storage/compression/bitpacking/bitpacking_storage_info.test
Labels: Ready To Merge, feature

#15730 Sniff Timestamp_TZ from CSV FIles
  data/csv/timestamp_timezone.csv
  src/common/enum_util.cpp
  src/common/operator/cast_operators.cpp
  src/common/types/timestamp.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/include/duckdb/common/types/timestamp.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_reader_options.hpp
  test/sql/copy/csv/test_csv_timestamp_tz.test
  test/sql/copy/csv/test_timestamp_offset.test
  test/sql/copy/csv/test_union_by_name.test
  test/sql/copy/csv/test_union_by_name_types.test
Labels: Ready To Merge, feature

#16107 BundleStaticLibs to be also triggered by InvokeCI
  .github/workflows/InvokeCI.yml
Labels: Ready To Merge

#16048 Feature #16044: TimeZone Offset Seconds
  extension/icu/icu-strptime.cpp
  src/common/types/time.cpp
  src/common/types/timestamp.cpp
  src/function/scalar/strftime_format.cpp
  src/include/duckdb/common/types/timestamp.hpp
  test/sql/function/timestamp/test_icu_strftime.test
  test/sql/types/timestamp/test_timestamp_tz.test
Labels: Ready For Review

#15355 ATTACH OR REPLACE database to allow swapping of new data.
  src/execution/operator/schema/physical_attach.cpp
  src/main/database_manager.cpp
  src/parser/parsed_data/attach_info.cpp
  test/sql/attach/attach_or_replace.test
  third_party/libpg_query/grammar/statements/attach.y
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Changes Requested

#15534 [Dev] Fix issue related to unpacked columns and the NOT operator
  src/planner/binder/expression/bind_unpacked_star_expression.cpp
  test/fuzzer/fuzz_not_unpacked_columns.test
Labels: Ready For Review

#15621 [Julia] Add support for named params in prepared statements
  tools/juliapkg/src/statement.jl
  tools/juliapkg/test/test_prepare.jl
  tools/juliapkg/test/test_sqlite.jl
Labels: Ready For Review

#16150 Hopefully fixing ci runs
  .github/workflows/LinuxRelease.yml
Labels: Needs Documentation

#16108 Rework invoke
  .github/workflows/BundleStaticLibs.yml
  .github/workflows/InvokeCI.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/OSX.yml
  .github/workflows/Python.yml
  .github/workflows/R.yml
  .github/workflows/Wasm.yml
  .github/workflows/Windows.yml
Labels: Ready To Merge

#15935 Unify behavior of `range`/`generate_series` with PostgreSQL
  extension/icu/icu-table-range.cpp
  src/function/table/range.cpp
  test/sql/table_function/icu_range_timestamptz.test
  test/sql/table_function/range_timestamp.test
  test/sql/table_function/test_range_function.test
Labels: feature

#15919 Adding an extension option shouldn't delete a set value and promote unrecognized options
  src/main/config.cpp
  src/main/database.cpp
Labels: Ready For Review

#16173 [CI] Avoid Linux CLI jobs to fail-fast
  .github/workflows/LinuxRelease.yml
Labels: Ready To Merge

#16179 unified names for duckdb-extensions
  .github/workflows/LinuxRelease.yml
  .github/workflows/Python.yml
  .github/workflows/R.yml
  .github/workflows/Windows.yml
Labels: Ready To Merge

#16201 Concurrency groups for R and Wasm
  .github/workflows/R.yml
  .github/workflows/Wasm.yml
Labels: Ready To Merge

#16207 Ensure MergeCollectionTask has a writer
  src/execution/operator/persistent/physical_batch_insert.cpp
Labels: Ready To Merge

#15939 Add the `TRY` expression
  src/common/enum_util.cpp
  src/common/enums/expression_type.cpp
  src/common/exception.cpp
  src/execution/expression_executor/execute_operator.cpp
  src/include/duckdb/common/enums/expression_type.hpp
  src/include/duckdb/common/exception.hpp
  src/include/duckdb/parser/expression/operator_expression.hpp
  src/parser/transform/expression/transform_function.cpp
  src/planner/binder/expression/bind_operator_expression.cpp
  test/sql/error/test_try_expression.test
Labels: Needs Documentation, feature

#16172 Add parallel memset when building hash join table
  src/execution/join_hashtable.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/include/duckdb/execution/join_hashtable.hpp
Labels: Ready For Review

#16227 Backport #16115
  src/include/duckdb/optimizer/optimizer_extension.hpp
  src/optimizer/optimizer.cpp
Labels: Ready To Merge

#16218 Issue #8265: AsOf Nested Loop
  src/common/settings.json
  src/execution/physical_plan/plan_asof_join.cpp
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/settings/autogenerated_settings.cpp
  test/optimizer/joins/asof_join_adds_rows.test
  test/optimizer/joins/cross_join_and_unnest_dont_work.test
  test/sql/join/asof/test_asof_join.test
  test/sql/join/asof/test_asof_join_doubles.test
  test/sql/join/asof/test_asof_join_inequalities.test
  test/sql/join/asof/test_asof_join_integers.test
  test/sql/join/asof/test_asof_join_merge.test_slow
  test/sql/join/asof/test_asof_join_missing.test_slow
  test/sql/join/asof/test_asof_join_pushdown.test
  test/sql/join/asof/test_asof_join_subquery.test
  test/sql/join/asof/test_asof_join_timestamps.test
  test/sql/join/asof/test_asof_join_varchar.test
Labels: Ready For Review

#16248 Generalize `rowid` into the concept of virtual columns, and make `filename` a virtual column in the Parquet/CSV/JSON readers
  extension/core_functions/scalar/generic/least.cpp
  extension/json/include/json_scan.hpp
  extension/json/json_scan.cpp
  extension/parquet/parquet_extension.cpp
  src/catalog/catalog_entry/table_catalog_entry.cpp
  src/common/constants.cpp
  src/common/multi_file_list.cpp
  src/common/multi_file_reader.cpp
  src/execution/operator/scan/physical_table_scan.cpp
  src/execution/physical_plan/plan_get.cpp
  src/function/table/read_csv.cpp
  src/function/table/table_scan.cpp
  src/function/table_function.cpp
  src/include/duckdb/catalog/catalog_entry/table_catalog_entry.hpp
  src/include/duckdb/common/column_index.hpp
  src/include/duckdb/common/constants.hpp
  src/include/duckdb/common/multi_file_reader.hpp
  src/include/duckdb/common/table_column.hpp
  src/include/duckdb/execution/operator/persistent/physical_export.hpp
  src/include/duckdb/execution/operator/scan/physical_table_scan.hpp
  src/include/duckdb/function/table_function.hpp
  src/include/duckdb/optimizer/late_materialization.hpp
  src/include/duckdb/planner/bind_context.hpp
  src/include/duckdb/planner/operator/logical_get.hpp
  src/include/duckdb/planner/table_binding.hpp
  src/optimizer/late_materialization.cpp
  src/optimizer/remove_unused_columns.cpp
  src/planner/bind_context.cpp
  src/planner/binder/statement/bind_delete.cpp
  src/planner/binder/statement/bind_update.cpp
  src/planner/binder/tableref/bind_basetableref.cpp
  src/planner/binder/tableref/bind_table_function.cpp
  src/planner/operator/logical_get.cpp
  src/planner/table_binding.cpp
  test/sql/copy/csv/test_union_by_name.test
  test/sql/copy/parquet/parquet_filename_filter.test
  test/sql/copy/parquet/parquet_virtual_columns.test
  test/sql/json/table/json_multi_file_reader.test
Labels: Needs Documentation

#16028 A little cleanup.
  src/optimizer/optimizer.cpp
Labels: Changes Requested

#16243 Improve Parquet writer performance
  benchmark/parquet/clickbench_write.benchmark
  extension/parquet/column_writer.cpp
  extension/parquet/include/column_writer.hpp
  extension/parquet/include/parquet_dlba_encoder.hpp
  extension/parquet/include/parquet_rle_bp_encoder.hpp
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/include/writer/parquet_write_operators.hpp
  extension/parquet/include/writer/primitive_column_writer.hpp
  extension/parquet/include/writer/templated_column_writer.hpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_writer.cpp
  extension/parquet/writer/boolean_column_writer.cpp
  extension/parquet/writer/enum_column_writer.cpp
  extension/parquet/writer/primitive_column_writer.cpp
  src/common/serializer/memory_stream.cpp
  src/common/types/column/column_data_collection.cpp
  src/common/types/hash.cpp
  src/execution/operator/persistent/physical_batch_copy_to_file.cpp
  src/include/duckdb/common/primitive_dictionary.hpp
  src/include/duckdb/common/serializer/memory_stream.hpp
  src/include/duckdb/common/types/datetime.hpp
  src/include/duckdb/common/types/hash.hpp
  test/api/adbc/test_adbc.cpp
  test/sql/copy/parquet/bloom_filters.test
  test/sql/copy/parquet/writer/parquet_write_memory_usage.test
  test/sql/function/generic/hash_func.test
Labels: Needs Documentation

#15825 Many reclaim storage fixes
  src/catalog/catalog_entry/duck_table_entry.cpp
  src/execution/operator/persistent/physical_batch_insert.cpp
  src/execution/operator/persistent/physical_insert.cpp
  src/include/duckdb/execution/operator/persistent/physical_insert.hpp
  src/include/duckdb/storage/data_table.hpp
  src/include/duckdb/storage/optimistic_data_writer.hpp
  src/include/duckdb/storage/partial_block_manager.hpp
  src/include/duckdb/storage/table/row_group.hpp
  src/include/duckdb/storage/table/row_group_collection.hpp
  src/include/duckdb/transaction/local_storage.hpp
  src/storage/checkpoint/write_overflow_strings_to_disk.cpp
  src/storage/compression/zstd.cpp
  src/storage/data_table.cpp
  src/storage/local_storage.cpp
  src/storage/partial_block_manager.cpp
  src/storage/table/column_checkpoint_state.cpp
  src/storage/table/row_group.cpp
  src/storage/table/row_group_collection.cpp
  test/sql/storage/optimistic_write/optimistic_write_alter_type.test_slow
  test/sql/storage/optimistic_write/optimistic_write_delete.test
  test/sql/storage/optimistic_write/optimistic_write_drop_column.test_slow
  test/sql/storage/optimistic_write/optimistic_write_update.test
  test/sql/storage/parallel/insert_order_preserving_odd_sized_batches.test_slow
  test/sql/storage/parallel/reclaim_space_insert_unique_idx_optimistic.test_slow
  test/sql/storage/parallel/reclaim_space_primary_key_optimistic.test_slow
Labels: Ready For Review

#16287 Some more Parquet writer performance improvements
  extension/parquet/include/writer/templated_column_writer.hpp
  src/common/types/column/column_data_collection.cpp
  src/common/types/hash.cpp
  test/api/adbc/test_adbc.cpp
  test/sql/function/generic/hash_func.test
Labels: Ready For Review

#16162 Do duckdb_extract_statements to be able to execute pivot in ADBC
  data/csv/flights.csv
  src/common/adbc/adbc.cpp
  test/api/adbc/test_adbc.cpp
Labels: Ready For Review

#16093 [Fix] Early-out on CREATE INDEX (IF NOT EXISTS)
  src/execution/operator/schema/physical_create_art_index.cpp
  src/execution/physical_plan/plan_create_index.cpp
  test/sql/alter/add_pk/test_add_pk_naming_conflict.test
  test/sql/index/art/create_drop/test_art_create_if_exists.test
Labels: Ready For Review

#16300 [Python] Fix the reverse binary expressions in the Expression API
  tools/pythonpkg/src/include/duckdb_python/expression/pyexpression.hpp
  tools/pythonpkg/src/pyexpression.cpp
  tools/pythonpkg/src/pyexpression/initialize.cpp
  tools/pythonpkg/tests/fast/test_expression.py
Labels: Ready To Merge

#16279 Fix heap buffer oveflow sampling
  src/execution/operator/helper/physical_reservoir_sample.cpp
  src/execution/sample/reservoir_sample.cpp
  src/include/duckdb/execution/reservoir_sample.hpp
  test/sql/sample/get_multiple_samples_small.test_slow
Labels: Ready For Review

#16327 Inline virtual list lambda bind functions
  extension/core_functions/lambda_functions.cpp
  src/include/duckdb/function/lambda_functions.hpp
Labels: Ready To Merge

#16330 Fix decorrelation of WITH USING KEY
  src/planner/subquery/flatten_dependent_join.cpp
  test/sql/cte/recursive_cte_key_variant.test
Labels: Ready To Merge

#16320 Issue #16250: Window Range Performance
  src/function/window/window_boundaries_state.cpp
Labels: Ready For Review

#16328 Verify UTF-8 in `DeltaLengthByteArrayDecoder` and speed it up
  extension/parquet/decoder/delta_length_byte_array_decoder.cpp
  extension/parquet/include/decoder/delta_length_byte_array_decoder.hpp
  src/function/scalar/string/strip_accents.cpp
  third_party/utf8proc/utf8proc_wrapper.cpp
Labels: Ready To Merge

#16348 [chore] No ccache for OSX Python
  .github/workflows/Python.yml
Labels: Ready For Review

#16347 Linux CLI: override platform for ARM manylinux
  .github/workflows/LinuxRelease.yml
Labels: Ready For Review

#16301 Parallel HT Zeroing: Set entries_per_task so that there are 4x more tasks than threads
  src/execution/operator/join/physical_hash_join.cpp
Labels: Ready To Merge

#16095 Internal #2176: SUMMARIZE Temporal Types
  extension/core_functions/aggregate/algebraic/avg.cpp
  src/planner/binder/statement/bind_summarize.cpp
  test/sql/aggregate/aggregates/test_avg.test
  test/sql/function/list/aggregates/types.test_slow
  test/sql/show_select/test_summarize.test
Labels: Ready To Merge

#16378 Add parquet 'unknown' logical type
  extension/parquet/parquet_reader.cpp
Labels: Ready To Merge

#16066 pb/compressed vector serialization
  src/common/types/data_chunk.cpp
  src/common/types/vector.cpp
  src/include/duckdb/common/types/data_chunk.hpp
  src/include/duckdb/common/types/vector.hpp
Labels: Changes Requested

#16416 Issue #16407: Try_Strptime Invalid TimeZone
  extension/icu/icu-datefunc.cpp
  extension/icu/icu-strptime.cpp
  extension/icu/include/icu-datefunc.hpp
  test/sql/function/timestamp/test_icu_strptime.test
Labels: Ready For Review

#16417 Internal #4303: Windowed DISTINCT Leaks
  src/function/window/window_aggregate_states.cpp
  src/function/window/window_distinct_aggregator.cpp
Labels: Ready For Review

#16415 Internal #4258: MODE Spooling Stability
  test/sql/window/test_custom_spooling.test_slow
Labels: Ready For Review

#16399 [Fix] Throw constraint violation for FK constraint checking
  src/execution/index/art/art.cpp
  test/sql/constraints/foreignkey/test_fk_eager_constraint_checking.test
Labels: Needs Documentation

#16435 Fixup #16400 by correctly passing down SETUPTOOLS_SCM_PRETEND_VERSION
  tools/pythonpkg/setup.py
Labels: Draft

#16438 Issue #16250: Window Range Performance
  src/function/window/window_boundaries_state.cpp
Labels: Ready For Review

#16444 Adding windows code signing using azure
  .github/workflows/Windows.yml
Labels: Ready To Merge

#16357 fix documents of C functions
  src/include/duckdb.h
  src/include/duckdb/main/capi/header_generation/functions/aggregate_functions.json
  src/include/duckdb/main/capi/header_generation/functions/query_execution.json
  src/include/duckdb/main/capi/header_generation/functions/scalar_functions.json
  src/include/duckdb/main/capi/header_generation/functions/table_functions.json
  src/include/duckdb/main/capi/header_generation/header_base.hpp.template
Labels: Ready To Merge
