Repository duckdb/duckdb, pull requests merged in 2025-04, with the labels that each got.

#16870 [Nested] Enable Varargs in `LIST_CONCAT`
  src/function/scalar/string/concat.cpp
  test/sql/function/list/list_concat.test
  test/sql/function/string/test_concat_binding.test
  test/sql/types/list/list_concat_null.test
Labels: Needs Documentation, Ready To Merge

#16923 Skip tests for Python 3.8, already end-of-life
  .github/workflows/Python.yml
Labels: Ready To Merge

#16916 Bump to avro version that now support wasm
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#16914 Unwrap DUCKDB_EXTENSION__LINKED_LIBS via CMake
  CMakeLists.txt
Labels: Ready To Merge

#16925 C API comments: Fix a/an typos
  src/include/duckdb.h
  src/include/duckdb/main/capi/header_generation/functions/bind_values_to_prepared_statements.json
  src/include/duckdb/main/capi/header_generation/functions/value_interface.json
  src/include/duckdb/main/capi/header_generation/functions/vector_interface.json
Labels: Ready For Review

#16931 Internal #4552: Short Circuit CSE
  extension/icu/icu-datefunc.cpp
  src/optimizer/cse_optimizer.cpp
Labels: Ready For Review

#16944 Add back manylinux extensions
  .github/actions/build_extensions_dockerized/action.yml
  .github/workflows/Python.yml
Labels: Ready To Merge

#16904 Internal #4516: Interval BIGINT Variants
  extension/core_functions/function_list.cpp
  extension/core_functions/include/core_functions/scalar/date_functions.hpp
  extension/core_functions/scalar/date/functions.json
  extension/core_functions/scalar/date/to_interval.cpp
  test/sql/types/interval/interval_constants.test
Labels: Ready To Merge

#16913 bump out-of-tree extensions to v1.2.2
  .github/config/out_of_tree_extensions.cmake
  scripts/generate_extensions_function.py
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#17003 Add support for altering struct columns (adding fields, dropping fields, renaming fields)
  src/catalog/catalog_entry/duck_table_entry.cpp
  src/common/enum_util.cpp
  src/include/duckdb/catalog/catalog_entry/duck_table_entry.hpp
  src/include/duckdb/catalog/catalog_entry/table_catalog_entry.hpp
  src/include/duckdb/parser/parsed_data/alter_table_info.hpp
  src/include/duckdb/parser/transformer.hpp
  src/include/duckdb/storage/serialization/parse_info.json
  src/parser/parsed_data/alter_table_info.cpp
  src/parser/transform/statement/transform_alter_table.cpp
  src/parser/transform/statement/transform_rename.cpp
  src/storage/serialization/serialize_parse_info.cpp
  test/sql/alter/struct/add_col_nested_struct.test
  test/sql/alter/struct/add_col_struct.test
  test/sql/alter/struct/drop_col_nested_struct.test
  test/sql/alter/struct/drop_col_struct.test
  test/sql/alter/struct/rename_col_nested_struct.test
  test/sql/alter/struct/rename_col_struct.test
  third_party/libpg_query/grammar/statements/alter_table.y
  third_party/libpg_query/grammar/statements/create.y
  third_party/libpg_query/grammar/statements/rename.y
  third_party/libpg_query/grammar/types/alter_table.yh
  third_party/libpg_query/grammar/types/create.yh
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation

#16999 Update links pointing to duckdb.org
  README.md
  data/storage/README.md
  extension/delta/README.md
  src/common/error_data.cpp
  src/common/local_file_system.cpp
  src/common/multi_file/multi_file_reader.cpp
  src/main/extension/extension_install.cpp
  test/extension/install_extension.test
  tools/pythonpkg/pyproject.toml
  tools/pythonpkg/setup.py
Labels: Needs Documentation, Ready To Merge

#16965 Fix for joining on floating columns #16901
  src/common/types.cpp
  src/include/duckdb/common/types.hpp
  src/optimizer/remove_unused_columns.cpp
  test/optimizer/joins/join_on_doubles.test
  test/optimizer/joins/join_on_floats.test
Labels: Changes Requested

#17028 Issue #17001: AsOf memory Management
  src/execution/operator/join/physical_asof_join.cpp
Labels: Ready For Review

#17031 Handle Parquet with compressed empty DataPage v2
  data/parquet-testing/compression/empty_datapage_v2.snappy.parquet
  extension/parquet/column_reader.cpp
  test/parquet/test_parquet_reader_compression.test
Labels: Ready To Merge

#17053 FORCE_ASYNC_SINK_SOURCE: pass also to unittester
  .github/workflows/NightlyTests.yml
Labels: Ready To Merge

#16949 trigger .github/workflows/NightlyBuildsCheck.yml from external repo
  .github/workflows/NotifyExternalRepositories.yml
Labels: Ready To Merge

#17072 Re-enable Avro on core
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/avro/avro_multi_file_reader.patch
  scripts/apply_extension_patches.py
Labels: Ready For Review

#17061 Grow string dictionary dynamically in Parquet writer
  extension/parquet/include/parquet_bss_encoder.hpp
  extension/parquet/include/parquet_dbp_encoder.hpp
  extension/parquet/include/parquet_dlba_encoder.hpp
  extension/parquet/include/writer/primitive_column_writer.hpp
  extension/parquet/include/writer/templated_column_writer.hpp
  extension/parquet/parquet_extension.cpp
  src/include/duckdb/common/primitive_dictionary.hpp
  test/sql/copy/parquet/bloom_filters.test
Labels: Ready For Review

#17094 fsst: Avoid to propagate alignment information in FSST_UNALIGNED_STORE
  third_party/fsst/fsst.h
Labels: Ready For Review

#17095 Fix sqlite3 api wrapper link + remove R-CMD-check + add more nightly tests
  .github/workflows/NightlyTests.yml
  .github/workflows/R_CMD_CHECK.yml
  tools/sqlite3_api_wrapper/CMakeLists.txt
Labels: Ready For Review

#17064 support large dictionary value and constant vector creation in the C API
  src/include/duckdb.h
  src/include/duckdb/main/capi/extension_api.hpp
  src/include/duckdb/main/capi/header_generation/apis/v1/unstable/new_vector_types.json
  src/include/duckdb/main/capi/header_generation/functions/vector_interface.json
  src/include/duckdb_extension.h
  src/main/capi/data_chunk-c.cpp
Labels: Changes Requested

#17101 Valgrind requires tpch
  .github/workflows/Main.yml
Labels: Ready To Merge

#16956 Switch to manylinux_2_28
  .github/actions/build_extensions/action.yml
  .github/actions/build_extensions_dockerized/action.yml
  .github/actions/manylinux_2014_setup/action.yml
  .github/config/distribution_matrix.json
  .github/workflows/BundleStaticLibs.yml
  .github/workflows/DockerTests.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/Main.yml
  .github/workflows/OSX.yml
  .github/workflows/Python.yml
  extension/delta/README.md
  scripts/setup_manylinux2014.sh
  src/include/duckdb/common/platform.hpp
Labels: Ready To Merge

#16196 Changing mbedtls encryption API
  .github/patches/extensions/httpfs/mbedtls_refactor.patch
  extension/parquet/parquet_crypto.cpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_writer.cpp
  src/common/encryption_state.cpp
  src/include/duckdb/common/encryption_state.hpp
  third_party/mbedtls/include/mbedtls_wrapper.hpp
  third_party/mbedtls/library/cipher_wrap.cpp
  third_party/mbedtls/mbedtls_wrapper.cpp
Labels: Ready To Merge

#17127 Remove R_CMD_CHECK.yml, now handled by duckdb/duckdb-r repo
  .github/workflows/R_CMD_CHECK.yml
Labels: Ready For Review

#17104 Refactor relassert runs, adding some variations in compiler / statically linked extensions
  .github/workflows/NightlyTests.yml
Labels: Ready To Merge

#17120 extension-upload-from-nightly.sh: Add --region
  scripts/extension-upload-from-nightly.sh
Labels: Ready To Merge

#17125 Remove misleading lock comment in data table
  src/include/duckdb/transaction/duck_transaction_manager.hpp
  src/storage/data_table.cpp
Labels: Ready To Merge

#17108 Notify nightly build status
  .github/workflows/InvokeCI.yml
  .github/workflows/NotifyExternalRepositories.yml
Labels: Ready To Merge

#17137 platform.hpp: Propagate DUCKDB_EXPLICIT_PLATFORM, avoid early return
  CMakeLists.txt
  src/include/duckdb/common/platform.hpp
Labels: Ready For Review

#17045 Keeping the filters which do not remove NULL values
  src/optimizer/pushdown/pushdown_left_join.cpp
  test/optimizer/pushdown/issue_17042.test
Labels: Ready For Review

#17163 [InvokeCI] Add missing pipe to run instruction
  .github/workflows/InvokeCI.yml
Labels: Ready To Merge

#17162 Issue #17115: TimeTZ Approximate Quantile
  extension/core_functions/aggregate/holistic/approximate_quantile.cpp
  test/sql/aggregate/aggregates/test_approx_quantile.test
  test/sql/show_select/test_summarize.test
Labels: Ready For Review

#17107 Python.yml: Add back logic to perform fast-fail on Python 3.10
  .github/workflows/Python.yml
Labels: Ready To Merge

#17099 Notify JDBC repo to run Vendor.yml workflow
  .github/workflows/NotifyExternalRepositories.yml
Labels: Ready To Merge

#17067 Issue #17049: ICU Date Cast
  extension/icu/icu-timezone.cpp
  test/sql/timezone/test_icu_timezone.test
Labels: Ready For Review

#17118 [ENCRYPTION] Make block header size adaptive
  src/common/file_buffer.cpp
  src/execution/index/fixed_size_buffer.cpp
  src/include/duckdb/common/file_buffer.hpp
  src/include/duckdb/common/types/row/row_data_collection.hpp
  src/include/duckdb/function/compression_function.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/storage/block.hpp
  src/include/duckdb/storage/block_manager.hpp
  src/include/duckdb/storage/buffer_manager.hpp
  src/include/duckdb/storage/compression/alp/alp_analyze.hpp
  src/include/duckdb/storage/compression/alp/alp_compress.hpp
  src/include/duckdb/storage/compression/alprd/alprd_analyze.hpp
  src/include/duckdb/storage/compression/alprd/alprd_compress.hpp
  src/include/duckdb/storage/compression/empty_validity.hpp
  src/include/duckdb/storage/single_file_block_manager.hpp
  src/include/duckdb/storage/standard_buffer_manager.hpp
  src/include/duckdb/storage/storage_info.hpp
  src/include/duckdb/storage/storage_options.hpp
  src/include/duckdb/storage/table/column_segment.hpp
  src/main/attached_database.cpp
  src/parser/parsed_data/attach_info.cpp
  src/storage/block.cpp
  src/storage/buffer/block_handle.cpp
  src/storage/buffer/block_manager.cpp
  src/storage/buffer_manager.cpp
  src/storage/checkpoint/write_overflow_strings_to_disk.cpp
  src/storage/compression/bitpacking.cpp
  src/storage/compression/dictionary/compression.cpp
  src/storage/compression/dictionary_compression.cpp
  src/storage/compression/fixed_size_uncompressed.cpp
  src/storage/compression/fsst.cpp
  src/storage/compression/rle.cpp
  src/storage/compression/roaring/common.cpp
  src/storage/compression/roaring/compress.cpp
  src/storage/compression/string_uncompressed.cpp
  src/storage/compression/validity_uncompressed.cpp
  src/storage/compression/zstd.cpp
  src/storage/metadata/metadata_manager.cpp
  src/storage/single_file_block_manager.cpp
  src/storage/standard_buffer_manager.cpp
  src/storage/storage_info.cpp
  src/storage/storage_manager.cpp
  src/storage/table/column_data.cpp
  src/storage/table/column_segment.cpp
  src/storage/temporary_file_manager.cpp
  src/storage/wal_replay.cpp
  test/sql/attach/attach_encryption_block_header.test
  test/sql/copy/encryption/simple_encryption.test
  test/sql/storage/test_buffer_manager.cpp
Labels: Ready For Review

#16899 Issue #16839: Disable TIMESTAMP Casts
  extension/icu/icu-timezone.cpp
  src/common/settings.json
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/settings/autogenerated_settings.cpp
  test/sql/timezone/disable_timestamptz_casts.test
Labels: Ready For Review

#17212 Fix [InvokeCI / NotifyExternalRepository] Unexpected value 'true'
  .github/workflows/InvokeCI.yml
  .github/workflows/NotifyExternalRepositories.yml
Labels: Ready To Merge

#17283 Internal #4772: Timestamp Error Parameter
  extension/icu/icu-timezone.cpp
Labels: Ready For Review

#17303 Internal #4532: 13 Month Intervals
  extension/icu/icu-dateadd.cpp
  extension/icu/include/icu-datefunc.hpp
  extension/icu/include/tz_calendar.hpp
  test/sql/timezone/icu_calendar_operations.test
Labels: Ready For Review

#17271 Add root's query_location also to TransformInterval
  .github/workflows/Windows.yml
  src/parser/transform/expression/transform_interval.cpp
Labels: Ready To Merge

#17302 Issue #16563: FLOAT to DECIMAL
  src/common/operator/cast_operators.cpp
  test/sql/cast/float_decimal_cast.test
  test/sql/join/iejoin/iejoin_projection_maps.test
Labels: Ready For Review

#17304 Feature #15873: Windowed ORDER BYs
  benchmark/micro/window/window_rownumber_orderbys.benchmark
  src/function/window/window_boundaries_state.cpp
  src/function/window/window_rank_function.cpp
  src/function/window/window_rownumber_function.cpp
  src/function/window/window_value_function.cpp
  test/sql/window/test_cume_dist_orderby.test
  test/sql/window/test_leadlag_orderby.test
  test/sql/window/test_rank_orderby.test
Labels: Ready For Review
