Repository duckdb/duckdb, pull requests merged in 2025-07, with the labels that each got.

#18111 Cleanup on correct branch (1.3-ossivalis) instead of v1.2-histrionicus
  .github/workflows/Python.yml
Labels: Ready To Merge

#18113 Internal #3273: Window Task Generation
  src/execution/operator/aggregate/physical_window.cpp
Labels: Ready To Merge

#18119 CI: Actually correctly skip building unnecessary extensions
  .github/actions/build_extensions/action.yml
Labels: Ready To Merge

#18114 Absorb patch from https://github.com/duckdb/duckdb/pull/18107
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/httpfs/httpfs.patch
Labels: Ready To Merge

#18053 Issue #17683: TIME_NS Compilation
  Makefile
  extension/core_functions/scalar/date/date_part.cpp
  extension/json/json_functions/json_create.cpp
  extension/json/json_functions/json_transform.cpp
  extension/parquet/column_reader.cpp
  extension/parquet/include/parquet_timestamp.hpp
  extension/parquet/parquet_statistics.cpp
  extension/parquet/parquet_timestamp.cpp
  extension/parquet/parquet_writer.cpp
  src/common/enum_util.cpp
  src/common/operator/cast_operators.cpp
  src/common/operator/string_cast.cpp
  src/common/types.cpp
  src/common/types/timestamp.cpp
  src/common/types/value.cpp
  src/common/types/vector.cpp
  src/function/cast/default_casts.cpp
  src/function/cast/string_cast.cpp
  src/function/cast/time_casts.cpp
  src/include/duckdb/catalog/default/builtin_types/types.hpp
  src/include/duckdb/catalog/default/builtin_types/types.json
  src/include/duckdb/common/operator/cast_operators.hpp
  src/include/duckdb/common/operator/string_cast.hpp
  src/include/duckdb/common/types.hpp
  src/include/duckdb/common/types/datetime.hpp
  src/include/duckdb/common/types/timestamp.hpp
  src/include/duckdb/common/types/value.hpp
  src/include/duckdb/function/cast/default_casts.hpp
  src/include/duckdb/main/extension_entries.hpp
  test/parquet/timens_parquet.test
  test/sql/types/time/test_time_ns.test
Labels: Ready For Review

#18148 Bump iceberg for 1.3.2, from @Tishj, and bumping also httpfs
  .github/config/out_of_tree_extensions.cmake
  scripts/merge_vcpkg_deps.py
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready For Review

#18167 Bump for wasm fixes (excel and httpfs) and test fixes (iceberg)
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#18162 Resolve some small build issues
  CMakeLists.txt
  Makefile
Labels: Ready To Merge

#18174 Avoid `realloc` in CSV writer
  src/function/table/copy_csv.cpp
Labels: Ready To Merge

#18172 Parquet reader logging
  extension/parquet/include/parquet_reader.hpp
  extension/parquet/parquet_multi_file_info.cpp
  extension/parquet/parquet_reader.cpp
  src/execution/operator/scan/physical_table_scan.cpp
  src/include/duckdb/common/multi_file/multi_file_function.hpp
  src/include/duckdb/common/multi_file/multi_file_states.hpp
  src/include/duckdb/function/table_function.hpp
  test/sql/logging/physical_operator_logging.test_slow
Labels: Ready To Merge

#18198 Add VS2019 compat flag to Python wheel build
  tools/pythonpkg/setup.py
Labels: Ready To Merge

#18219 Allow explicit compression for user types
  src/planner/binder/statement/bind_create_table.cpp
  test/sql/json/issues/internal_issue5288.test
Labels: Ready For Review

#18217 Improve Parquet reader `NULL` statistics and compress all-`NULL` columns using `CompressedMaterialization`
  extension/parquet/column_reader.cpp
  extension/parquet/include/parquet_column_schema.hpp
  extension/parquet/include/parquet_reader.hpp
  extension/parquet/parquet_multi_file_info.cpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_statistics.cpp
  src/common/multi_file/base_file_reader.cpp
  src/include/duckdb/common/multi_file/base_file_reader.hpp
  src/include/duckdb/common/multi_file/multi_file_function.hpp
  src/include/duckdb/optimizer/compressed_materialization.hpp
  src/optimizer/compressed_materialization.cpp
  src/optimizer/compressed_materialization/compress_comparison_join.cpp
  test/optimizer/compressed_materialization.test_slow
  test/parquet/parquet_null_compressed_materialization.test_slow
  test/parquet/parquet_stats_function.test
  test/sql/copy/parquet/writer/write_stats_null_count.test
Labels: Ready For Review

#18216 Internal #5264: NLJ Not Distinct
  src/execution/nested_loop_join/nested_loop_join_inner.cpp
  src/planner/operator/logical_comparison_join.cpp
  test/sql/join/iejoin/merge_join_switch.test
  test/sql/join/inner/test_join_is_not_distinct.test
Labels: Ready For Review

#18127 Dictionary functions
  benchmark/micro/functions/dictionary_function.benchmark
  src/common/types/vector.cpp
  src/execution/aggregate_hashtable.cpp
  src/execution/expression_executor/execute_function.cpp
  src/include/duckdb/common/types/vector.hpp
  src/include/duckdb/execution/expression_executor_state.hpp
  src/include/duckdb/storage/compression/dict_fsst/decompression.hpp
  src/storage/compression/dict_fsst.cpp
  src/storage/compression/dict_fsst/decompression.cpp
Labels: Ready To Merge

#17942 Add support for geoarrow encoded geometries in geoparquet files.
  extension/parquet/geo_parquet.cpp
  extension/parquet/parquet_reader.cpp
  test/geoparquet/geoarrow.test
  test/geoparquet/seattle.parquet
Labels: Ready To Merge

#18203 [Fix] Don't write empty (partial) blocks for FSST dictionary compression
  src/include/duckdb/storage/table/column_segment.hpp
  src/storage/partial_block_manager.cpp
  src/storage/table/column_checkpoint_state.cpp
  src/storage/table/column_segment.cpp
  test/sql/storage/compression/dict_fsst/fetch_row.test
  test/sql/storage/compression/dict_fsst/test_dict_fsst_with_smaller_block_size.test
Labels: Ready For Review

#18235 Slightly higher memory limit for test
  test/parquet/parquet_null_compressed_materialization.test_slow
Labels: Ready To Merge

#17976 update run_extension_medata_tests.sh
  scripts/run_extension_medata_tests.sh
  test/extension/update_extensions_ci.test
Labels: Changes Requested

#18129 disable WebAssembly duckdb-wasm builds job in NightlyTests triggered by 'workflow_dispatch' event
  .github/workflows/NightlyTests.yml
Labels: Ready To Merge

#18226 Allow for static libs from extension dependencies to be bundled
  Makefile
Labels: Ready To Merge

#13277 Support HUGEINT in printf and format
  extension/core_functions/scalar/string/printf.cpp
  test/sql/function/string/test_format_extensions.test
  test/sql/function/string/test_printf.test
  third_party/fmt/include/fmt/core.h
  third_party/fmt/include/fmt/format-inl.h
  third_party/fmt/include/fmt/format.h
  third_party/fmt/include/fmt/printf.h
Labels: Changes Requested

#18289 Fixup Main.yml for v1.3-ossivalis post https://github.com/duckdb/duckdb/pull/18282
  .github/workflows/Main.yml
Labels: Ready To Merge

#18292 resolve hidden merge conflict with duplicate db name in json configs
  test/configs/encrypted_db.json
  test/configs/latest_storage.json
Labels: Ready To Merge

#18317 Skip test/sql/copy/s3/url_encode.test due to httpfs update
  test/sql/copy/s3/url_encode.test
Labels: Ready To Merge

#18306 Backport #18254
  test/extension/autoloading_base.test
  test/extension/autoloading_current_setting.test
  test/extension/autoloading_filesystems.test
  test/extension/autoloading_load_only.test
  test/extension/autoloading_reset_setting.test
  test/extension/duckdb_extension_settings.test
  test/issues/general/test_16213.test_slow
  test/sql/function/list/lambdas/incorrect.test
  test/sql/logging/file_system_logging.test
  test/sql/pragma/test_enable_http_logging.test
Labels: Ready For Review

#18344 Fix debug error in join order optimizer
  src/optimizer/join_order/plan_enumerator.cpp
  test/optimizer/join_reorder_optimizer.test
  test/optimizer/joins/test_tpcds_pushdown.test
Labels: Ready To Merge

#18348 Add support for checkpointing in-memory tables
  .github/workflows/Main.yml
  src/execution/operator/schema/physical_attach.cpp
  src/include/duckdb/common/enums/checkpoint_type.hpp
  src/include/duckdb/main/attached_database.hpp
  src/include/duckdb/parser/parsed_data/attach_info.hpp
  src/include/duckdb/storage/checkpoint/row_group_writer.hpp
  src/include/duckdb/storage/checkpoint_manager.hpp
  src/include/duckdb/storage/partial_block_manager.hpp
  src/include/duckdb/storage/storage_manager.hpp
  src/include/duckdb/storage/storage_options.hpp
  src/include/duckdb/storage/table/column_checkpoint_state.hpp
  src/include/duckdb/storage/table/column_data.hpp
  src/include/duckdb/storage/table/column_data_checkpointer.hpp
  src/include/duckdb/storage/table/column_segment.hpp
  src/include/duckdb/storage/table/in_memory_checkpoint.hpp
  src/main/attached_database.cpp
  src/parser/parsed_data/attach_info.cpp
  src/storage/checkpoint/row_group_writer.cpp
  src/storage/checkpoint_manager.cpp
  src/storage/compression/fixed_size_uncompressed.cpp
  src/storage/partial_block_manager.cpp
  src/storage/storage_manager.cpp
  src/storage/table/CMakeLists.txt
  src/storage/table/column_checkpoint_state.cpp
  src/storage/table/column_data.cpp
  src/storage/table/column_data_checkpointer.cpp
  src/storage/table/column_segment.cpp
  src/storage/table/in_memory_checkpoint.cpp
  src/storage/table/row_group.cpp
  src/storage/table/row_group_collection.cpp
  src/storage/table/standard_column_data.cpp
  src/transaction/duck_transaction.cpp
  src/transaction/duck_transaction_manager.cpp
  src/transaction/meta_transaction.cpp
  test/configs/compressed_in_memory.json
  test/sql/delete/in_memory_bulk_delete.test_slow
  test/sql/delete/in_memory_truncate.test_slow
  test/sql/index/art/nodes/test_art_sparse_row_ids.test_slow
  test/sql/storage/memory/in_memory_compress.test
Labels: Needs Documentation

#18377 Re-enable but deprecate CORE_EXTENSIONS in CMakeLists.txt
  CMakeLists.txt
Labels: Ready To Merge

#18397 CI: Fix Discussion mirroring
  .github/workflows/InternalIssuesCreateMirror.yml
Labels: Ready To Merge

#18400 Wrap runner.ExecuteFile, otherwise cleanup is not properly performed
  test/sqlite/test_sqllogictest.cpp
Labels: Ready For Review

#18407 CI: Add separate job for discussion mirroring
  .github/workflows/InternalIssuesCreateMirror.yml
  .github/workflows/MirrorDiscussions.yml
Labels: Ready To Merge

#18401 Merge `v1.3-ossivalis` in `main`
  .github/actions/build_extensions/action.yml
  .github/workflows/BundleStaticLibs.yml
  .github/workflows/Main.yml
  .github/workflows/NightlyTests.yml
  CMakeLists.txt
  Makefile
  extension/core_functions/scalar/generic/current_setting.cpp
  src/catalog/catalog.cpp
  src/execution/operator/helper/physical_reset.cpp
  src/execution/operator/helper/physical_set.cpp
  src/include/duckdb/catalog/catalog.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/storage/storage_info.hpp
  test/configs/latest_storage_block_size_16kB.json
  test/configs/small_block_size.json
  test/helpers/test_config.cpp
  test/helpers/test_helpers.cpp
  test/include/test_config.hpp
Labels: Ready For Review

#18361 Refactor extension CI to use extension-ci-tools
  .github/actions/build_extensions/action.yml
  .github/actions/build_extensions_dockerized/action.yml
  .github/config/distribution_matrix.json
  .github/config/extensions/delta.cmake
  .github/config/in_tree_extensions.cmake
  .github/config/out_of_tree_extensions.cmake
  .github/config/rust_based_extensions.cmake
  .github/patches/extensions/delta/multi_file_reader.patch
  .github/patches/extensions/delta/zzz_delta_loader.patch
  .github/workflows/BundleStaticLibs.yml
  .github/workflows/Extensions.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/OSX.yml
  .github/workflows/R.yml
  .github/workflows/Wasm.yml
  .github/workflows/Windows.yml
  .github/workflows/_extension_distribution.yml
  .github/workflows/_sign_deploy_extensions.yml
  Makefile
  scripts/extension-upload-repository.sh
  scripts/merge_vcpkg_deps.py
Labels: Ready To Merge

#18408 Internal #5367: SortedAggregateFunction Sort Update
  src/function/aggregate/sorted_aggregate_function.cpp
Labels: Ready For Review

#18410 Add support for "template" types
  extension/core_functions/aggregate/nested/list.cpp
  extension/core_functions/function_list.cpp
  extension/core_functions/include/core_functions/scalar/list_functions.hpp
  extension/core_functions/include/core_functions/scalar/map_functions.hpp
  extension/core_functions/scalar/list/flatten.cpp
  extension/core_functions/scalar/list/functions.json
  extension/core_functions/scalar/list/list_aggregates.cpp
  extension/core_functions/scalar/list/list_has_any_or_all.cpp
  extension/core_functions/scalar/list/list_value.cpp
  extension/core_functions/scalar/map/functions.json
  extension/core_functions/scalar/map/map.cpp
  extension/core_functions/scalar/map/map_entries.cpp
  extension/core_functions/scalar/map/map_extract.cpp
  extension/core_functions/scalar/map/map_from_entries.cpp
  extension/core_functions/scalar/map/map_keys_values.cpp
  extension/core_functions/scalar/string/repeat.cpp
  src/common/enum_util.cpp
  src/common/extra_type_info.cpp
  src/common/types.cpp
  src/function/cast_rules.cpp
  src/function/function_binder.cpp
  src/function/scalar/list/contains_or_position.cpp
  src/function/scalar/list/list_extract.cpp
  src/function/scalar/list/list_select.cpp
  src/function/scalar/map/map_contains.cpp
  src/include/duckdb/common/extra_type_info.hpp
  src/include/duckdb/common/type_visitor.hpp
  src/include/duckdb/common/types.hpp
  src/include/duckdb/function/function_binder.hpp
  src/include/duckdb/function/function_serialization.hpp
  src/include/duckdb/storage/serialization/types.json
  src/storage/serialization/serialize_types.cpp
  test/sql/binder/old_implicit_cast.test
  test/sql/function/list/list_contains.test
  test/sql/function/list/list_distinct.test
  test/sql/function/list/list_has_any_and_has_all.test
  test/sql/function/list/list_position.test
  test/sql/function/list/list_unique.test
  test/sql/function/list/list_value_arrays.test
  test/sql/function/list/list_value_nested_lists.test
  test/sql/types/map/map_cast.test
  test/sql/types/nested/list/array.test
  test/sql/types/nested/map/map_error.test
  test/sql/types/nested/map/test_map_subscript.test
  test/sql/types/nested/map/test_map_subscript_composite.test
Labels: Ready To Merge

#18442 Internal #5384: WindowDistinctAggregator Sort Update
  src/execution/operator/aggregate/physical_window.cpp
  src/function/window/window_collection.cpp
  src/function/window/window_distinct_aggregator.cpp
  src/include/duckdb/function/window/window_collection.hpp
Labels: Ready For Review

#18313 Buffer index appends during WAL replay
  .github/patches/extensions/spatial/arrow_capi.patch
  .github/patches/extensions/spatial/fix.patch
  .github/patches/extensions/spatial/tuple_data_layout_nulls.patch
  .github/patches/extensions/vss/fix.patch
  src/common/enum_util.cpp
  src/execution/index/bound_index.cpp
  src/execution/index/unbound_index.cpp
  src/execution/operator/persistent/physical_batch_insert.cpp
  src/execution/operator/persistent/physical_copy_database.cpp
  src/execution/operator/persistent/physical_insert.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/execution/index/bound_index.hpp
  src/include/duckdb/execution/index/unbound_index.hpp
  src/include/duckdb/storage/data_table.hpp
  src/include/duckdb/storage/table/data_table_info.hpp
  src/include/duckdb/storage/table/table_index_list.hpp
  src/planner/binder/statement/bind_insert.cpp
  src/storage/data_table.cpp
  src/storage/local_storage.cpp
  src/storage/table_index_list.cpp
  test/sql/index/art/storage/test_art_wal_replay_with_buffer.test
  test/sql/index/art/storage/test_art_wal_replay_with_buffer_concurrent.test
  test/sql/index/art/types/test_art_union.test
  test/sql/upsert/insert_or_replace/unique_index.test
  test/sql/upsert/test_generated_column.test
Labels: Ready For Review, Ready To Merge
