Repository duckdb/duckdb, pull requests merged in 2025-06, with the labels that each got.

#17730 Internal #4995: Commutative INTERVAL Multiply
  src/function/scalar/operator/arithmetic.cpp
  test/fuzzer/sqlsmith/interval_multiply_overflow.test
  test/sql/function/interval/test_interval_muldiv.test
Labels: Ready For Review

#17745 Deprecate windows-2019 runners
  .github/workflows/BundleStaticLibs.yml
  .github/workflows/Python.yml
  .github/workflows/R.yml
  .github/workflows/Windows.yml
Labels: Ready To Merge

#17722 [CAPI] Expose ErrorData
  scripts/generate_c_api.py
  src/include/duckdb.h
  src/include/duckdb/common/error_data.hpp
  src/include/duckdb/main/capi/capi_internal.hpp
  src/include/duckdb/main/capi/extension_api.hpp
  src/include/duckdb/main/capi/header_generation/apis/v1/unstable/new_append_functions.json
  src/include/duckdb/main/capi/header_generation/apis/v1/unstable/new_error_data_functions.json
  src/include/duckdb/main/capi/header_generation/functions/appender.json
  src/include/duckdb/main/capi/header_generation/functions/error_data.json
  src/include/duckdb/main/capi/header_generation/header_base.hpp.template
  src/include/duckdb_extension.h
  src/main/capi/CMakeLists.txt
  src/main/capi/appender-c.cpp
  src/main/capi/error_data-c.cpp
  src/main/capi/helper-c.cpp
  src/main/capi/logical_types-c.cpp
  src/main/capi/prepared-c.cpp
  src/main/capi/result-c.cpp
  test/api/capi/test_capi_appender.cpp
Labels: Ready To Merge

#17753 [Dev] Fix `TRY` expression crash on literals
  src/planner/binder/expression/bind_operator_expression.cpp
  test/sql/error/test_try_expression.test
Labels: Ready For Review

#17777 [chore] Avoid caching msys artifacts on PRs
  .github/workflows/Windows.yml
Labels: Ready To Merge

#17786 Check page filtered out flag before reading it
  extension/parquet/column_reader.cpp
Labels: Ready To Merge

#17801 Pushdown pivot filter
  src/optimizer/pushdown/pushdown_aggregate.cpp
  test/sql/tpcds/tpcds_sf001.test_slow
Labels: Changes Requested

#17825 Replace string for const data ptr in encryption api
  .github/patches/extensions/httpfs/httpfs_loader.patch
  extension/parquet/parquet_crypto.cpp
  src/common/encryption_state.cpp
  src/include/duckdb/common/encryption_state.hpp
  third_party/mbedtls/include/mbedtls_wrapper.hpp
  third_party/mbedtls/mbedtls_wrapper.cpp
Labels: Ready For Review

#17831 Fixup confict
  .github/workflows/BundleStaticLibs.yml
  .github/workflows/LinuxRelease.yml
Labels: Ready To Merge

#17833 Merge130
  .github/actions/build_extensions_dockerized/action.yml
  .github/workflows/LinuxRelease.yml
  extension/parquet/column_reader.cpp
  src/common/arrow/arrow_appender.cpp
  src/common/arrow/arrow_converter.cpp
  src/common/multi_file/multi_file_column_mapper.cpp
  src/common/multi_file/multi_file_reader.cpp
  src/common/settings.json
  src/common/string_util.cpp
  src/execution/operator/aggregate/physical_streaming_window.cpp
  src/execution/operator/persistent/physical_copy_to_file.cpp
  src/include/duckdb/common/multi_file/multi_file_column_mapper.hpp
  src/include/duckdb/common/multi_file/multi_file_reader.hpp
  src/include/duckdb/function/cast/vector_cast_helpers.hpp
  src/include/duckdb/main/client_properties.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/client_context.cpp
  src/main/config.cpp
  src/main/query_result.cpp
  src/main/settings/autogenerated_settings.cpp
  src/main/settings/custom_settings.cpp
  src/planner/binder/statement/bind_copy.cpp
  test/api/test_reset.cpp
  test/sql/copy/parquet/writer/skip_empty_write.test
  test/sql/copy/row_groups_per_file.test
  tools/pythonpkg/setup.py
  tools/pythonpkg/tests/fast/arrow/test_arrow_decimal_32_64.py
  tools/pythonpkg/tests/fast/arrow/test_arrow_version_format.py
  tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp
Labels: Ready To Merge

#17832 [Fix] Throw serialisation error when encountering invalid row IDs in WAL delete
  src/storage/wal_replay.cpp
Labels: Ready To Merge

#17840 Fixup `unique_ptr<T[], deleter>`, now with working custom deleters
  src/common/local_file_system.cpp
  src/execution/operator/csv_scanner/encode/csv_encoder.cpp
  src/include/duckdb/common/helper.hpp
  src/include/duckdb/common/unique_ptr.hpp
  src/include/duckdb/execution/operator/csv_scanner/encode/csv_encoder.hpp
Labels: Ready For Review

#17821 Issue #17040: FILL Secondary Sorts
  src/function/window/window_boundaries_state.cpp
  src/function/window/window_executor.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/function/window/window_executor.hpp
  src/include/duckdb/function/window/window_value_function.hpp
  src/parser/transform/expression/transform_function.cpp
  test/sql/window/test_fill.test
  test/sql/window/test_fill_orderby.test
Labels: Ready For Review

#17889 Issue #17781: ASOF Predicate Binding
  src/execution/column_binding_resolver.cpp
  test/sql/join/asof/test_asof_join_pushdown.test
Labels: Ready For Review

#17866 `duckdb_base_std::` plus compile time test on discontinued functions
  CMakeLists.txt
  Makefile
  extension/icu/third_party/icu/common/uloc.cpp
  extension/parquet/include/parquet_reader.hpp
  extension/parquet/parquet_crypto.cpp
  extension/parquet/parquet_metadata.cpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/parquet_writer.cpp
  src/include/duckdb/common/helper.hpp
  src/include/duckdb/common/shadow_forbidden_functions.hpp
  src/include/duckdb/common/unique_ptr.hpp
  src/include/duckdb/original/std/locale.hpp
  src/include/duckdb/original/std/memory.hpp
  src/include/duckdb/original/std/sstream.hpp
  test/sqlite/sqllogic_command.cpp
  third_party/catch/catch.hpp
  third_party/fmt/include/fmt/format.h
  third_party/fsst/libfsst.cpp
  third_party/httplib/httplib.hpp
  third_party/hyperloglog/sds.cpp
  third_party/libpg_query/src_common_keywords.cpp
  third_party/re2/re2/filtered_re2.h
  third_party/re2/re2/pod_array.h
  third_party/re2/re2/re2.cc
  third_party/re2/re2/set.cc
  third_party/re2/re2/set.h
  tools/shell/include/shell_state.hpp
  tools/shell/linenoise/linenoise.cpp
Labels: Ready For Review

#17881 Leverage `VectorType` in `ColumnDataCollection`
  src/common/types/column/column_data_allocator.cpp
  src/common/types/column/column_data_collection.cpp
  src/common/types/column/column_data_collection_segment.cpp
  src/include/duckdb/common/types/column/column_data_allocator.hpp
  src/include/duckdb/common/types/column/column_data_collection_segment.hpp
  test/parquet/constant_dictionary_vector_parquet.test
  test/parquet/constant_dictionary_vector_parquet.test_slow
Labels: Ready For Review

#17914 http_log.test: solve non-determinism at the test level
  test/sql/copy/s3/http_log.test
Labels: Ready To Merge

#17916 Enable Test extension (inside docker) step in build_extensions_dockerized
  .github/actions/build_extensions/action.yml
  .github/actions/build_extensions_dockerized/action.yml
  .github/config/out_of_tree_extensions.cmake
  scripts/run_tests_one_by_one.py
Labels: Ready To Merge

#17937 Do not dispatch JDBC/ODBC jobs in release CI runs
  .github/workflows/InvokeCI.yml
  .github/workflows/NotifyExternalRepositories.yml
Labels: Ready To Merge

#17275 Block based encryption
  src/common/CMakeLists.txt
  src/common/encryption_functions.cpp
  src/common/encryption_key_manager.cpp
  src/include/duckdb/common/encryption_functions.hpp
  src/include/duckdb/common/encryption_key_manager.hpp
  src/include/duckdb/common/file_buffer.hpp
  src/include/duckdb/main/database.hpp
  src/include/duckdb/storage/single_file_block_manager.hpp
  src/include/duckdb/storage/storage_info.hpp
  src/include/duckdb/storage/storage_manager.hpp
  src/include/duckdb/storage/storage_options.hpp
  src/main/attached_database.cpp
  src/main/database.cpp
  src/parser/parsed_data/attach_info.cpp
  src/storage/single_file_block_manager.cpp
  src/storage/storage_info.cpp
  src/storage/storage_manager.cpp
  src/storage/version_map.json
  test/sql/attach/attach_encrypted_db_key_test.test
  test/sql/attach/attach_encryption_block_header.test
  test/sql/copy/encryption/different_aes_ciphers.test
  test/sql/copy/encryption/encrypted_to_unencrypted.test_slow
  test/sql/copy/encryption/encryption_storage_versions.test
  test/sql/copy/encryption/multiple_encrypted_databases.test_slow
  test/sql/copy/encryption/reencrypt.test_slow
  test/sql/copy/encryption/tpch_sf1_encrypted.test_slow
  test/sql/copy/encryption/unencrypted_to_encrypted.test
  test/sql/copy/encryption/unencrypted_to_encrypted_direct_query.test
  test/sql/copy/encryption/write_encrypted_database.test
  third_party/mbedtls/include/mbedtls_wrapper.hpp
  third_party/mbedtls/mbedtls_wrapper.cpp
Labels: Ready To Merge

#17913 Eviction queue: Sort purged nodes and bulk re-add
  src/storage/buffer/buffer_pool.cpp
Labels: Ready To Merge

#17960 Enable building spatial and encodings extensions
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#17968 [nested] Allow fixed-size arrays to be unnested
  src/planner/binder/expression/bind_unnest_expression.cpp
  test/sql/types/nested/array/array_unnest.test
Labels: Ready To Merge

#17949 [CI] Skip some workflows when updating out of tree extensions SHA
  .github/workflows/CodeQuality.yml
  .github/workflows/Julia.yml
  .github/workflows/LinuxRelease.yml
  .github/workflows/Main.yml
  .github/workflows/Python.yml
  .github/workflows/Regression.yml
  .github/workflows/Swift.yml
Labels: Ready To Merge

#17978 Issue #5144: AsOf Join Threshold
  src/execution/physical_plan/plan_asof_join.cpp
Labels: Ready For Review

#17938 Flag to disable database invalidation
  src/common/settings.json
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/include/duckdb/main/valid_checker.hpp
  src/main/client_context.cpp
  src/main/config.cpp
  src/main/database.cpp
  src/main/settings/autogenerated_settings.cpp
  src/main/settings/custom_settings.cpp
  src/main/valid_checker.cpp
  src/transaction/meta_transaction.cpp
  test/api/test_reset.cpp
  test/sql/pragma/pragma_database_size_readonly.test
  test/sql/pragma/test_db_invalidation_after_load.test
Labels: Ready To Merge

#17988 Fix for IsDenseRange check in filter_combiner
  src/optimizer/filter_combiner.cpp
Labels: Ready To Merge

#17860 Use correct expression function after filter pushdown
  .github/regression/micro.csv
  benchmark/micro/filter/choose_correct_filter_function.benchmark
  src/include/duckdb/planner/filter/expression_filter.hpp
  src/optimizer/statistics/operator/propagate_get.cpp
  src/planner/filter/expression_filter.cpp
Labels: Ready To Merge

#18032 Implement bulk enqueue for non-concurrent queue
  src/include/duckdb/parallel/concurrentqueue.hpp
Labels: Ready To Merge

#18019 Bring back libduckdb-src.zip as release artifact
  .github/workflows/LinuxRelease.yml
Labels: Changes Requested

#17837 Add ppc64le spin-wait instruction
  extension/jemalloc/jemalloc/include/jemalloc/internal/jemalloc_internal_defs.h
Labels: Ready To Merge

#18045 Issue #18035: Zero Fill TIMESTAMP_NS
  src/common/operator/string_cast.cpp
  test/sql/types/timestamp/test_timestamp_types.test
Labels: Ready For Review

#18064 Issue #18047: TIMESTAMP_TZ Upcast Costs
  extension/icu/icu-timezone.cpp
  test/sql/function/timestamp/test_icu_datediff.test
Labels: Ready For Review

#18067 Properly handle empty RHS in IE Join
  src/execution/operator/join/physical_iejoin.cpp
  test/sql/join/iejoin/test_iejoin.test
Labels: Ready To Merge

#18037 Use `timestamp_t` instead of `time_t` for file last modified time
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/azure/azure_loader_and_timestamp.patch
  .github/patches/extensions/httpfs/httpfs_loader_and_timestamp.patch
  .github/patches/extensions/spatial/fix_and_timestamp.patch
  extension/parquet/include/parquet_file_metadata_cache.hpp
  extension/parquet/parquet_file_metadata_cache.cpp
  src/common/file_system.cpp
  src/common/local_file_system.cpp
  src/common/virtual_file_system.cpp
  src/function/table/read_file.cpp
  src/include/duckdb/common/file_system.hpp
  src/include/duckdb/common/local_file_system.hpp
  src/include/duckdb/common/opener_file_system.hpp
  src/include/duckdb/common/virtual_file_system.hpp
  src/include/duckdb/storage/caching_file_system.hpp
  src/include/duckdb/storage/external_file_cache.hpp
  src/storage/caching_file_system.cpp
  src/storage/external_file_cache.cpp
  tools/pythonpkg/src/include/duckdb_python/pyfilesystem.hpp
  tools/pythonpkg/src/pyfilesystem.cpp
Labels: Ready To Merge

#17985 Fix some scaling issues
  src/common/enum_util.cpp
  src/common/settings.json
  src/common/types/row/tuple_data_collection.cpp
  src/common/types/row/tuple_data_iterator.cpp
  src/common/types/row/tuple_data_segment.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/enums/thread_pin_mode.hpp
  src/include/duckdb/common/types/row/tuple_data_collection.hpp
  src/include/duckdb/common/types/row/tuple_data_segment.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/include/duckdb/parallel/task_scheduler.hpp
  src/main/config.cpp
  src/main/settings/autogenerated_settings.cpp
  src/parallel/event.cpp
  src/parallel/task_scheduler.cpp
  src/storage/buffer/buffer_pool.cpp
  src/storage/table/column_data.cpp
  test/api/test_reset.cpp
Labels: Needs Documentation, Ready To Merge

#18081 Main.yml: Move very long job from debug to release with `-DDEBUG` and `FORCE_ASSERT`
  .github/workflows/Main.yml
Labels: Ready For Review

#18090 Avoid running DraftPR.yml until timeout if token is missing
  .github/workflows/DraftPR.yml
Labels: Ready To Merge
