Repository duckdb/duckdb, pull requests merged in 2025-01, with the labels that each got.

#15166 Functions can throw errors
  extension/core_functions/aggregate/holistic/mad.cpp
  extension/core_functions/scalar/array/array_functions.cpp
  extension/core_functions/scalar/bit/bitstring.cpp
  extension/core_functions/scalar/blob/base64.cpp
  extension/core_functions/scalar/blob/encode.cpp
  extension/core_functions/scalar/date/date_part.cpp
  extension/core_functions/scalar/date/date_trunc.cpp
  extension/core_functions/scalar/date/make_date.cpp
  extension/core_functions/scalar/date/time_bucket.cpp
  extension/core_functions/scalar/date/to_interval.cpp
  extension/core_functions/scalar/generic/binning.cpp
  extension/core_functions/scalar/list/array_slice.cpp
  extension/core_functions/scalar/list/list_aggregates.cpp
  extension/core_functions/scalar/list/list_distance.cpp
  extension/core_functions/scalar/list/range.cpp
  extension/core_functions/scalar/map/map.cpp
  extension/core_functions/scalar/map/map_from_entries.cpp
  extension/core_functions/scalar/map/map_keys_values.cpp
  extension/core_functions/scalar/math/numeric.cpp
  extension/core_functions/scalar/operators/bitwise.cpp
  extension/core_functions/scalar/random/setseed.cpp
  extension/core_functions/scalar/string/hex.cpp
  extension/core_functions/scalar/string/pad.cpp
  extension/core_functions/scalar/string/printf.cpp
  extension/core_functions/scalar/string/repeat.cpp
  extension/icu/icu-datepart.cpp
  extension/icu/icu-makedate.cpp
  extension/icu/icu-timebucket.cpp
  extension/icu/icu-timezone.cpp
  src/common/enum_util.cpp
  src/execution/expression_executor/execute_function.cpp
  src/function/function.cpp
  src/function/scalar/date/strftime.cpp
  src/function/scalar/generic/error.cpp
  src/function/scalar/list/list_extract.cpp
  src/function/scalar/list/list_resize.cpp
  src/function/scalar/operator/arithmetic.cpp
  src/function/scalar/sequence/nextval.cpp
  src/function/scalar/string/length.cpp
  src/function/scalar/string/regexp.cpp
  src/include/duckdb/common/enums/function_errors.hpp
  src/include/duckdb/common/vector_operations/unary_executor.hpp
  src/include/duckdb/function/function.hpp
  src/include/duckdb/planner/expression/bound_function_expression.hpp
  src/planner/expression/bound_function_expression.cpp
  test/optimizer/expression_rewriter/functions_that_error_are_not_reordered.test
Labels: Ready For Review

#15429 Introduce 2 new platforms: `musllinux_arm64` and `musllinux_amd64`
  src/include/duckdb/common/platform.hpp
Labels: Ready For Review

#15497 Feature #12699: LEAD/LAG Secondary Sorts
  src/execution/operator/aggregate/physical_streaming_window.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/function/window/window_value_function.hpp
  src/parser/transform/expression/transform_function.cpp
  test/sql/window/test_leadlag_orderby.test
  third_party/libpg_query/grammar/statements/select.y
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Ready For Review

#15524 Fix window/test_window_wide_frame.test_slow after random() changes
  test/sql/window/test_window_wide_frame.test_slow
Labels: Ready To Merge

#15470 remove duplicate FastMem copies in binary
  src/include/duckdb/common/fast_mem.hpp
Labels: Ready To Merge

#15530 Don't create config folder on extension listing
  src/function/table/system/duckdb_extensions.cpp
  src/include/duckdb/main/extension_helper.hpp
  src/main/extension/extension_install.cpp
Labels: Changes Requested

#15561 Fix some external join benchmark specifications
  benchmark/micro/join/external_join_partition_order.benchmark
  benchmark/micro/join/external_join_partition_selection.benchmark
Labels: Ready To Merge

#15549 Make `max_temp_directory_size` round-trip
  src/main/config.cpp
  src/main/settings/custom_settings.cpp
Labels: Ready For Review

#15548 Allow databases with table_macros to be copyable via COPY FROM DATABASE
  src/execution/operator/persistent/physical_copy_database.cpp
  test/sql/catalog/function/test_table_macro_copy.test
Labels: Ready For Review

#14674 Allow a variable type `rowid` pseudocolumn in tables
  src/execution/physical_plan/plan_get.cpp
  src/function/table/arrow_conversion.cpp
  src/include/duckdb/catalog/catalog_entry/table_catalog_entry.hpp
  src/include/duckdb/function/table/arrow.hpp
  src/include/duckdb/planner/operator/logical_get.hpp
  src/include/duckdb/planner/table_binding.hpp
  src/planner/binder/statement/bind_delete.cpp
  src/planner/binder/statement/bind_update.cpp
  src/planner/binder/tableref/bind_basetableref.cpp
  src/planner/operator/logical_get.cpp
  src/planner/table_binding.cpp
Labels: needs maintainer approval

#15541 Internal #3860: Deserialise Secondary Orderings
  src/planner/expression/bound_window_expression.cpp
Labels: Ready For Review

#15529 Use ISNULL in conjunction or filters
  src/optimizer/filter_combiner.cpp
  test/optimizer/pushdown/table_or_pushdown.test
Labels: Ready For Review

#15558 Avoid fast fail: change defaults to run all tests in more cases
  scripts/run_tests_one_by_one.py
  scripts/sqllogictest/result.py
  tools/pythonpkg/scripts/sqllogictest_python.py
Labels: Ready For Review

#15477 Implicit STRUCT to STRUCT cast for mismatching member names
  src/common/types.cpp
  src/common/types/vector.cpp
  src/function/cast/struct_cast.cpp
  src/include/duckdb/function/cast/bound_cast_data.hpp
  test/common/test_cast_struct.test
  test/sql/cast/cast_error_location.test
  test/sql/setops/test_union_by_name.test
  test/sql/types/struct/struct_cast.test
  test/sql/types/struct/struct_different_names.test
  test/sql/types/struct/struct_named_cast.test
Labels: Needs Documentation

#15577 CI: Bump container for Android build
  .github/workflows/Android.yml
Labels: Ready To Merge

#15566 [Dev] `ColumnDataCheckpointer` can now checkpoint column data and validity data together
  src/common/types/vector.cpp
  src/include/duckdb/common/types/vector.hpp
  src/include/duckdb/function/compression_function.hpp
  src/include/duckdb/storage/compression/alp/alp_compress.hpp
  src/include/duckdb/storage/compression/alprd/alprd_compress.hpp
  src/include/duckdb/storage/compression/chimp/chimp_compress.hpp
  src/include/duckdb/storage/compression/dictionary/compression.hpp
  src/include/duckdb/storage/compression/patas/patas_compress.hpp
  src/include/duckdb/storage/compression/roaring/roaring.hpp
  src/include/duckdb/storage/segment/uncompressed.hpp
  src/include/duckdb/storage/table/column_data_checkpointer.hpp
  src/storage/compression/bitpacking.cpp
  src/storage/compression/dictionary/compression.cpp
  src/storage/compression/dictionary_compression.cpp
  src/storage/compression/fixed_size_uncompressed.cpp
  src/storage/compression/fsst.cpp
  src/storage/compression/rle.cpp
  src/storage/compression/roaring/common.cpp
  src/storage/compression/roaring/compress.cpp
  src/storage/compression/zstd.cpp
  src/storage/table/column_data.cpp
  src/storage/table/column_data_checkpointer.cpp
  src/storage/table/standard_column_data.cpp
Labels: Ready For Review

#15523 Feature #12699: Secondary Sort Framing
  data/csv/tpcc_results.csv
  src/function/window/window_boundaries_state.cpp
  src/function/window/window_rank_function.cpp
  src/function/window/window_rownumber_function.cpp
  src/function/window/window_value_function.cpp
  test/sql/window/test_cume_dist_orderby.test
  test/sql/window/test_leadlag_orderby.test
  test/sql/window/test_rank_orderby.test
  test/sql/window/test_rownumber_orderby.test
  test/sql/window/test_tpcc_results.test
Labels: Ready For Review

#15565 DuckFuzz Fix on Null parameters for both read_csv and sniff_csv
  src/execution/operator/csv_scanner/util/csv_reader_options.cpp
  src/function/table/sniff_csv.cpp
  test/sql/copy/csv/csv_duck_fuzz.test
Labels: CI Failure

#15605 More bugfixes
  extension/parquet/column_reader.cpp
  extension/parquet/include/column_reader.hpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_reader.cpp
  src/execution/aggregate_hashtable.cpp
  src/function/scalar/sequence/nextval.cpp
  src/function/scalar/string/length.cpp
  src/planner/binder/expression/bind_operator_expression.cpp
  src/planner/binder/statement/bind_create.cpp
  src/storage/arena_allocator.cpp
  test/issues/general/test_15432.test
  test/parquet/test_parquet_schema.test
  test/sql/catalog/function/test_complex_macro.test
Labels: Ready For Review

#15591 [Compression] `Dictionary` compression data now also includes the validity data
  src/common/enum_util.cpp
  src/common/enums/compression_type.cpp
  src/function/compression_config.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/enums/compression_type.hpp
  src/include/duckdb/function/compression/compression.hpp
  src/include/duckdb/function/compression_function.hpp
  src/include/duckdb/storage/compression/empty_validity.hpp
  src/include/duckdb/storage/table/column_data.hpp
  src/include/duckdb/storage/table/column_data_checkpointer.hpp
  src/main/database.cpp
  src/storage/compression/CMakeLists.txt
  src/storage/compression/dictionary/decompression.cpp
  src/storage/compression/dictionary_compression.cpp
  src/storage/compression/empty_validity.cpp
  src/storage/table/column_data.cpp
  src/storage/table/column_data_checkpointer.cpp
  test/sql/storage/compression/dictionary/dictionary_covers_validity.test
Labels: Ready To Merge

#15592 Issue #14996: Aggregate Secondary Orderings
  benchmark/micro/window/mode_fixed_orderby.benchmark
  benchmark/micro/window/mode_variable_400.benchmark
  benchmark/micro/window/mode_variable_orderby.benchmark
  src/function/window/window_aggregate_function.cpp
  src/function/window/window_aggregator.cpp
  src/function/window/window_constant_aggregator.cpp
  src/function/window/window_custom_aggregator.cpp
  src/function/window/window_distinct_aggregator.cpp
  src/function/window/window_executor.cpp
  src/function/window/window_naive_aggregator.cpp
  src/function/window/window_segment_tree.cpp
  src/include/duckdb/function/window/window_aggregate_function.hpp
  src/include/duckdb/function/window/window_aggregator.hpp
  src/include/duckdb/function/window/window_constant_aggregator.hpp
  src/include/duckdb/function/window/window_custom_aggregator.hpp
  src/include/duckdb/function/window/window_distinct_aggregator.hpp
  src/include/duckdb/function/window/window_naive_aggregator.hpp
  src/include/duckdb/function/window/window_segment_tree.hpp
  src/include/duckdb/planner/expression/bound_window_expression.hpp
  src/parser/transform/expression/transform_function.cpp
  src/planner/expression/bound_window_expression.cpp
  test/sql/window/test_invalid_window.test
  test/sql/window/test_naive_aggregation.test
Labels: Ready For Review

#15611 Backport ENTRY_VISIBILITY from duckdb/extension-template-c
  scripts/generate_c_api.py
  src/include/duckdb_extension.h
Labels: Ready To Merge

#15614 Adjust list_reduce to use a 1-based indexing
  extension/core_functions/scalar/list/list_reduce.cpp
  test/sql/function/list/lambdas/reduce.test
Labels: Needs Documentation

#15615 Improve reading duplicate column names in JSON
  data/json/15601/bunch_of_key_collisions.json
  data/json/15601/fragment1.json
  data/json/15601/fragment2.json
  extension/json/json_functions/read_json.cpp
  test/sql/json/issues/issue15601.test
Labels: Ready For Review

#15619 Implement `simple_update` for `first` aggregate function
  src/function/aggregate/distributive/first_last_any.cpp
Labels: Ready For Review

#15620 Issue #15596: Infinite Value Checks
  extension/core_functions/scalar/date/make_date.cpp
  extension/icu/icu-dateadd.cpp
  extension/icu/icu-datefunc.cpp
  extension/icu/icu-makedate.cpp
  extension/icu/include/icu-datefunc.hpp
  src/common/types/timestamp.cpp
  test/sql/function/timestamp/make_date.test
  test/sql/function/timestamp/test_icu_dateadd.test
  test/sql/function/timestamp/test_icu_makedate.test
  test/sql/function/timestamp/test_icu_strptime.test
  test/sql/types/timestamp/timestamp_precision.test
Labels: Ready For Review

#15630 Fix an if statement that is always True
  scripts/python_helpers.py
Labels: Ready To Merge

#15593 Parallel `union_by_name` for `read_json`
  extension/json/include/json_scan.hpp
  extension/json/include/json_structure.hpp
  extension/json/json_functions/json_structure.cpp
  extension/json/json_functions/read_json.cpp
  extension/json/json_scan.cpp
Labels: Ready To Merge

#15540 Not using Random Device in DuckDB Core
  scripts/exported_symbols_check.py
  src/common/random_engine.cpp
  src/common/string_util.cpp
  third_party/httplib/httplib.hpp
  third_party/skiplist/SkipList.h
Labels: Ready To Merge

#15649 Initialize random_seed to silence warning on uninitialized variable
  src/common/random_engine.cpp
Labels: Ready To Merge

#15616 Added `weighted_avg` function using macro
  src/catalog/default/default_functions.cpp
  test/sql/aggregate/aggregates/test_weighted_avg.test
Labels: Needs Documentation, Ready To Merge

#15651 Skip tests, cleaning up known failures in CI
  test/sql/catalog/dependencies/test_concurrent_index_creation.test
  test/sql/copy/csv/14874.test
  test/sql/copy/csv/test_big_line.test_slow
  test/sql/types/nested/array/array_large.test
  tools/pythonpkg/scripts/sqllogictest_python.py
Labels: Ready For Review

#15638 Extension type modifier followup
  src/catalog/catalog_entry/type_catalog_entry.cpp
  src/common/extra_type_info.cpp
  src/common/types.cpp
  src/include/duckdb/catalog/catalog_entry/type_catalog_entry.hpp
  src/include/duckdb/common/extension_type_info.hpp
  src/include/duckdb/main/extension_util.hpp
  src/include/duckdb/parser/parsed_data/create_type_info.hpp
  src/include/duckdb/storage/serialization/types.json
  src/main/extension/extension_util.cpp
  src/parser/parsed_data/create_type_info.cpp
  src/planner/binder/statement/bind_create.cpp
  src/storage/serialization/serialize_types.cpp
  test/extension/loadable_extension_demo.cpp
  test/extension/test_custom_type_modifier.test_slow
  test/extension/test_custom_type_modifier_cast.test
Labels: Ready For Review

#15410 Index scan on (dynamic) table filters
  benchmark/micro/index/point/in_filter_with_index_scan.benchmark
  src/execution/index/art/art.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/operator/scan/physical_table_scan.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/function/table/table_scan.hpp
  src/include/duckdb/function/table_function.hpp
  src/include/duckdb/main/profiling_info.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/include/duckdb/planner/filter/in_filter.hpp
  src/main/query_profiler.cpp
  src/planner/filter/in_filter.cpp
  test/extension/test_custom_type_modifier.test_slow
  test/optimizer/index_optimizer.test
  test/sql/copy_database/copy_database_index.test
  test/sql/index/art/scan/test_art_adaptive_scan.test
  test/sql/index/art/scan/test_art_prepared_scan.test
  test/sql/index/art/scan/test_art_scan_thresholds.test
  test/sql/index/art/scan/test_in_filter_index_scan.test_slow
  test/sql/storage/wal/wal_create_index.test
  test/sql/transactions/test_index_local_update.test
  test/sql/update/string_update_transaction_local_7348.test
Labels: Needs Documentation

#15634 Feature #12699: Windowed Aggregate Ordering
  benchmark/micro/window/window_mode_constant.benchmark
  src/function/aggregate/sorted_aggregate_function.cpp
  src/function/window/window_aggregate_function.cpp
  src/function/window/window_constant_aggregator.cpp
  src/function/window/window_executor.cpp
  src/function/window/window_rank_function.cpp
  src/function/window/window_rownumber_function.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/function/function_binder.hpp
  src/include/duckdb/function/window/window_constant_aggregator.hpp
  src/include/duckdb/function/window/window_executor.hpp
  src/include/duckdb/function/window/window_rank_function.hpp
  src/include/duckdb/function/window/window_rownumber_function.hpp
  src/include/duckdb/function/window/window_value_function.hpp
  src/include/duckdb/planner/bound_result_modifier.hpp
  src/planner/bound_result_modifier.cpp
  test/sql/window/test_constant_orderby.test
  test/sql/window/test_window_constant_aggregate.test
Labels: Ready To Merge

#15653 Implement `DELTA_LENGTH_BYTE_ARRAY` and `BYTE_STREAM_SPLIT` encodings for Parquet writer
  extension/parquet/column_writer.cpp
  extension/parquet/include/parquet_bss_encoder.hpp
  extension/parquet/include/parquet_dlba_encoder.hpp
  test/parquet/bss_roundtrip.test_slow
  test/sql/copy/file_size_bytes.test
  test/sql/copy/parquet/parquet_5209.test
Labels: Ready For Review

#15624 Allow switching to a different catalog from a detached catalog
  src/catalog/catalog.cpp
  src/catalog/catalog_search_path.cpp
  src/main/database_manager.cpp
  test/sql/catalog/test_switching_from_detached_catalog.test
Labels: Changes Requested

#15668 TableCatalogEntry instead of DuckTableEntry in TableScanBindData
  src/catalog/catalog.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/catalog/catalog.hpp
  src/include/duckdb/function/table/table_scan.hpp
Labels: Ready For Review

#15681 Throw on unknown logging_storage set
  .github/regression/micro.csv
  src/logging/log_manager.cpp
  test/sql/logging/logging.test
Labels: Ready For Review

#15680 Remove mention to not existing logging_disabled_thread_local.benchmark
  .github/regression/micro.csv
Labels: Ready For Review

#15672 Fix sign-compare compilation warning
  src/common/types/varint.cpp
Labels: Ready To Merge

#15521 Varint to varchar optimization
  src/common/types/varint.cpp
  src/include/duckdb/common/types/varint.hpp
Labels: Ready To Merge

#15689 Reduce test size so CI is less likely to fail
  test/sql/aggregate/aggregates/first_memory_usage.test_slow
Labels: Ready For Review

#15688 Clean up temporary test directory in `run_tests_one_by_one.py` even if test segfaults
  scripts/run_tests_one_by_one.py
Labels: Ready For Review

#15697 Add late_materialization_max_rows setting that allows you to configure the threshold at which late materialization is triggered
  src/common/settings.json
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/main/settings.hpp
  src/include/duckdb/optimizer/late_materialization.hpp
  src/main/config.cpp
  src/main/settings/autogenerated_settings.cpp
  src/optimizer/late_materialization.cpp
  test/sql/topn/top_n_materialization.test
Labels: Needs Documentation

#15707 DatabaseInstance's destructor: avoid throwing (and not cleaning up)
  src/main/database.cpp
Labels: Ready To Merge

#15716 Remove iceberg, again
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#15709 Preserve stack trace information when re-throwing
  src/common/exception.cpp
Labels: Changes Requested

#15446 [MultiFileReader] Extend support for column mapping from local -> global column
  .github/patches/extensions/delta/multi_file_reader_column_definition.patch
  extension/json/json_scan.cpp
  extension/parquet/include/parquet.json
  extension/parquet/include/parquet_reader.hpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_metadata.cpp
  extension/parquet/parquet_reader.cpp
  extension/parquet/serialize_parquet.cpp
  src/common/enum_util.cpp
  src/common/multi_file_reader.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/execution/operator/csv_scanner/util/csv_error.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/multi_file_reader.hpp
  src/include/duckdb/common/multi_file_reader_options.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_error.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_scanner.hpp
  test/parquet/test_parquet_schema.test
Labels: Ready For Review

#15684 Implement `parquet_version` parameter for Parquet writer
  extension/parquet/column_writer.cpp
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_writer.cpp
  test/parquet/parquet_version.test
  test/sql/copy/parquet/parquet_5209.test
Labels: Ready For Review

#15702 Storage version 65
  data/storage/empty64.db
  data/storage/empty65.db
  data/storage/empty66.db
  data/storage/storage_versions65.db.gz
  src/include/duckdb/storage/storage_info.hpp
  src/storage/single_file_block_manager.cpp
  src/storage/storage_info.cpp
  src/storage/version_map.json
  test/sql/storage/storage_version_65.test
  test/sql/storage/storage_versions.test
Labels: Needs Documentation, Ready For Review

#15665 Enable index scan for dynamic IN filter
  src/execution/operator/join/physical_hash_join.cpp
  src/function/table/table_scan.cpp
  src/include/duckdb/planner/filter/constant_filter.hpp
  src/include/duckdb/planner/filter/in_filter.hpp
  src/include/duckdb/planner/filter/optional_filter.hpp
  src/planner/filter/conjunction_filter.cpp
  src/planner/filter/constant_filter.cpp
  src/planner/filter/in_filter.cpp
  test/sql/index/art/scan/test_hash_join_in_filter_index_scan.test
  test/sql/index/art/scan/test_in_filter_index_scan.test
Labels: Changes Requested

#15738 Initialize create_index_info.catalog
  src/planner/expression_binder/index_binder.cpp
Labels: Ready To Merge

#15739 Feature #15717: Window GROUPS
  src/common/enum_util.cpp
  src/function/window/window_aggregate_function.cpp
  src/function/window/window_boundaries_state.cpp
  src/function/window/window_segment_tree.cpp
  src/include/duckdb/function/window/window_boundaries_state.hpp
  src/include/duckdb/parser/expression/window_expression.hpp
  src/parser/transform/expression/transform_function.cpp
  test/sql/parallelism/intraquery/depth_first_evaluation.test_slow
  test/sql/window/test_invalid_window.test
  test/sql/window/test_window_groups.test
Labels: Ready For Review

#15746 Fetch only required columns in physical delete
  src/execution/operator/persistent/physical_delete.cpp
  src/execution/operator/persistent/physical_insert.cpp
  src/include/duckdb/execution/operator/persistent/physical_insert.hpp
  src/storage/table/row_group_collection.cpp
  test/sql/delete/test_delete_indexed.test
Labels: Ready For Review

#15655 First round of extension bumps
  .github/config/extensions.csv
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/aws/require_autoloading.patch
  .github/patches/extensions/iceberg/exclude.patch
  .github/patches/extensions/mysql_scanner/table_fun_to_string.patch
  .github/patches/extensions/postgres_scanner/partitiondata.patch
  .github/patches/extensions/postgres_scanner/table_fun_to_string.patch
  .github/patches/extensions/spatial/arrow_extension.patch
  .github/patches/extensions/spatial/cmake.patch
  .github/patches/extensions/spatial/fix_constraint_checking.patch
  .github/patches/extensions/sqlite_scanner/show.patch
  .github/patches/extensions/sqlite_scanner/table_fun_to_string.patch
  .github/patches/extensions/vss/remove_constraints.patch
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#15754 Add `disabled_compression_methods` setting that can be used to disable certain compression methods
  src/common/settings.json
  src/function/compression_config.cpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/settings/custom_settings.cpp
  test/api/test_reset.cpp
  test/sql/pragma/test_disabled_compression.test
  test/sql/storage/compression/fsst/fsst_disable_compression.test
Labels: Needs Documentation

#15748 Fix CI for Linux Release Building
  .github/workflows/LinuxRelease.yml
  .github/workflows/NightlyTests.yml
  scripts/setup_ubuntu1804.sh
Labels: Ready To Merge

#15765 Fix minor DuckDB-Wasm problem with stacktraces, that would be shown twice
  src/common/error_data.cpp
Labels: Ready To Merge

#15774 Bundle MingW static library with the default extension configuration
  .github/workflows/BundleStaticLibs.yml
  Makefile
Labels: Ready To Merge

#15780 Add back Iceberg extension
  .github/config/out_of_tree_extensions.cmake
Labels: Ready For Review

#15785 Internal #4002: SQLite EXCLUDE Tests
  test/sql/window/test_window_range.test
  test/sql/window/test_window_rows.test
Labels: Ready For Review

#15790 Skip 3 tests, to be reviewed on a side
  test/sql/copy/csv/test_skip.test_slow
  test/sql/parallelism/intraquery/depth_first_evaluation.test_slow
  test/sql/storage/concurrent_table_insertion.test_slow
Labels: Ready To Merge

#15794 Add `STORAGE_VERSION` option that allows you to specify the target storage version when serializing a database
  data/storage/empty65.db
  data/storage/storage_versions65.db.gz
  scripts/regression_test_storage_size.py
  src/include/duckdb/common/serializer/serializer.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/storage/single_file_block_manager.hpp
  src/include/duckdb/storage/storage_info.hpp
  src/include/duckdb/storage/storage_manager.hpp
  src/include/duckdb/storage/storage_options.hpp
  src/include/duckdb/storage/table/column_data.hpp
  src/include/duckdb/storage/write_ahead_log.hpp
  src/main/attached_database.cpp
  src/main/config.cpp
  src/parser/parsed_data/attach_info.cpp
  src/planner/logical_operator.cpp
  src/storage/checkpoint/table_data_writer.cpp
  src/storage/checkpoint_manager.cpp
  src/storage/compression/roaring/common.cpp
  src/storage/compression/zstd.cpp
  src/storage/single_file_block_manager.cpp
  src/storage/storage_info.cpp
  src/storage/storage_manager.cpp
  src/storage/table/column_data.cpp
  src/storage/write_ahead_log.cpp
  test/sql/attach/attach_new_compression.test
  test/sql/attach/attach_row_group_size.test
  test/sql/attach/attach_storage_version.test
  test/sql/catalog/function/test_macro_default_arg_with_dependencies.test
  test/sql/catalog/view/test_view_schema_change_with_dependencies.test
  test/sql/catalog/view/test_view_sql_with_dependencies.test
  test/sql/export/export_generated_columns.test
  test/sql/storage/compression/roaring/fetch_row.test
  test/sql/storage/compression/roaring/roaring_analyze_array.test
  test/sql/storage/compression/roaring/roaring_analyze_bitset.test
  test/sql/storage/compression/roaring/roaring_analyze_run.test
  test/sql/storage/compression/roaring/roaring_appends.test_slow
  test/sql/storage/compression/roaring/roaring_array_simple.test
  test/sql/storage/compression/roaring/roaring_bitset_simple.test
  test/sql/storage/compression/roaring/roaring_compression_ratio.test_slow
  test/sql/storage/compression/roaring/roaring_inverted_array_simple.test
  test/sql/storage/compression/roaring/roaring_inverted_run_simple.test
  test/sql/storage/compression/roaring/roaring_run_simple.test
  test/sql/storage/compression/roaring/roaring_smaller_than_vector.test
  test/sql/storage/compression/zstd/fetch_row.test
  test/sql/storage/compression/zstd/nulls.test
  test/sql/storage/compression/zstd/page_flushing_test1.test_slow
  test/sql/storage/compression/zstd/reclaim_space_column.test_slow
  test/sql/storage/compression/zstd/reclaim_space_table.test_slow
  test/sql/storage/compression/zstd/test_giant_lists.test_slow
  test/sql/storage/compression/zstd/test_skipping.test
  test/sql/storage/compression/zstd/zstd.test
  test/sql/storage/compression/zstd/zstd_compression_ratio.test_slow
  test/sql/storage/storage_version_65.test
  test/sql/storage/storage_versions.test
  test/sqlite/sqllogic_command.cpp
Labels: Needs Documentation

#15807 Fix tests for storage 65
  test/sql/storage/optimistic_write/optimistic_write_custom_row_group_size.test_slow
  test/sql/storage/parallel/custom_row_group_size.test_slow
  test/sql/storage/storage_version_65.test
Labels: Ready To Merge

#15806 Enable tests using no_alternative_verify
  test/optimizer/topn/topn_optimizer.test
  test/sql/cte/materialized/test_cte_in_cte_materialized.test
  test/sql/cte/test_cte.test
  test/sql/cte/test_issue_5673.test
Labels: Ready To Merge

#15703 Remove shuffle from sampling
  src/execution/sample/reservoir_sample.cpp
  test/sql/sample/table_samples/basic_sample_tests.test
  test/sql/sample/table_samples/table_sample_is_stored.test_slow
Labels: Ready To Merge

#15804 bump inet
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/inet/require_autoloading.patch
Labels: Ready To Merge

#15802 Fix `map_inference_threshold` issue in JSON reader
  data/json/internal_4014.json
  extension/json/json_functions/json_structure.cpp
  test/sql/json/issues/internal_issue4014.test
Labels: Ready To Merge

#15820 [CI] Invert operations for Linux CLI: first deploy, then test
  .github/workflows/LinuxRelease.yml
Labels: Ready To Merge

#15823 Fixup shell & autocomplete versioning information
  extension/autocomplete/autocomplete_extension.cpp
  src/function/table/system/duckdb_extensions.cpp
  src/include/duckdb/main/extension.hpp
  src/main/extension.cpp
  tools/sqlite3_api_wrapper/include/shell_extension.hpp
  tools/sqlite3_api_wrapper/shell_extension.cpp
Labels: Ready To Merge

#15834 Issue #15758: Streaming LEAD Buffering
  src/execution/operator/aggregate/physical_streaming_window.cpp
  test/sql/window/test_streaming_lead_lag.test
Labels: Ready For Review

#15810 Removing all core code and CI related to the substrait extension
  .github/patches/extensions/substrait/or_filter_pushdown.patch
  .github/workflows/ExtensionTrigger.yml
  Makefile
  scripts/generate_extensions_function.py
  src/common/adbc/adbc.cpp
  src/include/duckdb/main/connection.hpp
  src/include/duckdb/main/extension_entries.hpp
  src/main/connection.cpp
  src/main/extension/extension_helper.cpp
  test/api/adbc/test_adbc.cpp
  test/sql/catalog/test_extension_suggestion.test
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb/__init__.py
  tools/pythonpkg/duckdb_python.cpp
  tools/pythonpkg/scripts/connection_methods.json
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/api/test_duckdb_connection.py
Labels: Ready To Merge

#15832 Relax RFC_4180=False a bit more flexible
  data/csv/extra_delimiters.csv
  data/csv/pollock/file_field_delimiter_0x20.csv
  data/csv/pollock/file_quotation_char_0x27.csv
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/include/duckdb/execution/operator/csv_scanner/string_value_scanner.hpp
  test/sql/copy/csv/14512.test
  test/sql/copy/csv/auto/test_csv_auto.test
  test/sql/copy/csv/pollock/test_field_delimiter.test
  test/sql/copy/csv/pollock/test_quotation_char.test
  test/sql/copy/csv/rejects/csv_incorrect_columns_amount_rejects.test
  test/sql/copy/csv/rejects/csv_rejects_read.test
  test/sql/copy/csv/rejects/test_multiple_errors_same_line.test
  test/sql/copy/csv/relaxed_quotes.test
  test/sql/copy/csv/test_comment_midline.test
  test/sql/copy/csv/test_extra_delimiters_rfc.test
  test/sql/copy/csv/test_ignore_errors.test
  test/sql/copy/csv/test_ignore_mid_null_line.test
  test/sql/copy/csv/test_null_padding_projection.test
Labels: Ready For Review

#15856 [tpch] dbgen: Avoid throwing interrupt that can't be caught
  extension/tpch/dbgen/dbgen.cpp
Labels: Ready For Review

#15854 Add CI run testing also slow tests on PRs
  .github/workflows/Main.yml
  test/sql/aggregate/external/simple_external_aggregate.test_slow
Labels: Ready To Merge

#15878 Issue #15877: CUME_DIST Moving Frame
  src/function/window/window_token_tree.cpp
  test/sql/window/test_cume_dist_orderby.test
Labels: Ready For Review, incorrect results

#15879 [Linux CI] Remove examples, already tested as part of OSX Release
  .github/workflows/LinuxRelease.yml
Labels: Ready To Merge

#15899 Call ProcessError also for PendingQueries
  src/common/error_data.cpp
  src/main/client_context.cpp
  test/api/test_pending_query.cpp
  test/sql/settings/errors_as_json.test
Labels: Ready To Merge

#15900 CI: Handle 'fixed on nightly' label
  .github/workflows/InternalIssuesCreateMirror.yml
Labels: Ready For Review

#15902 CheckMagicBytes: zero initialise buffer
  src/storage/magic_bytes.cpp
Labels: Ready To Merge

#15904 In destructor try/catch exceptions thrown when closing MiniZ streams
  src/common/compressed_file_system.cpp
Labels: Ready To Merge

#15908 Issue #15907: Window Function EXCLUDE
  src/parser/transform/expression/transform_function.cpp
  test/sql/window/test_invalid_window.test
Labels: Ready For Review

#15764 Fix issue with CSV reader pruning
  data/csv/filename_filter/a.csv
  data/csv/filename_filter/b.csv
  data/csv/filename_filter/c.csv
  data/csv/filename_filter/d.csv
  src/common/multi_file_reader.cpp
  src/function/table/read_csv.cpp
  test/sql/copy/csv/test_filename_filter.test
Labels: Ready For Review

#15905 Remove bundled TPCH
  .github/config/bundled_extensions.cmake
Labels: Ready For Review

#15918 [shell] UBIGINT is also an integer type
  tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp
Labels: Ready For Review

#15940 [Fix] WAL replay in the presence of eager index duplicates
  src/common/enum_util.cpp
  src/execution/index/art/art.cpp
  src/execution/index/art/leaf.cpp
  src/execution/index/art/node.cpp
  src/execution/index/art/prefix.cpp
  src/execution/index/bound_index.cpp
  src/execution/operator/persistent/physical_delete.cpp
  src/execution/operator/schema/physical_create_art_index.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/art/prefix.hpp
  src/include/duckdb/execution/index/bound_index.hpp
  src/include/duckdb/storage/data_table.hpp
  src/include/duckdb/transaction/local_storage.hpp
  src/storage/data_table.cpp
  src/storage/local_storage.cpp
  src/storage/table_index_list.cpp
  src/storage/wal_replay.cpp
  test/sql/index/art/constraints/test_art_eager_with_wal.test
Labels: Ready To Merge

#15964 [Fix] Add unbound physical index to the table storage during COPY DATABASE
  src/execution/operator/persistent/physical_copy_database.cpp
  src/include/duckdb/storage/index_storage_info.hpp
  src/planner/binder/statement/bind_copy_database.cpp
  src/storage/table_index_list.cpp
  test/sql/copy_database/copy_database_index.test
  test/sql/copy_database/copy_database_with_index.test
  test/sql/copy_database/copy_database_with_unique_index.test
Labels: Needs Documentation, Ready To Merge

#15979 [Dev] Fix pyodide test failures
  .github/workflows/Pyodide.yml
Labels: Ready To Merge

#15997 [chore] Add Wasm extensions to InvokeCI
  .github/workflows/InvokeCI.yml
Labels: Ready To Merge

#15995 Add run_all option to Python.yml (and InvokeCI.yml)
  .github/workflows/InvokeCI.yml
  .github/workflows/Python.yml
Labels: Ready For Review

#16001 Fix pyodide, add version 0.27.2
  .github/workflows/Pyodide.yml
  tools/pythonpkg/tests/fast/spark/test_spark_functions_array.py
Labels: Ready To Merge

#16000 std::thread::hardware_concurrency() might fail, use 1 in that case
  benchmark/include/benchmark_runner.hpp
  extension/jemalloc/jemalloc_extension.cpp
  src/main/config.cpp
  test/sqlite/result_helper.cpp
Labels: Ready For Review
