Repository duckdb/duckdb, pull requests merged in 2025-03, with the labels that each got.

#16464 Mirror discussions to the internal repository
  .github/workflows/InternalIssuesCreateMirror.yml
  .github/workflows/InternalIssuesUpdateMirror.yml
Labels: Ready For Review

#16480 Fixed reading piped JSON
  extension/json/buffered_json_reader.cpp
Labels: Ready For Review

#16492 Bump `postgres_scanner` and `fts` extensions
  .github/config/out_of_tree_extensions.cmake
Labels: Ready For Review

#16430 Prevent external joins (if possible)
  extension/core_functions/scalar/list/list_sort.cpp
  src/common/sort/merge_sorter.cpp
  src/common/sort/partition_state.cpp
  src/common/sort/sort_state.cpp
  src/common/types/row/partitioned_tuple_data.cpp
  src/execution/aggregate_hashtable.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/operator/join/physical_piecewise_merge_join.cpp
  src/execution/operator/join/physical_range_join.cpp
  src/execution/operator/order/physical_order.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/function/aggregate/sorted_aggregate_function.cpp
  src/function/window/window_distinct_aggregator.cpp
  src/function/window/window_merge_sort_tree.cpp
  src/function/window/window_naive_aggregator.cpp
  src/include/duckdb/common/sort/partition_state.hpp
  src/include/duckdb/common/sort/sort.hpp
  src/include/duckdb/common/types/row/partitioned_tuple_data.hpp
  src/include/duckdb/execution/aggregate_hashtable.hpp
  src/include/duckdb/execution/join_hashtable.hpp
  src/include/duckdb/storage/temporary_memory_manager.hpp
  src/optimizer/build_probe_side_optimizer.cpp
  src/storage/temporary_memory_manager.cpp
Labels: Ready To Merge

#16508 Optimize FSST decoding
  src/common/fsst.cpp
  src/common/types/vector.cpp
  src/include/duckdb/common/fsst.hpp
  src/include/duckdb/common/types/string_heap.hpp
  src/include/duckdb/common/types/string_type.hpp
  src/include/duckdb/common/types/vector.hpp
  src/include/duckdb/common/types/vector_buffer.hpp
  src/include/duckdb/storage/arena_allocator.hpp
  src/storage/arena_allocator.cpp
  src/storage/compression/fsst.cpp
  third_party/fsst/fsst.h
Labels: Ready To Merge

#16507 Prefetch Parquet page header
  extension/parquet/column_reader.cpp
  extension/parquet/include/thrift_tools.hpp
Labels: Ready To Merge

#16541 Add `duckdb_prepared_statements`
  src/catalog/default/default_views.cpp
  src/function/table/system/CMakeLists.txt
  src/function/table/system/duckdb_prepared_statements.cpp
  src/function/table/system_functions.cpp
  src/include/duckdb/function/table/system_functions.hpp
  test/sql/pg_catalog/pg_prepared_statements.test
  test/sql/table_function/duckdb_prepared_statements.test
Labels: Needs Documentation

#16577 remove invalid tokens from nanosecond example
  extension/core_functions/include/core_functions/scalar/date_functions.hpp
  extension/core_functions/scalar/date/functions.json
Labels: Ready To Merge

#16576 CrossVersion.yml: Add v1.2.1, v1.2-histrionicus and main
  .github/workflows/CrossVersion.yml
Labels: Ready For Review

#16468 [PySpark] - Add `expr` function
  tools/pythonpkg/duckdb/experimental/spark/sql/functions.py
  tools/pythonpkg/tests/fast/spark/test_spark_functions_expr.py
Labels: Ready For Review

#16595 Add support for `RETURN_STATS` to `COPY`
  extension/parquet/include/parquet_writer.hpp
  extension/parquet/parquet_extension.cpp
  extension/parquet/parquet_writer.cpp
  src/common/enum_util.cpp
  src/execution/operator/persistent/physical_batch_copy_to_file.cpp
  src/execution/operator/persistent/physical_copy_to_file.cpp
  src/function/copy_function.cpp
  src/include/duckdb/execution/operator/persistent/physical_copy_to_file.hpp
  src/include/duckdb/function/copy_function.hpp
  src/planner/binder/statement/bind_copy.cpp
  src/planner/operator/logical_copy_to_file.cpp
  test/sql/copy/return_stats.test
  test/sql/copy/return_stats_tpch.test_slow
Labels: Needs Documentation

#16585 Better error messages for the CSV Scanner
  src/execution/operator/csv_scanner/sniffer/CMakeLists.txt
  src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/sniffer/set_columns.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/execution/operator/csv_scanner/util/csv_error.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_error.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_reader_options.hpp
  src/include/duckdb/execution/operator/csv_scanner/set_columns.hpp
  src/include/duckdb/execution/operator/csv_scanner/sniffer/csv_sniffer.hpp
  src/planner/binder/tableref/bind_named_parameters.cpp
  test/sql/copy/csv/csv_error_message.test
Labels: CI Failure

#15710 Support Enum types in read_csv - Python
  data/csv/enum_type.csv
  src/main/relation/read_csv_relation.cpp
  test/sql/copy/csv/test_enum_csv.test
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/api/test_read_csv.py
Labels: Ready For Review, feature

#16385 Read and Write Complex Json from Arrow Types
  src/common/CMakeLists.txt
  src/common/arrow/schema_metadata.cpp
  src/common/complex_json.cpp
  src/common/error_data.cpp
  src/common/string_util.cpp
  src/include/duckdb/common/arrow/schema_metadata.hpp
  src/include/duckdb/common/complex_json.hpp
  src/include/duckdb/common/string_util.hpp
  src/main/settings/custom_settings.cpp
  tools/pythonpkg/tests/fast/arrow/test_arrow_extensions.py
Labels: Ready For Review

#16549 Add Docker support for RISC-V CI with appropriate build commands
  scripts/test_docker_images.sh
Labels: Ready To Merge

#16471 Expose `Value::ToSQLString()` in C API
  scripts/regression/benchmark.py
  src/include/duckdb.h
  src/include/duckdb/main/capi/extension_api.hpp
  src/include/duckdb/main/capi/header_generation/apis/v1/unstable/new_string_functions.json
  src/include/duckdb/main/capi/header_generation/functions/value_interface.json
  src/include/duckdb_extension.h
  src/main/capi/duckdb_value-c.cpp
  test/api/capi/test_capi_values.cpp
  tools/pythonpkg/tests/fast/numpy/test_numpy_new_path.py
  tools/pythonpkg/tests/fast/udf/test_null_filtering.py
  tools/pythonpkg/tests/fast/udf/test_scalar.py
Labels: Changes Requested

#16651 [Fix] Perform eager constraint checking during physical batch insert
  src/execution/operator/persistent/physical_batch_insert.cpp
  src/execution/operator/persistent/physical_insert.cpp
Labels: Ready For Review

#16656 move OrderPreservationRecursive to physical_plan_generator.hpp
  src/execution/physical_plan/plan_insert.cpp
  src/include/duckdb/execution/physical_plan_generator.hpp
Labels: Ready To Merge

#16655 Add libs folder to bundled static libs
  .github/workflows/BundleStaticLibs.yml
  Makefile
Labels: Ready For Review

#16653 Character length and date functions
  src/function/function_list.cpp
  src/function/scalar/string/functions.json
  src/include/duckdb/function/scalar/string_functions.hpp
  src/parser/transform/expression/transform_function.cpp
  test/sql/function/string/test_length.test
  test/sql/types/date/test_date.test
Labels: Ready To Merge

#15959 Make CSV Parser strict_mode=True fail on a mix of new line delimiters.
  data/csv/afl/4172/case_4.csv
  data/csv/one_n_two.csv
  data/csv/one_r_n_two.csv
  data/csv/one_r_two.csv
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.cpp
  src/execution/operator/csv_scanner/util/csv_error.cpp
  src/include/duckdb/execution/operator/csv_scanner/base_scanner.hpp
  test/parallel_csv/test_parallel_csv.cpp
  test/sql/copy/csv/14512.test
  test/sql/copy/csv/auto/test_csv_auto.test
  test/sql/copy/csv/code_cov/csv_exact_buffer_size.test
  test/sql/copy/csv/csv_nullstr_list.test
  test/sql/copy/csv/parallel/csv_parallel_buffer_size.test
  test/sql/copy/csv/parallel/csv_parallel_new_line.test_slow
  test/sql/copy/csv/parallel/test_parallel_csv.test
  test/sql/copy/csv/test_auto_date.test
  test/sql/copy/csv/test_encodings.test_slow
  test/sql/copy/csv/test_mixed_new_line.test
  test/sql/copy/csv/test_wrong_newline_delimiter.test
  tools/pythonpkg/tests/fast/api/test_read_csv.py
Labels: Ready For Review

#16634 [pypi] Fix cleanup logic for multiple branches
  .github/workflows/Python.yml
  scripts/pypi_cleanup.py
Labels: Changes Requested

#16718 Issue #16652: Implicit Ordered Aggregation
  src/function/aggregate/sorted_aggregate_function.cpp
  test/sql/window/test_window_constant_aggregate.test
Labels: Ready For Review

#16705 Issue #16649: SelectNth Remainders
  extension/core_functions/include/core_functions/aggregate/quantile_sort_tree.hpp
  src/function/window/window_index_tree.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/execution/merge_sort_tree.hpp
  src/include/duckdb/function/window/window_index_tree.hpp
  test/sql/window/test_value_orderby.test
Labels: Ready For Review

#16722 add workaround for patching httpfs ext
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#15819 Implement UUID v7
  extension/core_functions/function_list.cpp
  extension/core_functions/include/core_functions/scalar/random_functions.hpp
  extension/core_functions/scalar/random/functions.json
  extension/core_functions/scalar/random/random.cpp
  src/common/types/uuid.cpp
  src/include/duckdb/common/types/uuid.hpp
  src/include/duckdb/main/extension_entries.hpp
  test/sql/function/uuid/test_uuid.test
  test/sql/function/uuid/test_uuid_function.test
Labels: Needs Documentation

#16602 Add an initial value to `list_reduce`
  extension/core_functions/function_list.cpp
  extension/core_functions/include/core_functions/scalar/list_functions.hpp
  extension/core_functions/lambda_functions.cpp
  extension/core_functions/scalar/list/functions.json
  extension/core_functions/scalar/list/list_reduce.cpp
  src/include/duckdb/function/lambda_functions.hpp
  src/planner/binder/expression/bind_function_expression.cpp
  test/sql/function/list/lambdas/incorrect.test
  test/sql/function/list/lambdas/reduce.test
  test/sql/function/list/lambdas/reduce_initial.test
  test/sql/function/list/lambdas/reduce_initial.test_slow
Labels: Needs Documentation

#16594 shell: make -bail work for more errors
  tools/shell/include/shell_state.hpp
  tools/shell/shell.cpp
Labels: Ready To Merge

#16745 [Test] Add missing test for eager-constraint checking fix
  test/sql/index/art/constraints/test_art_eager_batch_insert.test
Labels: Ready To Merge

#16747 Call Notify External Repositories from Invoke CI
  .github/workflows/InvokeCI.yml
  .github/workflows/NotifyExternalRepositories.yml
Labels: Ready To Merge

#16765 Issue #16250: Window Range Performance
  src/execution/operator/aggregate/physical_window.cpp
Labels: Ready For Review

#16769 Avoid building Python 3.7 wheels also for Linux
  .github/workflows/Python.yml
Labels: Ready To Merge

#16776 Fix two minor problems with NotifyExternalRepositories / odbc
  .github/workflows/InvokeCI.yml
  .github/workflows/NotifyExternalRepositories.yml
Labels: Ready To Merge

#16789 Python docs: List all join types
  tools/pythonpkg/src/pyrelation/initialize.cpp
Labels: Ready To Merge

#16793 [chore] NotifyExternalRepositories.yml: Fix endpoint to be pinged
  .github/workflows/NotifyExternalRepositories.yml
Labels: Ready To Merge

#16794 Remove delta from extensions built on a nightly basis (vs 1.2-histrionicus)
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#16795 Remove delta from extensions built on a nightly basis (vs main branch)
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#16796 OSX.yml & Windows.yml: remove repository_dispatch, already handled by InvokeCI
  .github/workflows/OSX.yml
  .github/workflows/Windows.yml
Labels: Ready To Merge

#16726 Make extensions be linked privitally into duckdb
  CMakeLists.txt
  extension/icu/CMakeLists.txt
  src/CMakeLists.txt
  tools/shell/CMakeLists.txt
  tools/sqlite3_api_wrapper/CMakeLists.txt
Labels: Ready For Review

#16822 regenerate function headers
  extension/core_functions/include/core_functions/scalar/random_functions.hpp
Labels: Ready To Merge

#16816 Internal #4490: Window Jump Reset
  src/function/window/window_boundaries_state.cpp
Labels: Ready For Review

#16824 Regression.yml: Actually checkout proper base.sha commit
  .github/workflows/Regression.yml
Labels: Ready For Review

#16802 Add extra check in normalize for commit, rollback and abort
  data/csv/test_commit_rollback.csv
  src/execution/operator/csv_scanner/sniffer/header_detection.cpp
  test/sql/copy/csv/auto/test_normalize_names.test
Labels: Changes Requested

#16817 NightlyTests.yml: Inline env variables into build command
  .github/workflows/NightlyTests.yml
Labels: Ready For Review

#16800 Add storage_version 66 for version 1.3.0
  data/storage/empty66.db
  data/storage/storage_versions66.db.gz
  src/storage/storage_info.cpp
  src/storage/version_map.json
  test/sql/attach/attach_storage_version.test
  test/sql/storage/storage_version_65.test
  test/sql/storage/storage_versions.test
  test/sql/storage_version/storage_version.db
  test/sql/storage_version/storage_version.test_slow
Labels: Ready For Review

#16837 Internal #4492: Ignore Nulls Orrification
  src/function/window/window_value_function.cpp
Labels: Ready For Review

#16648 compressed vector serialization fixes
  src/common/types/vector.cpp
Labels: Changes Requested

#16727 [ART] Immediately erase empty fixed-size buffers
  src/execution/index/art/art.cpp
  src/execution/index/bound_index.cpp
  src/execution/index/fixed_size_allocator.cpp
  src/execution/index/fixed_size_buffer.cpp
  src/execution/operator/helper/physical_vacuum.cpp
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/bound_index.hpp
  src/include/duckdb/execution/index/fixed_size_allocator.hpp
  src/include/duckdb/execution/index/fixed_size_buffer.hpp
  src/include/duckdb/storage/data_table.hpp
  src/storage/data_table.cpp
  src/storage/local_storage.cpp
  src/transaction/undo_buffer.cpp
  test/sql/index/art/memory/test_art_linear.test_slow
  test/sql/index/art/memory/test_art_non_linear.test_slow
Labels: Ready For Review

#16861 [ART] Introduce a new ARTScanner and make InitMerge and Vacuum iterative
  src/common/enum_util.cpp
  src/execution/index/art/node.cpp
  src/execution/index/art/prefix.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/execution/index/art/art_scanner.hpp
  src/include/duckdb/execution/index/art/node.hpp
  src/include/duckdb/execution/index/art/prefix.hpp
Labels: Ready For Review

#16849 Reduce allocations during aggregations
  src/common/radix_partitioning.cpp
  src/common/row_operations/row_aggregate.cpp
  src/common/sort/partition_state.cpp
  src/common/types/hash.cpp
  src/common/types/row/partitioned_tuple_data.cpp
  src/common/types/row/tuple_data_allocator.cpp
  src/common/types/row/tuple_data_collection.cpp
  src/common/types/row/tuple_data_segment.cpp
  src/common/types/selection_vector.cpp
  src/common/types/vector.cpp
  src/execution/aggregate_hashtable.cpp
  src/execution/base_aggregate_hashtable.cpp
  src/execution/join_hashtable.cpp
  src/execution/operator/join/perfect_hash_join_executor.cpp
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/perfect_aggregate_hashtable.cpp
  src/execution/radix_partitioned_hashtable.cpp
  src/include/duckdb/common/radix_partitioning.hpp
  src/include/duckdb/common/row_operations/row_operations.hpp
  src/include/duckdb/common/sort/partition_state.hpp
  src/include/duckdb/common/types/row/partitioned_tuple_data.hpp
  src/include/duckdb/common/types/row/tuple_data_allocator.hpp
  src/include/duckdb/common/types/row/tuple_data_collection.hpp
  src/include/duckdb/common/types/row/tuple_data_segment.hpp
  src/include/duckdb/common/types/row/tuple_data_states.hpp
  src/include/duckdb/common/types/selection_vector.hpp
  src/include/duckdb/common/types/vector_buffer.hpp
  src/include/duckdb/execution/aggregate_hashtable.hpp
  src/include/duckdb/execution/base_aggregate_hashtable.hpp
  src/include/duckdb/execution/join_hashtable.hpp
  src/include/duckdb/execution/radix_partitioned_hashtable.hpp
Labels: Ready For Review

#16879 Internal #4490: Window Threading Cleanup
  src/common/sort/partition_state.cpp
  src/include/duckdb/common/sort/partition_state.hpp
  src/include/duckdb/common/types/validity_mask.hpp
  src/include/duckdb/execution/task_error_manager.hpp
Labels: Ready For Review
