Repository duckdb/duckdb, pull requests merged in 2025-08, with the labels that each got.

#18468 Internal #5366: WindowDeltaScanner
  src/execution/operator/aggregate/physical_window.cpp
  src/function/window/window_distinct_aggregator.cpp
  src/function/window/window_token_tree.cpp
  src/include/duckdb/function/window/window_collection.hpp
Labels: Ready For Review

#17585 julia: config improvements
  .github/workflows/Julia.yml
  tools/juliapkg/Project.toml
  tools/juliapkg/src/config.jl
  tools/juliapkg/src/database.jl
  tools/juliapkg/src/table_function.jl
  tools/juliapkg/test/test_big_nested.jl
  tools/juliapkg/test/test_config.jl
Labels: Changes Requested

#18516 Remove `immediate_transaction_mode` from DB config options
  src/include/duckdb/main/config.hpp
Labels: Ready To Merge

#18507 Restore missing `test/configs/small_block_size.json` file
  .github/workflows/NightlyTests.yml
Labels: Ready To Merge

#18544 [ART] Node::Free refactoring
  src/common/enum_util.cpp
  src/execution/index/art/art.cpp
  src/execution/index/art/art_merger.cpp
  src/execution/index/art/base_leaf.cpp
  src/execution/index/art/base_node.cpp
  src/execution/index/art/leaf.cpp
  src/execution/index/art/node.cpp
  src/execution/index/art/node256.cpp
  src/execution/index/art/node256_leaf.cpp
  src/execution/index/art/node48.cpp
  src/execution/index/art/prefix.cpp
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/art/art_scanner.hpp
  src/include/duckdb/execution/index/art/base_node.hpp
  src/include/duckdb/execution/index/art/node.hpp
  src/include/duckdb/execution/index/art/node256.hpp
  src/include/duckdb/execution/index/art/node48.hpp
  src/include/duckdb/execution/index/art/prefix.hpp
  test/sql/update/string_update_transaction_local_7348.test
Labels: Ready For Review, Ready To Merge

#18541 Implement special-case `VARCHAR` to `JSON[]` casts and vice versa
  extension/json/include/json_functions.hpp
  extension/json/json_extension.cpp
  extension/json/json_functions.cpp
  extension/json/json_functions/json_create.cpp
  extension/json/json_functions/json_transform.cpp
  src/function/cast/cast_function_set.cpp
  src/include/duckdb/function/cast/cast_function_set.hpp
  test/sql/json/scalar/json_nested_casts.test
  test/sql/json/scalar/test_json_extract.test
  test/sql/json/scalar/test_json_path.test
  test/sql/json/table/read_json.test
Labels: Ready For Review

#18556 Check if `heap_block_ids` is empty before getting start/end when destroying chunks in `TupleDataCollection`
  src/common/types/row/tuple_data_collection.cpp
Labels: Ready For Review

#17433 Add compile option standalone-debug for clang
  CMakeLists.txt
  Makefile
Labels: Changes Requested

#18566 fix: add formatting to explain row counts
  src/common/tree_renderer/text_tree_renderer.cpp
  src/include/duckdb/common/tree_renderer/text_tree_renderer.hpp
  test/sql/function/list/generate_series.test
Labels: CI Failure

#18552 Flip left/right delim join based on cardinalities
  .github/patches/extensions/vss/fix.patch
  src/include/duckdb/optimizer/build_probe_side_optimizer.hpp
  src/optimizer/build_probe_side_optimizer.cpp
  test/sql/cte/test_correlated_recursive_cte.test_slow
  test/sql/cte/test_fib_complex.test_slow
  test/sql/json/table/test_json_table_in_out.test_slow
  test/sql/subquery/lateral/test_lateral_join.test
  test/sql/types/list/unnest_table_function.test
Labels: Ready For Review

#18536 correctly setting log transaction id in ThreadContext
  src/parallel/thread_context.cpp
Labels: Ready For Review

#18581 Backport renaming a config name `small_block_size.json` to `block_size_16kB` in NightlyTests
  .github/workflows/NightlyTests.yml
Labels: Ready To Merge

#18514 [Profiling] Add client context into more read functions
  extension/parquet/include/zstd_file_system.hpp
  extension/parquet/zstd_file_system.cpp
  src/common/compressed_file_system.cpp
  src/common/file_system.cpp
  src/common/gzip_file_system.cpp
  src/common/local_file_system.cpp
  src/common/pipe_file_system.cpp
  src/common/virtual_file_system.cpp
  src/execution/operator/csv_scanner/buffer_manager/csv_buffer.cpp
  src/execution/operator/csv_scanner/buffer_manager/csv_file_handle.cpp
  src/execution/operator/csv_scanner/encode/csv_encoder.cpp
  src/function/table/read_file.cpp
  src/include/duckdb/common/compressed_file_system.hpp
  src/include/duckdb/common/file_open_flags.hpp
  src/include/duckdb/common/file_system.hpp
  src/include/duckdb/common/gzip_file_system.hpp
  src/include/duckdb/common/pipe_file_system.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_handle.hpp
  src/include/duckdb/execution/operator/csv_scanner/encode/csv_encoder.hpp
  src/include/duckdb/main/database_path_and_type.hpp
  src/include/duckdb/storage/magic_bytes.hpp
  src/main/database_manager.cpp
  src/main/database_path_and_type.cpp
  src/main/extension/extension_install.cpp
  src/storage/caching_file_system.cpp
  src/storage/magic_bytes.cpp
  src/storage/single_file_block_manager.cpp
  src/storage/write_ahead_log.cpp
Labels: CI Failure

#18591 bump httpfs
  .github/config/out_of_tree_extensions.cmake
Labels: Ready To Merge

#18434 bump avro to v1.4
  .github/config/extensions/avro.cmake
  .github/patches/extensions/avro/avro_loader.patch
Labels: CI Failure

#18197 bump spatial (on main)
  .github/config/extensions/spatial.cmake
  .github/patches/extensions/spatial/fix.patch
  src/include/duckdb/main/extension_entries.hpp
Labels: Ready To Merge

#18563 Correctly set weights in reservoir sample when switch to slow sampling
  src/execution/sample/base_reservoir_sample.cpp
  src/include/duckdb/execution/reservoir_sample.hpp
  test/sql/sample/test_sampling_stats.test_slow
Labels: Changes Requested

#18651 Internal #5366: Window Interrupt Arguments
  extension/core_functions/include/core_functions/aggregate/quantile_sort_tree.hpp
  src/execution/operator/aggregate/physical_window.cpp
  src/function/window/window_aggregate_function.cpp
  src/function/window/window_aggregator.cpp
  src/function/window/window_constant_aggregator.cpp
  src/function/window/window_custom_aggregator.cpp
  src/function/window/window_distinct_aggregator.cpp
  src/function/window/window_executor.cpp
  src/function/window/window_merge_sort_tree.cpp
  src/function/window/window_naive_aggregator.cpp
  src/function/window/window_rank_function.cpp
  src/function/window/window_rownumber_function.cpp
  src/function/window/window_segment_tree.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/function/aggregate_function.hpp
  src/include/duckdb/function/window/window_aggregate_function.hpp
  src/include/duckdb/function/window/window_aggregator.hpp
  src/include/duckdb/function/window/window_constant_aggregator.hpp
  src/include/duckdb/function/window/window_custom_aggregator.hpp
  src/include/duckdb/function/window/window_distinct_aggregator.hpp
  src/include/duckdb/function/window/window_executor.hpp
  src/include/duckdb/function/window/window_merge_sort_tree.hpp
  src/include/duckdb/function/window/window_naive_aggregator.hpp
  src/include/duckdb/function/window/window_rank_function.hpp
  src/include/duckdb/function/window/window_rownumber_function.hpp
  src/include/duckdb/function/window/window_segment_tree.hpp
  src/include/duckdb/function/window/window_value_function.hpp
Labels: Ready For Review

#18616 Fix the issue where delta_for isn't used in bitpacking when for is unavailable
  src/storage/compression/bitpacking.cpp
  test/sql/storage/compression/bitpacking/bitpacking_delta_for.test
Labels: CI Failure

#18457 Add `date_trunc()` simplification rules
  src/include/duckdb/optimizer/rule/date_trunc_simplification.hpp
  src/include/duckdb/optimizer/rule/list.hpp
  src/optimizer/optimizer.cpp
  src/optimizer/rule/CMakeLists.txt
  src/optimizer/rule/date_trunc_simplification.cpp
  test/optimizer/date_trunc_simplification.test
  test/optimizer/date_trunc_simplification_icu.test
Labels: Ready To Merge

#18676 Internal #5366: Window State Arguments
  src/execution/operator/aggregate/physical_window.cpp
  src/function/window/window_aggregate_function.cpp
  src/function/window/window_aggregator.cpp
  src/function/window/window_constant_aggregator.cpp
  src/function/window/window_custom_aggregator.cpp
  src/function/window/window_distinct_aggregator.cpp
  src/function/window/window_executor.cpp
  src/function/window/window_index_tree.cpp
  src/function/window/window_naive_aggregator.cpp
  src/function/window/window_rank_function.cpp
  src/function/window/window_rownumber_function.cpp
  src/function/window/window_segment_tree.cpp
  src/function/window/window_token_tree.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/function/window/window_aggregate_function.hpp
  src/include/duckdb/function/window/window_aggregator.hpp
  src/include/duckdb/function/window/window_constant_aggregator.hpp
  src/include/duckdb/function/window/window_custom_aggregator.hpp
  src/include/duckdb/function/window/window_distinct_aggregator.hpp
  src/include/duckdb/function/window/window_executor.hpp
  src/include/duckdb/function/window/window_index_tree.hpp
  src/include/duckdb/function/window/window_merge_sort_tree.hpp
  src/include/duckdb/function/window/window_naive_aggregator.hpp
  src/include/duckdb/function/window/window_rank_function.hpp
  src/include/duckdb/function/window/window_rownumber_function.hpp
  src/include/duckdb/function/window/window_segment_tree.hpp
  src/include/duckdb/function/window/window_token_tree.hpp
  src/include/duckdb/function/window/window_value_function.hpp
Labels: Ready For Review

#18693 Move attached databases from a CatalogSet to a dedicated map of shared pointers
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/mysql_scanner/fix.patch
  .github/patches/extensions/postgres_scanner/fix.patch
  .github/patches/extensions/sqlsmith/fix.patch
  extension/autocomplete/autocomplete_extension.cpp
  src/catalog/catalog.cpp
  src/common/enum_util.cpp
  src/execution/operator/helper/physical_transaction.cpp
  src/execution/operator/schema/physical_attach.cpp
  src/function/table/system/duckdb_databases.cpp
  src/function/table/system/pragma_database_size.cpp
  src/include/duckdb/common/enums/undo_flags.hpp
  src/include/duckdb/main/attached_database.hpp
  src/include/duckdb/main/database.hpp
  src/include/duckdb/main/database_manager.hpp
  src/include/duckdb/transaction/duck_transaction.hpp
  src/include/duckdb/transaction/duck_transaction_manager.hpp
  src/include/duckdb/transaction/meta_transaction.hpp
  src/main/attached_database.cpp
  src/main/client_context.cpp
  src/main/database.cpp
  src/main/database_manager.cpp
  src/transaction/commit_state.cpp
  src/transaction/duck_transaction.cpp
  src/transaction/duck_transaction_manager.cpp
  src/transaction/meta_transaction.cpp
  src/transaction/rollback_state.cpp
  src/transaction/wal_write_state.cpp
  test/configs/force_storage_restart.json
  test/configs/wal_verification.json
  test/sql/attach/attach_concurrent_detach_mix.test_slow
  test/sql/attach/attach_filepath_roundtrip.test
  test/sql/attach/attach_transactionality.test
  test/sql/attach/attach_use_rollback.test
  test/sql/copy/encryption/simple_encryption.test
  test/sql/parallelism/interquery/CMakeLists.txt
  test/sql/parallelism/interquery/concurrent_attach_detach.cpp
  test/sqlite/sqllogic_command.cpp
Labels: Needs Documentation

#17992 Add Option to Allocate Using an Arena in `string_t`
  extension/core_functions/scalar/generic/current_setting.cpp
  src/catalog/catalog.cpp
  src/common/exception_format_value.cpp
  src/common/types/value.cpp
  src/execution/operator/helper/physical_reset.cpp
  src/include/duckdb/catalog/catalog.hpp
  src/include/duckdb/common/exception_format_value.hpp
  src/include/duckdb/common/types/string.hpp
  src/include/duckdb/common/types/value.hpp
  src/include/duckdb/execution/operator/helper/physical_reset.hpp
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/main/config.hpp
  src/include/duckdb/main/error_manager.hpp
  src/include/duckdb/storage/arena_allocator.hpp
  src/main/client_config.cpp
  src/main/config.cpp
  src/main/error_manager.cpp
Labels: Ready For Review

#18686 #Fix 18558: add row_group scan fast path
  src/storage/table/row_group.cpp
Labels: Ready To Merge

#18027 Added support for blob<->uuid conversions
  extension/parquet/include/reader/uuid_column_reader.hpp
  extension/parquet/include/writer/parquet_write_operators.hpp
  src/common/operator/cast_operators.cpp
  src/common/types/uuid.cpp
  src/function/cast/blob_cast.cpp
  src/function/cast/uuid_casts.cpp
  src/include/duckdb/common/operator/cast_operators.hpp
  src/include/duckdb/common/types/uuid.hpp
  test/sql/types/uuid/test_uuid_cast.test
Labels: Ready To Merge

#18733 Internal #5669: Loop Join Thresholds
  src/execution/physical_plan/plan_comparison_join.cpp
  test/sql/join/iejoin/test_iejoin_null_keys.test
Labels: Ready For Review

#18747 Add OS X notarization for DuckDB CLI and libduckdb.dylib
  .github/workflows/OSX.yml
Labels: Ready To Merge

#18319 Fix index resolution when querying table with index via view
  src/function/table/table_scan.cpp
  test/sql/index/art/issues/test_art_view_col_binding.test
Labels: Ready To Merge

#18731 Internal #3273: Parallel Window Masks
  src/common/sorting/hashed_sort.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/include/duckdb/common/types/validity_mask.hpp
Labels: Ready For Review

#18672 fix: coalesce query progress updates to reduce terminal writes
  src/common/progress_bar/terminal_progress_bar_display.cpp
  src/include/duckdb/common/progress_bar/display/terminal_progress_bar_display.hpp
Labels: Changes Requested

#18795 Support expressions as COPY file target
  src/common/file_system.cpp
  src/include/duckdb/parser/parsed_data/copy_info.hpp
  src/parser/parsed_data/copy_info.cpp
  src/parser/transform/statement/transform_copy.cpp
  src/planner/binder/statement/bind_copy.cpp
  test/sql/copy/csv/copy_expression.test
  test/sql/prepared/prepare_copy.test
  third_party/libpg_query/grammar/statements/copy.y
  third_party/libpg_query/grammar/types/copy.yh
  third_party/libpg_query/include/nodes/parsenodes.hpp
  third_party/libpg_query/src_backend_parser_gram.cpp
Labels: Needs Documentation

#18691 bump httpfs so it includes curl option
  .github/config/extensions/httpfs.cmake
  .github/patches/extensions/httpfs/fix.patch
  .github/workflows/LinuxRelease.yml
  .github/workflows/Regression.yml
Labels: CI Failure

#18794 Issue #18767: Ignore Timestamp Offsets
  extension/icu/icu-strptime.cpp
  src/common/operator/cast_operators.cpp
  src/common/types/time.cpp
  src/common/types/timestamp.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/type_detection.cpp
  src/function/cast/string_cast.cpp
  src/function/table/system/test_all_types.cpp
  src/include/duckdb/common/operator/cast_operators.hpp
  src/include/duckdb/common/types/timestamp.hpp
  test/sql/function/timestamp/test_icu_datetrunc.test
  test/sql/types/timestamp/timestamp_limits.test
  test/sql/types/timestamp/utc_offset.test
  tools/juliapkg/test/test_old_interface.jl
Labels: Needs Documentation, Ready For Review
