Repository duckdb/duckdb, pull requests merged in 2025-05, with the labels that each got.

#17314 [Arrow] Implement support to consuming and producing Decimal 32 and 64.
  src/common/arrow/arrow_appender.cpp
  src/common/arrow/arrow_converter.cpp
  src/common/enum_util.cpp
  src/function/table/arrow.cpp
  src/function/table/arrow/arrow_duck_schema.cpp
  src/function/table/arrow/arrow_type_info.cpp
  src/function/table/arrow_conversion.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/function/table/arrow/arrow_type_info.hpp
  src/include/duckdb/function/table/arrow/enum/arrow_type_info_type.hpp
  tools/pythonpkg/src/arrow/arrow_array_stream.cpp
  tools/pythonpkg/tests/fast/arrow/test_arrow_decimal_32_64.py
  tools/pythonpkg/tests/fast/arrow/test_arrow_run_end_encoding.py
Labels: Ready To Merge

#17315 take the column ids from the logical get, don't require a LogicalGet …
  src/include/duckdb/optimizer/filter_combiner.hpp
  src/optimizer/filter_combiner.cpp
  src/optimizer/pushdown/pushdown_get.cpp
Labels: Ready To Merge

#17316 Allow installing extensions with external access allowlist
  src/common/file_system.cpp
  src/include/duckdb/common/file_system.hpp
  src/main/extension/extension_install.cpp
  test/sql/extensions/allowed_directories_install.test
Labels: Ready To Merge

#17243 Implement ARTMerger replacing the recursive ART merge algorithm
  src/common/enum_util.cpp
  src/execution/index/art/CMakeLists.txt
  src/execution/index/art/art.cpp
  src/execution/index/art/art_merger.cpp
  src/execution/index/art/base_leaf.cpp
  src/execution/index/art/leaf.cpp
  src/execution/index/art/node.cpp
  src/execution/index/art/node256_leaf.cpp
  src/execution/index/art/prefix.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/execution/index/art/art.hpp
  src/include/duckdb/execution/index/art/art_merger.hpp
  src/include/duckdb/execution/index/art/art_scanner.hpp
  src/include/duckdb/execution/index/art/base_leaf.hpp
  src/include/duckdb/execution/index/art/base_node.hpp
  src/include/duckdb/execution/index/art/leaf.hpp
  src/include/duckdb/execution/index/art/node.hpp
  src/include/duckdb/execution/index/art/node256.hpp
  src/include/duckdb/execution/index/art/node256_leaf.hpp
  src/include/duckdb/execution/index/art/node48.hpp
  src/include/duckdb/execution/index/art/prefix.hpp
  test/sql/index/art/nodes/test_art_sparse_merge.test
Labels: Ready To Merge

#17234 Share null mask with constant null arg vector
  src/function/scalar/generic/constant_or_null.cpp
  test/sql/join/inner/not_between_is_null.test
Labels: Changes Requested

#17284 [CSV Reader] Simplify Quote/Escape detection code, make it more robust and decouple comment and skip_rows option.
  data/csv/comments/17226.csv
  data/csv/comments/comment_skip.csv
  src/common/enum_util.cpp
  src/execution/operator/csv_scanner/scanner/column_count_scanner.cpp
  src/execution/operator/csv_scanner/scanner/skip_scanner.cpp
  src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
  src/execution/operator/csv_scanner/sniffer/dialect_detection.cpp
  src/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.cpp
  src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
  src/execution/operator/csv_scanner/table_function/global_csv_state.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/execution/operator/csv_scanner/base_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/column_count_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/csv_state_machine_cache.hpp
  src/include/duckdb/execution/operator/csv_scanner/quote_rules.hpp
  src/include/duckdb/execution/operator/csv_scanner/skip_scanner.hpp
  src/include/duckdb/execution/operator/csv_scanner/sniffer/csv_sniffer.hpp
  src/main/relation/read_csv_relation.cpp
  test/sql/cast/string_to_list_cast.test
  test/sql/copy/csv/test_comment_option.test
  test/sql/copy/csv/test_cranlogs.test_slow
  test/sql/copy/csv/test_csv_remote.test
  test/sql/copy/csv/test_read_csv.test
  test/sql/copy/csv/test_sniff_csv.test
  test/sql/copy/csv/test_sniff_csv_options.test
  tools/pythonpkg/tests/fast/api/test_read_csv.py
Labels: Merge Conflict

#17317 Internal #4723: Inequality Condition Pushdown
  benchmark/micro/pushdown/nlj_inequality_pushdown.benchmark
  src/execution/operator/join/physical_hash_join.cpp
  src/execution/operator/join/physical_nested_loop_join.cpp
  src/execution/physical_plan/plan_comparison_join.cpp
  src/include/duckdb/execution/operator/join/join_filter_pushdown.hpp
  src/include/duckdb/execution/operator/join/physical_nested_loop_join.hpp
  src/optimizer/join_filter_pushdown_optimizer.cpp
Labels: Ready For Review

#17331 Properly format strings when throw JSON errors
  data/json/format_string_key.json
  extension/json/json_functions/json_transform.cpp
  test/sql/json/issues/internal_issue4794.test
Labels: Ready To Merge

#17342 Revert "Skip MinGW, currently failing on main"
  .github/workflows/Windows.yml
Labels: Ready To Merge

#17332 Fix issue with empty ranges
  src/function/table/range.cpp
  test/sql/function/list/generate_series.test
Labels: Ready To Merge

#17330 Internal #4797: Timestamp Range Cardinality
  extension/icu/icu-table-range.cpp
  src/common/types/interval.cpp
  src/function/table/range.cpp
  src/include/duckdb/common/types/interval.hpp
  test/sql/table_function/icu_range_timestamptz.test
  test/sql/table_function/range_timestamp.test
Labels: Ready For Review

#17328 Issue #17299: Integer Rounding
  extension/core_functions/scalar/math/numeric.cpp
  src/common/operator/cast_operators.cpp
  src/include/duckdb/common/types/cast_helpers.hpp
  src/include/duckdb/common/types/hugeint.hpp
  src/include/duckdb/common/types/uhugeint.hpp
  test/sql/function/numeric/test_round_integers.test
  test/sql/window/test_custom_spooling.test_slow
Labels: Ready For Review

#17345 Add support for UUID v7 to Filename Pattern - and clean it up so that it correctly supports composite patterns
  src/common/enum_util.cpp
  src/common/filename_pattern.cpp
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/common/filename_pattern.hpp
  src/include/duckdb/common/optional_idx.hpp
  src/include/duckdb/planner/operator/logical_empty_result.hpp
  src/include/duckdb/storage/serialization/logical_operator.json
  src/planner/operator/logical_empty_result.cpp
  src/storage/serialization/serialize_logical_operator.cpp
  test/sql/copy/format_uuid.test
Labels: Needs Documentation

#17357 Handle both ENCRYPTION_KEY and STORAGE_VERSION passed as options
  src/parser/parsed_data/attach_info.cpp
  test/sql/attach/attach_encryption_block_header.test
Labels: Ready For Review

#17080 [Nested] Fix: 16489 - Find `NULL`s in lists using `list_position`
  extension/core_functions/scalar/map/map_extract.cpp
  src/function/scalar/list/contains_or_position.cpp
  src/function/scalar/map/map_contains.cpp
  src/include/duckdb/function/scalar/list/contains_or_position.hpp
  test/sql/function/list/list_position.test
Labels: Ready To Merge

#17062 Join Hash Table Probing Optimization: Optional Probing Selection Vector
  src/execution/join_hashtable.cpp
  src/include/duckdb/execution/join_hashtable.hpp
Labels: Ready For Review

#15923 Remove bundled TPCH & TPCDS in Python wheels
  tools/pythonpkg/duckdb_extension_config.cmake
  tools/pythonpkg/setup.py
  tools/pythonpkg/tests/fast/arrow/test_tpch.py
Labels: Ready To Merge

#17379 fix not setting nested validity when map_extract returns null
  extension/core_functions/scalar/map/map_extract.cpp
  test/sql/types/map/map_extract_nested_null.test
Labels: Ready To Merge

#17391 Issue #17266: Lead Lag Nulls
  src/function/window/window_value_function.cpp
  test/sql/window/test_lead_lag.test
  test/sql/window/test_leadlag_orderby.test
Labels: Ready For Review

#17403 [Dev] Add `QualifiedName::ParseComponents`, add input to the error messages
  src/include/duckdb/parser/qualified_name.hpp
  src/parser/qualified_name.cpp
Labels: Ready To Merge

#17389 Use an insertion order preserving map in Value::MAP
  .github/patches/extensions/spatial/fix.patch
  src/common/types/value.cpp
  src/include/duckdb/catalog/catalog_entry.hpp
  src/include/duckdb/common/insertion_order_preserving_map.hpp
  src/include/duckdb/common/types/value.hpp
  src/include/duckdb/parser/parsed_data/create_info.hpp
  src/include/duckdb/storage/serialization/create_info.json
  src/main/capi/profiling_info-c.cpp
  src/storage/serialization/serialize_create_info.cpp
Labels: CI Failure

#17400 Internal #4723: PWMJ Inequality Pushdown
  benchmark/micro/pushdown/nlj_inequality_pushdown.benchmark
  benchmark/micro/pushdown/pwmj_inequality_pushdown.benchmark
  src/execution/operator/join/physical_piecewise_merge_join.cpp
  src/execution/physical_plan/plan_comparison_join.cpp
  src/include/duckdb/execution/operator/join/physical_piecewise_merge_join.hpp
Labels: Ready For Review

#17360 Use argparse in scripts/format.py
  scripts/format.py
Labels: Ready To Merge

#17422 Internal #4830: IEJoin Inequality Pushdown
  benchmark/micro/pushdown/iejoin_inequality_pushdown.benchmark
  src/execution/operator/join/physical_iejoin.cpp
  src/execution/physical_plan/plan_comparison_join.cpp
  src/include/duckdb/execution/operator/join/physical_iejoin.hpp
Labels: Ready For Review

#16927 Add conn.query_progress() method
  src/include/duckdb/main/connection.hpp
  src/main/connection.cpp
  tools/pythonpkg/duckdb-stubs/__init__.pyi
  tools/pythonpkg/duckdb/__init__.py
  tools/pythonpkg/duckdb_python.cpp
  tools/pythonpkg/requirements-dev.txt
  tools/pythonpkg/scripts/connection_methods.json
  tools/pythonpkg/src/include/duckdb_python/pyconnection/pyconnection.hpp
  tools/pythonpkg/src/pyconnection.cpp
  tools/pythonpkg/tests/fast/api/test_query_progress.py
Labels: Ready For Review

#17434 Fix JSON extension compilation on Ubuntu 22.04
  extension/json/json_functions/json_table_in_out.cpp
Labels: Ready To Merge

#16910 BUGFIX: DELIM_JOINS should reflect functionality of NULL filtering conditions in joins with DELIM_GETS
  src/optimizer/deliminator.cpp
  test/issues/general/test_4950.test
  test/sql/join/semianti/test_simple_anti_join.test
Labels: Ready For Review

#17415 Allow directly attaching of Parquet/CSV/JSON files
  src/catalog/catalog_set.cpp
  src/catalog/duck_catalog.cpp
  src/common/enum_util.cpp
  src/execution/operator/schema/physical_attach.cpp
  src/include/duckdb/catalog/catalog_entry/duck_schema_entry.hpp
  src/include/duckdb/catalog/catalog_set.hpp
  src/include/duckdb/main/attached_database.hpp
  src/include/duckdb/main/database.hpp
  src/include/duckdb/main/database_manager.hpp
  src/include/duckdb/storage/magic_bytes.hpp
  src/include/duckdb/storage/storage_extension.hpp
  src/main/attached_database.cpp
  src/main/database.cpp
  src/main/database_manager.cpp
  src/main/database_path_and_type.cpp
  src/storage/CMakeLists.txt
  src/storage/magic_bytes.cpp
  src/storage/open_file_storage_extension.cpp
  test/api/test_api.cpp
  test/sql/attach/attach_remote.test
  test/sql/copy/parquet/attach_parquet.test
  tools/shell/tests/test_shell_basics.py
Labels: Needs Documentation

#17407 Enable `SYSTEM_PEAK_BUFFER_MEMORY` and `SYSTEM_PEAK_TEMP_DIR_SIZE` profiling by default
  src/main/profiling_info.cpp
  test/sql/pragma/profiling/test_custom_profiling_memory_and_temp_dir.test_slow
  test/sql/pragma/profiling/test_custom_profiling_optimizer.test
  test/sql/pragma/profiling/test_default_profiling_settings.test
Labels: Ready For Review

#17448 Recurse into `MAP` and `LIST` with the `remap_struct` and the MFR ColumnMapper
  src/common/multi_file/multi_file_column_mapper.cpp
  src/function/scalar/struct/remap_struct.cpp
  test/sql/types/struct/remap_struct.test
  test/sql/types/struct/remap_struct_in_list.test
  test/sql/types/struct/remap_struct_in_map.test
Labels: Ready For Review

#17468 Fix TIMETZ cast in example
  extension/core_functions/include/core_functions/scalar/date_functions.hpp
  extension/core_functions/scalar/date/functions.json
Labels: Ready For Review

#17428 [Serializer] Lambda Compatibilty Fix
  extension/core_functions/lambda_functions.cpp
  test/sql/attach/attach_lambda_view.test
Labels: Ready To Merge

#17479 Add release version
  src/function/table/version/pragma_version.cpp
  src/include/duckdb/main/database.hpp
  tools/shell/shell.cpp
Labels: Ready For Review

#17206 Make the encodings extension a core extension, and make it auto-loadable.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/config/out_of_tree_extensions.cmake
  src/execution/operator/csv_scanner/buffer_manager/csv_file_handle.cpp
  src/execution/operator/csv_scanner/encode/csv_encoder.cpp
  src/function/table/read_csv.cpp
  src/include/duckdb/execution/operator/csv_scanner/csv_file_handle.hpp
  src/include/duckdb/execution/operator/csv_scanner/encode/csv_encoder.hpp
  src/include/duckdb/function/encoding_function.hpp
  src/main/extension/extension_helper.cpp
  test/extension/autoloading_encodings.test
Labels: Needs Documentation, Ready To Merge

#17501 Allow passing down rc-style version also via OVERRIDE_GIT_DESCRIBE
  CMakeLists.txt
  Makefile
Labels: Ready For Review

#17509 Remove spatial from OSX Relassert
  .github/workflows/NightlyTests.yml
Labels: Ready To Merge

#17527 Fix update extensions
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/httpfs/no_follow_no_keep_alive.patch
  src/include/duckdb/common/http_util.hpp
  src/main/extension/extension_install.cpp
  src/main/http/http_util.cpp
Labels: Ready For Review

#17528 Minor fixes to exception error messages
  src/main/extension.cpp
  src/parallel/executor_task.cpp
  src/parallel/pipeline_event.cpp
Labels: Ready For Review

#17536 Fix extension test
  CMakeLists.txt
  scripts/run_extension_medata_tests.sh
Labels: Ready To Merge

#17548 [Dev] Fix `allowed_directories` crash
  src/main/settings/custom_settings.cpp
  test/api/test_config.cpp
Labels: Ready To Merge

#17539 Generate data for tpch sf100 in steps
  benchmark/benchmark_runner.cpp
  benchmark/large/tpch-sf100/load.sql
Labels: Ready For Review

#17556 Issue #17537: Fractional Second Padding
  src/function/scalar/strftime_format.cpp
  test/sql/function/timestamp/test_strptime.test
Labels: Ready To Merge

#17558 Remove patch and bump httpfs
  .github/config/out_of_tree_extensions.cmake
  .github/patches/extensions/httpfs/no_follow_no_keep_alive.patch
  test/sql/secrets/secret_types_function.test
Labels: Ready To Merge

#17602 Main branch versioning set to false
  CMakeLists.txt
  scripts/amalgamation.py
  scripts/package_build.py
  tools/pythonpkg/setup.py
Labels: Ready To Merge

#17614 Issue #17606: Disable TIMESTAMPTZ Casts
  extension/icu/icu-timezone.cpp
  test/sql/timezone/disable_timestamptz_casts.test
Labels: Ready For Review

#17623 C API tidying
  src/include/duckdb.h
  src/include/duckdb/main/capi/extension_api.hpp
  src/include/duckdb/main/capi/header_generation/functions/scalar_functions.json
  src/include/duckdb/main/capi/header_generation/functions/selection_vector_interface.json
  src/include/duckdb/main/capi/header_generation/functions/value_interface.json
  src/include/duckdb/main/capi/header_generation/functions/vector_interface.json
  src/include/duckdb/main/capi/header_generation/header_base.hpp.template
  src/include/duckdb_extension.h
  src/main/capi/data_chunk-c.cpp
Labels: Needs Documentation

#17649 Issue #17621: Streaming Window Reset
  src/execution/operator/aggregate/physical_streaming_window.cpp
  test/sql/window/test_streaming_window.test
Labels: Ready For Review

#17665 Enable profiling output for all operator types
  src/common/enum_util.cpp
  src/common/settings.json
  src/include/duckdb/common/enum_util.hpp
  src/include/duckdb/main/client_config.hpp
  src/include/duckdb/main/query_profiler.hpp
  src/include/duckdb/main/settings.hpp
  src/main/config.cpp
  src/main/query_profiler.cpp
  src/main/settings/custom_settings.cpp
  test/api/test_reset.cpp
  test/sql/pragma/profiling/test_custom_profiling_blocked_thread_time.test
  test/sql/pragma/profiling/test_profiling_all.test
Labels: Needs Documentation

#17686 Issue #17040: FILL Window Function
  benchmark/micro/window/window_fill.benchmark
  extension/core_functions/aggregate/holistic/mad.cpp
  extension/core_functions/aggregate/holistic/quantile.cpp
  extension/core_functions/include/core_functions/aggregate/quantile_sort_tree.hpp
  extension/core_functions/include/core_functions/aggregate/quantile_state.hpp
  src/common/enum_util.cpp
  src/common/enums/expression_type.cpp
  src/execution/operator/aggregate/physical_window.cpp
  src/function/scalar/operator/arithmetic.cpp
  src/function/window/window_boundaries_state.cpp
  src/function/window/window_value_function.cpp
  src/include/duckdb/common/enums/expression_type.hpp
  src/include/duckdb/common/operator/interpolate.hpp
  src/include/duckdb/function/window/window_value_function.hpp
  src/parser/expression/window_expression.cpp
  src/parser/transform/expression/transform_function.cpp
  src/planner/binder/expression/bind_window_expression.cpp
  test/sql/window/test_fill.test
Labels: Ready For Review

#17695 Bugfixes
  extension/parquet/include/writer/templated_column_writer.hpp
  src/storage/caching_file_system.cpp
Labels: Ready To Merge

#17698 Do not get file handle unnecessarily.
  src/storage/caching_file_system.cpp
Labels: Ready To Merge
